package org.lyranthe.araethura.codebuild.http4s
import org.http4s.Method._
import org.lyranthe.araethura.codebuild.circe._
import org.lyranthe.araethura.codebuild.models
class AmazoncodebuildClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.codebuild.Amazoncodebuild[F] {
  private[this] final val ServiceType: String = "codebuild"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CodeBuild_20161006")
  override def listCuratedEnvironmentImages: F[org.lyranthe.araethura.codebuild.models.ListCuratedEnvironmentImagesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.ListCuratedEnvironmentImagesOutput, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "ListCuratedEnvironmentImages", POST, "/", ())
  override def createProject(input: org.lyranthe.araethura.codebuild.models.CreateProjectInput): F[org.lyranthe.araethura.codebuild.models.CreateProjectOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.CreateProjectOutput, org.lyranthe.araethura.codebuild.models.CreateProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateProject", POST, "/", input)
  override def listProjects(input: org.lyranthe.araethura.codebuild.models.ListProjectsInput): F[org.lyranthe.araethura.codebuild.models.ListProjectsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.ListProjectsOutput, org.lyranthe.araethura.codebuild.models.ListProjectsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListProjects", POST, "/", input)
  override def batchGetBuilds(input: org.lyranthe.araethura.codebuild.models.BatchGetBuildsInput): F[org.lyranthe.araethura.codebuild.models.BatchGetBuildsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.BatchGetBuildsOutput, org.lyranthe.araethura.codebuild.models.BatchGetBuildsInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetBuilds", POST, "/", input)
  override def createWebhook(input: org.lyranthe.araethura.codebuild.models.CreateWebhookInput): F[org.lyranthe.araethura.codebuild.models.CreateWebhookOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.CreateWebhookOutput, org.lyranthe.araethura.codebuild.models.CreateWebhookInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateWebhook", POST, "/", input)
  override def listBuildsForProject(input: org.lyranthe.araethura.codebuild.models.ListBuildsForProjectInput): F[org.lyranthe.araethura.codebuild.models.ListBuildsForProjectOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.ListBuildsForProjectOutput, org.lyranthe.araethura.codebuild.models.ListBuildsForProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBuildsForProject", POST, "/", input)
  override def batchGetProjects(input: org.lyranthe.araethura.codebuild.models.BatchGetProjectsInput): F[org.lyranthe.araethura.codebuild.models.BatchGetProjectsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.BatchGetProjectsOutput, org.lyranthe.araethura.codebuild.models.BatchGetProjectsInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetProjects", POST, "/", input)
  override def listBuilds(input: org.lyranthe.araethura.codebuild.models.ListBuildsInput): F[org.lyranthe.araethura.codebuild.models.ListBuildsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.ListBuildsOutput, org.lyranthe.araethura.codebuild.models.ListBuildsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBuilds", POST, "/", input)
  override def deleteWebhook(input: org.lyranthe.araethura.codebuild.models.DeleteWebhookInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codebuild.models.DeleteWebhookInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteWebhook", POST, "/", input)
  override def stopBuild(input: org.lyranthe.araethura.codebuild.models.StopBuildInput): F[org.lyranthe.araethura.codebuild.models.StopBuildOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.StopBuildOutput, org.lyranthe.araethura.codebuild.models.StopBuildInput](client, awsData, ServiceType, ServiceAndPrefix, "StopBuild", POST, "/", input)
  override def deleteProject(input: org.lyranthe.araethura.codebuild.models.DeleteProjectInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codebuild.models.DeleteProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteProject", POST, "/", input)
  override def batchDeleteBuilds(input: org.lyranthe.araethura.codebuild.models.BatchDeleteBuildsInput): F[org.lyranthe.araethura.codebuild.models.BatchDeleteBuildsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.BatchDeleteBuildsOutput, org.lyranthe.araethura.codebuild.models.BatchDeleteBuildsInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchDeleteBuilds", POST, "/", input)
  override def startBuild(input: org.lyranthe.araethura.codebuild.models.StartBuildInput): F[org.lyranthe.araethura.codebuild.models.StartBuildOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.StartBuildOutput, org.lyranthe.araethura.codebuild.models.StartBuildInput](client, awsData, ServiceType, ServiceAndPrefix, "StartBuild", POST, "/", input)
  override def updateProject(input: org.lyranthe.araethura.codebuild.models.UpdateProjectInput): F[org.lyranthe.araethura.codebuild.models.UpdateProjectOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codebuild.models.UpdateProjectOutput, org.lyranthe.araethura.codebuild.models.UpdateProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateProject", POST, "/", input)
}