package org.lyranthe.araethura.codebuild.http4s
import org.http4s.Method._
import org.lyranthe.araethura.codebuild.circe._
import org.lyranthe.araethura.codebuild.models
class AmazoncodebuildClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.codebuild.Amazoncodebuild[F] {
  private[this] final val ServiceType: String = "codebuild"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CodeBuild_20161006")
  override def listCuratedEnvironmentImages: F[models.ListCuratedEnvironmentImagesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListCuratedEnvironmentImagesOutput, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "ListCuratedEnvironmentImages", POST, "/", ())
  override def createProject(input: models.CreateProjectInput): F[models.CreateProjectOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateProjectOutput, models.CreateProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateProject", POST, "/", input)
  override def listProjects(input: models.ListProjectsInput): F[models.ListProjectsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListProjectsOutput, models.ListProjectsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListProjects", POST, "/", input)
  override def batchGetBuilds(input: models.BatchGetBuildsInput): F[models.BatchGetBuildsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.BatchGetBuildsOutput, models.BatchGetBuildsInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetBuilds", POST, "/", input)
  override def createWebhook(input: models.CreateWebhookInput): F[models.CreateWebhookOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateWebhookOutput, models.CreateWebhookInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateWebhook", POST, "/", input)
  override def listBuildsForProject(input: models.ListBuildsForProjectInput): F[models.ListBuildsForProjectOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListBuildsForProjectOutput, models.ListBuildsForProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBuildsForProject", POST, "/", input)
  override def batchGetProjects(input: models.BatchGetProjectsInput): F[models.BatchGetProjectsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.BatchGetProjectsOutput, models.BatchGetProjectsInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetProjects", POST, "/", input)
  override def listBuilds(input: models.ListBuildsInput): F[models.ListBuildsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListBuildsOutput, models.ListBuildsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBuilds", POST, "/", input)
  override def deleteWebhook(input: models.DeleteWebhookInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteWebhookInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteWebhook", POST, "/", input)
  override def stopBuild(input: models.StopBuildInput): F[models.StopBuildOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StopBuildOutput, models.StopBuildInput](client, awsData, ServiceType, ServiceAndPrefix, "StopBuild", POST, "/", input)
  override def deleteProject(input: models.DeleteProjectInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteProject", POST, "/", input)
  override def batchDeleteBuilds(input: models.BatchDeleteBuildsInput): F[models.BatchDeleteBuildsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.BatchDeleteBuildsOutput, models.BatchDeleteBuildsInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchDeleteBuilds", POST, "/", input)
  override def startBuild(input: models.StartBuildInput): F[models.StartBuildOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StartBuildOutput, models.StartBuildInput](client, awsData, ServiceType, ServiceAndPrefix, "StartBuild", POST, "/", input)
  override def updateProject(input: models.UpdateProjectInput): F[models.UpdateProjectOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateProjectOutput, models.UpdateProjectInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateProject", POST, "/", input)
}