package org.lyranthe.araethura.codestar
trait Amazoncodestar[F[_]] {
  def associateTeamMember(input: org.lyranthe.araethura.codestar.models.AssociateTeamMemberRequest): F[org.lyranthe.araethura.codestar.models.AssociateTeamMemberResult]
  def updateTeamMember(input: org.lyranthe.araethura.codestar.models.UpdateTeamMemberRequest): F[org.lyranthe.araethura.codestar.models.UpdateTeamMemberResult]
  def createUserProfile(input: org.lyranthe.araethura.codestar.models.CreateUserProfileRequest): F[org.lyranthe.araethura.codestar.models.CreateUserProfileResult]
  def tagProject(input: org.lyranthe.araethura.codestar.models.TagProjectRequest): F[org.lyranthe.araethura.codestar.models.TagProjectResult]
  def listUserProfiles(input: org.lyranthe.araethura.codestar.models.ListUserProfilesRequest): F[org.lyranthe.araethura.codestar.models.ListUserProfilesResult]
  def listResources(input: org.lyranthe.araethura.codestar.models.ListResourcesRequest): F[org.lyranthe.araethura.codestar.models.ListResourcesResult]
  def describeUserProfile(input: org.lyranthe.araethura.codestar.models.DescribeUserProfileRequest): F[org.lyranthe.araethura.codestar.models.DescribeUserProfileResult]
  def listTagsForProject(input: org.lyranthe.araethura.codestar.models.ListTagsForProjectRequest): F[org.lyranthe.araethura.codestar.models.ListTagsForProjectResult]
  def describeProject(input: org.lyranthe.araethura.codestar.models.DescribeProjectRequest): F[org.lyranthe.araethura.codestar.models.DescribeProjectResult]
  def deleteProject(input: org.lyranthe.araethura.codestar.models.DeleteProjectRequest): F[org.lyranthe.araethura.codestar.models.DeleteProjectResult]
  def listProjects(input: org.lyranthe.araethura.codestar.models.ListProjectsRequest): F[org.lyranthe.araethura.codestar.models.ListProjectsResult]
  def updateProject(input: org.lyranthe.araethura.codestar.models.UpdateProjectRequest): F[scala.Unit]
  def createProject(input: org.lyranthe.araethura.codestar.models.CreateProjectRequest): F[org.lyranthe.araethura.codestar.models.CreateProjectResult]
  def untagProject(input: org.lyranthe.araethura.codestar.models.UntagProjectRequest): F[scala.Unit]
  def listTeamMembers(input: org.lyranthe.araethura.codestar.models.ListTeamMembersRequest): F[org.lyranthe.araethura.codestar.models.ListTeamMembersResult]
  def updateUserProfile(input: org.lyranthe.araethura.codestar.models.UpdateUserProfileRequest): F[org.lyranthe.araethura.codestar.models.UpdateUserProfileResult]
  def disassociateTeamMember(input: org.lyranthe.araethura.codestar.models.DisassociateTeamMemberRequest): F[scala.Unit]
  def deleteUserProfile(input: org.lyranthe.araethura.codestar.models.DeleteUserProfileRequest): F[org.lyranthe.araethura.codestar.models.DeleteUserProfileResult]
}