package org.lyranthe.araethura.discovery.models
import org.lyranthe.araethura.discovery.models
final case class ResourceNotFoundException(message: scala.Option[java.lang.String] = None)
final case class ExportFilter(name: java.lang.String, values: scala.List[java.lang.String], condition: java.lang.String)
final case class CustomerConnectorInfo(totalConnectors: scala.Int, activeConnectors: scala.Int, shutdownConnectors: scala.Int, unknownConnectors: scala.Int, unhealthyConnectors: scala.Int, blackListedConnectors: scala.Int, healthyConnectors: scala.Int)
final case class AgentNetworkInfo(ipAddress: scala.Option[java.lang.String] = None, macAddress: scala.Option[java.lang.String] = None)
final case class NeighborConnectionDetail(sourceServerId: java.lang.String, destinationServerId: java.lang.String, connectionsCount: scala.Long, destinationPort: scala.Option[scala.Int] = None, transportProtocol: scala.Option[java.lang.String] = None)
case object DisassociateConfigurationItemsFromApplicationResponse
final case class StartExportTaskRequest(exportDataFormat: scala.Option[scala.List[java.lang.String]] = None, filters: scala.Option[scala.List[models.ExportFilter]] = None, startTime: scala.Option[java.time.Instant] = None, endTime: scala.Option[java.time.Instant] = None)
final case class DescribeConfigurationsResponse(configurations: scala.Option[scala.List[scala.collection.immutable.Map[java.lang.String, java.lang.String]]] = None)
final case class StartDataCollectionByAgentIdsRequest(agentIds: scala.List[java.lang.String])
final case class ListConfigurationsResponse(configurations: scala.Option[scala.List[scala.collection.immutable.Map[java.lang.String, java.lang.String]]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class CustomerAgentInfo(totalAgents: scala.Int, blackListedAgents: scala.Int, shutdownAgents: scala.Int, activeAgents: scala.Int, unhealthyAgents: scala.Int, healthyAgents: scala.Int, unknownAgents: scala.Int)
case object DeleteTagsResponse
final case class DeleteTagsRequest(configurationIds: scala.List[java.lang.String], tags: scala.Option[scala.List[models.Tag]] = None)
case object CreateTagsResponse
final case class DeleteApplicationsRequest(configurationIds: scala.List[java.lang.String])
final case class AgentConfigurationStatus(agentId: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None, operationSucceeded: scala.Option[scala.Boolean] = None)
final case class ExportConfigurationsResponse(exportId: scala.Option[java.lang.String] = None)
final case class TagFilter(name: java.lang.String, values: scala.List[java.lang.String])
final case class UpdateApplicationRequest(configurationId: java.lang.String, name: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None)
final case class GetDiscoverySummaryResponse(servers: scala.Option[scala.Long] = None, applications: scala.Option[scala.Long] = None, serversMappedToApplications: scala.Option[scala.Long] = None, serversMappedtoTags: scala.Option[scala.Long] = None, agentSummary: scala.Option[models.CustomerAgentInfo] = None, connectorSummary: scala.Option[models.CustomerConnectorInfo] = None)
final case class DescribeConfigurationsRequest(configurationIds: scala.List[java.lang.String])
case object AssociateConfigurationItemsToApplicationResponse
final case class DescribeAgentsResponse(agentsInfo: scala.Option[scala.List[models.AgentInfo]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class ListConfigurationsRequest(configurationType: java.lang.String, orderBy: scala.Option[scala.List[models.OrderByElement]] = None, filters: scala.Option[scala.List[models.Filter]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class AssociateConfigurationItemsToApplicationRequest(applicationConfigurationId: java.lang.String, configurationIds: scala.List[java.lang.String])
final case class DescribeTagsRequest(filters: scala.Option[scala.List[models.TagFilter]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class StartDataCollectionByAgentIdsResponse(agentsConfigurationStatus: scala.Option[scala.List[models.AgentConfigurationStatus]] = None)
final case class DescribeTagsResponse(tags: scala.Option[scala.List[models.ConfigurationTag]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class Filter(name: java.lang.String, values: scala.List[java.lang.String], condition: java.lang.String)
final case class ListServerNeighborsResponse(neighbors: scala.List[models.NeighborConnectionDetail], nextToken: scala.Option[java.lang.String] = None, knownDependencyCount: scala.Option[scala.Long] = None)
final case class DescribeAgentsRequest(agentIds: scala.Option[scala.List[java.lang.String]] = None, filters: scala.Option[scala.List[models.Filter]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class AuthorizationErrorException(message: scala.Option[java.lang.String] = None)
final case class Tag(key: java.lang.String, value: java.lang.String)
final case class ServerInternalErrorException(message: scala.Option[java.lang.String] = None)
case object DeleteApplicationsResponse
final case class DescribeExportTasksResponse(exportsInfo: scala.Option[scala.List[models.ExportInfo]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DescribeExportTasksRequest(exportIds: scala.Option[scala.List[java.lang.String]] = None, filters: scala.Option[scala.List[models.ExportFilter]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
case object UpdateApplicationResponse
final case class CreateTagsRequest(configurationIds: scala.List[java.lang.String], tags: scala.List[models.Tag])
final case class DescribeExportConfigurationsRequest(exportIds: scala.Option[scala.List[java.lang.String]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class OrderByElement(fieldName: java.lang.String, sortOrder: scala.Option[java.lang.String] = None)
final case class StopDataCollectionByAgentIdsRequest(agentIds: scala.List[java.lang.String])
final case class StopDataCollectionByAgentIdsResponse(agentsConfigurationStatus: scala.Option[scala.List[models.AgentConfigurationStatus]] = None)
final case class InvalidParameterValueException(message: scala.Option[java.lang.String] = None)
final case class InvalidParameterException(message: scala.Option[java.lang.String] = None)
final case class OperationNotPermittedException(message: scala.Option[java.lang.String] = None)
final case class CreateApplicationRequest(name: java.lang.String, description: scala.Option[java.lang.String] = None)
final case class AgentInfo(agentId: scala.Option[java.lang.String] = None, hostName: scala.Option[java.lang.String] = None, lastHealthPingTime: scala.Option[java.lang.String] = None, collectionStatus: scala.Option[java.lang.String] = None, version: scala.Option[java.lang.String] = None, registeredTime: scala.Option[java.lang.String] = None, connectorId: scala.Option[java.lang.String] = None, agentType: scala.Option[java.lang.String] = None, agentNetworkInfoList: scala.Option[scala.List[models.AgentNetworkInfo]] = None, health: scala.Option[java.lang.String] = None)
final case class CreateApplicationResponse(configurationId: scala.Option[java.lang.String] = None)
final case class ListServerNeighborsRequest(configurationId: java.lang.String, neighborConfigurationIds: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None, portInformationNeeded: scala.Option[scala.Boolean] = None)
final case class DisassociateConfigurationItemsFromApplicationRequest(applicationConfigurationId: java.lang.String, configurationIds: scala.List[java.lang.String])
final case class ConfigurationTag(value: scala.Option[java.lang.String] = None, configurationId: scala.Option[java.lang.String] = None, configurationType: scala.Option[java.lang.String] = None, timeOfCreation: scala.Option[java.time.Instant] = None, key: scala.Option[java.lang.String] = None)
final case class DescribeExportConfigurationsResponse(exportsInfo: scala.Option[scala.List[models.ExportInfo]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class StartExportTaskResponse(exportId: scala.Option[java.lang.String] = None)
final case class ExportInfo(statusMessage: java.lang.String, exportId: java.lang.String, exportStatus: java.lang.String, exportRequestTime: java.time.Instant, requestedStartTime: scala.Option[java.time.Instant] = None, requestedEndTime: scala.Option[java.time.Instant] = None, isTruncated: scala.Option[scala.Boolean] = None, configurationsDownloadUrl: scala.Option[java.lang.String] = None)
case object GetDiscoverySummaryRequest