package org.lyranthe.araethura.discovery
trait Amazondiscovery[F[_]] {
  def listConfigurations(input: org.lyranthe.araethura.discovery.models.ListConfigurationsRequest): F[org.lyranthe.araethura.discovery.models.ListConfigurationsResponse]
  def listServerNeighbors(input: org.lyranthe.araethura.discovery.models.ListServerNeighborsRequest): F[org.lyranthe.araethura.discovery.models.ListServerNeighborsResponse]
  def deleteTags(input: org.lyranthe.araethura.discovery.models.DeleteTagsRequest): F[scala.Unit]
  def describeAgents(input: org.lyranthe.araethura.discovery.models.DescribeAgentsRequest): F[org.lyranthe.araethura.discovery.models.DescribeAgentsResponse]
  def createTags(input: org.lyranthe.araethura.discovery.models.CreateTagsRequest): F[scala.Unit]
  def describeTags(input: org.lyranthe.araethura.discovery.models.DescribeTagsRequest): F[org.lyranthe.araethura.discovery.models.DescribeTagsResponse]
  def describeExportConfigurations(input: org.lyranthe.araethura.discovery.models.DescribeExportConfigurationsRequest): F[org.lyranthe.araethura.discovery.models.DescribeExportConfigurationsResponse]
  def updateApplication(input: org.lyranthe.araethura.discovery.models.UpdateApplicationRequest): F[scala.Unit]
  def startDataCollectionByAgentIds(input: org.lyranthe.araethura.discovery.models.StartDataCollectionByAgentIdsRequest): F[org.lyranthe.araethura.discovery.models.StartDataCollectionByAgentIdsResponse]
  def createApplication(input: org.lyranthe.araethura.discovery.models.CreateApplicationRequest): F[org.lyranthe.araethura.discovery.models.CreateApplicationResponse]
  def startExportTask(input: org.lyranthe.araethura.discovery.models.StartExportTaskRequest): F[org.lyranthe.araethura.discovery.models.StartExportTaskResponse]
  def exportConfigurations: F[org.lyranthe.araethura.discovery.models.ExportConfigurationsResponse]
  def associateConfigurationItemsToApplication(input: org.lyranthe.araethura.discovery.models.AssociateConfigurationItemsToApplicationRequest): F[scala.Unit]
  def stopDataCollectionByAgentIds(input: org.lyranthe.araethura.discovery.models.StopDataCollectionByAgentIdsRequest): F[org.lyranthe.araethura.discovery.models.StopDataCollectionByAgentIdsResponse]
  def disassociateConfigurationItemsFromApplication(input: org.lyranthe.araethura.discovery.models.DisassociateConfigurationItemsFromApplicationRequest): F[scala.Unit]
  def describeExportTasks(input: org.lyranthe.araethura.discovery.models.DescribeExportTasksRequest): F[org.lyranthe.araethura.discovery.models.DescribeExportTasksResponse]
  def getDiscoverySummary: F[org.lyranthe.araethura.discovery.models.GetDiscoverySummaryResponse]
  def describeConfigurations(input: org.lyranthe.araethura.discovery.models.DescribeConfigurationsRequest): F[org.lyranthe.araethura.discovery.models.DescribeConfigurationsResponse]
  def deleteApplications(input: org.lyranthe.araethura.discovery.models.DeleteApplicationsRequest): F[scala.Unit]
}