package org.lyranthe.araethura.shield.http4s
import org.http4s.Method._
import org.lyranthe.araethura.shield.circe._
import org.lyranthe.araethura.shield.models
class AmazonshieldClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.shield.Amazonshield[F] {
  private[this] final val ServiceType: String = "shield"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSShield_20160616")
  override def describeSubscription: F[org.lyranthe.araethura.shield.models.DescribeSubscriptionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.shield.models.DescribeSubscriptionResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSubscription", POST, "/", ())
  override def describeAttack(input: org.lyranthe.araethura.shield.models.DescribeAttackRequest): F[org.lyranthe.araethura.shield.models.DescribeAttackResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.shield.models.DescribeAttackResponse, org.lyranthe.araethura.shield.models.DescribeAttackRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAttack", POST, "/", input)
  override def deleteSubscription: F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSubscription", POST, "/", ())
  override def createSubscription: F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "CreateSubscription", POST, "/", ())
  override def createProtection(input: org.lyranthe.araethura.shield.models.CreateProtectionRequest): F[org.lyranthe.araethura.shield.models.CreateProtectionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.shield.models.CreateProtectionResponse, org.lyranthe.araethura.shield.models.CreateProtectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateProtection", POST, "/", input)
  override def describeProtection(input: org.lyranthe.araethura.shield.models.DescribeProtectionRequest): F[org.lyranthe.araethura.shield.models.DescribeProtectionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.shield.models.DescribeProtectionResponse, org.lyranthe.araethura.shield.models.DescribeProtectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeProtection", POST, "/", input)
  override def listProtections(input: org.lyranthe.araethura.shield.models.ListProtectionsRequest): F[org.lyranthe.araethura.shield.models.ListProtectionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.shield.models.ListProtectionsResponse, org.lyranthe.araethura.shield.models.ListProtectionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListProtections", POST, "/", input)
  override def deleteProtection(input: org.lyranthe.araethura.shield.models.DeleteProtectionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.shield.models.DeleteProtectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteProtection", POST, "/", input)
  override def listAttacks(input: org.lyranthe.araethura.shield.models.ListAttacksRequest): F[org.lyranthe.araethura.shield.models.ListAttacksResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.shield.models.ListAttacksResponse, org.lyranthe.araethura.shield.models.ListAttacksRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListAttacks", POST, "/", input)
}