package avias.opsworkscm.http4s
import org.http4s.Method._
import avias.opsworkscm.circe._
import avias.opsworkscm.models
import avias.common.http4s.ClientUtils._
class AmazonopsworkscmClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.opsworkscm.Amazonopsworkscm[F] {
  private[this] final val ServiceType: String = "opsworks-cm"
  private[this] final val ServiceAndPrefix: Option[String] = Some("OpsWorksCM_V2016_11_01")
  override def describeAccountAttributes: F[avias.opsworkscm.models.DescribeAccountAttributesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.DescribeAccountAttributesResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAccountAttributes", POST, "/", ())
  override def updateServer(input: avias.opsworkscm.models.UpdateServerRequest): F[avias.opsworkscm.models.UpdateServerResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.UpdateServerResponse, avias.opsworkscm.models.UpdateServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateServer", POST, "/", input)
  override def startMaintenance(input: avias.opsworkscm.models.StartMaintenanceRequest): F[avias.opsworkscm.models.StartMaintenanceResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.StartMaintenanceResponse, avias.opsworkscm.models.StartMaintenanceRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartMaintenance", POST, "/", input)
  override def updateServerEngineAttributes(input: avias.opsworkscm.models.UpdateServerEngineAttributesRequest): F[avias.opsworkscm.models.UpdateServerEngineAttributesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.UpdateServerEngineAttributesResponse, avias.opsworkscm.models.UpdateServerEngineAttributesRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateServerEngineAttributes", POST, "/", input)
  override def createServer(input: avias.opsworkscm.models.CreateServerRequest): F[avias.opsworkscm.models.CreateServerResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.CreateServerResponse, avias.opsworkscm.models.CreateServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateServer", POST, "/", input)
  override def describeServers(input: avias.opsworkscm.models.DescribeServersRequest): F[avias.opsworkscm.models.DescribeServersResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.DescribeServersResponse, avias.opsworkscm.models.DescribeServersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeServers", POST, "/", input)
  override def describeNodeAssociationStatus(input: avias.opsworkscm.models.DescribeNodeAssociationStatusRequest): F[avias.opsworkscm.models.DescribeNodeAssociationStatusResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.DescribeNodeAssociationStatusResponse, avias.opsworkscm.models.DescribeNodeAssociationStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeNodeAssociationStatus", POST, "/", input)
  override def describeBackups(input: avias.opsworkscm.models.DescribeBackupsRequest): F[avias.opsworkscm.models.DescribeBackupsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.DescribeBackupsResponse, avias.opsworkscm.models.DescribeBackupsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBackups", POST, "/", input)
  override def describeEvents(input: avias.opsworkscm.models.DescribeEventsRequest): F[avias.opsworkscm.models.DescribeEventsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.DescribeEventsResponse, avias.opsworkscm.models.DescribeEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEvents", POST, "/", input)
  override def createBackup(input: avias.opsworkscm.models.CreateBackupRequest): F[avias.opsworkscm.models.CreateBackupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.CreateBackupResponse, avias.opsworkscm.models.CreateBackupRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateBackup", POST, "/", input)
  override def deleteServer(input: avias.opsworkscm.models.DeleteServerRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.opsworkscm.models.DeleteServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteServer", POST, "/", input)
  override def deleteBackup(input: avias.opsworkscm.models.DeleteBackupRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.opsworkscm.models.DeleteBackupRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteBackup", POST, "/", input)
  override def associateNode(input: avias.opsworkscm.models.AssociateNodeRequest): F[avias.opsworkscm.models.AssociateNodeResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.AssociateNodeResponse, avias.opsworkscm.models.AssociateNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateNode", POST, "/", input)
  override def disassociateNode(input: avias.opsworkscm.models.DisassociateNodeRequest): F[avias.opsworkscm.models.DisassociateNodeResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.opsworkscm.models.DisassociateNodeResponse, avias.opsworkscm.models.DisassociateNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateNode", POST, "/", input)
  override def restoreServer(input: avias.opsworkscm.models.RestoreServerRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.opsworkscm.models.RestoreServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "RestoreServer", POST, "/", input)
}