package org.lyranthe.araethura.dynamodb.http4s
import org.http4s.Method._
import org.lyranthe.araethura.dynamodb.circe._
import org.lyranthe.araethura.dynamodb.models
class AmazondynamodbClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.dynamodb.Amazondynamodb[F] {
  private[this] final val ServiceType: String = "dynamodb"
  private[this] final val ServiceAndPrefix: Option[String] = Some("DynamoDB_20120810")
  override def listTables(input: org.lyranthe.araethura.dynamodb.models.ListTablesInput): F[org.lyranthe.araethura.dynamodb.models.ListTablesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.ListTablesOutput, org.lyranthe.araethura.dynamodb.models.ListTablesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListTables", POST, "/", input)
  override def scan(input: org.lyranthe.araethura.dynamodb.models.ScanInput): F[org.lyranthe.araethura.dynamodb.models.ScanOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.ScanOutput, org.lyranthe.araethura.dynamodb.models.ScanInput](client, awsData, ServiceType, ServiceAndPrefix, "Scan", POST, "/", input)
  override def batchWriteItem(input: org.lyranthe.araethura.dynamodb.models.BatchWriteItemInput): F[org.lyranthe.araethura.dynamodb.models.BatchWriteItemOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.BatchWriteItemOutput, org.lyranthe.araethura.dynamodb.models.BatchWriteItemInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchWriteItem", POST, "/", input)
  override def putItem(input: org.lyranthe.araethura.dynamodb.models.PutItemInput): F[org.lyranthe.araethura.dynamodb.models.PutItemOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.PutItemOutput, org.lyranthe.araethura.dynamodb.models.PutItemInput](client, awsData, ServiceType, ServiceAndPrefix, "PutItem", POST, "/", input)
  override def deleteItem(input: org.lyranthe.araethura.dynamodb.models.DeleteItemInput): F[org.lyranthe.araethura.dynamodb.models.DeleteItemOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.DeleteItemOutput, org.lyranthe.araethura.dynamodb.models.DeleteItemInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteItem", POST, "/", input)
  override def untagResource(input: org.lyranthe.araethura.dynamodb.models.UntagResourceInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.dynamodb.models.UntagResourceInput](client, awsData, ServiceType, ServiceAndPrefix, "UntagResource", POST, "/", input)
  override def createTable(input: org.lyranthe.araethura.dynamodb.models.CreateTableInput): F[org.lyranthe.araethura.dynamodb.models.CreateTableOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.CreateTableOutput, org.lyranthe.araethura.dynamodb.models.CreateTableInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateTable", POST, "/", input)
  override def describeTimeToLive(input: org.lyranthe.araethura.dynamodb.models.DescribeTimeToLiveInput): F[org.lyranthe.araethura.dynamodb.models.DescribeTimeToLiveOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.DescribeTimeToLiveOutput, org.lyranthe.araethura.dynamodb.models.DescribeTimeToLiveInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTimeToLive", POST, "/", input)
  override def deleteTable(input: org.lyranthe.araethura.dynamodb.models.DeleteTableInput): F[org.lyranthe.araethura.dynamodb.models.DeleteTableOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.DeleteTableOutput, org.lyranthe.araethura.dynamodb.models.DeleteTableInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTable", POST, "/", input)
  override def getItem(input: org.lyranthe.araethura.dynamodb.models.GetItemInput): F[org.lyranthe.araethura.dynamodb.models.GetItemOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.GetItemOutput, org.lyranthe.araethura.dynamodb.models.GetItemInput](client, awsData, ServiceType, ServiceAndPrefix, "GetItem", POST, "/", input)
  override def updateItem(input: org.lyranthe.araethura.dynamodb.models.UpdateItemInput): F[org.lyranthe.araethura.dynamodb.models.UpdateItemOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.UpdateItemOutput, org.lyranthe.araethura.dynamodb.models.UpdateItemInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateItem", POST, "/", input)
  override def tagResource(input: org.lyranthe.araethura.dynamodb.models.TagResourceInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.dynamodb.models.TagResourceInput](client, awsData, ServiceType, ServiceAndPrefix, "TagResource", POST, "/", input)
  override def describeLimits: F[org.lyranthe.araethura.dynamodb.models.DescribeLimitsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.DescribeLimitsOutput, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeLimits", POST, "/", ())
  override def updateTable(input: org.lyranthe.araethura.dynamodb.models.UpdateTableInput): F[org.lyranthe.araethura.dynamodb.models.UpdateTableOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.UpdateTableOutput, org.lyranthe.araethura.dynamodb.models.UpdateTableInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTable", POST, "/", input)
  override def query(input: org.lyranthe.araethura.dynamodb.models.QueryInput): F[org.lyranthe.araethura.dynamodb.models.QueryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.QueryOutput, org.lyranthe.araethura.dynamodb.models.QueryInput](client, awsData, ServiceType, ServiceAndPrefix, "Query", POST, "/", input)
  override def listTagsOfResource(input: org.lyranthe.araethura.dynamodb.models.ListTagsOfResourceInput): F[org.lyranthe.araethura.dynamodb.models.ListTagsOfResourceOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.ListTagsOfResourceOutput, org.lyranthe.araethura.dynamodb.models.ListTagsOfResourceInput](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsOfResource", POST, "/", input)
  override def describeTable(input: org.lyranthe.araethura.dynamodb.models.DescribeTableInput): F[org.lyranthe.araethura.dynamodb.models.DescribeTableOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.DescribeTableOutput, org.lyranthe.araethura.dynamodb.models.DescribeTableInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTable", POST, "/", input)
  override def updateTimeToLive(input: org.lyranthe.araethura.dynamodb.models.UpdateTimeToLiveInput): F[org.lyranthe.araethura.dynamodb.models.UpdateTimeToLiveOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.UpdateTimeToLiveOutput, org.lyranthe.araethura.dynamodb.models.UpdateTimeToLiveInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTimeToLive", POST, "/", input)
  override def batchGetItem(input: org.lyranthe.araethura.dynamodb.models.BatchGetItemInput): F[org.lyranthe.araethura.dynamodb.models.BatchGetItemOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodb.models.BatchGetItemOutput, org.lyranthe.araethura.dynamodb.models.BatchGetItemInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetItem", POST, "/", input)
}