package avias.simpleworkflow
trait Amazonsimpleworkflow[F[_]] {
  def countClosedWorkflowExecutions(input: avias.simpleworkflow.models.CountClosedWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionCount]
  def listClosedWorkflowExecutions(input: avias.simpleworkflow.models.ListClosedWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionInfos]
  def deprecateActivityType(input: avias.simpleworkflow.models.DeprecateActivityTypeInput): F[scala.Unit]
  def registerWorkflowType(input: avias.simpleworkflow.models.RegisterWorkflowTypeInput): F[scala.Unit]
  def listDomains(input: avias.simpleworkflow.models.ListDomainsInput): F[avias.simpleworkflow.models.DomainInfos]
  def respondActivityTaskFailed(input: avias.simpleworkflow.models.RespondActivityTaskFailedInput): F[scala.Unit]
  def listWorkflowTypes(input: avias.simpleworkflow.models.ListWorkflowTypesInput): F[avias.simpleworkflow.models.WorkflowTypeInfos]
  def describeWorkflowType(input: avias.simpleworkflow.models.DescribeWorkflowTypeInput): F[avias.simpleworkflow.models.WorkflowTypeDetail]
  def listActivityTypes(input: avias.simpleworkflow.models.ListActivityTypesInput): F[avias.simpleworkflow.models.ActivityTypeInfos]
  def countPendingActivityTasks(input: avias.simpleworkflow.models.CountPendingActivityTasksInput): F[avias.simpleworkflow.models.PendingTaskCount]
  def startWorkflowExecution(input: avias.simpleworkflow.models.StartWorkflowExecutionInput): F[avias.simpleworkflow.models.Run]
  def registerDomain(input: avias.simpleworkflow.models.RegisterDomainInput): F[scala.Unit]
  def recordActivityTaskHeartbeat(input: avias.simpleworkflow.models.RecordActivityTaskHeartbeatInput): F[avias.simpleworkflow.models.ActivityTaskStatus]
  def describeActivityType(input: avias.simpleworkflow.models.DescribeActivityTypeInput): F[avias.simpleworkflow.models.ActivityTypeDetail]
  def getWorkflowExecutionHistory(input: avias.simpleworkflow.models.GetWorkflowExecutionHistoryInput): F[avias.simpleworkflow.models.History]
  def pollForDecisionTask(input: avias.simpleworkflow.models.PollForDecisionTaskInput): F[avias.simpleworkflow.models.DecisionTask]
  def countOpenWorkflowExecutions(input: avias.simpleworkflow.models.CountOpenWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionCount]
  def listOpenWorkflowExecutions(input: avias.simpleworkflow.models.ListOpenWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionInfos]
  def pollForActivityTask(input: avias.simpleworkflow.models.PollForActivityTaskInput): F[avias.simpleworkflow.models.ActivityTask]
  def terminateWorkflowExecution(input: avias.simpleworkflow.models.TerminateWorkflowExecutionInput): F[scala.Unit]
  def describeDomain(input: avias.simpleworkflow.models.DescribeDomainInput): F[avias.simpleworkflow.models.DomainDetail]
  def respondDecisionTaskCompleted(input: avias.simpleworkflow.models.RespondDecisionTaskCompletedInput): F[scala.Unit]
  def deprecateWorkflowType(input: avias.simpleworkflow.models.DeprecateWorkflowTypeInput): F[scala.Unit]
  def signalWorkflowExecution(input: avias.simpleworkflow.models.SignalWorkflowExecutionInput): F[scala.Unit]
  def describeWorkflowExecution(input: avias.simpleworkflow.models.DescribeWorkflowExecutionInput): F[avias.simpleworkflow.models.WorkflowExecutionDetail]
  def respondActivityTaskCompleted(input: avias.simpleworkflow.models.RespondActivityTaskCompletedInput): F[scala.Unit]
  def countPendingDecisionTasks(input: avias.simpleworkflow.models.CountPendingDecisionTasksInput): F[avias.simpleworkflow.models.PendingTaskCount]
  def registerActivityType(input: avias.simpleworkflow.models.RegisterActivityTypeInput): F[scala.Unit]
  def respondActivityTaskCanceled(input: avias.simpleworkflow.models.RespondActivityTaskCanceledInput): F[scala.Unit]
  def deprecateDomain(input: avias.simpleworkflow.models.DeprecateDomainInput): F[scala.Unit]
  def requestCancelWorkflowExecution(input: avias.simpleworkflow.models.RequestCancelWorkflowExecutionInput): F[scala.Unit]
}