package avias.dax
trait Amazondax[F[_]] {
  def describeClusters(input: avias.dax.models.DescribeClustersRequest): F[avias.dax.models.DescribeClustersResponse]
  def describeEvents(input: avias.dax.models.DescribeEventsRequest): F[avias.dax.models.DescribeEventsResponse]
  def rebootNode(input: avias.dax.models.RebootNodeRequest): F[avias.dax.models.RebootNodeResponse]
  def tagResource(input: avias.dax.models.TagResourceRequest): F[avias.dax.models.TagResourceResponse]
  def createSubnetGroup(input: avias.dax.models.CreateSubnetGroupRequest): F[avias.dax.models.CreateSubnetGroupResponse]
  def describeParameterGroups(input: avias.dax.models.DescribeParameterGroupsRequest): F[avias.dax.models.DescribeParameterGroupsResponse]
  def untagResource(input: avias.dax.models.UntagResourceRequest): F[avias.dax.models.UntagResourceResponse]
  def deleteCluster(input: avias.dax.models.DeleteClusterRequest): F[avias.dax.models.DeleteClusterResponse]
  def deleteParameterGroup(input: avias.dax.models.DeleteParameterGroupRequest): F[avias.dax.models.DeleteParameterGroupResponse]
  def increaseReplicationFactor(input: avias.dax.models.IncreaseReplicationFactorRequest): F[avias.dax.models.IncreaseReplicationFactorResponse]
  def updateCluster(input: avias.dax.models.UpdateClusterRequest): F[avias.dax.models.UpdateClusterResponse]
  def listTags(input: avias.dax.models.ListTagsRequest): F[avias.dax.models.ListTagsResponse]
  def describeParameters(input: avias.dax.models.DescribeParametersRequest): F[avias.dax.models.DescribeParametersResponse]
  def deleteSubnetGroup(input: avias.dax.models.DeleteSubnetGroupRequest): F[avias.dax.models.DeleteSubnetGroupResponse]
  def describeSubnetGroups(input: avias.dax.models.DescribeSubnetGroupsRequest): F[avias.dax.models.DescribeSubnetGroupsResponse]
  def updateParameterGroup(input: avias.dax.models.UpdateParameterGroupRequest): F[avias.dax.models.UpdateParameterGroupResponse]
  def describeDefaultParameters(input: avias.dax.models.DescribeDefaultParametersRequest): F[avias.dax.models.DescribeDefaultParametersResponse]
  def createParameterGroup(input: avias.dax.models.CreateParameterGroupRequest): F[avias.dax.models.CreateParameterGroupResponse]
  def createCluster(input: avias.dax.models.CreateClusterRequest): F[avias.dax.models.CreateClusterResponse]
  def decreaseReplicationFactor(input: avias.dax.models.DecreaseReplicationFactorRequest): F[avias.dax.models.DecreaseReplicationFactorResponse]
  def updateSubnetGroup(input: avias.dax.models.UpdateSubnetGroupRequest): F[avias.dax.models.UpdateSubnetGroupResponse]
}