package org.lyranthe.araethura.cloudtrail.http4s
import org.http4s.Method._
import org.lyranthe.araethura.cloudtrail.circe._
import org.lyranthe.araethura.cloudtrail.models
class AmazoncloudtrailClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.cloudtrail.Amazoncloudtrail[F] {
  private[this] final val ServiceType: String = "cloudtrail"
  private[this] final val ServiceAndPrefix: Option[String] = Some("com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101")
  override def addTags(input: models.AddTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddTags", POST, "/", input)
  override def listTags(input: models.ListTagsRequest): F[models.ListTagsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTagsResponse, models.ListTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTags", POST, "/", input)
  override def createTrail(input: models.CreateTrailRequest): F[models.CreateTrailResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateTrailResponse, models.CreateTrailRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateTrail", POST, "/", input)
  override def describeTrails(input: models.DescribeTrailsRequest): F[models.DescribeTrailsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeTrailsResponse, models.DescribeTrailsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTrails", POST, "/", input)
  override def startLogging(input: models.StartLoggingRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.StartLoggingRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartLogging", POST, "/", input)
  override def lookupEvents(input: models.LookupEventsRequest): F[models.LookupEventsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.LookupEventsResponse, models.LookupEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "LookupEvents", POST, "/", input)
  override def stopLogging(input: models.StopLoggingRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.StopLoggingRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopLogging", POST, "/", input)
  override def removeTags(input: models.RemoveTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.RemoveTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTags", POST, "/", input)
  override def deleteTrail(input: models.DeleteTrailRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteTrailRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTrail", POST, "/", input)
  override def updateTrail(input: models.UpdateTrailRequest): F[models.UpdateTrailResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateTrailResponse, models.UpdateTrailRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTrail", POST, "/", input)
  override def putEventSelectors(input: models.PutEventSelectorsRequest): F[models.PutEventSelectorsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutEventSelectorsResponse, models.PutEventSelectorsRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutEventSelectors", POST, "/", input)
  override def getEventSelectors(input: models.GetEventSelectorsRequest): F[models.GetEventSelectorsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetEventSelectorsResponse, models.GetEventSelectorsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetEventSelectors", POST, "/", input)
  override def getTrailStatus(input: models.GetTrailStatusRequest): F[models.GetTrailStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetTrailStatusResponse, models.GetTrailStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetTrailStatus", POST, "/", input)
  override def listPublicKeys(input: models.ListPublicKeysRequest): F[models.ListPublicKeysResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListPublicKeysResponse, models.ListPublicKeysRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListPublicKeys", POST, "/", input)
}