package org.lyranthe.araethura.emr.http4s
import org.http4s.Method._
import org.lyranthe.araethura.emr.circe._
import org.lyranthe.araethura.emr.models
class AmazonemrClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.emr.Amazonemr[F] {
  private[this] final val ServiceType: String = "elasticmapreduce"
  private[this] final val ServiceAndPrefix: Option[String] = Some("ElasticMapReduce")
  override def modifyInstanceFleet(input: models.ModifyInstanceFleetInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.ModifyInstanceFleetInput](client, awsData, ServiceType, ServiceAndPrefix, "ModifyInstanceFleet", POST, "/", input)
  override def deleteSecurityConfiguration(input: models.DeleteSecurityConfigurationInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSecurityConfiguration", POST, "/", input)
  override def listSecurityConfigurations(input: models.ListSecurityConfigurationsInput): F[models.ListSecurityConfigurationsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListSecurityConfigurationsOutput, models.ListSecurityConfigurationsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListSecurityConfigurations", POST, "/", input)
  override def modifyInstanceGroups(input: models.ModifyInstanceGroupsInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.ModifyInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "ModifyInstanceGroups", POST, "/", input)
  override def describeSecurityConfiguration(input: models.DescribeSecurityConfigurationInput): F[models.DescribeSecurityConfigurationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeSecurityConfigurationOutput, models.DescribeSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSecurityConfiguration", POST, "/", input)
  override def putAutoScalingPolicy(input: models.PutAutoScalingPolicyInput): F[models.PutAutoScalingPolicyOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutAutoScalingPolicyOutput, models.PutAutoScalingPolicyInput](client, awsData, ServiceType, ServiceAndPrefix, "PutAutoScalingPolicy", POST, "/", input)
  override def listSteps(input: models.ListStepsInput): F[models.ListStepsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListStepsOutput, models.ListStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListSteps", POST, "/", input)
  override def addJobFlowSteps(input: models.AddJobFlowStepsInput): F[models.AddJobFlowStepsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.AddJobFlowStepsOutput, models.AddJobFlowStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddJobFlowSteps", POST, "/", input)
  override def cancelSteps(input: models.CancelStepsInput): F[models.CancelStepsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CancelStepsOutput, models.CancelStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "CancelSteps", POST, "/", input)
  override def listInstanceFleets(input: models.ListInstanceFleetsInput): F[models.ListInstanceFleetsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListInstanceFleetsOutput, models.ListInstanceFleetsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstanceFleets", POST, "/", input)
  override def addInstanceFleet(input: models.AddInstanceFleetInput): F[models.AddInstanceFleetOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.AddInstanceFleetOutput, models.AddInstanceFleetInput](client, awsData, ServiceType, ServiceAndPrefix, "AddInstanceFleet", POST, "/", input)
  override def listClusters(input: models.ListClustersInput): F[models.ListClustersOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListClustersOutput, models.ListClustersInput](client, awsData, ServiceType, ServiceAndPrefix, "ListClusters", POST, "/", input)
  override def runJobFlow(input: models.RunJobFlowInput): F[models.RunJobFlowOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RunJobFlowOutput, models.RunJobFlowInput](client, awsData, ServiceType, ServiceAndPrefix, "RunJobFlow", POST, "/", input)
  override def listInstances(input: models.ListInstancesInput): F[models.ListInstancesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListInstancesOutput, models.ListInstancesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstances", POST, "/", input)
  override def describeStep(input: models.DescribeStepInput): F[models.DescribeStepOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeStepOutput, models.DescribeStepInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStep", POST, "/", input)
  override def setVisibleToAllUsers(input: models.SetVisibleToAllUsersInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.SetVisibleToAllUsersInput](client, awsData, ServiceType, ServiceAndPrefix, "SetVisibleToAllUsers", POST, "/", input)
  override def describeCluster(input: models.DescribeClusterInput): F[models.DescribeClusterOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeClusterOutput, models.DescribeClusterInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeCluster", POST, "/", input)
  override def terminateJobFlows(input: models.TerminateJobFlowsInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.TerminateJobFlowsInput](client, awsData, ServiceType, ServiceAndPrefix, "TerminateJobFlows", POST, "/", input)
  override def removeAutoScalingPolicy(input: models.RemoveAutoScalingPolicyInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.RemoveAutoScalingPolicyInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveAutoScalingPolicy", POST, "/", input)
  override def addInstanceGroups(input: models.AddInstanceGroupsInput): F[models.AddInstanceGroupsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.AddInstanceGroupsOutput, models.AddInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddInstanceGroups", POST, "/", input)
  override def listInstanceGroups(input: models.ListInstanceGroupsInput): F[models.ListInstanceGroupsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListInstanceGroupsOutput, models.ListInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstanceGroups", POST, "/", input)
  override def addTags(input: models.AddTagsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTags", POST, "/", input)
  override def createSecurityConfiguration(input: models.CreateSecurityConfigurationInput): F[models.CreateSecurityConfigurationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateSecurityConfigurationOutput, models.CreateSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateSecurityConfiguration", POST, "/", input)
  override def removeTags(input: models.RemoveTagsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.RemoveTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTags", POST, "/", input)
  override def listBootstrapActions(input: models.ListBootstrapActionsInput): F[models.ListBootstrapActionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListBootstrapActionsOutput, models.ListBootstrapActionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBootstrapActions", POST, "/", input)
  override def setTerminationProtection(input: models.SetTerminationProtectionInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.SetTerminationProtectionInput](client, awsData, ServiceType, ServiceAndPrefix, "SetTerminationProtection", POST, "/", input)
  override def describeJobFlows(input: models.DescribeJobFlowsInput): F[models.DescribeJobFlowsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeJobFlowsOutput, models.DescribeJobFlowsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeJobFlows", POST, "/", input)
}