package org.lyranthe.araethura.emr.http4s
import org.http4s.Method._
import org.lyranthe.araethura.emr.circe._
import org.lyranthe.araethura.emr.models
class AmazonemrClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.emr.Amazonemr[F] {
  private[this] final val ServiceType: String = "elasticmapreduce"
  private[this] final val ServiceAndPrefix: Option[String] = Some("ElasticMapReduce")
  override def modifyInstanceFleet(input: org.lyranthe.araethura.emr.models.ModifyInstanceFleetInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.ModifyInstanceFleetInput](client, awsData, ServiceType, ServiceAndPrefix, "ModifyInstanceFleet", POST, "/", input)
  override def deleteSecurityConfiguration(input: org.lyranthe.araethura.emr.models.DeleteSecurityConfigurationInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.DeleteSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSecurityConfiguration", POST, "/", input)
  override def listSecurityConfigurations(input: org.lyranthe.araethura.emr.models.ListSecurityConfigurationsInput): F[org.lyranthe.araethura.emr.models.ListSecurityConfigurationsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListSecurityConfigurationsOutput, org.lyranthe.araethura.emr.models.ListSecurityConfigurationsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListSecurityConfigurations", POST, "/", input)
  override def modifyInstanceGroups(input: org.lyranthe.araethura.emr.models.ModifyInstanceGroupsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.ModifyInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "ModifyInstanceGroups", POST, "/", input)
  override def describeSecurityConfiguration(input: org.lyranthe.araethura.emr.models.DescribeSecurityConfigurationInput): F[org.lyranthe.araethura.emr.models.DescribeSecurityConfigurationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.DescribeSecurityConfigurationOutput, org.lyranthe.araethura.emr.models.DescribeSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSecurityConfiguration", POST, "/", input)
  override def putAutoScalingPolicy(input: org.lyranthe.araethura.emr.models.PutAutoScalingPolicyInput): F[org.lyranthe.araethura.emr.models.PutAutoScalingPolicyOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.PutAutoScalingPolicyOutput, org.lyranthe.araethura.emr.models.PutAutoScalingPolicyInput](client, awsData, ServiceType, ServiceAndPrefix, "PutAutoScalingPolicy", POST, "/", input)
  override def listSteps(input: org.lyranthe.araethura.emr.models.ListStepsInput): F[org.lyranthe.araethura.emr.models.ListStepsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListStepsOutput, org.lyranthe.araethura.emr.models.ListStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListSteps", POST, "/", input)
  override def addJobFlowSteps(input: org.lyranthe.araethura.emr.models.AddJobFlowStepsInput): F[org.lyranthe.araethura.emr.models.AddJobFlowStepsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.AddJobFlowStepsOutput, org.lyranthe.araethura.emr.models.AddJobFlowStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddJobFlowSteps", POST, "/", input)
  override def cancelSteps(input: org.lyranthe.araethura.emr.models.CancelStepsInput): F[org.lyranthe.araethura.emr.models.CancelStepsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.CancelStepsOutput, org.lyranthe.araethura.emr.models.CancelStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "CancelSteps", POST, "/", input)
  override def listInstanceFleets(input: org.lyranthe.araethura.emr.models.ListInstanceFleetsInput): F[org.lyranthe.araethura.emr.models.ListInstanceFleetsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListInstanceFleetsOutput, org.lyranthe.araethura.emr.models.ListInstanceFleetsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstanceFleets", POST, "/", input)
  override def addInstanceFleet(input: org.lyranthe.araethura.emr.models.AddInstanceFleetInput): F[org.lyranthe.araethura.emr.models.AddInstanceFleetOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.AddInstanceFleetOutput, org.lyranthe.araethura.emr.models.AddInstanceFleetInput](client, awsData, ServiceType, ServiceAndPrefix, "AddInstanceFleet", POST, "/", input)
  override def listClusters(input: org.lyranthe.araethura.emr.models.ListClustersInput): F[org.lyranthe.araethura.emr.models.ListClustersOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListClustersOutput, org.lyranthe.araethura.emr.models.ListClustersInput](client, awsData, ServiceType, ServiceAndPrefix, "ListClusters", POST, "/", input)
  override def runJobFlow(input: org.lyranthe.araethura.emr.models.RunJobFlowInput): F[org.lyranthe.araethura.emr.models.RunJobFlowOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.RunJobFlowOutput, org.lyranthe.araethura.emr.models.RunJobFlowInput](client, awsData, ServiceType, ServiceAndPrefix, "RunJobFlow", POST, "/", input)
  override def listInstances(input: org.lyranthe.araethura.emr.models.ListInstancesInput): F[org.lyranthe.araethura.emr.models.ListInstancesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListInstancesOutput, org.lyranthe.araethura.emr.models.ListInstancesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstances", POST, "/", input)
  override def describeStep(input: org.lyranthe.araethura.emr.models.DescribeStepInput): F[org.lyranthe.araethura.emr.models.DescribeStepOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.DescribeStepOutput, org.lyranthe.araethura.emr.models.DescribeStepInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStep", POST, "/", input)
  override def setVisibleToAllUsers(input: org.lyranthe.araethura.emr.models.SetVisibleToAllUsersInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.SetVisibleToAllUsersInput](client, awsData, ServiceType, ServiceAndPrefix, "SetVisibleToAllUsers", POST, "/", input)
  override def describeCluster(input: org.lyranthe.araethura.emr.models.DescribeClusterInput): F[org.lyranthe.araethura.emr.models.DescribeClusterOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.DescribeClusterOutput, org.lyranthe.araethura.emr.models.DescribeClusterInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeCluster", POST, "/", input)
  override def terminateJobFlows(input: org.lyranthe.araethura.emr.models.TerminateJobFlowsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.TerminateJobFlowsInput](client, awsData, ServiceType, ServiceAndPrefix, "TerminateJobFlows", POST, "/", input)
  override def removeAutoScalingPolicy(input: org.lyranthe.araethura.emr.models.RemoveAutoScalingPolicyInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.RemoveAutoScalingPolicyInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveAutoScalingPolicy", POST, "/", input)
  override def addInstanceGroups(input: org.lyranthe.araethura.emr.models.AddInstanceGroupsInput): F[org.lyranthe.araethura.emr.models.AddInstanceGroupsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.AddInstanceGroupsOutput, org.lyranthe.araethura.emr.models.AddInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddInstanceGroups", POST, "/", input)
  override def listInstanceGroups(input: org.lyranthe.araethura.emr.models.ListInstanceGroupsInput): F[org.lyranthe.araethura.emr.models.ListInstanceGroupsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListInstanceGroupsOutput, org.lyranthe.araethura.emr.models.ListInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstanceGroups", POST, "/", input)
  override def addTags(input: org.lyranthe.araethura.emr.models.AddTagsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.AddTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTags", POST, "/", input)
  override def createSecurityConfiguration(input: org.lyranthe.araethura.emr.models.CreateSecurityConfigurationInput): F[org.lyranthe.araethura.emr.models.CreateSecurityConfigurationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.CreateSecurityConfigurationOutput, org.lyranthe.araethura.emr.models.CreateSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateSecurityConfiguration", POST, "/", input)
  override def removeTags(input: org.lyranthe.araethura.emr.models.RemoveTagsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.RemoveTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTags", POST, "/", input)
  override def listBootstrapActions(input: org.lyranthe.araethura.emr.models.ListBootstrapActionsInput): F[org.lyranthe.araethura.emr.models.ListBootstrapActionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.ListBootstrapActionsOutput, org.lyranthe.araethura.emr.models.ListBootstrapActionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBootstrapActions", POST, "/", input)
  override def setTerminationProtection(input: org.lyranthe.araethura.emr.models.SetTerminationProtectionInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.emr.models.SetTerminationProtectionInput](client, awsData, ServiceType, ServiceAndPrefix, "SetTerminationProtection", POST, "/", input)
  override def describeJobFlows(input: org.lyranthe.araethura.emr.models.DescribeJobFlowsInput): F[org.lyranthe.araethura.emr.models.DescribeJobFlowsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.emr.models.DescribeJobFlowsOutput, org.lyranthe.araethura.emr.models.DescribeJobFlowsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeJobFlows", POST, "/", input)
}