package org.lyranthe.araethura.acm.models
import org.lyranthe.araethura.acm.models
final case class DescribeCertificateResponse(certificate: scala.Option[models.CertificateDetail] = None)
final case class RemoveTagsFromCertificateRequest(certificateArn: java.lang.String, tags: scala.List[models.Tag])
final case class ListTagsForCertificateResponse(tags: scala.Option[scala.List[models.Tag]] = None)
final case class InvalidTagException(message: scala.Option[java.lang.String] = None)
final case class DescribeCertificateRequest(certificateArn: java.lang.String)
final case class ResendValidationEmailRequest(certificateArn: java.lang.String, domain: java.lang.String, validationDomain: java.lang.String)
final case class ListCertificatesResponse(nextToken: scala.Option[java.lang.String] = None, certificateSummaryList: scala.Option[scala.List[models.CertificateSummary]] = None)
final case class RequestCertificateRequest(domainName: java.lang.String, subjectAlternativeNames: scala.Option[scala.List[java.lang.String]] = None, idempotencyToken: scala.Option[java.lang.String] = None, domainValidationOptions: scala.Option[scala.List[models.DomainValidationOption]] = None)
final case class ListCertificatesRequest(certificateStatuses: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None, maxItems: scala.Option[scala.Int] = None)
final case class DomainValidationOption(domainName: java.lang.String, validationDomain: java.lang.String)
final case class AddTagsToCertificateRequest(certificateArn: java.lang.String, tags: scala.List[models.Tag])
final case class Tag(key: java.lang.String, value: scala.Option[java.lang.String] = None)
final case class ResourceNotFoundException(message: scala.Option[java.lang.String] = None)
final case class LimitExceededException(message: scala.Option[java.lang.String] = None)
final case class GetCertificateResponse(certificate: scala.Option[java.lang.String] = None, certificateChain: scala.Option[java.lang.String] = None)
final case class InvalidArnException(message: scala.Option[java.lang.String] = None)
final case class TooManyTagsException(message: scala.Option[java.lang.String] = None)
final case class RequestInProgressException(message: scala.Option[java.lang.String] = None)
final case class GetCertificateRequest(certificateArn: java.lang.String)
final case class InvalidStateException(message: scala.Option[java.lang.String] = None)
final case class InvalidDomainValidationOptionsException(message: scala.Option[java.lang.String] = None)
final case class RequestCertificateResponse(certificateArn: scala.Option[java.lang.String] = None)
final case class ImportCertificateRequest(certificate: scala.Array[scala.Byte], privateKey: scala.Array[scala.Byte], certificateArn: scala.Option[java.lang.String] = None, certificateChain: scala.Option[scala.Array[scala.Byte]] = None)
final case class CertificateDetail(`type`: scala.Option[java.lang.String] = None, keyAlgorithm: scala.Option[java.lang.String] = None, revocationReason: scala.Option[java.lang.String] = None, certificateArn: scala.Option[java.lang.String] = None, serial: scala.Option[java.lang.String] = None, subject: scala.Option[java.lang.String] = None, issuer: scala.Option[java.lang.String] = None, signatureAlgorithm: scala.Option[java.lang.String] = None, domainValidationOptions: scala.Option[scala.List[models.DomainValidation]] = None, domainName: scala.Option[java.lang.String] = None, inUseBy: scala.Option[scala.List[java.lang.String]] = None, subjectAlternativeNames: scala.Option[scala.List[java.lang.String]] = None, failureReason: scala.Option[java.lang.String] = None, status: scala.Option[java.lang.String] = None, notBefore: scala.Option[java.time.Instant] = None, revokedAt: scala.Option[java.time.Instant] = None, issuedAt: scala.Option[java.time.Instant] = None, createdAt: scala.Option[java.time.Instant] = None, importedAt: scala.Option[java.time.Instant] = None, notAfter: scala.Option[java.time.Instant] = None, renewalSummary: scala.Option[models.RenewalSummary] = None)
final case class DeleteCertificateRequest(certificateArn: java.lang.String)
final case class ResourceInUseException(message: scala.Option[java.lang.String] = None)
final case class ListTagsForCertificateRequest(certificateArn: java.lang.String)
final case class DomainValidation(domainName: java.lang.String, validationDomain: scala.Option[java.lang.String] = None, validationEmails: scala.Option[scala.List[java.lang.String]] = None, validationStatus: scala.Option[java.lang.String] = None)
final case class ImportCertificateResponse(certificateArn: scala.Option[java.lang.String] = None)
final case class CertificateSummary(certificateArn: scala.Option[java.lang.String] = None, domainName: scala.Option[java.lang.String] = None)
final case class RenewalSummary(renewalStatus: java.lang.String, domainValidationOptions: scala.List[models.DomainValidation])