package avias.config.http4s
import org.http4s.Method._
import avias.config.circe._
import avias.config.models
import avias.common.http4s.ClientUtils._
class AmazonconfigClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.config.Amazonconfig[F] {
  private[this] final val ServiceType: String = "config"
  private[this] final val ServiceAndPrefix: Option[String] = Some("StarlingDoveService")
  override def describeConfigRuleEvaluationStatus(input: avias.config.models.DescribeConfigRuleEvaluationStatusRequest): F[avias.config.models.DescribeConfigRuleEvaluationStatusResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeConfigRuleEvaluationStatusResponse, avias.config.models.DescribeConfigRuleEvaluationStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigRuleEvaluationStatus", POST, "/", input)
  override def deleteEvaluationResults(input: avias.config.models.DeleteEvaluationResultsRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.DeleteEvaluationResultsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteEvaluationResults", POST, "/", input)
  override def deleteDeliveryChannel(input: avias.config.models.DeleteDeliveryChannelRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.DeleteDeliveryChannelRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDeliveryChannel", POST, "/", input)
  override def deliverConfigSnapshot(input: avias.config.models.DeliverConfigSnapshotRequest): F[avias.config.models.DeliverConfigSnapshotResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DeliverConfigSnapshotResponse, avias.config.models.DeliverConfigSnapshotRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeliverConfigSnapshot", POST, "/", input)
  override def describeDeliveryChannels(input: avias.config.models.DescribeDeliveryChannelsRequest): F[avias.config.models.DescribeDeliveryChannelsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeDeliveryChannelsResponse, avias.config.models.DescribeDeliveryChannelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryChannels", POST, "/", input)
  override def deleteConfigRule(input: avias.config.models.DeleteConfigRuleRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.DeleteConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteConfigRule", POST, "/", input)
  override def describeDeliveryChannelStatus(input: avias.config.models.DescribeDeliveryChannelStatusRequest): F[avias.config.models.DescribeDeliveryChannelStatusResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeDeliveryChannelStatusResponse, avias.config.models.DescribeDeliveryChannelStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryChannelStatus", POST, "/", input)
  override def putConfigRule(input: avias.config.models.PutConfigRuleRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.PutConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutConfigRule", POST, "/", input)
  override def getResourceConfigHistory(input: avias.config.models.GetResourceConfigHistoryRequest): F[avias.config.models.GetResourceConfigHistoryResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.GetResourceConfigHistoryResponse, avias.config.models.GetResourceConfigHistoryRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetResourceConfigHistory", POST, "/", input)
  override def getComplianceDetailsByConfigRule(input: avias.config.models.GetComplianceDetailsByConfigRuleRequest): F[avias.config.models.GetComplianceDetailsByConfigRuleResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.GetComplianceDetailsByConfigRuleResponse, avias.config.models.GetComplianceDetailsByConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceDetailsByConfigRule", POST, "/", input)
  override def getDiscoveredResourceCounts(input: avias.config.models.GetDiscoveredResourceCountsRequest): F[avias.config.models.GetDiscoveredResourceCountsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.GetDiscoveredResourceCountsResponse, avias.config.models.GetDiscoveredResourceCountsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetDiscoveredResourceCounts", POST, "/", input)
  override def describeConfigurationRecorderStatus(input: avias.config.models.DescribeConfigurationRecorderStatusRequest): F[avias.config.models.DescribeConfigurationRecorderStatusResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeConfigurationRecorderStatusResponse, avias.config.models.DescribeConfigurationRecorderStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurationRecorderStatus", POST, "/", input)
  override def listDiscoveredResources(input: avias.config.models.ListDiscoveredResourcesRequest): F[avias.config.models.ListDiscoveredResourcesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.ListDiscoveredResourcesResponse, avias.config.models.ListDiscoveredResourcesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListDiscoveredResources", POST, "/", input)
  override def stopConfigurationRecorder(input: avias.config.models.StopConfigurationRecorderRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.StopConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopConfigurationRecorder", POST, "/", input)
  override def describeComplianceByResource(input: avias.config.models.DescribeComplianceByResourceRequest): F[avias.config.models.DescribeComplianceByResourceResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeComplianceByResourceResponse, avias.config.models.DescribeComplianceByResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeComplianceByResource", POST, "/", input)
  override def describeComplianceByConfigRule(input: avias.config.models.DescribeComplianceByConfigRuleRequest): F[avias.config.models.DescribeComplianceByConfigRuleResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeComplianceByConfigRuleResponse, avias.config.models.DescribeComplianceByConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeComplianceByConfigRule", POST, "/", input)
  override def deleteConfigurationRecorder(input: avias.config.models.DeleteConfigurationRecorderRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.DeleteConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteConfigurationRecorder", POST, "/", input)
  override def startConfigRulesEvaluation(input: avias.config.models.StartConfigRulesEvaluationRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.StartConfigRulesEvaluationRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartConfigRulesEvaluation", POST, "/", input)
  override def putDeliveryChannel(input: avias.config.models.PutDeliveryChannelRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.PutDeliveryChannelRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutDeliveryChannel", POST, "/", input)
  override def getComplianceDetailsByResource(input: avias.config.models.GetComplianceDetailsByResourceRequest): F[avias.config.models.GetComplianceDetailsByResourceResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.GetComplianceDetailsByResourceResponse, avias.config.models.GetComplianceDetailsByResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceDetailsByResource", POST, "/", input)
  override def startConfigurationRecorder(input: avias.config.models.StartConfigurationRecorderRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.StartConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartConfigurationRecorder", POST, "/", input)
  override def describeConfigurationRecorders(input: avias.config.models.DescribeConfigurationRecordersRequest): F[avias.config.models.DescribeConfigurationRecordersResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeConfigurationRecordersResponse, avias.config.models.DescribeConfigurationRecordersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurationRecorders", POST, "/", input)
  override def describeConfigRules(input: avias.config.models.DescribeConfigRulesRequest): F[avias.config.models.DescribeConfigRulesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.DescribeConfigRulesResponse, avias.config.models.DescribeConfigRulesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigRules", POST, "/", input)
  override def getComplianceSummaryByResourceType(input: avias.config.models.GetComplianceSummaryByResourceTypeRequest): F[avias.config.models.GetComplianceSummaryByResourceTypeResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.GetComplianceSummaryByResourceTypeResponse, avias.config.models.GetComplianceSummaryByResourceTypeRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceSummaryByResourceType", POST, "/", input)
  override def putConfigurationRecorder(input: avias.config.models.PutConfigurationRecorderRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.config.models.PutConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutConfigurationRecorder", POST, "/", input)
  override def getComplianceSummaryByConfigRule: F[avias.config.models.GetComplianceSummaryByConfigRuleResponse] = avias.common.http4s.ClientUtils.doRequestWithoutBody[F, avias.config.models.GetComplianceSummaryByConfigRuleResponse](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceSummaryByConfigRule", POST, "/")
  override def putEvaluations(input: avias.config.models.PutEvaluationsRequest): F[avias.config.models.PutEvaluationsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.config.models.PutEvaluationsResponse, avias.config.models.PutEvaluationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutEvaluations", POST, "/", input)
}