package org.lyranthe.araethura.config.http4s
import org.http4s.Method._
import org.lyranthe.araethura.config.circe._
import org.lyranthe.araethura.config.models
class AmazonconfigClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.config.Amazonconfig[F] {
  private[this] final val ServiceType: String = "config"
  private[this] final val ServiceAndPrefix: Option[String] = Some("StarlingDoveService")
  override def describeConfigRuleEvaluationStatus(input: org.lyranthe.araethura.config.models.DescribeConfigRuleEvaluationStatusRequest): F[org.lyranthe.araethura.config.models.DescribeConfigRuleEvaluationStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeConfigRuleEvaluationStatusResponse, org.lyranthe.araethura.config.models.DescribeConfigRuleEvaluationStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigRuleEvaluationStatus", POST, "/", input)
  override def deleteEvaluationResults(input: org.lyranthe.araethura.config.models.DeleteEvaluationResultsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.DeleteEvaluationResultsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteEvaluationResults", POST, "/", input)
  override def deleteDeliveryChannel(input: org.lyranthe.araethura.config.models.DeleteDeliveryChannelRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.DeleteDeliveryChannelRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDeliveryChannel", POST, "/", input)
  override def deliverConfigSnapshot(input: org.lyranthe.araethura.config.models.DeliverConfigSnapshotRequest): F[org.lyranthe.araethura.config.models.DeliverConfigSnapshotResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DeliverConfigSnapshotResponse, org.lyranthe.araethura.config.models.DeliverConfigSnapshotRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeliverConfigSnapshot", POST, "/", input)
  override def describeDeliveryChannels(input: org.lyranthe.araethura.config.models.DescribeDeliveryChannelsRequest): F[org.lyranthe.araethura.config.models.DescribeDeliveryChannelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeDeliveryChannelsResponse, org.lyranthe.araethura.config.models.DescribeDeliveryChannelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryChannels", POST, "/", input)
  override def deleteConfigRule(input: org.lyranthe.araethura.config.models.DeleteConfigRuleRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.DeleteConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteConfigRule", POST, "/", input)
  override def describeDeliveryChannelStatus(input: org.lyranthe.araethura.config.models.DescribeDeliveryChannelStatusRequest): F[org.lyranthe.araethura.config.models.DescribeDeliveryChannelStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeDeliveryChannelStatusResponse, org.lyranthe.araethura.config.models.DescribeDeliveryChannelStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryChannelStatus", POST, "/", input)
  override def putConfigRule(input: org.lyranthe.araethura.config.models.PutConfigRuleRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.PutConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutConfigRule", POST, "/", input)
  override def getResourceConfigHistory(input: org.lyranthe.araethura.config.models.GetResourceConfigHistoryRequest): F[org.lyranthe.araethura.config.models.GetResourceConfigHistoryResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.GetResourceConfigHistoryResponse, org.lyranthe.araethura.config.models.GetResourceConfigHistoryRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetResourceConfigHistory", POST, "/", input)
  override def getComplianceDetailsByConfigRule(input: org.lyranthe.araethura.config.models.GetComplianceDetailsByConfigRuleRequest): F[org.lyranthe.araethura.config.models.GetComplianceDetailsByConfigRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.GetComplianceDetailsByConfigRuleResponse, org.lyranthe.araethura.config.models.GetComplianceDetailsByConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceDetailsByConfigRule", POST, "/", input)
  override def getDiscoveredResourceCounts(input: org.lyranthe.araethura.config.models.GetDiscoveredResourceCountsRequest): F[org.lyranthe.araethura.config.models.GetDiscoveredResourceCountsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.GetDiscoveredResourceCountsResponse, org.lyranthe.araethura.config.models.GetDiscoveredResourceCountsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetDiscoveredResourceCounts", POST, "/", input)
  override def describeConfigurationRecorderStatus(input: org.lyranthe.araethura.config.models.DescribeConfigurationRecorderStatusRequest): F[org.lyranthe.araethura.config.models.DescribeConfigurationRecorderStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeConfigurationRecorderStatusResponse, org.lyranthe.araethura.config.models.DescribeConfigurationRecorderStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurationRecorderStatus", POST, "/", input)
  override def listDiscoveredResources(input: org.lyranthe.araethura.config.models.ListDiscoveredResourcesRequest): F[org.lyranthe.araethura.config.models.ListDiscoveredResourcesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.ListDiscoveredResourcesResponse, org.lyranthe.araethura.config.models.ListDiscoveredResourcesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListDiscoveredResources", POST, "/", input)
  override def stopConfigurationRecorder(input: org.lyranthe.araethura.config.models.StopConfigurationRecorderRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.StopConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopConfigurationRecorder", POST, "/", input)
  override def describeComplianceByResource(input: org.lyranthe.araethura.config.models.DescribeComplianceByResourceRequest): F[org.lyranthe.araethura.config.models.DescribeComplianceByResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeComplianceByResourceResponse, org.lyranthe.araethura.config.models.DescribeComplianceByResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeComplianceByResource", POST, "/", input)
  override def describeComplianceByConfigRule(input: org.lyranthe.araethura.config.models.DescribeComplianceByConfigRuleRequest): F[org.lyranthe.araethura.config.models.DescribeComplianceByConfigRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeComplianceByConfigRuleResponse, org.lyranthe.araethura.config.models.DescribeComplianceByConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeComplianceByConfigRule", POST, "/", input)
  override def deleteConfigurationRecorder(input: org.lyranthe.araethura.config.models.DeleteConfigurationRecorderRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.DeleteConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteConfigurationRecorder", POST, "/", input)
  override def startConfigRulesEvaluation(input: org.lyranthe.araethura.config.models.StartConfigRulesEvaluationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.StartConfigRulesEvaluationRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartConfigRulesEvaluation", POST, "/", input)
  override def putDeliveryChannel(input: org.lyranthe.araethura.config.models.PutDeliveryChannelRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.PutDeliveryChannelRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutDeliveryChannel", POST, "/", input)
  override def getComplianceDetailsByResource(input: org.lyranthe.araethura.config.models.GetComplianceDetailsByResourceRequest): F[org.lyranthe.araethura.config.models.GetComplianceDetailsByResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.GetComplianceDetailsByResourceResponse, org.lyranthe.araethura.config.models.GetComplianceDetailsByResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceDetailsByResource", POST, "/", input)
  override def startConfigurationRecorder(input: org.lyranthe.araethura.config.models.StartConfigurationRecorderRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.StartConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartConfigurationRecorder", POST, "/", input)
  override def describeConfigurationRecorders(input: org.lyranthe.araethura.config.models.DescribeConfigurationRecordersRequest): F[org.lyranthe.araethura.config.models.DescribeConfigurationRecordersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeConfigurationRecordersResponse, org.lyranthe.araethura.config.models.DescribeConfigurationRecordersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurationRecorders", POST, "/", input)
  override def describeConfigRules(input: org.lyranthe.araethura.config.models.DescribeConfigRulesRequest): F[org.lyranthe.araethura.config.models.DescribeConfigRulesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.DescribeConfigRulesResponse, org.lyranthe.araethura.config.models.DescribeConfigRulesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigRules", POST, "/", input)
  override def getComplianceSummaryByResourceType(input: org.lyranthe.araethura.config.models.GetComplianceSummaryByResourceTypeRequest): F[org.lyranthe.araethura.config.models.GetComplianceSummaryByResourceTypeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.GetComplianceSummaryByResourceTypeResponse, org.lyranthe.araethura.config.models.GetComplianceSummaryByResourceTypeRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceSummaryByResourceType", POST, "/", input)
  override def putConfigurationRecorder(input: org.lyranthe.araethura.config.models.PutConfigurationRecorderRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.config.models.PutConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutConfigurationRecorder", POST, "/", input)
  override def getComplianceSummaryByConfigRule: F[org.lyranthe.araethura.config.models.GetComplianceSummaryByConfigRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequestWithoutBody[F, org.lyranthe.araethura.config.models.GetComplianceSummaryByConfigRuleResponse](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceSummaryByConfigRule", POST, "/")
  override def putEvaluations(input: org.lyranthe.araethura.config.models.PutEvaluationsRequest): F[org.lyranthe.araethura.config.models.PutEvaluationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.config.models.PutEvaluationsResponse, org.lyranthe.araethura.config.models.PutEvaluationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutEvaluations", POST, "/", input)
}