package org.lyranthe.araethura.config.http4s
import org.http4s.Method._
import org.lyranthe.araethura.config.circe._
import org.lyranthe.araethura.config.models
class AmazonconfigClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.config.Amazonconfig[F] {
  private[this] final val ServiceType: String = "config"
  private[this] final val ServiceAndPrefix: Option[String] = Some("StarlingDoveService")
  override def describeConfigRuleEvaluationStatus(input: models.DescribeConfigRuleEvaluationStatusRequest): F[models.DescribeConfigRuleEvaluationStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeConfigRuleEvaluationStatusResponse, models.DescribeConfigRuleEvaluationStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigRuleEvaluationStatus", POST, "/", input)
  override def deleteEvaluationResults(input: models.DeleteEvaluationResultsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteEvaluationResultsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteEvaluationResults", POST, "/", input)
  override def deleteDeliveryChannel(input: models.DeleteDeliveryChannelRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.DeleteDeliveryChannelRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDeliveryChannel", POST, "/", input)
  override def deliverConfigSnapshot(input: models.DeliverConfigSnapshotRequest): F[models.DeliverConfigSnapshotResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeliverConfigSnapshotResponse, models.DeliverConfigSnapshotRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeliverConfigSnapshot", POST, "/", input)
  override def describeDeliveryChannels(input: models.DescribeDeliveryChannelsRequest): F[models.DescribeDeliveryChannelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeDeliveryChannelsResponse, models.DescribeDeliveryChannelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryChannels", POST, "/", input)
  override def deleteConfigRule(input: models.DeleteConfigRuleRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.DeleteConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteConfigRule", POST, "/", input)
  override def describeDeliveryChannelStatus(input: models.DescribeDeliveryChannelStatusRequest): F[models.DescribeDeliveryChannelStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeDeliveryChannelStatusResponse, models.DescribeDeliveryChannelStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryChannelStatus", POST, "/", input)
  override def putConfigRule(input: models.PutConfigRuleRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.PutConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutConfigRule", POST, "/", input)
  override def getResourceConfigHistory(input: models.GetResourceConfigHistoryRequest): F[models.GetResourceConfigHistoryResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetResourceConfigHistoryResponse, models.GetResourceConfigHistoryRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetResourceConfigHistory", POST, "/", input)
  override def getComplianceDetailsByConfigRule(input: models.GetComplianceDetailsByConfigRuleRequest): F[models.GetComplianceDetailsByConfigRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetComplianceDetailsByConfigRuleResponse, models.GetComplianceDetailsByConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceDetailsByConfigRule", POST, "/", input)
  override def getDiscoveredResourceCounts(input: models.GetDiscoveredResourceCountsRequest): F[models.GetDiscoveredResourceCountsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetDiscoveredResourceCountsResponse, models.GetDiscoveredResourceCountsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetDiscoveredResourceCounts", POST, "/", input)
  override def describeConfigurationRecorderStatus(input: models.DescribeConfigurationRecorderStatusRequest): F[models.DescribeConfigurationRecorderStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeConfigurationRecorderStatusResponse, models.DescribeConfigurationRecorderStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurationRecorderStatus", POST, "/", input)
  override def listDiscoveredResources(input: models.ListDiscoveredResourcesRequest): F[models.ListDiscoveredResourcesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListDiscoveredResourcesResponse, models.ListDiscoveredResourcesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListDiscoveredResources", POST, "/", input)
  override def stopConfigurationRecorder(input: models.StopConfigurationRecorderRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.StopConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopConfigurationRecorder", POST, "/", input)
  override def describeComplianceByResource(input: models.DescribeComplianceByResourceRequest): F[models.DescribeComplianceByResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeComplianceByResourceResponse, models.DescribeComplianceByResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeComplianceByResource", POST, "/", input)
  override def describeComplianceByConfigRule(input: models.DescribeComplianceByConfigRuleRequest): F[models.DescribeComplianceByConfigRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeComplianceByConfigRuleResponse, models.DescribeComplianceByConfigRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeComplianceByConfigRule", POST, "/", input)
  override def deleteConfigurationRecorder(input: models.DeleteConfigurationRecorderRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.DeleteConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteConfigurationRecorder", POST, "/", input)
  override def startConfigRulesEvaluation(input: models.StartConfigRulesEvaluationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.StartConfigRulesEvaluationRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartConfigRulesEvaluation", POST, "/", input)
  override def putDeliveryChannel(input: models.PutDeliveryChannelRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.PutDeliveryChannelRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutDeliveryChannel", POST, "/", input)
  override def getComplianceDetailsByResource(input: models.GetComplianceDetailsByResourceRequest): F[models.GetComplianceDetailsByResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetComplianceDetailsByResourceResponse, models.GetComplianceDetailsByResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceDetailsByResource", POST, "/", input)
  override def startConfigurationRecorder(input: models.StartConfigurationRecorderRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.StartConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartConfigurationRecorder", POST, "/", input)
  override def describeConfigurationRecorders(input: models.DescribeConfigurationRecordersRequest): F[models.DescribeConfigurationRecordersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeConfigurationRecordersResponse, models.DescribeConfigurationRecordersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurationRecorders", POST, "/", input)
  override def describeConfigRules(input: models.DescribeConfigRulesRequest): F[models.DescribeConfigRulesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeConfigRulesResponse, models.DescribeConfigRulesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigRules", POST, "/", input)
  override def getComplianceSummaryByResourceType(input: models.GetComplianceSummaryByResourceTypeRequest): F[models.GetComplianceSummaryByResourceTypeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetComplianceSummaryByResourceTypeResponse, models.GetComplianceSummaryByResourceTypeRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceSummaryByResourceType", POST, "/", input)
  override def putConfigurationRecorder(input: models.PutConfigurationRecorderRequest): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.PutConfigurationRecorderRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutConfigurationRecorder", POST, "/", input)
  override def getComplianceSummaryByConfigRule: F[models.GetComplianceSummaryByConfigRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequestWithoutBody[F, models.GetComplianceSummaryByConfigRuleResponse](client, awsData, ServiceType, ServiceAndPrefix, "GetComplianceSummaryByConfigRule", POST, "/")
  override def putEvaluations(input: models.PutEvaluationsRequest): F[models.PutEvaluationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutEvaluationsResponse, models.PutEvaluationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutEvaluations", POST, "/", input)
}