package org.lyranthe.araethura.kinesisfirehose.http4s
import org.http4s.Method._
import org.lyranthe.araethura.kinesisfirehose.circe._
import org.lyranthe.araethura.kinesisfirehose.models
class AmazonkinesisfirehoseClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.kinesisfirehose.Amazonkinesisfirehose[F] {
  private[this] final val ServiceType: String = "firehose"
  private[this] final val ServiceAndPrefix: Option[String] = Some("Firehose_20150804")
  override def updateDestination(input: org.lyranthe.araethura.kinesisfirehose.models.UpdateDestinationInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.kinesisfirehose.models.UpdateDestinationInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDestination", POST, "/", input)
  override def describeDeliveryStream(input: org.lyranthe.araethura.kinesisfirehose.models.DescribeDeliveryStreamInput): F[org.lyranthe.araethura.kinesisfirehose.models.DescribeDeliveryStreamOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.kinesisfirehose.models.DescribeDeliveryStreamOutput, org.lyranthe.araethura.kinesisfirehose.models.DescribeDeliveryStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryStream", POST, "/", input)
  override def putRecord(input: org.lyranthe.araethura.kinesisfirehose.models.PutRecordInput): F[org.lyranthe.araethura.kinesisfirehose.models.PutRecordOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.kinesisfirehose.models.PutRecordOutput, org.lyranthe.araethura.kinesisfirehose.models.PutRecordInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecord", POST, "/", input)
  override def listDeliveryStreams(input: org.lyranthe.araethura.kinesisfirehose.models.ListDeliveryStreamsInput): F[org.lyranthe.araethura.kinesisfirehose.models.ListDeliveryStreamsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.kinesisfirehose.models.ListDeliveryStreamsOutput, org.lyranthe.araethura.kinesisfirehose.models.ListDeliveryStreamsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListDeliveryStreams", POST, "/", input)
  override def createDeliveryStream(input: org.lyranthe.araethura.kinesisfirehose.models.CreateDeliveryStreamInput): F[org.lyranthe.araethura.kinesisfirehose.models.CreateDeliveryStreamOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.kinesisfirehose.models.CreateDeliveryStreamOutput, org.lyranthe.araethura.kinesisfirehose.models.CreateDeliveryStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateDeliveryStream", POST, "/", input)
  override def deleteDeliveryStream(input: org.lyranthe.araethura.kinesisfirehose.models.DeleteDeliveryStreamInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.kinesisfirehose.models.DeleteDeliveryStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDeliveryStream", POST, "/", input)
  override def putRecordBatch(input: org.lyranthe.araethura.kinesisfirehose.models.PutRecordBatchInput): F[org.lyranthe.araethura.kinesisfirehose.models.PutRecordBatchOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.kinesisfirehose.models.PutRecordBatchOutput, org.lyranthe.araethura.kinesisfirehose.models.PutRecordBatchInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecordBatch", POST, "/", input)
}