package org.lyranthe.araethura.athena.models
import org.lyranthe.araethura.athena.models
final case class DeleteNamedQueryInput(namedQueryId: java.lang.String)
final case class BatchGetQueryExecutionOutput(queryExecutions: scala.Option[scala.List[models.QueryExecution]] = None, unprocessedQueryExecutionIds: scala.Option[scala.List[models.UnprocessedQueryExecutionId]] = None)
final case class ListNamedQueriesOutput(namedQueryIds: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class EncryptionConfiguration(encryptionOption: java.lang.String, kmsKey: scala.Option[java.lang.String] = None)
final case class QueryExecution(query: scala.Option[java.lang.String] = None, queryExecutionId: scala.Option[java.lang.String] = None, resultConfiguration: scala.Option[models.ResultConfiguration] = None, status: scala.Option[models.QueryExecutionStatus] = None, queryExecutionContext: scala.Option[models.QueryExecutionContext] = None, statistics: scala.Option[models.QueryExecutionStatistics] = None)
final case class UnprocessedNamedQueryId(namedQueryId: scala.Option[java.lang.String] = None, errorCode: scala.Option[java.lang.String] = None, errorMessage: scala.Option[java.lang.String] = None)
final case class Datum(varCharValue: scala.Option[java.lang.String] = None)
final case class ListNamedQueriesInput(nextToken: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None)
final case class ResultConfiguration(outputLocation: java.lang.String, encryptionConfiguration: scala.Option[models.EncryptionConfiguration] = None)
final case class StartQueryExecutionOutput(queryExecutionId: scala.Option[java.lang.String] = None)
final case class BatchGetQueryExecutionInput(queryExecutionIds: scala.List[java.lang.String])
final case class ListQueryExecutionsInput(nextToken: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None)
final case class UnprocessedQueryExecutionId(queryExecutionId: scala.Option[java.lang.String] = None, errorCode: scala.Option[java.lang.String] = None, errorMessage: scala.Option[java.lang.String] = None)
final case class ResultSetMetadata(columnInfo: scala.Option[scala.List[models.ColumnInfo]] = None)
case object StopQueryExecutionOutput
case object DeleteNamedQueryOutput
final case class InternalServerException(message: scala.Option[java.lang.String] = None)
final case class ColumnInfo(name: java.lang.String, `type`: java.lang.String, schemaName: scala.Option[java.lang.String] = None, catalogName: scala.Option[java.lang.String] = None, tableName: scala.Option[java.lang.String] = None, label: scala.Option[java.lang.String] = None, precision: scala.Option[scala.Int] = None, scale: scala.Option[scala.Int] = None, nullable: scala.Option[java.lang.String] = None, caseSensitive: scala.Option[scala.Boolean] = None)
final case class GetQueryExecutionInput(queryExecutionId: java.lang.String)
final case class BatchGetNamedQueryInput(namedQueryIds: scala.List[java.lang.String])
final case class Row(data: scala.Option[scala.List[models.Datum]] = None)
final case class ListQueryExecutionsOutput(queryExecutionIds: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class QueryExecutionStatus(state: scala.Option[java.lang.String] = None, stateChangeReason: scala.Option[java.lang.String] = None, submissionDateTime: scala.Option[java.time.Instant] = None, completionDateTime: scala.Option[java.time.Instant] = None)
final case class InvalidRequestException(athenaErrorCode: scala.Option[java.lang.String] = None, message: scala.Option[java.lang.String] = None)
final case class BatchGetNamedQueryOutput(namedQueries: scala.Option[scala.List[models.NamedQuery]] = None, unprocessedNamedQueryIds: scala.Option[scala.List[models.UnprocessedNamedQueryId]] = None)
final case class GetQueryResultsInput(queryExecutionId: java.lang.String, nextToken: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None)
final case class StopQueryExecutionInput(queryExecutionId: java.lang.String)
final case class GetQueryExecutionOutput(queryExecution: scala.Option[models.QueryExecution] = None)
final case class GetNamedQueryInput(namedQueryId: java.lang.String)
final case class StartQueryExecutionInput(queryString: java.lang.String, resultConfiguration: models.ResultConfiguration, clientRequestToken: scala.Option[java.lang.String] = None, queryExecutionContext: scala.Option[models.QueryExecutionContext] = None)
final case class GetNamedQueryOutput(namedQuery: scala.Option[models.NamedQuery] = None)
final case class CreateNamedQueryInput(queryString: java.lang.String, name: java.lang.String, database: java.lang.String, clientRequestToken: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None)
final case class QueryExecutionContext(database: scala.Option[java.lang.String] = None)
final case class TooManyRequestsException(message: scala.Option[java.lang.String] = None, reason: scala.Option[java.lang.String] = None)
final case class NamedQuery(queryString: java.lang.String, name: java.lang.String, database: java.lang.String, description: scala.Option[java.lang.String] = None, namedQueryId: scala.Option[java.lang.String] = None)
final case class ResultSet(rows: scala.Option[scala.List[models.Row]] = None, resultSetMetadata: scala.Option[models.ResultSetMetadata] = None)
final case class CreateNamedQueryOutput(namedQueryId: scala.Option[java.lang.String] = None)
final case class QueryExecutionStatistics(engineExecutionTimeInMillis: scala.Option[scala.Long] = None, dataScannedInBytes: scala.Option[scala.Long] = None)
final case class GetQueryResultsOutput(resultSet: scala.Option[models.ResultSet] = None, nextToken: scala.Option[java.lang.String] = None)