package org.lyranthe.araethura.stepfunctions.http4s
import org.http4s.Method._
import org.lyranthe.araethura.stepfunctions.circe._
import org.lyranthe.araethura.stepfunctions.models
class AmazonstepfunctionsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.stepfunctions.Amazonstepfunctions[F] {
  private[this] final val ServiceType: String = "states"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSStepFunctions")
  override def listStateMachines(input: models.ListStateMachinesInput): F[models.ListStateMachinesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListStateMachinesOutput, models.ListStateMachinesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListStateMachines", POST, "/", input)
  override def createActivity(input: models.CreateActivityInput): F[models.CreateActivityOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateActivityOutput, models.CreateActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateActivity", POST, "/", input)
  override def startExecution(input: models.StartExecutionInput): F[models.StartExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StartExecutionOutput, models.StartExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartExecution", POST, "/", input)
  override def sendTaskFailure(input: models.SendTaskFailureInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.SendTaskFailureInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskFailure", POST, "/", input)
  override def describeActivity(input: models.DescribeActivityInput): F[models.DescribeActivityOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeActivityOutput, models.DescribeActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeActivity", POST, "/", input)
  override def stopExecution(input: models.StopExecutionInput): F[models.StopExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StopExecutionOutput, models.StopExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopExecution", POST, "/", input)
  override def deleteActivity(input: models.DeleteActivityInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteActivity", POST, "/", input)
  override def describeStateMachineForExecution(input: models.DescribeStateMachineForExecutionInput): F[models.DescribeStateMachineForExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeStateMachineForExecutionOutput, models.DescribeStateMachineForExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStateMachineForExecution", POST, "/", input)
  override def getExecutionHistory(input: models.GetExecutionHistoryInput): F[models.GetExecutionHistoryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetExecutionHistoryOutput, models.GetExecutionHistoryInput](client, awsData, ServiceType, ServiceAndPrefix, "GetExecutionHistory", POST, "/", input)
  override def listActivities(input: models.ListActivitiesInput): F[models.ListActivitiesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListActivitiesOutput, models.ListActivitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListActivities", POST, "/", input)
  override def deleteStateMachine(input: models.DeleteStateMachineInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteStateMachine", POST, "/", input)
  override def updateStateMachine(input: models.UpdateStateMachineInput): F[models.UpdateStateMachineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateStateMachineOutput, models.UpdateStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateStateMachine", POST, "/", input)
  override def createStateMachine(input: models.CreateStateMachineInput): F[models.CreateStateMachineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateStateMachineOutput, models.CreateStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateStateMachine", POST, "/", input)
  override def getActivityTask(input: models.GetActivityTaskInput): F[models.GetActivityTaskOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetActivityTaskOutput, models.GetActivityTaskInput](client, awsData, ServiceType, ServiceAndPrefix, "GetActivityTask", POST, "/", input)
  override def sendTaskHeartbeat(input: models.SendTaskHeartbeatInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.SendTaskHeartbeatInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskHeartbeat", POST, "/", input)
  override def listExecutions(input: models.ListExecutionsInput): F[models.ListExecutionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListExecutionsOutput, models.ListExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListExecutions", POST, "/", input)
  override def sendTaskSuccess(input: models.SendTaskSuccessInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.SendTaskSuccessInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskSuccess", POST, "/", input)
  override def describeStateMachine(input: models.DescribeStateMachineInput): F[models.DescribeStateMachineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeStateMachineOutput, models.DescribeStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStateMachine", POST, "/", input)
  override def describeExecution(input: models.DescribeExecutionInput): F[models.DescribeExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeExecutionOutput, models.DescribeExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExecution", POST, "/", input)
}