package org.lyranthe.araethura.stepfunctions.http4s
import org.http4s.Method._
import org.lyranthe.araethura.stepfunctions.circe._
import org.lyranthe.araethura.stepfunctions.models
class AmazonstepfunctionsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.stepfunctions.Amazonstepfunctions[F] {
  private[this] final val ServiceType: String = "states"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSStepFunctions")
  override def listStateMachines(input: org.lyranthe.araethura.stepfunctions.models.ListStateMachinesInput): F[org.lyranthe.araethura.stepfunctions.models.ListStateMachinesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.ListStateMachinesOutput, org.lyranthe.araethura.stepfunctions.models.ListStateMachinesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListStateMachines", POST, "/", input)
  override def createActivity(input: org.lyranthe.araethura.stepfunctions.models.CreateActivityInput): F[org.lyranthe.araethura.stepfunctions.models.CreateActivityOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.CreateActivityOutput, org.lyranthe.araethura.stepfunctions.models.CreateActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateActivity", POST, "/", input)
  override def startExecution(input: org.lyranthe.araethura.stepfunctions.models.StartExecutionInput): F[org.lyranthe.araethura.stepfunctions.models.StartExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.StartExecutionOutput, org.lyranthe.araethura.stepfunctions.models.StartExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartExecution", POST, "/", input)
  override def sendTaskFailure(input: org.lyranthe.araethura.stepfunctions.models.SendTaskFailureInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.stepfunctions.models.SendTaskFailureInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskFailure", POST, "/", input)
  override def describeActivity(input: org.lyranthe.araethura.stepfunctions.models.DescribeActivityInput): F[org.lyranthe.araethura.stepfunctions.models.DescribeActivityOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.DescribeActivityOutput, org.lyranthe.araethura.stepfunctions.models.DescribeActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeActivity", POST, "/", input)
  override def stopExecution(input: org.lyranthe.araethura.stepfunctions.models.StopExecutionInput): F[org.lyranthe.araethura.stepfunctions.models.StopExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.StopExecutionOutput, org.lyranthe.araethura.stepfunctions.models.StopExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopExecution", POST, "/", input)
  override def deleteActivity(input: org.lyranthe.araethura.stepfunctions.models.DeleteActivityInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.stepfunctions.models.DeleteActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteActivity", POST, "/", input)
  override def describeStateMachineForExecution(input: org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineForExecutionInput): F[org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineForExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineForExecutionOutput, org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineForExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStateMachineForExecution", POST, "/", input)
  override def getExecutionHistory(input: org.lyranthe.araethura.stepfunctions.models.GetExecutionHistoryInput): F[org.lyranthe.araethura.stepfunctions.models.GetExecutionHistoryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.GetExecutionHistoryOutput, org.lyranthe.araethura.stepfunctions.models.GetExecutionHistoryInput](client, awsData, ServiceType, ServiceAndPrefix, "GetExecutionHistory", POST, "/", input)
  override def listActivities(input: org.lyranthe.araethura.stepfunctions.models.ListActivitiesInput): F[org.lyranthe.araethura.stepfunctions.models.ListActivitiesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.ListActivitiesOutput, org.lyranthe.araethura.stepfunctions.models.ListActivitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListActivities", POST, "/", input)
  override def deleteStateMachine(input: org.lyranthe.araethura.stepfunctions.models.DeleteStateMachineInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.stepfunctions.models.DeleteStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteStateMachine", POST, "/", input)
  override def updateStateMachine(input: org.lyranthe.araethura.stepfunctions.models.UpdateStateMachineInput): F[org.lyranthe.araethura.stepfunctions.models.UpdateStateMachineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.UpdateStateMachineOutput, org.lyranthe.araethura.stepfunctions.models.UpdateStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateStateMachine", POST, "/", input)
  override def createStateMachine(input: org.lyranthe.araethura.stepfunctions.models.CreateStateMachineInput): F[org.lyranthe.araethura.stepfunctions.models.CreateStateMachineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.CreateStateMachineOutput, org.lyranthe.araethura.stepfunctions.models.CreateStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateStateMachine", POST, "/", input)
  override def getActivityTask(input: org.lyranthe.araethura.stepfunctions.models.GetActivityTaskInput): F[org.lyranthe.araethura.stepfunctions.models.GetActivityTaskOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.GetActivityTaskOutput, org.lyranthe.araethura.stepfunctions.models.GetActivityTaskInput](client, awsData, ServiceType, ServiceAndPrefix, "GetActivityTask", POST, "/", input)
  override def sendTaskHeartbeat(input: org.lyranthe.araethura.stepfunctions.models.SendTaskHeartbeatInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.stepfunctions.models.SendTaskHeartbeatInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskHeartbeat", POST, "/", input)
  override def listExecutions(input: org.lyranthe.araethura.stepfunctions.models.ListExecutionsInput): F[org.lyranthe.araethura.stepfunctions.models.ListExecutionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.ListExecutionsOutput, org.lyranthe.araethura.stepfunctions.models.ListExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListExecutions", POST, "/", input)
  override def sendTaskSuccess(input: org.lyranthe.araethura.stepfunctions.models.SendTaskSuccessInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.stepfunctions.models.SendTaskSuccessInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskSuccess", POST, "/", input)
  override def describeStateMachine(input: org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineInput): F[org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineOutput, org.lyranthe.araethura.stepfunctions.models.DescribeStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStateMachine", POST, "/", input)
  override def describeExecution(input: org.lyranthe.araethura.stepfunctions.models.DescribeExecutionInput): F[org.lyranthe.araethura.stepfunctions.models.DescribeExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.stepfunctions.models.DescribeExecutionOutput, org.lyranthe.araethura.stepfunctions.models.DescribeExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExecution", POST, "/", input)
}