package org.lyranthe.araethura.support.models
import org.lyranthe.araethura.support.models
final case class DescribeCommunicationsRequest(caseId: java.lang.String, beforeTime: scala.Option[java.lang.String] = None, afterTime: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DescribeServicesResponse(services: scala.Option[scala.List[models.Service]] = None)
final case class DescribeTrustedAdvisorCheckResultRequest(checkId: java.lang.String, language: scala.Option[java.lang.String] = None)
final case class AddCommunicationToCaseResponse(result: scala.Option[scala.Boolean] = None)
final case class DescribeTrustedAdvisorCheckSummariesRequest(checkIds: scala.List[java.lang.String])
final case class DescribeAttachmentResponse(attachment: scala.Option[models.Attachment] = None)
final case class AttachmentSetIdNotFound(message: scala.Option[java.lang.String] = None)
final case class AddAttachmentsToSetResponse(attachmentSetId: scala.Option[java.lang.String] = None, expiryTime: scala.Option[java.lang.String] = None)
final case class TrustedAdvisorCheckRefreshStatus(checkId: java.lang.String, status: java.lang.String, millisUntilNextRefreshable: scala.Long)
final case class AttachmentLimitExceeded(message: scala.Option[java.lang.String] = None)
final case class DescribeAttachmentRequest(attachmentId: java.lang.String)
final case class DescribeSeverityLevelsRequest(language: scala.Option[java.lang.String] = None)
final case class AttachmentDetails(attachmentId: scala.Option[java.lang.String] = None, fileName: scala.Option[java.lang.String] = None)
final case class TrustedAdvisorResourceDetail(status: java.lang.String, resourceId: java.lang.String, metadata: scala.List[java.lang.String], region: scala.Option[java.lang.String] = None, isSuppressed: scala.Option[scala.Boolean] = None)
final case class DescribeCasesRequest(beforeTime: scala.Option[java.lang.String] = None, language: scala.Option[java.lang.String] = None, caseIdList: scala.Option[scala.List[java.lang.String]] = None, includeResolvedCases: scala.Option[scala.Boolean] = None, afterTime: scala.Option[java.lang.String] = None, displayId: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None, includeCommunications: scala.Option[scala.Boolean] = None, nextToken: scala.Option[java.lang.String] = None)
final case class AddCommunicationToCaseRequest(communicationBody: java.lang.String, caseId: scala.Option[java.lang.String] = None, ccEmailAddresses: scala.Option[scala.List[java.lang.String]] = None, attachmentSetId: scala.Option[java.lang.String] = None)
final case class DescribeSeverityLevelsResponse(severityLevels: scala.Option[scala.List[models.SeverityLevel]] = None)
final case class DescribeTrustedAdvisorCheckResultResponse(result: scala.Option[models.TrustedAdvisorCheckResult] = None)
final case class DescribeTrustedAdvisorCheckSummariesResponse(summaries: scala.List[models.TrustedAdvisorCheckSummary])
final case class RefreshTrustedAdvisorCheckResponse(status: models.TrustedAdvisorCheckRefreshStatus)
final case class RecentCaseCommunications(communications: scala.Option[scala.List[models.Communication]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class CaseIdNotFound(message: scala.Option[java.lang.String] = None)
final case class AttachmentSetExpired(message: scala.Option[java.lang.String] = None)
final case class Category(code: scala.Option[java.lang.String] = None, name: scala.Option[java.lang.String] = None)
final case class TrustedAdvisorCheckResult(checkId: java.lang.String, timestamp: java.lang.String, status: java.lang.String, resourcesSummary: models.TrustedAdvisorResourcesSummary, categorySpecificSummary: models.TrustedAdvisorCategorySpecificSummary, flaggedResources: scala.List[models.TrustedAdvisorResourceDetail])
final case class TrustedAdvisorResourcesSummary(resourcesProcessed: scala.Long, resourcesFlagged: scala.Long, resourcesIgnored: scala.Long, resourcesSuppressed: scala.Long)
final case class DescribeCasesResponse(cases: scala.Option[scala.List[models.CaseDetails]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class ResolveCaseRequest(caseId: scala.Option[java.lang.String] = None)
final case class TrustedAdvisorCheckDescription(id: java.lang.String, name: java.lang.String, description: java.lang.String, category: java.lang.String, metadata: scala.List[java.lang.String])
final case class CreateCaseRequest(communicationBody: java.lang.String, subject: java.lang.String, categoryCode: scala.Option[java.lang.String] = None, issueType: scala.Option[java.lang.String] = None, language: scala.Option[java.lang.String] = None, severityCode: scala.Option[java.lang.String] = None, serviceCode: scala.Option[java.lang.String] = None, ccEmailAddresses: scala.Option[scala.List[java.lang.String]] = None, attachmentSetId: scala.Option[java.lang.String] = None)
final case class AddAttachmentsToSetRequest(attachments: scala.List[models.Attachment], attachmentSetId: scala.Option[java.lang.String] = None)
final case class AttachmentSetSizeLimitExceeded(message: scala.Option[java.lang.String] = None)
final case class DescribeServicesRequest(serviceCodeList: scala.Option[scala.List[java.lang.String]] = None, language: scala.Option[java.lang.String] = None)
final case class CaseDetails(status: scala.Option[java.lang.String] = None, categoryCode: scala.Option[java.lang.String] = None, language: scala.Option[java.lang.String] = None, severityCode: scala.Option[java.lang.String] = None, serviceCode: scala.Option[java.lang.String] = None, submittedBy: scala.Option[java.lang.String] = None, ccEmailAddresses: scala.Option[scala.List[java.lang.String]] = None, timeCreated: scala.Option[java.lang.String] = None, displayId: scala.Option[java.lang.String] = None, recentCommunications: scala.Option[models.RecentCaseCommunications] = None, subject: scala.Option[java.lang.String] = None, caseId: scala.Option[java.lang.String] = None)
final case class AttachmentIdNotFound(message: scala.Option[java.lang.String] = None)
final case class ResolveCaseResponse(initialCaseStatus: scala.Option[java.lang.String] = None, finalCaseStatus: scala.Option[java.lang.String] = None)
final case class DescribeTrustedAdvisorChecksRequest(language: java.lang.String)
final case class CreateCaseResponse(caseId: scala.Option[java.lang.String] = None)
final case class Service(code: scala.Option[java.lang.String] = None, name: scala.Option[java.lang.String] = None, categories: scala.Option[scala.List[models.Category]] = None)
final case class Attachment(fileName: scala.Option[java.lang.String] = None, data: scala.Option[scala.Array[scala.Byte]] = None)
final case class TrustedAdvisorCategorySpecificSummary(costOptimizing: scala.Option[models.TrustedAdvisorCostOptimizingSummary] = None)
final case class RefreshTrustedAdvisorCheckRequest(checkId: java.lang.String)
final case class SeverityLevel(code: scala.Option[java.lang.String] = None, name: scala.Option[java.lang.String] = None)
final case class Communication(submittedBy: scala.Option[java.lang.String] = None, timeCreated: scala.Option[java.lang.String] = None, body: scala.Option[java.lang.String] = None, attachmentSet: scala.Option[scala.List[models.AttachmentDetails]] = None, caseId: scala.Option[java.lang.String] = None)
final case class DescribeTrustedAdvisorCheckRefreshStatusesResponse(statuses: scala.List[models.TrustedAdvisorCheckRefreshStatus])
final case class TrustedAdvisorCheckSummary(checkId: java.lang.String, timestamp: java.lang.String, status: java.lang.String, resourcesSummary: models.TrustedAdvisorResourcesSummary, categorySpecificSummary: models.TrustedAdvisorCategorySpecificSummary, hasFlaggedResources: scala.Option[scala.Boolean] = None)
final case class DescribeTrustedAdvisorCheckRefreshStatusesRequest(checkIds: scala.List[java.lang.String])
final case class DescribeAttachmentLimitExceeded(message: scala.Option[java.lang.String] = None)
final case class InternalServerError(message: scala.Option[java.lang.String] = None)
final case class TrustedAdvisorCostOptimizingSummary(estimatedMonthlySavings: scala.Double, estimatedPercentMonthlySavings: scala.Double)
final case class CaseCreationLimitExceeded(message: scala.Option[java.lang.String] = None)
final case class DescribeCommunicationsResponse(communications: scala.Option[scala.List[models.Communication]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DescribeTrustedAdvisorChecksResponse(checks: scala.List[models.TrustedAdvisorCheckDescription])