package org.lyranthe.araethura.support.models
final case class DescribeCommunicationsRequest(caseId: java.lang.String, beforeTime: scala.Option[java.lang.String] = scala.None, afterTime: scala.Option[java.lang.String] = scala.None, maxResults: scala.Option[scala.Int] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class DescribeServicesResponse(services: scala.Option[scala.List[org.lyranthe.araethura.support.models.Service]] = scala.None)
final case class DescribeTrustedAdvisorCheckResultRequest(checkId: java.lang.String, language: scala.Option[java.lang.String] = scala.None)
final case class AddCommunicationToCaseResponse(result: scala.Option[scala.Boolean] = scala.None)
final case class DescribeTrustedAdvisorCheckSummariesRequest(checkIds: scala.List[java.lang.String])
final case class DescribeAttachmentResponse(attachment: scala.Option[org.lyranthe.araethura.support.models.Attachment] = scala.None)
final case class AttachmentSetIdNotFound(message: scala.Option[java.lang.String] = scala.None)
final case class AddAttachmentsToSetResponse(attachmentSetId: scala.Option[java.lang.String] = scala.None, expiryTime: scala.Option[java.lang.String] = scala.None)
final case class TrustedAdvisorCheckRefreshStatus(checkId: java.lang.String, status: java.lang.String, millisUntilNextRefreshable: scala.Long)
final case class AttachmentLimitExceeded(message: scala.Option[java.lang.String] = scala.None)
final case class DescribeAttachmentRequest(attachmentId: java.lang.String)
final case class DescribeSeverityLevelsRequest(language: scala.Option[java.lang.String] = scala.None)
final case class AttachmentDetails(attachmentId: scala.Option[java.lang.String] = scala.None, fileName: scala.Option[java.lang.String] = scala.None)
final case class TrustedAdvisorResourceDetail(status: java.lang.String, resourceId: java.lang.String, metadata: scala.List[java.lang.String], region: scala.Option[java.lang.String] = scala.None, isSuppressed: scala.Option[scala.Boolean] = scala.None)
final case class DescribeCasesRequest(beforeTime: scala.Option[java.lang.String] = scala.None, language: scala.Option[java.lang.String] = scala.None, caseIdList: scala.Option[scala.List[java.lang.String]] = scala.None, includeResolvedCases: scala.Option[scala.Boolean] = scala.None, afterTime: scala.Option[java.lang.String] = scala.None, displayId: scala.Option[java.lang.String] = scala.None, maxResults: scala.Option[scala.Int] = scala.None, includeCommunications: scala.Option[scala.Boolean] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class AddCommunicationToCaseRequest(communicationBody: java.lang.String, caseId: scala.Option[java.lang.String] = scala.None, ccEmailAddresses: scala.Option[scala.List[java.lang.String]] = scala.None, attachmentSetId: scala.Option[java.lang.String] = scala.None)
final case class DescribeSeverityLevelsResponse(severityLevels: scala.Option[scala.List[org.lyranthe.araethura.support.models.SeverityLevel]] = scala.None)
final case class DescribeTrustedAdvisorCheckResultResponse(result: scala.Option[org.lyranthe.araethura.support.models.TrustedAdvisorCheckResult] = scala.None)
final case class DescribeTrustedAdvisorCheckSummariesResponse(summaries: scala.List[org.lyranthe.araethura.support.models.TrustedAdvisorCheckSummary])
final case class RefreshTrustedAdvisorCheckResponse(status: org.lyranthe.araethura.support.models.TrustedAdvisorCheckRefreshStatus)
final case class RecentCaseCommunications(communications: scala.Option[scala.List[org.lyranthe.araethura.support.models.Communication]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class CaseIdNotFound(message: scala.Option[java.lang.String] = scala.None)
final case class AttachmentSetExpired(message: scala.Option[java.lang.String] = scala.None)
final case class Category(code: scala.Option[java.lang.String] = scala.None, name: scala.Option[java.lang.String] = scala.None)
final case class TrustedAdvisorCheckResult(checkId: java.lang.String, timestamp: java.lang.String, status: java.lang.String, resourcesSummary: org.lyranthe.araethura.support.models.TrustedAdvisorResourcesSummary, categorySpecificSummary: org.lyranthe.araethura.support.models.TrustedAdvisorCategorySpecificSummary, flaggedResources: scala.List[org.lyranthe.araethura.support.models.TrustedAdvisorResourceDetail])
final case class TrustedAdvisorResourcesSummary(resourcesProcessed: scala.Long, resourcesFlagged: scala.Long, resourcesIgnored: scala.Long, resourcesSuppressed: scala.Long)
final case class DescribeCasesResponse(cases: scala.Option[scala.List[org.lyranthe.araethura.support.models.CaseDetails]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class ResolveCaseRequest(caseId: scala.Option[java.lang.String] = scala.None)
final case class TrustedAdvisorCheckDescription(id: java.lang.String, name: java.lang.String, description: java.lang.String, category: java.lang.String, metadata: scala.List[java.lang.String])
final case class CreateCaseRequest(communicationBody: java.lang.String, subject: java.lang.String, categoryCode: scala.Option[java.lang.String] = scala.None, issueType: scala.Option[java.lang.String] = scala.None, language: scala.Option[java.lang.String] = scala.None, severityCode: scala.Option[java.lang.String] = scala.None, serviceCode: scala.Option[java.lang.String] = scala.None, ccEmailAddresses: scala.Option[scala.List[java.lang.String]] = scala.None, attachmentSetId: scala.Option[java.lang.String] = scala.None)
final case class AddAttachmentsToSetRequest(attachments: scala.List[org.lyranthe.araethura.support.models.Attachment], attachmentSetId: scala.Option[java.lang.String] = scala.None)
final case class AttachmentSetSizeLimitExceeded(message: scala.Option[java.lang.String] = scala.None)
final case class DescribeServicesRequest(serviceCodeList: scala.Option[scala.List[java.lang.String]] = scala.None, language: scala.Option[java.lang.String] = scala.None)
final case class CaseDetails(status: scala.Option[java.lang.String] = scala.None, categoryCode: scala.Option[java.lang.String] = scala.None, language: scala.Option[java.lang.String] = scala.None, severityCode: scala.Option[java.lang.String] = scala.None, serviceCode: scala.Option[java.lang.String] = scala.None, submittedBy: scala.Option[java.lang.String] = scala.None, ccEmailAddresses: scala.Option[scala.List[java.lang.String]] = scala.None, timeCreated: scala.Option[java.lang.String] = scala.None, displayId: scala.Option[java.lang.String] = scala.None, recentCommunications: scala.Option[org.lyranthe.araethura.support.models.RecentCaseCommunications] = scala.None, subject: scala.Option[java.lang.String] = scala.None, caseId: scala.Option[java.lang.String] = scala.None)
final case class AttachmentIdNotFound(message: scala.Option[java.lang.String] = scala.None)
final case class ResolveCaseResponse(initialCaseStatus: scala.Option[java.lang.String] = scala.None, finalCaseStatus: scala.Option[java.lang.String] = scala.None)
final case class DescribeTrustedAdvisorChecksRequest(language: java.lang.String)
final case class CreateCaseResponse(caseId: scala.Option[java.lang.String] = scala.None)
final case class Service(code: scala.Option[java.lang.String] = scala.None, name: scala.Option[java.lang.String] = scala.None, categories: scala.Option[scala.List[org.lyranthe.araethura.support.models.Category]] = scala.None)
final case class Attachment(fileName: scala.Option[java.lang.String] = scala.None, data: scala.Option[scala.Array[scala.Byte]] = scala.None)
final case class TrustedAdvisorCategorySpecificSummary(costOptimizing: scala.Option[org.lyranthe.araethura.support.models.TrustedAdvisorCostOptimizingSummary] = scala.None)
final case class RefreshTrustedAdvisorCheckRequest(checkId: java.lang.String)
final case class SeverityLevel(code: scala.Option[java.lang.String] = scala.None, name: scala.Option[java.lang.String] = scala.None)
final case class Communication(submittedBy: scala.Option[java.lang.String] = scala.None, timeCreated: scala.Option[java.lang.String] = scala.None, body: scala.Option[java.lang.String] = scala.None, attachmentSet: scala.Option[scala.List[org.lyranthe.araethura.support.models.AttachmentDetails]] = scala.None, caseId: scala.Option[java.lang.String] = scala.None)
final case class DescribeTrustedAdvisorCheckRefreshStatusesResponse(statuses: scala.List[org.lyranthe.araethura.support.models.TrustedAdvisorCheckRefreshStatus])
final case class TrustedAdvisorCheckSummary(checkId: java.lang.String, timestamp: java.lang.String, status: java.lang.String, resourcesSummary: org.lyranthe.araethura.support.models.TrustedAdvisorResourcesSummary, categorySpecificSummary: org.lyranthe.araethura.support.models.TrustedAdvisorCategorySpecificSummary, hasFlaggedResources: scala.Option[scala.Boolean] = scala.None)
final case class DescribeTrustedAdvisorCheckRefreshStatusesRequest(checkIds: scala.List[java.lang.String])
final case class DescribeAttachmentLimitExceeded(message: scala.Option[java.lang.String] = scala.None)
final case class InternalServerError(message: scala.Option[java.lang.String] = scala.None)
final case class TrustedAdvisorCostOptimizingSummary(estimatedMonthlySavings: scala.Double, estimatedPercentMonthlySavings: scala.Double)
final case class CaseCreationLimitExceeded(message: scala.Option[java.lang.String] = scala.None)
final case class DescribeCommunicationsResponse(communications: scala.Option[scala.List[org.lyranthe.araethura.support.models.Communication]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class DescribeTrustedAdvisorChecksResponse(checks: scala.List[org.lyranthe.araethura.support.models.TrustedAdvisorCheckDescription])