package org.lyranthe.araethura.workspaces.http4s
import org.http4s.Method._
import org.lyranthe.araethura.workspaces.circe._
import org.lyranthe.araethura.workspaces.models
class AmazonworkspacesClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.workspaces.Amazonworkspaces[F] {
  private[this] final val ServiceType: String = "workspaces"
  private[this] final val ServiceAndPrefix: Option[String] = Some("WorkspacesService")
  override def terminateWorkspaces(input: models.TerminateWorkspacesRequest): F[models.TerminateWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.TerminateWorkspacesResult, models.TerminateWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "TerminateWorkspaces", POST, "/", input)
  override def stopWorkspaces(input: models.StopWorkspacesRequest): F[models.StopWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StopWorkspacesResult, models.StopWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopWorkspaces", POST, "/", input)
  override def rebootWorkspaces(input: models.RebootWorkspacesRequest): F[models.RebootWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RebootWorkspacesResult, models.RebootWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebootWorkspaces", POST, "/", input)
  override def describeTags(input: models.DescribeTagsRequest): F[models.DescribeTagsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeTagsResult, models.DescribeTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTags", POST, "/", input)
  override def describeWorkspaceBundles(input: models.DescribeWorkspaceBundlesRequest): F[models.DescribeWorkspaceBundlesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeWorkspaceBundlesResult, models.DescribeWorkspaceBundlesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaceBundles", POST, "/", input)
  override def describeWorkspacesConnectionStatus(input: models.DescribeWorkspacesConnectionStatusRequest): F[models.DescribeWorkspacesConnectionStatusResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeWorkspacesConnectionStatusResult, models.DescribeWorkspacesConnectionStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspacesConnectionStatus", POST, "/", input)
  override def describeWorkspaceDirectories(input: models.DescribeWorkspaceDirectoriesRequest): F[models.DescribeWorkspaceDirectoriesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeWorkspaceDirectoriesResult, models.DescribeWorkspaceDirectoriesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaceDirectories", POST, "/", input)
  override def deleteTags(input: models.DeleteTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTags", POST, "/", input)
  override def createTags(input: models.CreateTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.CreateTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateTags", POST, "/", input)
  override def describeWorkspaces(input: models.DescribeWorkspacesRequest): F[models.DescribeWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeWorkspacesResult, models.DescribeWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaces", POST, "/", input)
  override def rebuildWorkspaces(input: models.RebuildWorkspacesRequest): F[models.RebuildWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RebuildWorkspacesResult, models.RebuildWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebuildWorkspaces", POST, "/", input)
  override def createWorkspaces(input: models.CreateWorkspacesRequest): F[models.CreateWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateWorkspacesResult, models.CreateWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateWorkspaces", POST, "/", input)
  override def startWorkspaces(input: models.StartWorkspacesRequest): F[models.StartWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StartWorkspacesResult, models.StartWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartWorkspaces", POST, "/", input)
  override def modifyWorkspaceProperties(input: models.ModifyWorkspacePropertiesRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.ModifyWorkspacePropertiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyWorkspaceProperties", POST, "/", input)
}