package org.lyranthe.araethura.workspaces.http4s
import org.http4s.Method._
import org.lyranthe.araethura.workspaces.circe._
import org.lyranthe.araethura.workspaces.models
class AmazonworkspacesClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.workspaces.Amazonworkspaces[F] {
  private[this] final val ServiceType: String = "workspaces"
  private[this] final val ServiceAndPrefix: Option[String] = Some("WorkspacesService")
  override def terminateWorkspaces(input: org.lyranthe.araethura.workspaces.models.TerminateWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.TerminateWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.TerminateWorkspacesResult, org.lyranthe.araethura.workspaces.models.TerminateWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "TerminateWorkspaces", POST, "/", input)
  override def stopWorkspaces(input: org.lyranthe.araethura.workspaces.models.StopWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.StopWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.StopWorkspacesResult, org.lyranthe.araethura.workspaces.models.StopWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopWorkspaces", POST, "/", input)
  override def rebootWorkspaces(input: org.lyranthe.araethura.workspaces.models.RebootWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.RebootWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.RebootWorkspacesResult, org.lyranthe.araethura.workspaces.models.RebootWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebootWorkspaces", POST, "/", input)
  override def describeTags(input: org.lyranthe.araethura.workspaces.models.DescribeTagsRequest): F[org.lyranthe.araethura.workspaces.models.DescribeTagsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.DescribeTagsResult, org.lyranthe.araethura.workspaces.models.DescribeTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTags", POST, "/", input)
  override def describeWorkspaceBundles(input: org.lyranthe.araethura.workspaces.models.DescribeWorkspaceBundlesRequest): F[org.lyranthe.araethura.workspaces.models.DescribeWorkspaceBundlesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.DescribeWorkspaceBundlesResult, org.lyranthe.araethura.workspaces.models.DescribeWorkspaceBundlesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaceBundles", POST, "/", input)
  override def describeWorkspacesConnectionStatus(input: org.lyranthe.araethura.workspaces.models.DescribeWorkspacesConnectionStatusRequest): F[org.lyranthe.araethura.workspaces.models.DescribeWorkspacesConnectionStatusResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.DescribeWorkspacesConnectionStatusResult, org.lyranthe.araethura.workspaces.models.DescribeWorkspacesConnectionStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspacesConnectionStatus", POST, "/", input)
  override def describeWorkspaceDirectories(input: org.lyranthe.araethura.workspaces.models.DescribeWorkspaceDirectoriesRequest): F[org.lyranthe.araethura.workspaces.models.DescribeWorkspaceDirectoriesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.DescribeWorkspaceDirectoriesResult, org.lyranthe.araethura.workspaces.models.DescribeWorkspaceDirectoriesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaceDirectories", POST, "/", input)
  override def deleteTags(input: org.lyranthe.araethura.workspaces.models.DeleteTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.workspaces.models.DeleteTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTags", POST, "/", input)
  override def createTags(input: org.lyranthe.araethura.workspaces.models.CreateTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.workspaces.models.CreateTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateTags", POST, "/", input)
  override def describeWorkspaces(input: org.lyranthe.araethura.workspaces.models.DescribeWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.DescribeWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.DescribeWorkspacesResult, org.lyranthe.araethura.workspaces.models.DescribeWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaces", POST, "/", input)
  override def rebuildWorkspaces(input: org.lyranthe.araethura.workspaces.models.RebuildWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.RebuildWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.RebuildWorkspacesResult, org.lyranthe.araethura.workspaces.models.RebuildWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebuildWorkspaces", POST, "/", input)
  override def createWorkspaces(input: org.lyranthe.araethura.workspaces.models.CreateWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.CreateWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.CreateWorkspacesResult, org.lyranthe.araethura.workspaces.models.CreateWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateWorkspaces", POST, "/", input)
  override def startWorkspaces(input: org.lyranthe.araethura.workspaces.models.StartWorkspacesRequest): F[org.lyranthe.araethura.workspaces.models.StartWorkspacesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.workspaces.models.StartWorkspacesResult, org.lyranthe.araethura.workspaces.models.StartWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartWorkspaces", POST, "/", input)
  override def modifyWorkspaceProperties(input: org.lyranthe.araethura.workspaces.models.ModifyWorkspacePropertiesRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.workspaces.models.ModifyWorkspacePropertiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyWorkspaceProperties", POST, "/", input)
}