package org.lyranthe.araethura.dax
trait Amazondax[F[_]] {
  def describeClusters(input: models.DescribeClustersRequest): F[models.DescribeClustersResponse]
  def describeEvents(input: models.DescribeEventsRequest): F[models.DescribeEventsResponse]
  def rebootNode(input: models.RebootNodeRequest): F[models.RebootNodeResponse]
  def tagResource(input: models.TagResourceRequest): F[models.TagResourceResponse]
  def createSubnetGroup(input: models.CreateSubnetGroupRequest): F[models.CreateSubnetGroupResponse]
  def describeParameterGroups(input: models.DescribeParameterGroupsRequest): F[models.DescribeParameterGroupsResponse]
  def untagResource(input: models.UntagResourceRequest): F[models.UntagResourceResponse]
  def deleteCluster(input: models.DeleteClusterRequest): F[models.DeleteClusterResponse]
  def deleteParameterGroup(input: models.DeleteParameterGroupRequest): F[models.DeleteParameterGroupResponse]
  def increaseReplicationFactor(input: models.IncreaseReplicationFactorRequest): F[models.IncreaseReplicationFactorResponse]
  def updateCluster(input: models.UpdateClusterRequest): F[models.UpdateClusterResponse]
  def listTags(input: models.ListTagsRequest): F[models.ListTagsResponse]
  def describeParameters(input: models.DescribeParametersRequest): F[models.DescribeParametersResponse]
  def deleteSubnetGroup(input: models.DeleteSubnetGroupRequest): F[models.DeleteSubnetGroupResponse]
  def describeSubnetGroups(input: models.DescribeSubnetGroupsRequest): F[models.DescribeSubnetGroupsResponse]
  def updateParameterGroup(input: models.UpdateParameterGroupRequest): F[models.UpdateParameterGroupResponse]
  def describeDefaultParameters(input: models.DescribeDefaultParametersRequest): F[models.DescribeDefaultParametersResponse]
  def createParameterGroup(input: models.CreateParameterGroupRequest): F[models.CreateParameterGroupResponse]
  def createCluster(input: models.CreateClusterRequest): F[models.CreateClusterResponse]
  def decreaseReplicationFactor(input: models.DecreaseReplicationFactorRequest): F[models.DecreaseReplicationFactorResponse]
  def updateSubnetGroup(input: models.UpdateSubnetGroupRequest): F[models.UpdateSubnetGroupResponse]
}