package org.lyranthe.araethura.dax
trait Amazondax[F[_]] {
  def describeClusters(input: org.lyranthe.araethura.dax.models.DescribeClustersRequest): F[org.lyranthe.araethura.dax.models.DescribeClustersResponse]
  def describeEvents(input: org.lyranthe.araethura.dax.models.DescribeEventsRequest): F[org.lyranthe.araethura.dax.models.DescribeEventsResponse]
  def rebootNode(input: org.lyranthe.araethura.dax.models.RebootNodeRequest): F[org.lyranthe.araethura.dax.models.RebootNodeResponse]
  def tagResource(input: org.lyranthe.araethura.dax.models.TagResourceRequest): F[org.lyranthe.araethura.dax.models.TagResourceResponse]
  def createSubnetGroup(input: org.lyranthe.araethura.dax.models.CreateSubnetGroupRequest): F[org.lyranthe.araethura.dax.models.CreateSubnetGroupResponse]
  def describeParameterGroups(input: org.lyranthe.araethura.dax.models.DescribeParameterGroupsRequest): F[org.lyranthe.araethura.dax.models.DescribeParameterGroupsResponse]
  def untagResource(input: org.lyranthe.araethura.dax.models.UntagResourceRequest): F[org.lyranthe.araethura.dax.models.UntagResourceResponse]
  def deleteCluster(input: org.lyranthe.araethura.dax.models.DeleteClusterRequest): F[org.lyranthe.araethura.dax.models.DeleteClusterResponse]
  def deleteParameterGroup(input: org.lyranthe.araethura.dax.models.DeleteParameterGroupRequest): F[org.lyranthe.araethura.dax.models.DeleteParameterGroupResponse]
  def increaseReplicationFactor(input: org.lyranthe.araethura.dax.models.IncreaseReplicationFactorRequest): F[org.lyranthe.araethura.dax.models.IncreaseReplicationFactorResponse]
  def updateCluster(input: org.lyranthe.araethura.dax.models.UpdateClusterRequest): F[org.lyranthe.araethura.dax.models.UpdateClusterResponse]
  def listTags(input: org.lyranthe.araethura.dax.models.ListTagsRequest): F[org.lyranthe.araethura.dax.models.ListTagsResponse]
  def describeParameters(input: org.lyranthe.araethura.dax.models.DescribeParametersRequest): F[org.lyranthe.araethura.dax.models.DescribeParametersResponse]
  def deleteSubnetGroup(input: org.lyranthe.araethura.dax.models.DeleteSubnetGroupRequest): F[org.lyranthe.araethura.dax.models.DeleteSubnetGroupResponse]
  def describeSubnetGroups(input: org.lyranthe.araethura.dax.models.DescribeSubnetGroupsRequest): F[org.lyranthe.araethura.dax.models.DescribeSubnetGroupsResponse]
  def updateParameterGroup(input: org.lyranthe.araethura.dax.models.UpdateParameterGroupRequest): F[org.lyranthe.araethura.dax.models.UpdateParameterGroupResponse]
  def describeDefaultParameters(input: org.lyranthe.araethura.dax.models.DescribeDefaultParametersRequest): F[org.lyranthe.araethura.dax.models.DescribeDefaultParametersResponse]
  def createParameterGroup(input: org.lyranthe.araethura.dax.models.CreateParameterGroupRequest): F[org.lyranthe.araethura.dax.models.CreateParameterGroupResponse]
  def createCluster(input: org.lyranthe.araethura.dax.models.CreateClusterRequest): F[org.lyranthe.araethura.dax.models.CreateClusterResponse]
  def decreaseReplicationFactor(input: org.lyranthe.araethura.dax.models.DecreaseReplicationFactorRequest): F[org.lyranthe.araethura.dax.models.DecreaseReplicationFactorResponse]
  def updateSubnetGroup(input: org.lyranthe.araethura.dax.models.UpdateSubnetGroupRequest): F[org.lyranthe.araethura.dax.models.UpdateSubnetGroupResponse]
}