package org.lyranthe.araethura.machinelearning.http4s
import org.http4s.Method._
import org.lyranthe.araethura.machinelearning.circe._
import org.lyranthe.araethura.machinelearning.models
class AmazonmachinelearningClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.machinelearning.Amazonmachinelearning[F] {
  private[this] final val ServiceType: String = "machinelearning"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AmazonML_20141212")
  override def describeTags(input: org.lyranthe.araethura.machinelearning.models.DescribeTagsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeTagsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DescribeTagsOutput, org.lyranthe.araethura.machinelearning.models.DescribeTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTags", POST, "/", input)
  override def createEvaluation(input: org.lyranthe.araethura.machinelearning.models.CreateEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.CreateEvaluationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateEvaluationOutput, org.lyranthe.araethura.machinelearning.models.CreateEvaluationInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateEvaluation", POST, "/", input)
  override def createDataSourceFromRedshift(input: org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRedshiftInput): F[org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRedshiftOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRedshiftOutput, org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRedshiftInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateDataSourceFromRedshift", POST, "/", input)
  override def describeBatchPredictions(input: org.lyranthe.araethura.machinelearning.models.DescribeBatchPredictionsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeBatchPredictionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DescribeBatchPredictionsOutput, org.lyranthe.araethura.machinelearning.models.DescribeBatchPredictionsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBatchPredictions", POST, "/", input)
  override def createDataSourceFromRDS(input: org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRDSInput): F[org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRDSOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRDSOutput, org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRDSInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateDataSourceFromRDS", POST, "/", input)
  override def createBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.CreateBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.CreateBatchPredictionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateBatchPredictionOutput, org.lyranthe.araethura.machinelearning.models.CreateBatchPredictionInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateBatchPrediction", POST, "/", input)
  override def addTags(input: org.lyranthe.araethura.machinelearning.models.AddTagsInput): F[org.lyranthe.araethura.machinelearning.models.AddTagsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.AddTagsOutput, org.lyranthe.araethura.machinelearning.models.AddTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTags", POST, "/", input)
  override def updateDataSource(input: org.lyranthe.araethura.machinelearning.models.UpdateDataSourceInput): F[org.lyranthe.araethura.machinelearning.models.UpdateDataSourceOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.UpdateDataSourceOutput, org.lyranthe.araethura.machinelearning.models.UpdateDataSourceInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDataSource", POST, "/", input)
  override def deleteMLModel(input: org.lyranthe.araethura.machinelearning.models.DeleteMLModelInput): F[org.lyranthe.araethura.machinelearning.models.DeleteMLModelOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DeleteMLModelOutput, org.lyranthe.araethura.machinelearning.models.DeleteMLModelInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteMLModel", POST, "/", input)
  override def deleteEvaluation(input: org.lyranthe.araethura.machinelearning.models.DeleteEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.DeleteEvaluationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DeleteEvaluationOutput, org.lyranthe.araethura.machinelearning.models.DeleteEvaluationInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteEvaluation", POST, "/", input)
  override def describeEvaluations(input: org.lyranthe.araethura.machinelearning.models.DescribeEvaluationsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeEvaluationsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DescribeEvaluationsOutput, org.lyranthe.araethura.machinelearning.models.DescribeEvaluationsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEvaluations", POST, "/", input)
  override def predict(input: org.lyranthe.araethura.machinelearning.models.PredictInput): F[org.lyranthe.araethura.machinelearning.models.PredictOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.PredictOutput, org.lyranthe.araethura.machinelearning.models.PredictInput](client, awsData, ServiceType, ServiceAndPrefix, "Predict", POST, "/", input)
  override def describeDataSources(input: org.lyranthe.araethura.machinelearning.models.DescribeDataSourcesInput): F[org.lyranthe.araethura.machinelearning.models.DescribeDataSourcesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DescribeDataSourcesOutput, org.lyranthe.araethura.machinelearning.models.DescribeDataSourcesInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDataSources", POST, "/", input)
  override def createDataSourceFromS3(input: org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromS3Input): F[org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromS3Output] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromS3Output, org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromS3Input](client, awsData, ServiceType, ServiceAndPrefix, "CreateDataSourceFromS3", POST, "/", input)
  override def deleteDataSource(input: org.lyranthe.araethura.machinelearning.models.DeleteDataSourceInput): F[org.lyranthe.araethura.machinelearning.models.DeleteDataSourceOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DeleteDataSourceOutput, org.lyranthe.araethura.machinelearning.models.DeleteDataSourceInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDataSource", POST, "/", input)
  override def getBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.GetBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.GetBatchPredictionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.GetBatchPredictionOutput, org.lyranthe.araethura.machinelearning.models.GetBatchPredictionInput](client, awsData, ServiceType, ServiceAndPrefix, "GetBatchPrediction", POST, "/", input)
  override def deleteRealtimeEndpoint(input: org.lyranthe.araethura.machinelearning.models.DeleteRealtimeEndpointInput): F[org.lyranthe.araethura.machinelearning.models.DeleteRealtimeEndpointOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DeleteRealtimeEndpointOutput, org.lyranthe.araethura.machinelearning.models.DeleteRealtimeEndpointInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteRealtimeEndpoint", POST, "/", input)
  override def describeMLModels(input: org.lyranthe.araethura.machinelearning.models.DescribeMLModelsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeMLModelsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DescribeMLModelsOutput, org.lyranthe.araethura.machinelearning.models.DescribeMLModelsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeMLModels", POST, "/", input)
  override def deleteBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.DeleteBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.DeleteBatchPredictionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DeleteBatchPredictionOutput, org.lyranthe.araethura.machinelearning.models.DeleteBatchPredictionInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteBatchPrediction", POST, "/", input)
  override def createMLModel(input: org.lyranthe.araethura.machinelearning.models.CreateMLModelInput): F[org.lyranthe.araethura.machinelearning.models.CreateMLModelOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateMLModelOutput, org.lyranthe.araethura.machinelearning.models.CreateMLModelInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateMLModel", POST, "/", input)
  override def updateBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.UpdateBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.UpdateBatchPredictionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.UpdateBatchPredictionOutput, org.lyranthe.araethura.machinelearning.models.UpdateBatchPredictionInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateBatchPrediction", POST, "/", input)
  override def getMLModel(input: org.lyranthe.araethura.machinelearning.models.GetMLModelInput): F[org.lyranthe.araethura.machinelearning.models.GetMLModelOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.GetMLModelOutput, org.lyranthe.araethura.machinelearning.models.GetMLModelInput](client, awsData, ServiceType, ServiceAndPrefix, "GetMLModel", POST, "/", input)
  override def updateMLModel(input: org.lyranthe.araethura.machinelearning.models.UpdateMLModelInput): F[org.lyranthe.araethura.machinelearning.models.UpdateMLModelOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.UpdateMLModelOutput, org.lyranthe.araethura.machinelearning.models.UpdateMLModelInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateMLModel", POST, "/", input)
  override def getEvaluation(input: org.lyranthe.araethura.machinelearning.models.GetEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.GetEvaluationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.GetEvaluationOutput, org.lyranthe.araethura.machinelearning.models.GetEvaluationInput](client, awsData, ServiceType, ServiceAndPrefix, "GetEvaluation", POST, "/", input)
  override def createRealtimeEndpoint(input: org.lyranthe.araethura.machinelearning.models.CreateRealtimeEndpointInput): F[org.lyranthe.araethura.machinelearning.models.CreateRealtimeEndpointOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.CreateRealtimeEndpointOutput, org.lyranthe.araethura.machinelearning.models.CreateRealtimeEndpointInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateRealtimeEndpoint", POST, "/", input)
  override def updateEvaluation(input: org.lyranthe.araethura.machinelearning.models.UpdateEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.UpdateEvaluationOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.UpdateEvaluationOutput, org.lyranthe.araethura.machinelearning.models.UpdateEvaluationInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateEvaluation", POST, "/", input)
  override def deleteTags(input: org.lyranthe.araethura.machinelearning.models.DeleteTagsInput): F[org.lyranthe.araethura.machinelearning.models.DeleteTagsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.DeleteTagsOutput, org.lyranthe.araethura.machinelearning.models.DeleteTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTags", POST, "/", input)
  override def getDataSource(input: org.lyranthe.araethura.machinelearning.models.GetDataSourceInput): F[org.lyranthe.araethura.machinelearning.models.GetDataSourceOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.machinelearning.models.GetDataSourceOutput, org.lyranthe.araethura.machinelearning.models.GetDataSourceInput](client, awsData, ServiceType, ServiceAndPrefix, "GetDataSource", POST, "/", input)
}