package org.lyranthe.araethura.ecr
trait Amazonecr[F[_]] {
  def initiateLayerUpload(input: org.lyranthe.araethura.ecr.models.InitiateLayerUploadRequest): F[org.lyranthe.araethura.ecr.models.InitiateLayerUploadResponse]
  def putImage(input: org.lyranthe.araethura.ecr.models.PutImageRequest): F[org.lyranthe.araethura.ecr.models.PutImageResponse]
  def uploadLayerPart(input: org.lyranthe.araethura.ecr.models.UploadLayerPartRequest): F[org.lyranthe.araethura.ecr.models.UploadLayerPartResponse]
  def setRepositoryPolicy(input: org.lyranthe.araethura.ecr.models.SetRepositoryPolicyRequest): F[org.lyranthe.araethura.ecr.models.SetRepositoryPolicyResponse]
  def putLifecyclePolicy(input: org.lyranthe.araethura.ecr.models.PutLifecyclePolicyRequest): F[org.lyranthe.araethura.ecr.models.PutLifecyclePolicyResponse]
  def batchCheckLayerAvailability(input: org.lyranthe.araethura.ecr.models.BatchCheckLayerAvailabilityRequest): F[org.lyranthe.araethura.ecr.models.BatchCheckLayerAvailabilityResponse]
  def batchDeleteImage(input: org.lyranthe.araethura.ecr.models.BatchDeleteImageRequest): F[org.lyranthe.araethura.ecr.models.BatchDeleteImageResponse]
  def describeImages(input: org.lyranthe.araethura.ecr.models.DescribeImagesRequest): F[org.lyranthe.araethura.ecr.models.DescribeImagesResponse]
  def listImages(input: org.lyranthe.araethura.ecr.models.ListImagesRequest): F[org.lyranthe.araethura.ecr.models.ListImagesResponse]
  def startLifecyclePolicyPreview(input: org.lyranthe.araethura.ecr.models.StartLifecyclePolicyPreviewRequest): F[org.lyranthe.araethura.ecr.models.StartLifecyclePolicyPreviewResponse]
  def completeLayerUpload(input: org.lyranthe.araethura.ecr.models.CompleteLayerUploadRequest): F[org.lyranthe.araethura.ecr.models.CompleteLayerUploadResponse]
  def deleteLifecyclePolicy(input: org.lyranthe.araethura.ecr.models.DeleteLifecyclePolicyRequest): F[org.lyranthe.araethura.ecr.models.DeleteLifecyclePolicyResponse]
  def createRepository(input: org.lyranthe.araethura.ecr.models.CreateRepositoryRequest): F[org.lyranthe.araethura.ecr.models.CreateRepositoryResponse]
  def getLifecyclePolicyPreview(input: org.lyranthe.araethura.ecr.models.GetLifecyclePolicyPreviewRequest): F[org.lyranthe.araethura.ecr.models.GetLifecyclePolicyPreviewResponse]
  def batchGetImage(input: org.lyranthe.araethura.ecr.models.BatchGetImageRequest): F[org.lyranthe.araethura.ecr.models.BatchGetImageResponse]
  def deleteRepository(input: org.lyranthe.araethura.ecr.models.DeleteRepositoryRequest): F[org.lyranthe.araethura.ecr.models.DeleteRepositoryResponse]
  def describeRepositories(input: org.lyranthe.araethura.ecr.models.DescribeRepositoriesRequest): F[org.lyranthe.araethura.ecr.models.DescribeRepositoriesResponse]
  def getDownloadUrlForLayer(input: org.lyranthe.araethura.ecr.models.GetDownloadUrlForLayerRequest): F[org.lyranthe.araethura.ecr.models.GetDownloadUrlForLayerResponse]
  def getLifecyclePolicy(input: org.lyranthe.araethura.ecr.models.GetLifecyclePolicyRequest): F[org.lyranthe.araethura.ecr.models.GetLifecyclePolicyResponse]
  def deleteRepositoryPolicy(input: org.lyranthe.araethura.ecr.models.DeleteRepositoryPolicyRequest): F[org.lyranthe.araethura.ecr.models.DeleteRepositoryPolicyResponse]
  def getAuthorizationToken(input: org.lyranthe.araethura.ecr.models.GetAuthorizationTokenRequest): F[org.lyranthe.araethura.ecr.models.GetAuthorizationTokenResponse]
  def getRepositoryPolicy(input: org.lyranthe.araethura.ecr.models.GetRepositoryPolicyRequest): F[org.lyranthe.araethura.ecr.models.GetRepositoryPolicyResponse]
}