package org.lyranthe.araethura.config
trait Amazonconfig[F[_]] {
  def describeConfigRuleEvaluationStatus(input: org.lyranthe.araethura.config.models.DescribeConfigRuleEvaluationStatusRequest): F[org.lyranthe.araethura.config.models.DescribeConfigRuleEvaluationStatusResponse]
  def deleteEvaluationResults(input: org.lyranthe.araethura.config.models.DeleteEvaluationResultsRequest): F[scala.Unit]
  def deleteDeliveryChannel(input: org.lyranthe.araethura.config.models.DeleteDeliveryChannelRequest): F[scala.Unit]
  def deliverConfigSnapshot(input: org.lyranthe.araethura.config.models.DeliverConfigSnapshotRequest): F[org.lyranthe.araethura.config.models.DeliverConfigSnapshotResponse]
  def describeDeliveryChannels(input: org.lyranthe.araethura.config.models.DescribeDeliveryChannelsRequest): F[org.lyranthe.araethura.config.models.DescribeDeliveryChannelsResponse]
  def deleteConfigRule(input: org.lyranthe.araethura.config.models.DeleteConfigRuleRequest): F[scala.Unit]
  def describeDeliveryChannelStatus(input: org.lyranthe.araethura.config.models.DescribeDeliveryChannelStatusRequest): F[org.lyranthe.araethura.config.models.DescribeDeliveryChannelStatusResponse]
  def putConfigRule(input: org.lyranthe.araethura.config.models.PutConfigRuleRequest): F[scala.Unit]
  def getResourceConfigHistory(input: org.lyranthe.araethura.config.models.GetResourceConfigHistoryRequest): F[org.lyranthe.araethura.config.models.GetResourceConfigHistoryResponse]
  def getComplianceDetailsByConfigRule(input: org.lyranthe.araethura.config.models.GetComplianceDetailsByConfigRuleRequest): F[org.lyranthe.araethura.config.models.GetComplianceDetailsByConfigRuleResponse]
  def getDiscoveredResourceCounts(input: org.lyranthe.araethura.config.models.GetDiscoveredResourceCountsRequest): F[org.lyranthe.araethura.config.models.GetDiscoveredResourceCountsResponse]
  def describeConfigurationRecorderStatus(input: org.lyranthe.araethura.config.models.DescribeConfigurationRecorderStatusRequest): F[org.lyranthe.araethura.config.models.DescribeConfigurationRecorderStatusResponse]
  def listDiscoveredResources(input: org.lyranthe.araethura.config.models.ListDiscoveredResourcesRequest): F[org.lyranthe.araethura.config.models.ListDiscoveredResourcesResponse]
  def stopConfigurationRecorder(input: org.lyranthe.araethura.config.models.StopConfigurationRecorderRequest): F[scala.Unit]
  def describeComplianceByResource(input: org.lyranthe.araethura.config.models.DescribeComplianceByResourceRequest): F[org.lyranthe.araethura.config.models.DescribeComplianceByResourceResponse]
  def describeComplianceByConfigRule(input: org.lyranthe.araethura.config.models.DescribeComplianceByConfigRuleRequest): F[org.lyranthe.araethura.config.models.DescribeComplianceByConfigRuleResponse]
  def deleteConfigurationRecorder(input: org.lyranthe.araethura.config.models.DeleteConfigurationRecorderRequest): F[scala.Unit]
  def startConfigRulesEvaluation(input: org.lyranthe.araethura.config.models.StartConfigRulesEvaluationRequest): F[scala.Unit]
  def putDeliveryChannel(input: org.lyranthe.araethura.config.models.PutDeliveryChannelRequest): F[scala.Unit]
  def getComplianceDetailsByResource(input: org.lyranthe.araethura.config.models.GetComplianceDetailsByResourceRequest): F[org.lyranthe.araethura.config.models.GetComplianceDetailsByResourceResponse]
  def startConfigurationRecorder(input: org.lyranthe.araethura.config.models.StartConfigurationRecorderRequest): F[scala.Unit]
  def describeConfigurationRecorders(input: org.lyranthe.araethura.config.models.DescribeConfigurationRecordersRequest): F[org.lyranthe.araethura.config.models.DescribeConfigurationRecordersResponse]
  def describeConfigRules(input: org.lyranthe.araethura.config.models.DescribeConfigRulesRequest): F[org.lyranthe.araethura.config.models.DescribeConfigRulesResponse]
  def getComplianceSummaryByResourceType(input: org.lyranthe.araethura.config.models.GetComplianceSummaryByResourceTypeRequest): F[org.lyranthe.araethura.config.models.GetComplianceSummaryByResourceTypeResponse]
  def putConfigurationRecorder(input: org.lyranthe.araethura.config.models.PutConfigurationRecorderRequest): F[scala.Unit]
  def getComplianceSummaryByConfigRule: F[org.lyranthe.araethura.config.models.GetComplianceSummaryByConfigRuleResponse]
  def putEvaluations(input: org.lyranthe.araethura.config.models.PutEvaluationsRequest): F[org.lyranthe.araethura.config.models.PutEvaluationsResponse]
}