package org.lyranthe.araethura.acm.http4s
import org.http4s.Method._
import org.lyranthe.araethura.acm.circe._
import org.lyranthe.araethura.acm.models
class AmazonacmClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.acm.Amazonacm[F] {
  private[this] final val ServiceType: String = "acm"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CertificateManager")
  override def deleteCertificate(input: org.lyranthe.araethura.acm.models.DeleteCertificateRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.acm.models.DeleteCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteCertificate", POST, "/", input)
  override def addTagsToCertificate(input: org.lyranthe.araethura.acm.models.AddTagsToCertificateRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.acm.models.AddTagsToCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddTagsToCertificate", POST, "/", input)
  override def listTagsForCertificate(input: org.lyranthe.araethura.acm.models.ListTagsForCertificateRequest): F[org.lyranthe.araethura.acm.models.ListTagsForCertificateResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.acm.models.ListTagsForCertificateResponse, org.lyranthe.araethura.acm.models.ListTagsForCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForCertificate", POST, "/", input)
  override def removeTagsFromCertificate(input: org.lyranthe.araethura.acm.models.RemoveTagsFromCertificateRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.acm.models.RemoveTagsFromCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTagsFromCertificate", POST, "/", input)
  override def importCertificate(input: org.lyranthe.araethura.acm.models.ImportCertificateRequest): F[org.lyranthe.araethura.acm.models.ImportCertificateResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.acm.models.ImportCertificateResponse, org.lyranthe.araethura.acm.models.ImportCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "ImportCertificate", POST, "/", input)
  override def listCertificates(input: org.lyranthe.araethura.acm.models.ListCertificatesRequest): F[org.lyranthe.araethura.acm.models.ListCertificatesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.acm.models.ListCertificatesResponse, org.lyranthe.araethura.acm.models.ListCertificatesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListCertificates", POST, "/", input)
  override def describeCertificate(input: org.lyranthe.araethura.acm.models.DescribeCertificateRequest): F[org.lyranthe.araethura.acm.models.DescribeCertificateResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.acm.models.DescribeCertificateResponse, org.lyranthe.araethura.acm.models.DescribeCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeCertificate", POST, "/", input)
  override def getCertificate(input: org.lyranthe.araethura.acm.models.GetCertificateRequest): F[org.lyranthe.araethura.acm.models.GetCertificateResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.acm.models.GetCertificateResponse, org.lyranthe.araethura.acm.models.GetCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetCertificate", POST, "/", input)
  override def requestCertificate(input: org.lyranthe.araethura.acm.models.RequestCertificateRequest): F[org.lyranthe.araethura.acm.models.RequestCertificateResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.acm.models.RequestCertificateResponse, org.lyranthe.araethura.acm.models.RequestCertificateRequest](client, awsData, ServiceType, ServiceAndPrefix, "RequestCertificate", POST, "/", input)
  override def resendValidationEmail(input: org.lyranthe.araethura.acm.models.ResendValidationEmailRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.acm.models.ResendValidationEmailRequest](client, awsData, ServiceType, ServiceAndPrefix, "ResendValidationEmail", POST, "/", input)
}