package org.lyranthe.araethura.cognitoidentity.models
import org.lyranthe.araethura.cognitoidentity.models
final case class GetOpenIdTokenForDeveloperIdentityInput(identityPoolId: java.lang.String, logins: scala.collection.immutable.Map[java.lang.String, java.lang.String], identityId: scala.Option[java.lang.String] = None, tokenDuration: scala.Option[scala.Long] = None)
final case class InvalidIdentityPoolConfigurationException(message: scala.Option[java.lang.String] = None)
final case class GetIdInput(identityPoolId: java.lang.String, accountId: scala.Option[java.lang.String] = None, logins: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None)
final case class LookupDeveloperIdentityInput(identityPoolId: java.lang.String, developerUserIdentifier: scala.Option[java.lang.String] = None, maxResults: scala.Option[scala.Int] = None, identityId: scala.Option[java.lang.String] = None, nextToken: scala.Option[java.lang.String] = None)
final case class Credentials(accessKeyId: scala.Option[java.lang.String] = None, secretKey: scala.Option[java.lang.String] = None, sessionToken: scala.Option[java.lang.String] = None, expiration: scala.Option[java.time.Instant] = None)
final case class ResourceConflictException(message: scala.Option[java.lang.String] = None)
final case class MergeDeveloperIdentitiesInput(sourceUserIdentifier: java.lang.String, destinationUserIdentifier: java.lang.String, developerProviderName: java.lang.String, identityPoolId: java.lang.String)
final case class GetIdentityPoolRolesResponse(identityPoolId: scala.Option[java.lang.String] = None, roles: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None, roleMappings: scala.Option[scala.collection.immutable.Map[java.lang.String, models.RoleMapping]] = None)
final case class RulesConfigurationType(rules: scala.List[models.MappingRule])
final case class UnprocessedIdentityId(identityId: scala.Option[java.lang.String] = None, errorCode: scala.Option[java.lang.String] = None)
final case class MappingRule(claim: java.lang.String, matchType: java.lang.String, value: java.lang.String, roleARN: java.lang.String)
final case class CreateIdentityPoolInput(identityPoolName: java.lang.String, allowUnauthenticatedIdentities: scala.Boolean, openIdConnectProviderARNs: scala.Option[scala.List[java.lang.String]] = None, cognitoIdentityProviders: scala.Option[scala.List[models.CognitoIdentityProvider]] = None, developerProviderName: scala.Option[java.lang.String] = None, samlProviderARNs: scala.Option[scala.List[java.lang.String]] = None, supportedLoginProviders: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None)
final case class InternalErrorException(message: scala.Option[java.lang.String] = None)
final case class GetIdResponse(identityId: scala.Option[java.lang.String] = None)
final case class ListIdentitiesResponse(identityPoolId: scala.Option[java.lang.String] = None, identities: scala.Option[scala.List[models.IdentityDescription]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DeleteIdentitiesInput(identityIdsToDelete: scala.List[java.lang.String])
final case class RoleMapping(`type`: java.lang.String, ambiguousRoleResolution: scala.Option[java.lang.String] = None, rulesConfiguration: scala.Option[models.RulesConfigurationType] = None)
final case class UnlinkIdentityInput(identityId: java.lang.String, logins: scala.collection.immutable.Map[java.lang.String, java.lang.String], loginsToRemove: scala.List[java.lang.String])
final case class IdentityPool(identityPoolName: java.lang.String, identityPoolId: java.lang.String, allowUnauthenticatedIdentities: scala.Boolean, openIdConnectProviderARNs: scala.Option[scala.List[java.lang.String]] = None, cognitoIdentityProviders: scala.Option[scala.List[models.CognitoIdentityProvider]] = None, developerProviderName: scala.Option[java.lang.String] = None, samlProviderARNs: scala.Option[scala.List[java.lang.String]] = None, supportedLoginProviders: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None)
final case class ResourceNotFoundException(message: scala.Option[java.lang.String] = None)
final case class NotAuthorizedException(message: scala.Option[java.lang.String] = None)
final case class TooManyRequestsException(message: scala.Option[java.lang.String] = None)
final case class ConcurrentModificationException(message: scala.Option[java.lang.String] = None)
final case class ExternalServiceException(message: scala.Option[java.lang.String] = None)
final case class CognitoIdentityProvider(providerName: scala.Option[java.lang.String] = None, clientId: scala.Option[java.lang.String] = None, serverSideTokenCheck: scala.Option[scala.Boolean] = None)
final case class InvalidParameterException(message: scala.Option[java.lang.String] = None)
final case class IdentityDescription(identityId: scala.Option[java.lang.String] = None, logins: scala.Option[scala.List[java.lang.String]] = None, creationDate: scala.Option[java.time.Instant] = None, lastModifiedDate: scala.Option[java.time.Instant] = None)
final case class DeleteIdentityPoolInput(identityPoolId: java.lang.String)
final case class SetIdentityPoolRolesInput(identityPoolId: java.lang.String, roles: scala.collection.immutable.Map[java.lang.String, java.lang.String], roleMappings: scala.Option[scala.collection.immutable.Map[java.lang.String, models.RoleMapping]] = None)
final case class GetOpenIdTokenForDeveloperIdentityResponse(identityId: scala.Option[java.lang.String] = None, token: scala.Option[java.lang.String] = None)
final case class DeveloperUserAlreadyRegisteredException(message: scala.Option[java.lang.String] = None)
final case class IdentityPoolShortDescription(identityPoolId: scala.Option[java.lang.String] = None, identityPoolName: scala.Option[java.lang.String] = None)
final case class GetCredentialsForIdentityInput(identityId: java.lang.String, logins: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None, customRoleArn: scala.Option[java.lang.String] = None)
final case class LimitExceededException(message: scala.Option[java.lang.String] = None)
final case class DescribeIdentityPoolInput(identityPoolId: java.lang.String)
final case class ListIdentityPoolsInput(maxResults: scala.Int, nextToken: scala.Option[java.lang.String] = None)
final case class ListIdentitiesInput(identityPoolId: java.lang.String, maxResults: scala.Int, nextToken: scala.Option[java.lang.String] = None, hideDisabled: scala.Option[scala.Boolean] = None)
final case class DescribeIdentityInput(identityId: java.lang.String)
final case class GetCredentialsForIdentityResponse(identityId: scala.Option[java.lang.String] = None, credentials: scala.Option[models.Credentials] = None)
final case class LookupDeveloperIdentityResponse(identityId: scala.Option[java.lang.String] = None, developerUserIdentifierList: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class UnlinkDeveloperIdentityInput(identityId: java.lang.String, identityPoolId: java.lang.String, developerProviderName: java.lang.String, developerUserIdentifier: java.lang.String)
final case class ListIdentityPoolsResponse(identityPools: scala.Option[scala.List[models.IdentityPoolShortDescription]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class MergeDeveloperIdentitiesResponse(identityId: scala.Option[java.lang.String] = None)
final case class DeleteIdentitiesResponse(unprocessedIdentityIds: scala.Option[scala.List[models.UnprocessedIdentityId]] = None)
final case class GetOpenIdTokenResponse(identityId: scala.Option[java.lang.String] = None, token: scala.Option[java.lang.String] = None)
final case class GetIdentityPoolRolesInput(identityPoolId: java.lang.String)
final case class GetOpenIdTokenInput(identityId: java.lang.String, logins: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None)