package avias.mechanicalturkrequester
trait Amazonmechanicalturkrequester[F[_]] {
  def getFileUploadURL(input: avias.mechanicalturkrequester.models.GetFileUploadURLRequest): F[avias.mechanicalturkrequester.models.GetFileUploadURLResponse]
  def listHITs(input: avias.mechanicalturkrequester.models.ListHITsRequest): F[avias.mechanicalturkrequester.models.ListHITsResponse]
  def listWorkersWithQualificationType(input: avias.mechanicalturkrequester.models.ListWorkersWithQualificationTypeRequest): F[avias.mechanicalturkrequester.models.ListWorkersWithQualificationTypeResponse]
  def getAccountBalance: F[avias.mechanicalturkrequester.models.GetAccountBalanceResponse]
  def approveAssignment(input: avias.mechanicalturkrequester.models.ApproveAssignmentRequest): F[scala.Unit]
  def updateExpirationForHIT(input: avias.mechanicalturkrequester.models.UpdateExpirationForHITRequest): F[scala.Unit]
  def deleteWorkerBlock(input: avias.mechanicalturkrequester.models.DeleteWorkerBlockRequest): F[scala.Unit]
  def updateHITReviewStatus(input: avias.mechanicalturkrequester.models.UpdateHITReviewStatusRequest): F[scala.Unit]
  def listReviewPolicyResultsForHIT(input: avias.mechanicalturkrequester.models.ListReviewPolicyResultsForHITRequest): F[avias.mechanicalturkrequester.models.ListReviewPolicyResultsForHITResponse]
  def acceptQualificationRequest(input: avias.mechanicalturkrequester.models.AcceptQualificationRequestRequest): F[scala.Unit]
  def listWorkerBlocks(input: avias.mechanicalturkrequester.models.ListWorkerBlocksRequest): F[avias.mechanicalturkrequester.models.ListWorkerBlocksResponse]
  def updateNotificationSettings(input: avias.mechanicalturkrequester.models.UpdateNotificationSettingsRequest): F[scala.Unit]
  def updateQualificationType(input: avias.mechanicalturkrequester.models.UpdateQualificationTypeRequest): F[avias.mechanicalturkrequester.models.UpdateQualificationTypeResponse]
  def notifyWorkers(input: avias.mechanicalturkrequester.models.NotifyWorkersRequest): F[avias.mechanicalturkrequester.models.NotifyWorkersResponse]
  def getQualificationScore(input: avias.mechanicalturkrequester.models.GetQualificationScoreRequest): F[avias.mechanicalturkrequester.models.GetQualificationScoreResponse]
  def rejectAssignment(input: avias.mechanicalturkrequester.models.RejectAssignmentRequest): F[scala.Unit]
  def updateHITTypeOfHIT(input: avias.mechanicalturkrequester.models.UpdateHITTypeOfHITRequest): F[scala.Unit]
  def listQualificationTypes(input: avias.mechanicalturkrequester.models.ListQualificationTypesRequest): F[avias.mechanicalturkrequester.models.ListQualificationTypesResponse]
  def listAssignmentsForHIT(input: avias.mechanicalturkrequester.models.ListAssignmentsForHITRequest): F[avias.mechanicalturkrequester.models.ListAssignmentsForHITResponse]
  def createQualificationType(input: avias.mechanicalturkrequester.models.CreateQualificationTypeRequest): F[avias.mechanicalturkrequester.models.CreateQualificationTypeResponse]
  def createHITWithHITType(input: avias.mechanicalturkrequester.models.CreateHITWithHITTypeRequest): F[avias.mechanicalturkrequester.models.CreateHITWithHITTypeResponse]
  def getQualificationType(input: avias.mechanicalturkrequester.models.GetQualificationTypeRequest): F[avias.mechanicalturkrequester.models.GetQualificationTypeResponse]
  def deleteQualificationType(input: avias.mechanicalturkrequester.models.DeleteQualificationTypeRequest): F[scala.Unit]
  def listHITsForQualificationType(input: avias.mechanicalturkrequester.models.ListHITsForQualificationTypeRequest): F[avias.mechanicalturkrequester.models.ListHITsForQualificationTypeResponse]
  def sendTestEventNotification(input: avias.mechanicalturkrequester.models.SendTestEventNotificationRequest): F[scala.Unit]
  def associateQualificationWithWorker(input: avias.mechanicalturkrequester.models.AssociateQualificationWithWorkerRequest): F[scala.Unit]
  def createHITType(input: avias.mechanicalturkrequester.models.CreateHITTypeRequest): F[avias.mechanicalturkrequester.models.CreateHITTypeResponse]
  def listBonusPayments(input: avias.mechanicalturkrequester.models.ListBonusPaymentsRequest): F[avias.mechanicalturkrequester.models.ListBonusPaymentsResponse]
  def deleteHIT(input: avias.mechanicalturkrequester.models.DeleteHITRequest): F[scala.Unit]
  def listReviewableHITs(input: avias.mechanicalturkrequester.models.ListReviewableHITsRequest): F[avias.mechanicalturkrequester.models.ListReviewableHITsResponse]
  def rejectQualificationRequest(input: avias.mechanicalturkrequester.models.RejectQualificationRequestRequest): F[scala.Unit]
  def getHIT(input: avias.mechanicalturkrequester.models.GetHITRequest): F[avias.mechanicalturkrequester.models.GetHITResponse]
  def getAssignment(input: avias.mechanicalturkrequester.models.GetAssignmentRequest): F[avias.mechanicalturkrequester.models.GetAssignmentResponse]
  def listQualificationRequests(input: avias.mechanicalturkrequester.models.ListQualificationRequestsRequest): F[avias.mechanicalturkrequester.models.ListQualificationRequestsResponse]
  def createHIT(input: avias.mechanicalturkrequester.models.CreateHITRequest): F[avias.mechanicalturkrequester.models.CreateHITResponse]
  def createWorkerBlock(input: avias.mechanicalturkrequester.models.CreateWorkerBlockRequest): F[scala.Unit]
  def sendBonus(input: avias.mechanicalturkrequester.models.SendBonusRequest): F[scala.Unit]
  def disassociateQualificationFromWorker(input: avias.mechanicalturkrequester.models.DisassociateQualificationFromWorkerRequest): F[scala.Unit]
  def createAdditionalAssignmentsForHIT(input: avias.mechanicalturkrequester.models.CreateAdditionalAssignmentsForHITRequest): F[scala.Unit]
}