package org.lyranthe.araethura.mechanicalturkrequester
trait Amazonmechanicalturkrequester[F[_]] {
  def getFileUploadURL(input: org.lyranthe.araethura.mechanicalturkrequester.models.GetFileUploadURLRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.GetFileUploadURLResponse]
  def listHITs(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListHITsRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListHITsResponse]
  def listWorkersWithQualificationType(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListWorkersWithQualificationTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListWorkersWithQualificationTypeResponse]
  def getAccountBalance: F[org.lyranthe.araethura.mechanicalturkrequester.models.GetAccountBalanceResponse]
  def approveAssignment(input: org.lyranthe.araethura.mechanicalturkrequester.models.ApproveAssignmentRequest): F[scala.Unit]
  def updateExpirationForHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.UpdateExpirationForHITRequest): F[scala.Unit]
  def deleteWorkerBlock(input: org.lyranthe.araethura.mechanicalturkrequester.models.DeleteWorkerBlockRequest): F[scala.Unit]
  def updateHITReviewStatus(input: org.lyranthe.araethura.mechanicalturkrequester.models.UpdateHITReviewStatusRequest): F[scala.Unit]
  def listReviewPolicyResultsForHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListReviewPolicyResultsForHITRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListReviewPolicyResultsForHITResponse]
  def acceptQualificationRequest(input: org.lyranthe.araethura.mechanicalturkrequester.models.AcceptQualificationRequestRequest): F[scala.Unit]
  def listWorkerBlocks(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListWorkerBlocksRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListWorkerBlocksResponse]
  def updateNotificationSettings(input: org.lyranthe.araethura.mechanicalturkrequester.models.UpdateNotificationSettingsRequest): F[scala.Unit]
  def updateQualificationType(input: org.lyranthe.araethura.mechanicalturkrequester.models.UpdateQualificationTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.UpdateQualificationTypeResponse]
  def notifyWorkers(input: org.lyranthe.araethura.mechanicalturkrequester.models.NotifyWorkersRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.NotifyWorkersResponse]
  def getQualificationScore(input: org.lyranthe.araethura.mechanicalturkrequester.models.GetQualificationScoreRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.GetQualificationScoreResponse]
  def rejectAssignment(input: org.lyranthe.araethura.mechanicalturkrequester.models.RejectAssignmentRequest): F[scala.Unit]
  def updateHITTypeOfHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.UpdateHITTypeOfHITRequest): F[scala.Unit]
  def listQualificationTypes(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListQualificationTypesRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListQualificationTypesResponse]
  def listAssignmentsForHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListAssignmentsForHITRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListAssignmentsForHITResponse]
  def createQualificationType(input: org.lyranthe.araethura.mechanicalturkrequester.models.CreateQualificationTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.CreateQualificationTypeResponse]
  def createHITWithHITType(input: org.lyranthe.araethura.mechanicalturkrequester.models.CreateHITWithHITTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.CreateHITWithHITTypeResponse]
  def getQualificationType(input: org.lyranthe.araethura.mechanicalturkrequester.models.GetQualificationTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.GetQualificationTypeResponse]
  def deleteQualificationType(input: org.lyranthe.araethura.mechanicalturkrequester.models.DeleteQualificationTypeRequest): F[scala.Unit]
  def listHITsForQualificationType(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListHITsForQualificationTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListHITsForQualificationTypeResponse]
  def sendTestEventNotification(input: org.lyranthe.araethura.mechanicalturkrequester.models.SendTestEventNotificationRequest): F[scala.Unit]
  def associateQualificationWithWorker(input: org.lyranthe.araethura.mechanicalturkrequester.models.AssociateQualificationWithWorkerRequest): F[scala.Unit]
  def createHITType(input: org.lyranthe.araethura.mechanicalturkrequester.models.CreateHITTypeRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.CreateHITTypeResponse]
  def listBonusPayments(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListBonusPaymentsRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListBonusPaymentsResponse]
  def deleteHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.DeleteHITRequest): F[scala.Unit]
  def listReviewableHITs(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListReviewableHITsRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListReviewableHITsResponse]
  def rejectQualificationRequest(input: org.lyranthe.araethura.mechanicalturkrequester.models.RejectQualificationRequestRequest): F[scala.Unit]
  def getHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.GetHITRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.GetHITResponse]
  def getAssignment(input: org.lyranthe.araethura.mechanicalturkrequester.models.GetAssignmentRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.GetAssignmentResponse]
  def listQualificationRequests(input: org.lyranthe.araethura.mechanicalturkrequester.models.ListQualificationRequestsRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.ListQualificationRequestsResponse]
  def createHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.CreateHITRequest): F[org.lyranthe.araethura.mechanicalturkrequester.models.CreateHITResponse]
  def createWorkerBlock(input: org.lyranthe.araethura.mechanicalturkrequester.models.CreateWorkerBlockRequest): F[scala.Unit]
  def sendBonus(input: org.lyranthe.araethura.mechanicalturkrequester.models.SendBonusRequest): F[scala.Unit]
  def disassociateQualificationFromWorker(input: org.lyranthe.araethura.mechanicalturkrequester.models.DisassociateQualificationFromWorkerRequest): F[scala.Unit]
  def createAdditionalAssignmentsForHIT(input: org.lyranthe.araethura.mechanicalturkrequester.models.CreateAdditionalAssignmentsForHITRequest): F[scala.Unit]
}