package org.lyranthe.araethura.athena.http4s
import org.http4s.Method._
import org.lyranthe.araethura.athena.circe._
import org.lyranthe.araethura.athena.models
class AmazonathenaClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.athena.Amazonathena[F] {
  private[this] final val ServiceType: String = "athena"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AmazonAthena")
  override def listQueryExecutions(input: org.lyranthe.araethura.athena.models.ListQueryExecutionsInput): F[org.lyranthe.araethura.athena.models.ListQueryExecutionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.ListQueryExecutionsOutput, org.lyranthe.araethura.athena.models.ListQueryExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListQueryExecutions", POST, "/", input)
  override def getQueryExecution(input: org.lyranthe.araethura.athena.models.GetQueryExecutionInput): F[org.lyranthe.araethura.athena.models.GetQueryExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.GetQueryExecutionOutput, org.lyranthe.araethura.athena.models.GetQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "GetQueryExecution", POST, "/", input)
  override def deleteNamedQuery(input: org.lyranthe.araethura.athena.models.DeleteNamedQueryInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.athena.models.DeleteNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteNamedQuery", POST, "/", input)
  override def batchGetQueryExecution(input: org.lyranthe.araethura.athena.models.BatchGetQueryExecutionInput): F[org.lyranthe.araethura.athena.models.BatchGetQueryExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.BatchGetQueryExecutionOutput, org.lyranthe.araethura.athena.models.BatchGetQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetQueryExecution", POST, "/", input)
  override def getNamedQuery(input: org.lyranthe.araethura.athena.models.GetNamedQueryInput): F[org.lyranthe.araethura.athena.models.GetNamedQueryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.GetNamedQueryOutput, org.lyranthe.araethura.athena.models.GetNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "GetNamedQuery", POST, "/", input)
  override def stopQueryExecution(input: org.lyranthe.araethura.athena.models.StopQueryExecutionInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.athena.models.StopQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopQueryExecution", POST, "/", input)
  override def getQueryResults(input: org.lyranthe.araethura.athena.models.GetQueryResultsInput): F[org.lyranthe.araethura.athena.models.GetQueryResultsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.GetQueryResultsOutput, org.lyranthe.araethura.athena.models.GetQueryResultsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetQueryResults", POST, "/", input)
  override def createNamedQuery(input: org.lyranthe.araethura.athena.models.CreateNamedQueryInput): F[org.lyranthe.araethura.athena.models.CreateNamedQueryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.CreateNamedQueryOutput, org.lyranthe.araethura.athena.models.CreateNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateNamedQuery", POST, "/", input)
  override def startQueryExecution(input: org.lyranthe.araethura.athena.models.StartQueryExecutionInput): F[org.lyranthe.araethura.athena.models.StartQueryExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.StartQueryExecutionOutput, org.lyranthe.araethura.athena.models.StartQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartQueryExecution", POST, "/", input)
  override def batchGetNamedQuery(input: org.lyranthe.araethura.athena.models.BatchGetNamedQueryInput): F[org.lyranthe.araethura.athena.models.BatchGetNamedQueryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.BatchGetNamedQueryOutput, org.lyranthe.araethura.athena.models.BatchGetNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetNamedQuery", POST, "/", input)
  override def listNamedQueries(input: org.lyranthe.araethura.athena.models.ListNamedQueriesInput): F[org.lyranthe.araethura.athena.models.ListNamedQueriesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.athena.models.ListNamedQueriesOutput, org.lyranthe.araethura.athena.models.ListNamedQueriesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListNamedQueries", POST, "/", input)
}