package org.lyranthe.araethura.support.http4s
import org.http4s.Method._
import org.lyranthe.araethura.support.circe._
import org.lyranthe.araethura.support.models
class AmazonsupportClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.support.Amazonsupport[F] {
  private[this] final val ServiceType: String = "support"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSSupport_20130415")
  override def describeServices(input: org.lyranthe.araethura.support.models.DescribeServicesRequest): F[org.lyranthe.araethura.support.models.DescribeServicesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeServicesResponse, org.lyranthe.araethura.support.models.DescribeServicesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeServices", POST, "/", input)
  override def describeTrustedAdvisorCheckSummaries(input: org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckSummariesRequest): F[org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckSummariesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckSummariesResponse, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckSummariesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTrustedAdvisorCheckSummaries", POST, "/", input)
  override def describeTrustedAdvisorCheckRefreshStatuses(input: org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckRefreshStatusesRequest): F[org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckRefreshStatusesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckRefreshStatusesResponse, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckRefreshStatusesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTrustedAdvisorCheckRefreshStatuses", POST, "/", input)
  override def describeTrustedAdvisorCheckResult(input: org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckResultRequest): F[org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckResultResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckResultResponse, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorCheckResultRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTrustedAdvisorCheckResult", POST, "/", input)
  override def addCommunicationToCase(input: org.lyranthe.araethura.support.models.AddCommunicationToCaseRequest): F[org.lyranthe.araethura.support.models.AddCommunicationToCaseResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.AddCommunicationToCaseResponse, org.lyranthe.araethura.support.models.AddCommunicationToCaseRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddCommunicationToCase", POST, "/", input)
  override def addAttachmentsToSet(input: org.lyranthe.araethura.support.models.AddAttachmentsToSetRequest): F[org.lyranthe.araethura.support.models.AddAttachmentsToSetResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.AddAttachmentsToSetResponse, org.lyranthe.araethura.support.models.AddAttachmentsToSetRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddAttachmentsToSet", POST, "/", input)
  override def refreshTrustedAdvisorCheck(input: org.lyranthe.araethura.support.models.RefreshTrustedAdvisorCheckRequest): F[org.lyranthe.araethura.support.models.RefreshTrustedAdvisorCheckResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.RefreshTrustedAdvisorCheckResponse, org.lyranthe.araethura.support.models.RefreshTrustedAdvisorCheckRequest](client, awsData, ServiceType, ServiceAndPrefix, "RefreshTrustedAdvisorCheck", POST, "/", input)
  override def describeSeverityLevels(input: org.lyranthe.araethura.support.models.DescribeSeverityLevelsRequest): F[org.lyranthe.araethura.support.models.DescribeSeverityLevelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeSeverityLevelsResponse, org.lyranthe.araethura.support.models.DescribeSeverityLevelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSeverityLevels", POST, "/", input)
  override def resolveCase(input: org.lyranthe.araethura.support.models.ResolveCaseRequest): F[org.lyranthe.araethura.support.models.ResolveCaseResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.ResolveCaseResponse, org.lyranthe.araethura.support.models.ResolveCaseRequest](client, awsData, ServiceType, ServiceAndPrefix, "ResolveCase", POST, "/", input)
  override def describeCommunications(input: org.lyranthe.araethura.support.models.DescribeCommunicationsRequest): F[org.lyranthe.araethura.support.models.DescribeCommunicationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeCommunicationsResponse, org.lyranthe.araethura.support.models.DescribeCommunicationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeCommunications", POST, "/", input)
  override def describeCases(input: org.lyranthe.araethura.support.models.DescribeCasesRequest): F[org.lyranthe.araethura.support.models.DescribeCasesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeCasesResponse, org.lyranthe.araethura.support.models.DescribeCasesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeCases", POST, "/", input)
  override def createCase(input: org.lyranthe.araethura.support.models.CreateCaseRequest): F[org.lyranthe.araethura.support.models.CreateCaseResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.CreateCaseResponse, org.lyranthe.araethura.support.models.CreateCaseRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateCase", POST, "/", input)
  override def describeTrustedAdvisorChecks(input: org.lyranthe.araethura.support.models.DescribeTrustedAdvisorChecksRequest): F[org.lyranthe.araethura.support.models.DescribeTrustedAdvisorChecksResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorChecksResponse, org.lyranthe.araethura.support.models.DescribeTrustedAdvisorChecksRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTrustedAdvisorChecks", POST, "/", input)
  override def describeAttachment(input: org.lyranthe.araethura.support.models.DescribeAttachmentRequest): F[org.lyranthe.araethura.support.models.DescribeAttachmentResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.support.models.DescribeAttachmentResponse, org.lyranthe.araethura.support.models.DescribeAttachmentRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAttachment", POST, "/", input)
}