package org.lyranthe.araethura.codestar.http4s
import org.http4s.Method._
import org.lyranthe.araethura.codestar.circe._
import org.lyranthe.araethura.codestar.models
class AmazoncodestarClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.codestar.Amazoncodestar[F] {
  private[this] final val ServiceType: String = "codestar"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CodeStar_20170419")
  override def associateTeamMember(input: models.AssociateTeamMemberRequest): F[models.AssociateTeamMemberResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.AssociateTeamMemberResult, models.AssociateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateTeamMember", POST, "/", input)
  override def updateTeamMember(input: models.UpdateTeamMemberRequest): F[models.UpdateTeamMemberResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateTeamMemberResult, models.UpdateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTeamMember", POST, "/", input)
  override def createUserProfile(input: models.CreateUserProfileRequest): F[models.CreateUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateUserProfileResult, models.CreateUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateUserProfile", POST, "/", input)
  override def tagProject(input: models.TagProjectRequest): F[models.TagProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.TagProjectResult, models.TagProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "TagProject", POST, "/", input)
  override def listUserProfiles(input: models.ListUserProfilesRequest): F[models.ListUserProfilesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListUserProfilesResult, models.ListUserProfilesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListUserProfiles", POST, "/", input)
  override def listResources(input: models.ListResourcesRequest): F[models.ListResourcesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListResourcesResult, models.ListResourcesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListResources", POST, "/", input)
  override def describeUserProfile(input: models.DescribeUserProfileRequest): F[models.DescribeUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeUserProfileResult, models.DescribeUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeUserProfile", POST, "/", input)
  override def listTagsForProject(input: models.ListTagsForProjectRequest): F[models.ListTagsForProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTagsForProjectResult, models.ListTagsForProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForProject", POST, "/", input)
  override def describeProject(input: models.DescribeProjectRequest): F[models.DescribeProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeProjectResult, models.DescribeProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeProject", POST, "/", input)
  override def deleteProject(input: models.DeleteProjectRequest): F[models.DeleteProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteProjectResult, models.DeleteProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteProject", POST, "/", input)
  override def listProjects(input: models.ListProjectsRequest): F[models.ListProjectsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListProjectsResult, models.ListProjectsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListProjects", POST, "/", input)
  override def updateProject(input: models.UpdateProjectRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.UpdateProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateProject", POST, "/", input)
  override def createProject(input: models.CreateProjectRequest): F[models.CreateProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateProjectResult, models.CreateProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateProject", POST, "/", input)
  override def untagProject(input: models.UntagProjectRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.UntagProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "UntagProject", POST, "/", input)
  override def listTeamMembers(input: models.ListTeamMembersRequest): F[models.ListTeamMembersResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTeamMembersResult, models.ListTeamMembersRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTeamMembers", POST, "/", input)
  override def updateUserProfile(input: models.UpdateUserProfileRequest): F[models.UpdateUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateUserProfileResult, models.UpdateUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateUserProfile", POST, "/", input)
  override def disassociateTeamMember(input: models.DisassociateTeamMemberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DisassociateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateTeamMember", POST, "/", input)
  override def deleteUserProfile(input: models.DeleteUserProfileRequest): F[models.DeleteUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteUserProfileResult, models.DeleteUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteUserProfile", POST, "/", input)
}