package org.lyranthe.araethura.codestar.http4s
import org.http4s.Method._
import org.lyranthe.araethura.codestar.circe._
import org.lyranthe.araethura.codestar.models
class AmazoncodestarClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.codestar.Amazoncodestar[F] {
  private[this] final val ServiceType: String = "codestar"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CodeStar_20170419")
  override def associateTeamMember(input: org.lyranthe.araethura.codestar.models.AssociateTeamMemberRequest): F[org.lyranthe.araethura.codestar.models.AssociateTeamMemberResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.AssociateTeamMemberResult, org.lyranthe.araethura.codestar.models.AssociateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateTeamMember", POST, "/", input)
  override def updateTeamMember(input: org.lyranthe.araethura.codestar.models.UpdateTeamMemberRequest): F[org.lyranthe.araethura.codestar.models.UpdateTeamMemberResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.UpdateTeamMemberResult, org.lyranthe.araethura.codestar.models.UpdateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTeamMember", POST, "/", input)
  override def createUserProfile(input: org.lyranthe.araethura.codestar.models.CreateUserProfileRequest): F[org.lyranthe.araethura.codestar.models.CreateUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.CreateUserProfileResult, org.lyranthe.araethura.codestar.models.CreateUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateUserProfile", POST, "/", input)
  override def tagProject(input: org.lyranthe.araethura.codestar.models.TagProjectRequest): F[org.lyranthe.araethura.codestar.models.TagProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.TagProjectResult, org.lyranthe.araethura.codestar.models.TagProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "TagProject", POST, "/", input)
  override def listUserProfiles(input: org.lyranthe.araethura.codestar.models.ListUserProfilesRequest): F[org.lyranthe.araethura.codestar.models.ListUserProfilesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.ListUserProfilesResult, org.lyranthe.araethura.codestar.models.ListUserProfilesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListUserProfiles", POST, "/", input)
  override def listResources(input: org.lyranthe.araethura.codestar.models.ListResourcesRequest): F[org.lyranthe.araethura.codestar.models.ListResourcesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.ListResourcesResult, org.lyranthe.araethura.codestar.models.ListResourcesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListResources", POST, "/", input)
  override def describeUserProfile(input: org.lyranthe.araethura.codestar.models.DescribeUserProfileRequest): F[org.lyranthe.araethura.codestar.models.DescribeUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.DescribeUserProfileResult, org.lyranthe.araethura.codestar.models.DescribeUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeUserProfile", POST, "/", input)
  override def listTagsForProject(input: org.lyranthe.araethura.codestar.models.ListTagsForProjectRequest): F[org.lyranthe.araethura.codestar.models.ListTagsForProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.ListTagsForProjectResult, org.lyranthe.araethura.codestar.models.ListTagsForProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForProject", POST, "/", input)
  override def describeProject(input: org.lyranthe.araethura.codestar.models.DescribeProjectRequest): F[org.lyranthe.araethura.codestar.models.DescribeProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.DescribeProjectResult, org.lyranthe.araethura.codestar.models.DescribeProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeProject", POST, "/", input)
  override def deleteProject(input: org.lyranthe.araethura.codestar.models.DeleteProjectRequest): F[org.lyranthe.araethura.codestar.models.DeleteProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.DeleteProjectResult, org.lyranthe.araethura.codestar.models.DeleteProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteProject", POST, "/", input)
  override def listProjects(input: org.lyranthe.araethura.codestar.models.ListProjectsRequest): F[org.lyranthe.araethura.codestar.models.ListProjectsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.ListProjectsResult, org.lyranthe.araethura.codestar.models.ListProjectsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListProjects", POST, "/", input)
  override def updateProject(input: org.lyranthe.araethura.codestar.models.UpdateProjectRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codestar.models.UpdateProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateProject", POST, "/", input)
  override def createProject(input: org.lyranthe.araethura.codestar.models.CreateProjectRequest): F[org.lyranthe.araethura.codestar.models.CreateProjectResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.CreateProjectResult, org.lyranthe.araethura.codestar.models.CreateProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateProject", POST, "/", input)
  override def untagProject(input: org.lyranthe.araethura.codestar.models.UntagProjectRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codestar.models.UntagProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "UntagProject", POST, "/", input)
  override def listTeamMembers(input: org.lyranthe.araethura.codestar.models.ListTeamMembersRequest): F[org.lyranthe.araethura.codestar.models.ListTeamMembersResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.ListTeamMembersResult, org.lyranthe.araethura.codestar.models.ListTeamMembersRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTeamMembers", POST, "/", input)
  override def updateUserProfile(input: org.lyranthe.araethura.codestar.models.UpdateUserProfileRequest): F[org.lyranthe.araethura.codestar.models.UpdateUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.UpdateUserProfileResult, org.lyranthe.araethura.codestar.models.UpdateUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateUserProfile", POST, "/", input)
  override def disassociateTeamMember(input: org.lyranthe.araethura.codestar.models.DisassociateTeamMemberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codestar.models.DisassociateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateTeamMember", POST, "/", input)
  override def deleteUserProfile(input: org.lyranthe.araethura.codestar.models.DeleteUserProfileRequest): F[org.lyranthe.araethura.codestar.models.DeleteUserProfileResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codestar.models.DeleteUserProfileResult, org.lyranthe.araethura.codestar.models.DeleteUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteUserProfile", POST, "/", input)
}