package avias.codestar.http4s
import org.http4s.Method._
import avias.codestar.circe._
import avias.codestar.models
class AmazoncodestarClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.codestar.Amazoncodestar[F] {
  private[this] final val ServiceType: String = "codestar"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CodeStar_20170419")
  override def associateTeamMember(input: avias.codestar.models.AssociateTeamMemberRequest): F[avias.codestar.models.AssociateTeamMemberResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.AssociateTeamMemberResult, avias.codestar.models.AssociateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateTeamMember", POST, "/", input)
  override def updateTeamMember(input: avias.codestar.models.UpdateTeamMemberRequest): F[avias.codestar.models.UpdateTeamMemberResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.UpdateTeamMemberResult, avias.codestar.models.UpdateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTeamMember", POST, "/", input)
  override def createUserProfile(input: avias.codestar.models.CreateUserProfileRequest): F[avias.codestar.models.CreateUserProfileResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.CreateUserProfileResult, avias.codestar.models.CreateUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateUserProfile", POST, "/", input)
  override def tagProject(input: avias.codestar.models.TagProjectRequest): F[avias.codestar.models.TagProjectResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.TagProjectResult, avias.codestar.models.TagProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "TagProject", POST, "/", input)
  override def listUserProfiles(input: avias.codestar.models.ListUserProfilesRequest): F[avias.codestar.models.ListUserProfilesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.ListUserProfilesResult, avias.codestar.models.ListUserProfilesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListUserProfiles", POST, "/", input)
  override def listResources(input: avias.codestar.models.ListResourcesRequest): F[avias.codestar.models.ListResourcesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.ListResourcesResult, avias.codestar.models.ListResourcesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListResources", POST, "/", input)
  override def describeUserProfile(input: avias.codestar.models.DescribeUserProfileRequest): F[avias.codestar.models.DescribeUserProfileResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.DescribeUserProfileResult, avias.codestar.models.DescribeUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeUserProfile", POST, "/", input)
  override def listTagsForProject(input: avias.codestar.models.ListTagsForProjectRequest): F[avias.codestar.models.ListTagsForProjectResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.ListTagsForProjectResult, avias.codestar.models.ListTagsForProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForProject", POST, "/", input)
  override def describeProject(input: avias.codestar.models.DescribeProjectRequest): F[avias.codestar.models.DescribeProjectResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.DescribeProjectResult, avias.codestar.models.DescribeProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeProject", POST, "/", input)
  override def deleteProject(input: avias.codestar.models.DeleteProjectRequest): F[avias.codestar.models.DeleteProjectResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.DeleteProjectResult, avias.codestar.models.DeleteProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteProject", POST, "/", input)
  override def listProjects(input: avias.codestar.models.ListProjectsRequest): F[avias.codestar.models.ListProjectsResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.ListProjectsResult, avias.codestar.models.ListProjectsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListProjects", POST, "/", input)
  override def updateProject(input: avias.codestar.models.UpdateProjectRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.codestar.models.UpdateProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateProject", POST, "/", input)
  override def createProject(input: avias.codestar.models.CreateProjectRequest): F[avias.codestar.models.CreateProjectResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.CreateProjectResult, avias.codestar.models.CreateProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateProject", POST, "/", input)
  override def untagProject(input: avias.codestar.models.UntagProjectRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.codestar.models.UntagProjectRequest](client, awsData, ServiceType, ServiceAndPrefix, "UntagProject", POST, "/", input)
  override def listTeamMembers(input: avias.codestar.models.ListTeamMembersRequest): F[avias.codestar.models.ListTeamMembersResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.ListTeamMembersResult, avias.codestar.models.ListTeamMembersRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTeamMembers", POST, "/", input)
  override def updateUserProfile(input: avias.codestar.models.UpdateUserProfileRequest): F[avias.codestar.models.UpdateUserProfileResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.UpdateUserProfileResult, avias.codestar.models.UpdateUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateUserProfile", POST, "/", input)
  override def disassociateTeamMember(input: avias.codestar.models.DisassociateTeamMemberRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.codestar.models.DisassociateTeamMemberRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateTeamMember", POST, "/", input)
  override def deleteUserProfile(input: avias.codestar.models.DeleteUserProfileRequest): F[avias.codestar.models.DeleteUserProfileResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.codestar.models.DeleteUserProfileResult, avias.codestar.models.DeleteUserProfileRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteUserProfile", POST, "/", input)
}