package avias.emr.http4s
import org.http4s.Method._
import avias.emr.circe._
import avias.emr.models
import avias.common.http4s.ClientUtils._
class AmazonemrClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.emr.Amazonemr[F] {
  private[this] final val ServiceType: String = "elasticmapreduce"
  private[this] final val ServiceAndPrefix: Option[String] = Some("ElasticMapReduce")
  override def modifyInstanceFleet(input: avias.emr.models.ModifyInstanceFleetInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.ModifyInstanceFleetInput](client, awsData, ServiceType, ServiceAndPrefix, "ModifyInstanceFleet", POST, "/", input)
  override def deleteSecurityConfiguration(input: avias.emr.models.DeleteSecurityConfigurationInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.DeleteSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSecurityConfiguration", POST, "/", input)
  override def listSecurityConfigurations(input: avias.emr.models.ListSecurityConfigurationsInput): F[avias.emr.models.ListSecurityConfigurationsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListSecurityConfigurationsOutput, avias.emr.models.ListSecurityConfigurationsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListSecurityConfigurations", POST, "/", input)
  override def modifyInstanceGroups(input: avias.emr.models.ModifyInstanceGroupsInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.ModifyInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "ModifyInstanceGroups", POST, "/", input)
  override def describeSecurityConfiguration(input: avias.emr.models.DescribeSecurityConfigurationInput): F[avias.emr.models.DescribeSecurityConfigurationOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.DescribeSecurityConfigurationOutput, avias.emr.models.DescribeSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSecurityConfiguration", POST, "/", input)
  override def putAutoScalingPolicy(input: avias.emr.models.PutAutoScalingPolicyInput): F[avias.emr.models.PutAutoScalingPolicyOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.PutAutoScalingPolicyOutput, avias.emr.models.PutAutoScalingPolicyInput](client, awsData, ServiceType, ServiceAndPrefix, "PutAutoScalingPolicy", POST, "/", input)
  override def listSteps(input: avias.emr.models.ListStepsInput): F[avias.emr.models.ListStepsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListStepsOutput, avias.emr.models.ListStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListSteps", POST, "/", input)
  override def addJobFlowSteps(input: avias.emr.models.AddJobFlowStepsInput): F[avias.emr.models.AddJobFlowStepsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.AddJobFlowStepsOutput, avias.emr.models.AddJobFlowStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddJobFlowSteps", POST, "/", input)
  override def cancelSteps(input: avias.emr.models.CancelStepsInput): F[avias.emr.models.CancelStepsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.CancelStepsOutput, avias.emr.models.CancelStepsInput](client, awsData, ServiceType, ServiceAndPrefix, "CancelSteps", POST, "/", input)
  override def listInstanceFleets(input: avias.emr.models.ListInstanceFleetsInput): F[avias.emr.models.ListInstanceFleetsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListInstanceFleetsOutput, avias.emr.models.ListInstanceFleetsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstanceFleets", POST, "/", input)
  override def addInstanceFleet(input: avias.emr.models.AddInstanceFleetInput): F[avias.emr.models.AddInstanceFleetOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.AddInstanceFleetOutput, avias.emr.models.AddInstanceFleetInput](client, awsData, ServiceType, ServiceAndPrefix, "AddInstanceFleet", POST, "/", input)
  override def listClusters(input: avias.emr.models.ListClustersInput): F[avias.emr.models.ListClustersOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListClustersOutput, avias.emr.models.ListClustersInput](client, awsData, ServiceType, ServiceAndPrefix, "ListClusters", POST, "/", input)
  override def runJobFlow(input: avias.emr.models.RunJobFlowInput): F[avias.emr.models.RunJobFlowOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.RunJobFlowOutput, avias.emr.models.RunJobFlowInput](client, awsData, ServiceType, ServiceAndPrefix, "RunJobFlow", POST, "/", input)
  override def listInstances(input: avias.emr.models.ListInstancesInput): F[avias.emr.models.ListInstancesOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListInstancesOutput, avias.emr.models.ListInstancesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstances", POST, "/", input)
  override def describeStep(input: avias.emr.models.DescribeStepInput): F[avias.emr.models.DescribeStepOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.DescribeStepOutput, avias.emr.models.DescribeStepInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStep", POST, "/", input)
  override def setVisibleToAllUsers(input: avias.emr.models.SetVisibleToAllUsersInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.SetVisibleToAllUsersInput](client, awsData, ServiceType, ServiceAndPrefix, "SetVisibleToAllUsers", POST, "/", input)
  override def describeCluster(input: avias.emr.models.DescribeClusterInput): F[avias.emr.models.DescribeClusterOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.DescribeClusterOutput, avias.emr.models.DescribeClusterInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeCluster", POST, "/", input)
  override def terminateJobFlows(input: avias.emr.models.TerminateJobFlowsInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.TerminateJobFlowsInput](client, awsData, ServiceType, ServiceAndPrefix, "TerminateJobFlows", POST, "/", input)
  override def removeAutoScalingPolicy(input: avias.emr.models.RemoveAutoScalingPolicyInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.RemoveAutoScalingPolicyInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveAutoScalingPolicy", POST, "/", input)
  override def addInstanceGroups(input: avias.emr.models.AddInstanceGroupsInput): F[avias.emr.models.AddInstanceGroupsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.AddInstanceGroupsOutput, avias.emr.models.AddInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddInstanceGroups", POST, "/", input)
  override def listInstanceGroups(input: avias.emr.models.ListInstanceGroupsInput): F[avias.emr.models.ListInstanceGroupsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListInstanceGroupsOutput, avias.emr.models.ListInstanceGroupsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListInstanceGroups", POST, "/", input)
  override def addTags(input: avias.emr.models.AddTagsInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.AddTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTags", POST, "/", input)
  override def createSecurityConfiguration(input: avias.emr.models.CreateSecurityConfigurationInput): F[avias.emr.models.CreateSecurityConfigurationOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.CreateSecurityConfigurationOutput, avias.emr.models.CreateSecurityConfigurationInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateSecurityConfiguration", POST, "/", input)
  override def removeTags(input: avias.emr.models.RemoveTagsInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.RemoveTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTags", POST, "/", input)
  override def listBootstrapActions(input: avias.emr.models.ListBootstrapActionsInput): F[avias.emr.models.ListBootstrapActionsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.ListBootstrapActionsOutput, avias.emr.models.ListBootstrapActionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListBootstrapActions", POST, "/", input)
  override def setTerminationProtection(input: avias.emr.models.SetTerminationProtectionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.emr.models.SetTerminationProtectionInput](client, awsData, ServiceType, ServiceAndPrefix, "SetTerminationProtection", POST, "/", input)
  override def describeJobFlows(input: avias.emr.models.DescribeJobFlowsInput): F[avias.emr.models.DescribeJobFlowsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.emr.models.DescribeJobFlowsOutput, avias.emr.models.DescribeJobFlowsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeJobFlows", POST, "/", input)
}