package avias.workspaces.http4s
import org.http4s.Method._
import avias.workspaces.circe._
import avias.workspaces.models
import avias.common.http4s.ClientUtils._
class AmazonworkspacesClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.workspaces.Amazonworkspaces[F] {
  private[this] final val ServiceType: String = "workspaces"
  private[this] final val ServiceAndPrefix: Option[String] = Some("WorkspacesService")
  override def terminateWorkspaces(input: avias.workspaces.models.TerminateWorkspacesRequest): F[avias.workspaces.models.TerminateWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.TerminateWorkspacesResult, avias.workspaces.models.TerminateWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "TerminateWorkspaces", POST, "/", input)
  override def stopWorkspaces(input: avias.workspaces.models.StopWorkspacesRequest): F[avias.workspaces.models.StopWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.StopWorkspacesResult, avias.workspaces.models.StopWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopWorkspaces", POST, "/", input)
  override def rebootWorkspaces(input: avias.workspaces.models.RebootWorkspacesRequest): F[avias.workspaces.models.RebootWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.RebootWorkspacesResult, avias.workspaces.models.RebootWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebootWorkspaces", POST, "/", input)
  override def describeTags(input: avias.workspaces.models.DescribeTagsRequest): F[avias.workspaces.models.DescribeTagsResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.DescribeTagsResult, avias.workspaces.models.DescribeTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTags", POST, "/", input)
  override def describeWorkspaceBundles(input: avias.workspaces.models.DescribeWorkspaceBundlesRequest): F[avias.workspaces.models.DescribeWorkspaceBundlesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.DescribeWorkspaceBundlesResult, avias.workspaces.models.DescribeWorkspaceBundlesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaceBundles", POST, "/", input)
  override def describeWorkspacesConnectionStatus(input: avias.workspaces.models.DescribeWorkspacesConnectionStatusRequest): F[avias.workspaces.models.DescribeWorkspacesConnectionStatusResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.DescribeWorkspacesConnectionStatusResult, avias.workspaces.models.DescribeWorkspacesConnectionStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspacesConnectionStatus", POST, "/", input)
  override def describeWorkspaceDirectories(input: avias.workspaces.models.DescribeWorkspaceDirectoriesRequest): F[avias.workspaces.models.DescribeWorkspaceDirectoriesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.DescribeWorkspaceDirectoriesResult, avias.workspaces.models.DescribeWorkspaceDirectoriesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaceDirectories", POST, "/", input)
  override def deleteTags(input: avias.workspaces.models.DeleteTagsRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.workspaces.models.DeleteTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTags", POST, "/", input)
  override def createTags(input: avias.workspaces.models.CreateTagsRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.workspaces.models.CreateTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateTags", POST, "/", input)
  override def describeWorkspaces(input: avias.workspaces.models.DescribeWorkspacesRequest): F[avias.workspaces.models.DescribeWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.DescribeWorkspacesResult, avias.workspaces.models.DescribeWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkspaces", POST, "/", input)
  override def rebuildWorkspaces(input: avias.workspaces.models.RebuildWorkspacesRequest): F[avias.workspaces.models.RebuildWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.RebuildWorkspacesResult, avias.workspaces.models.RebuildWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebuildWorkspaces", POST, "/", input)
  override def createWorkspaces(input: avias.workspaces.models.CreateWorkspacesRequest): F[avias.workspaces.models.CreateWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.CreateWorkspacesResult, avias.workspaces.models.CreateWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateWorkspaces", POST, "/", input)
  override def startWorkspaces(input: avias.workspaces.models.StartWorkspacesRequest): F[avias.workspaces.models.StartWorkspacesResult] = avias.common.http4s.ClientUtils.doRequest[F, avias.workspaces.models.StartWorkspacesResult, avias.workspaces.models.StartWorkspacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartWorkspaces", POST, "/", input)
  override def modifyWorkspaceProperties(input: avias.workspaces.models.ModifyWorkspacePropertiesRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.workspaces.models.ModifyWorkspacePropertiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyWorkspaceProperties", POST, "/", input)
}