package org.lyranthe.araethura.budgets.http4s
import org.http4s.Method._
import org.lyranthe.araethura.budgets.circe._
import org.lyranthe.araethura.budgets.models
class AmazonbudgetsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.budgets.Amazonbudgets[F] {
  private[this] final val ServiceType: String = "budgets"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSBudgetServiceGateway")
  override def describeSubscribersForNotification(input: org.lyranthe.araethura.budgets.models.DescribeSubscribersForNotificationRequest): F[org.lyranthe.araethura.budgets.models.DescribeSubscribersForNotificationResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.budgets.models.DescribeSubscribersForNotificationResponse, org.lyranthe.araethura.budgets.models.DescribeSubscribersForNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSubscribersForNotification", POST, "/", input)
  override def createSubscriber(input: org.lyranthe.araethura.budgets.models.CreateSubscriberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.CreateSubscriberRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateSubscriber", POST, "/", input)
  override def deleteSubscriber(input: org.lyranthe.araethura.budgets.models.DeleteSubscriberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.DeleteSubscriberRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSubscriber", POST, "/", input)
  override def createBudget(input: org.lyranthe.araethura.budgets.models.CreateBudgetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.CreateBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateBudget", POST, "/", input)
  override def describeBudget(input: org.lyranthe.araethura.budgets.models.DescribeBudgetRequest): F[org.lyranthe.araethura.budgets.models.DescribeBudgetResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.budgets.models.DescribeBudgetResponse, org.lyranthe.araethura.budgets.models.DescribeBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBudget", POST, "/", input)
  override def deleteBudget(input: org.lyranthe.araethura.budgets.models.DeleteBudgetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.DeleteBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteBudget", POST, "/", input)
  override def updateSubscriber(input: org.lyranthe.araethura.budgets.models.UpdateSubscriberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.UpdateSubscriberRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateSubscriber", POST, "/", input)
  override def describeNotificationsForBudget(input: org.lyranthe.araethura.budgets.models.DescribeNotificationsForBudgetRequest): F[org.lyranthe.araethura.budgets.models.DescribeNotificationsForBudgetResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.budgets.models.DescribeNotificationsForBudgetResponse, org.lyranthe.araethura.budgets.models.DescribeNotificationsForBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeNotificationsForBudget", POST, "/", input)
  override def describeBudgets(input: org.lyranthe.araethura.budgets.models.DescribeBudgetsRequest): F[org.lyranthe.araethura.budgets.models.DescribeBudgetsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.budgets.models.DescribeBudgetsResponse, org.lyranthe.araethura.budgets.models.DescribeBudgetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBudgets", POST, "/", input)
  override def updateBudget(input: org.lyranthe.araethura.budgets.models.UpdateBudgetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.UpdateBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateBudget", POST, "/", input)
  override def deleteNotification(input: org.lyranthe.araethura.budgets.models.DeleteNotificationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.DeleteNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteNotification", POST, "/", input)
  override def createNotification(input: org.lyranthe.araethura.budgets.models.CreateNotificationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.CreateNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateNotification", POST, "/", input)
  override def updateNotification(input: org.lyranthe.araethura.budgets.models.UpdateNotificationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.budgets.models.UpdateNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateNotification", POST, "/", input)
}