package org.lyranthe.araethura.budgets.http4s
import org.http4s.Method._
import org.lyranthe.araethura.budgets.circe._
import org.lyranthe.araethura.budgets.models
class AmazonbudgetsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.budgets.Amazonbudgets[F] {
  private[this] final val ServiceType: String = "budgets"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSBudgetServiceGateway")
  override def describeSubscribersForNotification(input: models.DescribeSubscribersForNotificationRequest): F[models.DescribeSubscribersForNotificationResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeSubscribersForNotificationResponse, models.DescribeSubscribersForNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSubscribersForNotification", POST, "/", input)
  override def createSubscriber(input: models.CreateSubscriberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.CreateSubscriberRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateSubscriber", POST, "/", input)
  override def deleteSubscriber(input: models.DeleteSubscriberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteSubscriberRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSubscriber", POST, "/", input)
  override def createBudget(input: models.CreateBudgetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.CreateBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateBudget", POST, "/", input)
  override def describeBudget(input: models.DescribeBudgetRequest): F[models.DescribeBudgetResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeBudgetResponse, models.DescribeBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBudget", POST, "/", input)
  override def deleteBudget(input: models.DeleteBudgetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteBudget", POST, "/", input)
  override def updateSubscriber(input: models.UpdateSubscriberRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.UpdateSubscriberRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateSubscriber", POST, "/", input)
  override def describeNotificationsForBudget(input: models.DescribeNotificationsForBudgetRequest): F[models.DescribeNotificationsForBudgetResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeNotificationsForBudgetResponse, models.DescribeNotificationsForBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeNotificationsForBudget", POST, "/", input)
  override def describeBudgets(input: models.DescribeBudgetsRequest): F[models.DescribeBudgetsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeBudgetsResponse, models.DescribeBudgetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBudgets", POST, "/", input)
  override def updateBudget(input: models.UpdateBudgetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.UpdateBudgetRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateBudget", POST, "/", input)
  override def deleteNotification(input: models.DeleteNotificationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteNotification", POST, "/", input)
  override def createNotification(input: models.CreateNotificationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.CreateNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateNotification", POST, "/", input)
  override def updateNotification(input: models.UpdateNotificationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.UpdateNotificationRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateNotification", POST, "/", input)
}