package avias.kinesisanalytics.models
final case class InputProcessingConfigurationUpdate(inputLambdaProcessorUpdate: avias.kinesisanalytics.models.InputLambdaProcessorUpdate)
final case class AddApplicationCloudWatchLoggingOptionRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, cloudWatchLoggingOption: avias.kinesisanalytics.models.CloudWatchLoggingOption)
final case class ListApplicationsRequest(limit: scala.Option[scala.Int] = scala.None, exclusiveStartApplicationName: scala.Option[java.lang.String] = scala.None)
final case class AddApplicationOutputRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, output: avias.kinesisanalytics.models.Output)
final case class InputLambdaProcessorUpdate(resourceARNUpdate: scala.Option[java.lang.String] = scala.None, roleARNUpdate: scala.Option[java.lang.String] = scala.None)
case object AddApplicationInputResponse
case object DeleteApplicationReferenceDataSourceResponse
final case class InputProcessingConfiguration(inputLambdaProcessor: avias.kinesisanalytics.models.InputLambdaProcessor)
final case class SourceSchema(recordFormat: avias.kinesisanalytics.models.RecordFormat, recordColumns: scala.List[avias.kinesisanalytics.models.RecordColumn], recordEncoding: scala.Option[java.lang.String] = scala.None)
final case class ResourceProvisionedThroughputExceededException(message: scala.Option[java.lang.String] = scala.None)
final case class KinesisStreamsOutputDescription(resourceARN: scala.Option[java.lang.String] = scala.None, roleARN: scala.Option[java.lang.String] = scala.None)
final case class KinesisFirehoseOutputDescription(resourceARN: scala.Option[java.lang.String] = scala.None, roleARN: scala.Option[java.lang.String] = scala.None)
final case class InvalidArgumentException(message: scala.Option[java.lang.String] = scala.None)
final case class InputStartingPositionConfiguration(inputStartingPosition: scala.Option[java.lang.String] = scala.None)
final case class LimitExceededException(message: scala.Option[java.lang.String] = scala.None)
final case class ConcurrentModificationException(message: scala.Option[java.lang.String] = scala.None)
final case class AddApplicationReferenceDataSourceRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, referenceDataSource: avias.kinesisanalytics.models.ReferenceDataSource)
final case class KinesisStreamsInputDescription(resourceARN: scala.Option[java.lang.String] = scala.None, roleARN: scala.Option[java.lang.String] = scala.None)
final case class DeleteApplicationReferenceDataSourceRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, referenceId: java.lang.String)
final case class CSVMappingParameters(recordRowDelimiter: java.lang.String, recordColumnDelimiter: java.lang.String)
final case class ReferenceDataSourceUpdate(referenceId: java.lang.String, tableNameUpdate: scala.Option[java.lang.String] = scala.None, s3ReferenceDataSourceUpdate: scala.Option[avias.kinesisanalytics.models.S3ReferenceDataSourceUpdate] = scala.None, referenceSchemaUpdate: scala.Option[avias.kinesisanalytics.models.SourceSchema] = scala.None)
final case class StopApplicationRequest(applicationName: java.lang.String)
final case class ServiceUnavailableException(message: scala.Option[java.lang.String] = scala.None)
final case class DeleteApplicationOutputRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, outputId: java.lang.String)
final case class InputParallelismUpdate(countUpdate: scala.Option[scala.Int] = scala.None)
final case class KinesisFirehoseInput(resourceARN: java.lang.String, roleARN: java.lang.String)
final case class ListApplicationsResponse(applicationSummaries: scala.List[avias.kinesisanalytics.models.ApplicationSummary], hasMoreApplications: scala.Boolean)
final case class InputConfiguration(id: java.lang.String, inputStartingPositionConfiguration: avias.kinesisanalytics.models.InputStartingPositionConfiguration)
case object DeleteApplicationInputProcessingConfigurationResponse
case object AddApplicationInputProcessingConfigurationResponse
final case class DeleteApplicationInputProcessingConfigurationRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, inputId: java.lang.String)
final case class Output(name: java.lang.String, destinationSchema: avias.kinesisanalytics.models.DestinationSchema, kinesisStreamsOutput: scala.Option[avias.kinesisanalytics.models.KinesisStreamsOutput] = scala.None, kinesisFirehoseOutput: scala.Option[avias.kinesisanalytics.models.KinesisFirehoseOutput] = scala.None)
final case class S3ReferenceDataSourceUpdate(bucketARNUpdate: scala.Option[java.lang.String] = scala.None, fileKeyUpdate: scala.Option[java.lang.String] = scala.None, referenceRoleARNUpdate: scala.Option[java.lang.String] = scala.None)
final case class OutputUpdate(outputId: java.lang.String, nameUpdate: scala.Option[java.lang.String] = scala.None, kinesisStreamsOutputUpdate: scala.Option[avias.kinesisanalytics.models.KinesisStreamsOutputUpdate] = scala.None, kinesisFirehoseOutputUpdate: scala.Option[avias.kinesisanalytics.models.KinesisFirehoseOutputUpdate] = scala.None, destinationSchemaUpdate: scala.Option[avias.kinesisanalytics.models.DestinationSchema] = scala.None)
final case class JSONMappingParameters(recordRowPath: java.lang.String)
case object StartApplicationResponse
final case class KinesisStreamsInputUpdate(resourceARNUpdate: scala.Option[java.lang.String] = scala.None, roleARNUpdate: scala.Option[java.lang.String] = scala.None)
case object DeleteApplicationResponse
final case class ApplicationDetail(applicationVersionId: scala.Long, applicationStatus: java.lang.String, applicationARN: java.lang.String, applicationName: java.lang.String, createTimestamp: scala.Option[java.time.Instant] = scala.None, lastUpdateTimestamp: scala.Option[java.time.Instant] = scala.None, inputDescriptions: scala.Option[scala.List[avias.kinesisanalytics.models.InputDescription]] = scala.None, cloudWatchLoggingOptionDescriptions: scala.Option[scala.List[avias.kinesisanalytics.models.CloudWatchLoggingOptionDescription]] = scala.None, outputDescriptions: scala.Option[scala.List[avias.kinesisanalytics.models.OutputDescription]] = scala.None, applicationCode: scala.Option[java.lang.String] = scala.None, referenceDataSourceDescriptions: scala.Option[scala.List[avias.kinesisanalytics.models.ReferenceDataSourceDescription]] = scala.None, applicationDescription: scala.Option[java.lang.String] = scala.None)
final case class DiscoverInputSchemaResponse(inputSchema: scala.Option[avias.kinesisanalytics.models.SourceSchema] = scala.None, parsedInputRecords: scala.Option[scala.List[scala.List[java.lang.String]]] = scala.None, processedInputRecords: scala.Option[scala.List[java.lang.String]] = scala.None, rawInputRecords: scala.Option[scala.List[java.lang.String]] = scala.None)
final case class KinesisStreamsOutputUpdate(resourceARNUpdate: scala.Option[java.lang.String] = scala.None, roleARNUpdate: scala.Option[java.lang.String] = scala.None)
final case class OutputDescription(name: scala.Option[java.lang.String] = scala.None, kinesisStreamsOutputDescription: scala.Option[avias.kinesisanalytics.models.KinesisStreamsOutputDescription] = scala.None, kinesisFirehoseOutputDescription: scala.Option[avias.kinesisanalytics.models.KinesisFirehoseOutputDescription] = scala.None, outputId: scala.Option[java.lang.String] = scala.None, destinationSchema: scala.Option[avias.kinesisanalytics.models.DestinationSchema] = scala.None)
final case class DescribeApplicationRequest(applicationName: java.lang.String)
final case class UnableToDetectSchemaException(message: scala.Option[java.lang.String] = scala.None, rawInputRecords: scala.Option[scala.List[java.lang.String]] = scala.None, processedInputRecords: scala.Option[scala.List[java.lang.String]] = scala.None)
final case class UpdateApplicationRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, applicationUpdate: avias.kinesisanalytics.models.ApplicationUpdate)
final case class AddApplicationInputRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, input: avias.kinesisanalytics.models.Input)
final case class CloudWatchLoggingOption(logStreamARN: java.lang.String, roleARN: java.lang.String)
final case class KinesisStreamsOutput(resourceARN: java.lang.String, roleARN: java.lang.String)
case object DeleteApplicationOutputResponse
final case class InputProcessingConfigurationDescription(inputLambdaProcessorDescription: scala.Option[avias.kinesisanalytics.models.InputLambdaProcessorDescription] = scala.None)
final case class AddApplicationInputProcessingConfigurationRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, inputId: java.lang.String, inputProcessingConfiguration: avias.kinesisanalytics.models.InputProcessingConfiguration)
final case class ApplicationSummary(applicationName: java.lang.String, applicationARN: java.lang.String, applicationStatus: java.lang.String)
final case class ResourceNotFoundException(message: scala.Option[java.lang.String] = scala.None)
final case class CloudWatchLoggingOptionUpdate(cloudWatchLoggingOptionId: java.lang.String, logStreamARNUpdate: scala.Option[java.lang.String] = scala.None, roleARNUpdate: scala.Option[java.lang.String] = scala.None)
final case class DiscoverInputSchemaRequest(inputProcessingConfiguration: scala.Option[avias.kinesisanalytics.models.InputProcessingConfiguration] = scala.None, inputStartingPositionConfiguration: scala.Option[avias.kinesisanalytics.models.InputStartingPositionConfiguration] = scala.None, s3Configuration: scala.Option[avias.kinesisanalytics.models.S3Configuration] = scala.None, roleARN: scala.Option[java.lang.String] = scala.None, resourceARN: scala.Option[java.lang.String] = scala.None)
final case class S3ReferenceDataSourceDescription(bucketARN: java.lang.String, fileKey: java.lang.String, referenceRoleARN: java.lang.String)
final case class CloudWatchLoggingOptionDescription(logStreamARN: java.lang.String, roleARN: java.lang.String, cloudWatchLoggingOptionId: scala.Option[java.lang.String] = scala.None)
final case class InputUpdate(inputId: java.lang.String, inputProcessingConfigurationUpdate: scala.Option[avias.kinesisanalytics.models.InputProcessingConfigurationUpdate] = scala.None, namePrefixUpdate: scala.Option[java.lang.String] = scala.None, inputParallelismUpdate: scala.Option[avias.kinesisanalytics.models.InputParallelismUpdate] = scala.None, kinesisStreamsInputUpdate: scala.Option[avias.kinesisanalytics.models.KinesisStreamsInputUpdate] = scala.None, inputSchemaUpdate: scala.Option[avias.kinesisanalytics.models.InputSchemaUpdate] = scala.None, kinesisFirehoseInputUpdate: scala.Option[avias.kinesisanalytics.models.KinesisFirehoseInputUpdate] = scala.None)
final case class S3Configuration(roleARN: java.lang.String, bucketARN: java.lang.String, fileKey: java.lang.String)
final case class CreateApplicationRequest(applicationName: java.lang.String, outputs: scala.Option[scala.List[avias.kinesisanalytics.models.Output]] = scala.None, cloudWatchLoggingOptions: scala.Option[scala.List[avias.kinesisanalytics.models.CloudWatchLoggingOption]] = scala.None, inputs: scala.Option[scala.List[avias.kinesisanalytics.models.Input]] = scala.None, applicationCode: scala.Option[java.lang.String] = scala.None, applicationDescription: scala.Option[java.lang.String] = scala.None)
final case class S3ReferenceDataSource(bucketARN: java.lang.String, fileKey: java.lang.String, referenceRoleARN: java.lang.String)
case object AddApplicationOutputResponse
final case class RecordColumn(name: java.lang.String, sqlType: java.lang.String, mapping: scala.Option[java.lang.String] = scala.None)
final case class Input(namePrefix: java.lang.String, inputSchema: avias.kinesisanalytics.models.SourceSchema, inputProcessingConfiguration: scala.Option[avias.kinesisanalytics.models.InputProcessingConfiguration] = scala.None, kinesisFirehoseInput: scala.Option[avias.kinesisanalytics.models.KinesisFirehoseInput] = scala.None, inputParallelism: scala.Option[avias.kinesisanalytics.models.InputParallelism] = scala.None, kinesisStreamsInput: scala.Option[avias.kinesisanalytics.models.KinesisStreamsInput] = scala.None)
case object StopApplicationResponse
final case class DeleteApplicationRequest(applicationName: java.lang.String, createTimestamp: java.time.Instant)
case object UpdateApplicationResponse
final case class ResourceInUseException(message: scala.Option[java.lang.String] = scala.None)
final case class CreateApplicationResponse(applicationSummary: avias.kinesisanalytics.models.ApplicationSummary)
final case class KinesisFirehoseOutputUpdate(resourceARNUpdate: scala.Option[java.lang.String] = scala.None, roleARNUpdate: scala.Option[java.lang.String] = scala.None)
final case class InputLambdaProcessorDescription(resourceARN: scala.Option[java.lang.String] = scala.None, roleARN: scala.Option[java.lang.String] = scala.None)
final case class InvalidApplicationConfigurationException(message: scala.Option[java.lang.String] = scala.None)
final case class MappingParameters(jsonmappingParameters: scala.Option[avias.kinesisanalytics.models.JSONMappingParameters] = scala.None, csvmappingParameters: scala.Option[avias.kinesisanalytics.models.CSVMappingParameters] = scala.None)
final case class ReferenceDataSourceDescription(referenceId: java.lang.String, tableName: java.lang.String, s3ReferenceDataSourceDescription: avias.kinesisanalytics.models.S3ReferenceDataSourceDescription, referenceSchema: scala.Option[avias.kinesisanalytics.models.SourceSchema] = scala.None)
case object DeleteApplicationCloudWatchLoggingOptionResponse
final case class InputLambdaProcessor(resourceARN: java.lang.String, roleARN: java.lang.String)
case object AddApplicationReferenceDataSourceResponse
final case class InputParallelism(count: scala.Option[scala.Int] = scala.None)
final case class KinesisStreamsInput(resourceARN: java.lang.String, roleARN: java.lang.String)
final case class DestinationSchema(recordFormatType: scala.Option[java.lang.String] = scala.None)
final case class KinesisFirehoseInputDescription(resourceARN: scala.Option[java.lang.String] = scala.None, roleARN: scala.Option[java.lang.String] = scala.None)
final case class CodeValidationException(message: scala.Option[java.lang.String] = scala.None)
final case class KinesisFirehoseOutput(resourceARN: java.lang.String, roleARN: java.lang.String)
final case class DeleteApplicationCloudWatchLoggingOptionRequest(applicationName: java.lang.String, currentApplicationVersionId: scala.Long, cloudWatchLoggingOptionId: java.lang.String)
final case class ApplicationUpdate(inputUpdates: scala.Option[scala.List[avias.kinesisanalytics.models.InputUpdate]] = scala.None, referenceDataSourceUpdates: scala.Option[scala.List[avias.kinesisanalytics.models.ReferenceDataSourceUpdate]] = scala.None, cloudWatchLoggingOptionUpdates: scala.Option[scala.List[avias.kinesisanalytics.models.CloudWatchLoggingOptionUpdate]] = scala.None, applicationCodeUpdate: scala.Option[java.lang.String] = scala.None, outputUpdates: scala.Option[scala.List[avias.kinesisanalytics.models.OutputUpdate]] = scala.None)
case object AddApplicationCloudWatchLoggingOptionResponse
final case class InputSchemaUpdate(recordFormatUpdate: scala.Option[avias.kinesisanalytics.models.RecordFormat] = scala.None, recordEncodingUpdate: scala.Option[java.lang.String] = scala.None, recordColumnUpdates: scala.Option[scala.List[avias.kinesisanalytics.models.RecordColumn]] = scala.None)
final case class RecordFormat(recordFormatType: java.lang.String, mappingParameters: scala.Option[avias.kinesisanalytics.models.MappingParameters] = scala.None)
final case class InputDescription(namePrefix: scala.Option[java.lang.String] = scala.None, inputSchema: scala.Option[avias.kinesisanalytics.models.SourceSchema] = scala.None, inputStartingPositionConfiguration: scala.Option[avias.kinesisanalytics.models.InputStartingPositionConfiguration] = scala.None, kinesisStreamsInputDescription: scala.Option[avias.kinesisanalytics.models.KinesisStreamsInputDescription] = scala.None, inAppStreamNames: scala.Option[scala.List[java.lang.String]] = scala.None, inputProcessingConfigurationDescription: scala.Option[avias.kinesisanalytics.models.InputProcessingConfigurationDescription] = scala.None, inputId: scala.Option[java.lang.String] = scala.None, inputParallelism: scala.Option[avias.kinesisanalytics.models.InputParallelism] = scala.None, kinesisFirehoseInputDescription: scala.Option[avias.kinesisanalytics.models.KinesisFirehoseInputDescription] = scala.None)
final case class DescribeApplicationResponse(applicationDetail: avias.kinesisanalytics.models.ApplicationDetail)
final case class StartApplicationRequest(applicationName: java.lang.String, inputConfigurations: scala.List[avias.kinesisanalytics.models.InputConfiguration])
final case class ReferenceDataSource(tableName: java.lang.String, referenceSchema: avias.kinesisanalytics.models.SourceSchema, s3ReferenceDataSource: scala.Option[avias.kinesisanalytics.models.S3ReferenceDataSource] = scala.None)
final case class KinesisFirehoseInputUpdate(resourceARNUpdate: scala.Option[java.lang.String] = scala.None, roleARNUpdate: scala.Option[java.lang.String] = scala.None)