package avias.kinesisanalytics
trait Amazonkinesisanalytics[F[_]] {
  def createApplication(input: avias.kinesisanalytics.models.CreateApplicationRequest): F[avias.kinesisanalytics.models.CreateApplicationResponse]
  def deleteApplicationInputProcessingConfiguration(input: avias.kinesisanalytics.models.DeleteApplicationInputProcessingConfigurationRequest): F[scala.Unit]
  def deleteApplicationOutput(input: avias.kinesisanalytics.models.DeleteApplicationOutputRequest): F[scala.Unit]
  def deleteApplicationReferenceDataSource(input: avias.kinesisanalytics.models.DeleteApplicationReferenceDataSourceRequest): F[scala.Unit]
  def listApplications(input: avias.kinesisanalytics.models.ListApplicationsRequest): F[avias.kinesisanalytics.models.ListApplicationsResponse]
  def deleteApplication(input: avias.kinesisanalytics.models.DeleteApplicationRequest): F[scala.Unit]
  def stopApplication(input: avias.kinesisanalytics.models.StopApplicationRequest): F[scala.Unit]
  def addApplicationOutput(input: avias.kinesisanalytics.models.AddApplicationOutputRequest): F[scala.Unit]
  def addApplicationReferenceDataSource(input: avias.kinesisanalytics.models.AddApplicationReferenceDataSourceRequest): F[scala.Unit]
  def updateApplication(input: avias.kinesisanalytics.models.UpdateApplicationRequest): F[scala.Unit]
  def describeApplication(input: avias.kinesisanalytics.models.DescribeApplicationRequest): F[avias.kinesisanalytics.models.DescribeApplicationResponse]
  def addApplicationInputProcessingConfiguration(input: avias.kinesisanalytics.models.AddApplicationInputProcessingConfigurationRequest): F[scala.Unit]
  def deleteApplicationCloudWatchLoggingOption(input: avias.kinesisanalytics.models.DeleteApplicationCloudWatchLoggingOptionRequest): F[scala.Unit]
  def startApplication(input: avias.kinesisanalytics.models.StartApplicationRequest): F[scala.Unit]
  def discoverInputSchema(input: avias.kinesisanalytics.models.DiscoverInputSchemaRequest): F[avias.kinesisanalytics.models.DiscoverInputSchemaResponse]
  def addApplicationInput(input: avias.kinesisanalytics.models.AddApplicationInputRequest): F[scala.Unit]
  def addApplicationCloudWatchLoggingOption(input: avias.kinesisanalytics.models.AddApplicationCloudWatchLoggingOptionRequest): F[scala.Unit]
}