package org.lyranthe.araethura.applicationautoscaling.http4s
import org.http4s.Method._
import org.lyranthe.araethura.applicationautoscaling.circe._
import org.lyranthe.araethura.applicationautoscaling.models
class AmazonapplicationautoscalingClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.applicationautoscaling.Amazonapplicationautoscaling[F] {
  private[this] final val ServiceType: String = "autoscaling"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AnyScaleFrontendService")
  override def deregisterScalableTarget(input: org.lyranthe.araethura.applicationautoscaling.models.DeregisterScalableTargetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.applicationautoscaling.models.DeregisterScalableTargetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeregisterScalableTarget", POST, "/", input)
  override def registerScalableTarget(input: org.lyranthe.araethura.applicationautoscaling.models.RegisterScalableTargetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.applicationautoscaling.models.RegisterScalableTargetRequest](client, awsData, ServiceType, ServiceAndPrefix, "RegisterScalableTarget", POST, "/", input)
  override def describeScalingActivities(input: org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingActivitiesRequest): F[org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingActivitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingActivitiesResponse, org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingActivitiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScalingActivities", POST, "/", input)
  override def deleteScalingPolicy(input: org.lyranthe.araethura.applicationautoscaling.models.DeleteScalingPolicyRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.applicationautoscaling.models.DeleteScalingPolicyRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteScalingPolicy", POST, "/", input)
  override def deleteScheduledAction(input: org.lyranthe.araethura.applicationautoscaling.models.DeleteScheduledActionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.applicationautoscaling.models.DeleteScheduledActionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteScheduledAction", POST, "/", input)
  override def putScalingPolicy(input: org.lyranthe.araethura.applicationautoscaling.models.PutScalingPolicyRequest): F[org.lyranthe.araethura.applicationautoscaling.models.PutScalingPolicyResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.applicationautoscaling.models.PutScalingPolicyResponse, org.lyranthe.araethura.applicationautoscaling.models.PutScalingPolicyRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutScalingPolicy", POST, "/", input)
  override def describeScalableTargets(input: org.lyranthe.araethura.applicationautoscaling.models.DescribeScalableTargetsRequest): F[org.lyranthe.araethura.applicationautoscaling.models.DescribeScalableTargetsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.applicationautoscaling.models.DescribeScalableTargetsResponse, org.lyranthe.araethura.applicationautoscaling.models.DescribeScalableTargetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScalableTargets", POST, "/", input)
  override def putScheduledAction(input: org.lyranthe.araethura.applicationautoscaling.models.PutScheduledActionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.applicationautoscaling.models.PutScheduledActionRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutScheduledAction", POST, "/", input)
  override def describeScalingPolicies(input: org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingPoliciesRequest): F[org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingPoliciesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingPoliciesResponse, org.lyranthe.araethura.applicationautoscaling.models.DescribeScalingPoliciesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScalingPolicies", POST, "/", input)
  override def describeScheduledActions(input: org.lyranthe.araethura.applicationautoscaling.models.DescribeScheduledActionsRequest): F[org.lyranthe.araethura.applicationautoscaling.models.DescribeScheduledActionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.applicationautoscaling.models.DescribeScheduledActionsResponse, org.lyranthe.araethura.applicationautoscaling.models.DescribeScheduledActionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScheduledActions", POST, "/", input)
}