package org.lyranthe.araethura.applicationautoscaling.http4s
import org.http4s.Method._
import org.lyranthe.araethura.applicationautoscaling.circe._
import org.lyranthe.araethura.applicationautoscaling.models
class AmazonapplicationautoscalingClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.applicationautoscaling.Amazonapplicationautoscaling[F] {
  private[this] final val ServiceType: String = "autoscaling"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AnyScaleFrontendService")
  override def deregisterScalableTarget(input: models.DeregisterScalableTargetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeregisterScalableTargetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeregisterScalableTarget", POST, "/", input)
  override def registerScalableTarget(input: models.RegisterScalableTargetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.RegisterScalableTargetRequest](client, awsData, ServiceType, ServiceAndPrefix, "RegisterScalableTarget", POST, "/", input)
  override def describeScalingActivities(input: models.DescribeScalingActivitiesRequest): F[models.DescribeScalingActivitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeScalingActivitiesResponse, models.DescribeScalingActivitiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScalingActivities", POST, "/", input)
  override def deleteScalingPolicy(input: models.DeleteScalingPolicyRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteScalingPolicyRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteScalingPolicy", POST, "/", input)
  override def deleteScheduledAction(input: models.DeleteScheduledActionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteScheduledActionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteScheduledAction", POST, "/", input)
  override def putScalingPolicy(input: models.PutScalingPolicyRequest): F[models.PutScalingPolicyResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutScalingPolicyResponse, models.PutScalingPolicyRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutScalingPolicy", POST, "/", input)
  override def describeScalableTargets(input: models.DescribeScalableTargetsRequest): F[models.DescribeScalableTargetsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeScalableTargetsResponse, models.DescribeScalableTargetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScalableTargets", POST, "/", input)
  override def putScheduledAction(input: models.PutScheduledActionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.PutScheduledActionRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutScheduledAction", POST, "/", input)
  override def describeScalingPolicies(input: models.DescribeScalingPoliciesRequest): F[models.DescribeScalingPoliciesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeScalingPoliciesResponse, models.DescribeScalingPoliciesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScalingPolicies", POST, "/", input)
  override def describeScheduledActions(input: models.DescribeScheduledActionsRequest): F[models.DescribeScheduledActionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeScheduledActionsResponse, models.DescribeScheduledActionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeScheduledActions", POST, "/", input)
}