package org.lyranthe.araethura.machinelearning
trait Amazonmachinelearning[F[_]] {
  def describeTags(input: org.lyranthe.araethura.machinelearning.models.DescribeTagsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeTagsOutput]
  def createEvaluation(input: org.lyranthe.araethura.machinelearning.models.CreateEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.CreateEvaluationOutput]
  def createDataSourceFromRedshift(input: org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRedshiftInput): F[org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRedshiftOutput]
  def describeBatchPredictions(input: org.lyranthe.araethura.machinelearning.models.DescribeBatchPredictionsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeBatchPredictionsOutput]
  def createDataSourceFromRDS(input: org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRDSInput): F[org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromRDSOutput]
  def createBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.CreateBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.CreateBatchPredictionOutput]
  def addTags(input: org.lyranthe.araethura.machinelearning.models.AddTagsInput): F[org.lyranthe.araethura.machinelearning.models.AddTagsOutput]
  def updateDataSource(input: org.lyranthe.araethura.machinelearning.models.UpdateDataSourceInput): F[org.lyranthe.araethura.machinelearning.models.UpdateDataSourceOutput]
  def deleteMLModel(input: org.lyranthe.araethura.machinelearning.models.DeleteMLModelInput): F[org.lyranthe.araethura.machinelearning.models.DeleteMLModelOutput]
  def deleteEvaluation(input: org.lyranthe.araethura.machinelearning.models.DeleteEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.DeleteEvaluationOutput]
  def describeEvaluations(input: org.lyranthe.araethura.machinelearning.models.DescribeEvaluationsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeEvaluationsOutput]
  def predict(input: org.lyranthe.araethura.machinelearning.models.PredictInput): F[org.lyranthe.araethura.machinelearning.models.PredictOutput]
  def describeDataSources(input: org.lyranthe.araethura.machinelearning.models.DescribeDataSourcesInput): F[org.lyranthe.araethura.machinelearning.models.DescribeDataSourcesOutput]
  def createDataSourceFromS3(input: org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromS3Input): F[org.lyranthe.araethura.machinelearning.models.CreateDataSourceFromS3Output]
  def deleteDataSource(input: org.lyranthe.araethura.machinelearning.models.DeleteDataSourceInput): F[org.lyranthe.araethura.machinelearning.models.DeleteDataSourceOutput]
  def getBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.GetBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.GetBatchPredictionOutput]
  def deleteRealtimeEndpoint(input: org.lyranthe.araethura.machinelearning.models.DeleteRealtimeEndpointInput): F[org.lyranthe.araethura.machinelearning.models.DeleteRealtimeEndpointOutput]
  def describeMLModels(input: org.lyranthe.araethura.machinelearning.models.DescribeMLModelsInput): F[org.lyranthe.araethura.machinelearning.models.DescribeMLModelsOutput]
  def deleteBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.DeleteBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.DeleteBatchPredictionOutput]
  def createMLModel(input: org.lyranthe.araethura.machinelearning.models.CreateMLModelInput): F[org.lyranthe.araethura.machinelearning.models.CreateMLModelOutput]
  def updateBatchPrediction(input: org.lyranthe.araethura.machinelearning.models.UpdateBatchPredictionInput): F[org.lyranthe.araethura.machinelearning.models.UpdateBatchPredictionOutput]
  def getMLModel(input: org.lyranthe.araethura.machinelearning.models.GetMLModelInput): F[org.lyranthe.araethura.machinelearning.models.GetMLModelOutput]
  def updateMLModel(input: org.lyranthe.araethura.machinelearning.models.UpdateMLModelInput): F[org.lyranthe.araethura.machinelearning.models.UpdateMLModelOutput]
  def getEvaluation(input: org.lyranthe.araethura.machinelearning.models.GetEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.GetEvaluationOutput]
  def createRealtimeEndpoint(input: org.lyranthe.araethura.machinelearning.models.CreateRealtimeEndpointInput): F[org.lyranthe.araethura.machinelearning.models.CreateRealtimeEndpointOutput]
  def updateEvaluation(input: org.lyranthe.araethura.machinelearning.models.UpdateEvaluationInput): F[org.lyranthe.araethura.machinelearning.models.UpdateEvaluationOutput]
  def deleteTags(input: org.lyranthe.araethura.machinelearning.models.DeleteTagsInput): F[org.lyranthe.araethura.machinelearning.models.DeleteTagsOutput]
  def getDataSource(input: org.lyranthe.araethura.machinelearning.models.GetDataSourceInput): F[org.lyranthe.araethura.machinelearning.models.GetDataSourceOutput]
}