package avias.discovery.http4s
import org.http4s.Method._
import avias.discovery.circe._
import avias.discovery.models
class AmazondiscoveryClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.discovery.Amazondiscovery[F] {
  private[this] final val ServiceType: String = "discovery"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSPoseidonService_V2015_11_01")
  override def listConfigurations(input: avias.discovery.models.ListConfigurationsRequest): F[avias.discovery.models.ListConfigurationsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.ListConfigurationsResponse, avias.discovery.models.ListConfigurationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListConfigurations", POST, "/", input)
  override def listServerNeighbors(input: avias.discovery.models.ListServerNeighborsRequest): F[avias.discovery.models.ListServerNeighborsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.ListServerNeighborsResponse, avias.discovery.models.ListServerNeighborsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListServerNeighbors", POST, "/", input)
  override def deleteTags(input: avias.discovery.models.DeleteTagsRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.discovery.models.DeleteTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTags", POST, "/", input)
  override def describeAgents(input: avias.discovery.models.DescribeAgentsRequest): F[avias.discovery.models.DescribeAgentsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.DescribeAgentsResponse, avias.discovery.models.DescribeAgentsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAgents", POST, "/", input)
  override def createTags(input: avias.discovery.models.CreateTagsRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.discovery.models.CreateTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateTags", POST, "/", input)
  override def describeTags(input: avias.discovery.models.DescribeTagsRequest): F[avias.discovery.models.DescribeTagsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.DescribeTagsResponse, avias.discovery.models.DescribeTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTags", POST, "/", input)
  override def describeExportConfigurations(input: avias.discovery.models.DescribeExportConfigurationsRequest): F[avias.discovery.models.DescribeExportConfigurationsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.DescribeExportConfigurationsResponse, avias.discovery.models.DescribeExportConfigurationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExportConfigurations", POST, "/", input)
  override def updateApplication(input: avias.discovery.models.UpdateApplicationRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.discovery.models.UpdateApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateApplication", POST, "/", input)
  override def startDataCollectionByAgentIds(input: avias.discovery.models.StartDataCollectionByAgentIdsRequest): F[avias.discovery.models.StartDataCollectionByAgentIdsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.StartDataCollectionByAgentIdsResponse, avias.discovery.models.StartDataCollectionByAgentIdsRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartDataCollectionByAgentIds", POST, "/", input)
  override def createApplication(input: avias.discovery.models.CreateApplicationRequest): F[avias.discovery.models.CreateApplicationResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.CreateApplicationResponse, avias.discovery.models.CreateApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateApplication", POST, "/", input)
  override def startExportTask(input: avias.discovery.models.StartExportTaskRequest): F[avias.discovery.models.StartExportTaskResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.StartExportTaskResponse, avias.discovery.models.StartExportTaskRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartExportTask", POST, "/", input)
  override def exportConfigurations: F[avias.discovery.models.ExportConfigurationsResponse] = avias.common.http4s.ClientUtils.doRequestWithoutBody[F, avias.discovery.models.ExportConfigurationsResponse](client, awsData, ServiceType, ServiceAndPrefix, "ExportConfigurations", POST, "/")
  override def associateConfigurationItemsToApplication(input: avias.discovery.models.AssociateConfigurationItemsToApplicationRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.discovery.models.AssociateConfigurationItemsToApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateConfigurationItemsToApplication", POST, "/", input)
  override def stopDataCollectionByAgentIds(input: avias.discovery.models.StopDataCollectionByAgentIdsRequest): F[avias.discovery.models.StopDataCollectionByAgentIdsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.StopDataCollectionByAgentIdsResponse, avias.discovery.models.StopDataCollectionByAgentIdsRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopDataCollectionByAgentIds", POST, "/", input)
  override def disassociateConfigurationItemsFromApplication(input: avias.discovery.models.DisassociateConfigurationItemsFromApplicationRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.discovery.models.DisassociateConfigurationItemsFromApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateConfigurationItemsFromApplication", POST, "/", input)
  override def describeExportTasks(input: avias.discovery.models.DescribeExportTasksRequest): F[avias.discovery.models.DescribeExportTasksResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.DescribeExportTasksResponse, avias.discovery.models.DescribeExportTasksRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExportTasks", POST, "/", input)
  override def getDiscoverySummary: F[avias.discovery.models.GetDiscoverySummaryResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.GetDiscoverySummaryResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "GetDiscoverySummary", POST, "/", ())
  override def describeConfigurations(input: avias.discovery.models.DescribeConfigurationsRequest): F[avias.discovery.models.DescribeConfigurationsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.discovery.models.DescribeConfigurationsResponse, avias.discovery.models.DescribeConfigurationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurations", POST, "/", input)
  override def deleteApplications(input: avias.discovery.models.DeleteApplicationsRequest): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.discovery.models.DeleteApplicationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplications", POST, "/", input)
}