package org.lyranthe.araethura.discovery.http4s
import org.http4s.Method._
import org.lyranthe.araethura.discovery.circe._
import org.lyranthe.araethura.discovery.models
class AmazondiscoveryClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.discovery.Amazondiscovery[F] {
  private[this] final val ServiceType: String = "discovery"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSPoseidonService_V2015_11_01")
  override def listConfigurations(input: org.lyranthe.araethura.discovery.models.ListConfigurationsRequest): F[org.lyranthe.araethura.discovery.models.ListConfigurationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.ListConfigurationsResponse, org.lyranthe.araethura.discovery.models.ListConfigurationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListConfigurations", POST, "/", input)
  override def listServerNeighbors(input: org.lyranthe.araethura.discovery.models.ListServerNeighborsRequest): F[org.lyranthe.araethura.discovery.models.ListServerNeighborsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.ListServerNeighborsResponse, org.lyranthe.araethura.discovery.models.ListServerNeighborsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListServerNeighbors", POST, "/", input)
  override def deleteTags(input: org.lyranthe.araethura.discovery.models.DeleteTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.discovery.models.DeleteTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTags", POST, "/", input)
  override def describeAgents(input: org.lyranthe.araethura.discovery.models.DescribeAgentsRequest): F[org.lyranthe.araethura.discovery.models.DescribeAgentsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.DescribeAgentsResponse, org.lyranthe.araethura.discovery.models.DescribeAgentsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAgents", POST, "/", input)
  override def createTags(input: org.lyranthe.araethura.discovery.models.CreateTagsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.discovery.models.CreateTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateTags", POST, "/", input)
  override def describeTags(input: org.lyranthe.araethura.discovery.models.DescribeTagsRequest): F[org.lyranthe.araethura.discovery.models.DescribeTagsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.DescribeTagsResponse, org.lyranthe.araethura.discovery.models.DescribeTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTags", POST, "/", input)
  override def describeExportConfigurations(input: org.lyranthe.araethura.discovery.models.DescribeExportConfigurationsRequest): F[org.lyranthe.araethura.discovery.models.DescribeExportConfigurationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.DescribeExportConfigurationsResponse, org.lyranthe.araethura.discovery.models.DescribeExportConfigurationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExportConfigurations", POST, "/", input)
  override def updateApplication(input: org.lyranthe.araethura.discovery.models.UpdateApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.discovery.models.UpdateApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateApplication", POST, "/", input)
  override def startDataCollectionByAgentIds(input: org.lyranthe.araethura.discovery.models.StartDataCollectionByAgentIdsRequest): F[org.lyranthe.araethura.discovery.models.StartDataCollectionByAgentIdsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.StartDataCollectionByAgentIdsResponse, org.lyranthe.araethura.discovery.models.StartDataCollectionByAgentIdsRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartDataCollectionByAgentIds", POST, "/", input)
  override def createApplication(input: org.lyranthe.araethura.discovery.models.CreateApplicationRequest): F[org.lyranthe.araethura.discovery.models.CreateApplicationResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.CreateApplicationResponse, org.lyranthe.araethura.discovery.models.CreateApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateApplication", POST, "/", input)
  override def startExportTask(input: org.lyranthe.araethura.discovery.models.StartExportTaskRequest): F[org.lyranthe.araethura.discovery.models.StartExportTaskResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.StartExportTaskResponse, org.lyranthe.araethura.discovery.models.StartExportTaskRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartExportTask", POST, "/", input)
  override def exportConfigurations: F[org.lyranthe.araethura.discovery.models.ExportConfigurationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequestWithoutBody[F, org.lyranthe.araethura.discovery.models.ExportConfigurationsResponse](client, awsData, ServiceType, ServiceAndPrefix, "ExportConfigurations", POST, "/")
  override def associateConfigurationItemsToApplication(input: org.lyranthe.araethura.discovery.models.AssociateConfigurationItemsToApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.discovery.models.AssociateConfigurationItemsToApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateConfigurationItemsToApplication", POST, "/", input)
  override def stopDataCollectionByAgentIds(input: org.lyranthe.araethura.discovery.models.StopDataCollectionByAgentIdsRequest): F[org.lyranthe.araethura.discovery.models.StopDataCollectionByAgentIdsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.StopDataCollectionByAgentIdsResponse, org.lyranthe.araethura.discovery.models.StopDataCollectionByAgentIdsRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopDataCollectionByAgentIds", POST, "/", input)
  override def disassociateConfigurationItemsFromApplication(input: org.lyranthe.araethura.discovery.models.DisassociateConfigurationItemsFromApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.discovery.models.DisassociateConfigurationItemsFromApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateConfigurationItemsFromApplication", POST, "/", input)
  override def describeExportTasks(input: org.lyranthe.araethura.discovery.models.DescribeExportTasksRequest): F[org.lyranthe.araethura.discovery.models.DescribeExportTasksResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.DescribeExportTasksResponse, org.lyranthe.araethura.discovery.models.DescribeExportTasksRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExportTasks", POST, "/", input)
  override def getDiscoverySummary: F[org.lyranthe.araethura.discovery.models.GetDiscoverySummaryResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.GetDiscoverySummaryResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "GetDiscoverySummary", POST, "/", ())
  override def describeConfigurations(input: org.lyranthe.araethura.discovery.models.DescribeConfigurationsRequest): F[org.lyranthe.araethura.discovery.models.DescribeConfigurationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.discovery.models.DescribeConfigurationsResponse, org.lyranthe.araethura.discovery.models.DescribeConfigurationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeConfigurations", POST, "/", input)
  override def deleteApplications(input: org.lyranthe.araethura.discovery.models.DeleteApplicationsRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.discovery.models.DeleteApplicationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplications", POST, "/", input)
}