package avias.athena.http4s
import org.http4s.Method._
import avias.athena.circe._
import avias.athena.models
import avias.common.http4s.ClientUtils._
class AmazonathenaClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.athena.Amazonathena[F] {
  private[this] final val ServiceType: String = "athena"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AmazonAthena")
  override def listQueryExecutions(input: avias.athena.models.ListQueryExecutionsInput): F[avias.athena.models.ListQueryExecutionsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.ListQueryExecutionsOutput, avias.athena.models.ListQueryExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListQueryExecutions", POST, "/", input)
  override def getQueryExecution(input: avias.athena.models.GetQueryExecutionInput): F[avias.athena.models.GetQueryExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.GetQueryExecutionOutput, avias.athena.models.GetQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "GetQueryExecution", POST, "/", input)
  override def deleteNamedQuery(input: avias.athena.models.DeleteNamedQueryInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.athena.models.DeleteNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteNamedQuery", POST, "/", input)
  override def batchGetQueryExecution(input: avias.athena.models.BatchGetQueryExecutionInput): F[avias.athena.models.BatchGetQueryExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.BatchGetQueryExecutionOutput, avias.athena.models.BatchGetQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetQueryExecution", POST, "/", input)
  override def getNamedQuery(input: avias.athena.models.GetNamedQueryInput): F[avias.athena.models.GetNamedQueryOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.GetNamedQueryOutput, avias.athena.models.GetNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "GetNamedQuery", POST, "/", input)
  override def stopQueryExecution(input: avias.athena.models.StopQueryExecutionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.athena.models.StopQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopQueryExecution", POST, "/", input)
  override def getQueryResults(input: avias.athena.models.GetQueryResultsInput): F[avias.athena.models.GetQueryResultsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.GetQueryResultsOutput, avias.athena.models.GetQueryResultsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetQueryResults", POST, "/", input)
  override def createNamedQuery(input: avias.athena.models.CreateNamedQueryInput): F[avias.athena.models.CreateNamedQueryOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.CreateNamedQueryOutput, avias.athena.models.CreateNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateNamedQuery", POST, "/", input)
  override def startQueryExecution(input: avias.athena.models.StartQueryExecutionInput): F[avias.athena.models.StartQueryExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.StartQueryExecutionOutput, avias.athena.models.StartQueryExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartQueryExecution", POST, "/", input)
  override def batchGetNamedQuery(input: avias.athena.models.BatchGetNamedQueryInput): F[avias.athena.models.BatchGetNamedQueryOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.BatchGetNamedQueryOutput, avias.athena.models.BatchGetNamedQueryInput](client, awsData, ServiceType, ServiceAndPrefix, "BatchGetNamedQuery", POST, "/", input)
  override def listNamedQueries(input: avias.athena.models.ListNamedQueriesInput): F[avias.athena.models.ListNamedQueriesOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.athena.models.ListNamedQueriesOutput, avias.athena.models.ListNamedQueriesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListNamedQueries", POST, "/", input)
}