package org.lyranthe.araethura.datapipeline.http4s
import org.http4s.Method._
import org.lyranthe.araethura.datapipeline.circe._
import org.lyranthe.araethura.datapipeline.models
class AmazondatapipelineClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.datapipeline.Amazondatapipeline[F] {
  private[this] final val ServiceType: String = "datapipeline"
  private[this] final val ServiceAndPrefix: Option[String] = Some("DataPipeline")
  override def deactivatePipeline(input: org.lyranthe.araethura.datapipeline.models.DeactivatePipelineInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.DeactivatePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "DeactivatePipeline", POST, "/", input)
  override def queryObjects(input: org.lyranthe.araethura.datapipeline.models.QueryObjectsInput): F[org.lyranthe.araethura.datapipeline.models.QueryObjectsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.QueryObjectsOutput, org.lyranthe.araethura.datapipeline.models.QueryObjectsInput](client, awsData, ServiceType, ServiceAndPrefix, "QueryObjects", POST, "/", input)
  override def putPipelineDefinition(input: org.lyranthe.araethura.datapipeline.models.PutPipelineDefinitionInput): F[org.lyranthe.araethura.datapipeline.models.PutPipelineDefinitionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.PutPipelineDefinitionOutput, org.lyranthe.araethura.datapipeline.models.PutPipelineDefinitionInput](client, awsData, ServiceType, ServiceAndPrefix, "PutPipelineDefinition", POST, "/", input)
  override def evaluateExpression(input: org.lyranthe.araethura.datapipeline.models.EvaluateExpressionInput): F[org.lyranthe.araethura.datapipeline.models.EvaluateExpressionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.EvaluateExpressionOutput, org.lyranthe.araethura.datapipeline.models.EvaluateExpressionInput](client, awsData, ServiceType, ServiceAndPrefix, "EvaluateExpression", POST, "/", input)
  override def reportTaskRunnerHeartbeat(input: org.lyranthe.araethura.datapipeline.models.ReportTaskRunnerHeartbeatInput): F[org.lyranthe.araethura.datapipeline.models.ReportTaskRunnerHeartbeatOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.ReportTaskRunnerHeartbeatOutput, org.lyranthe.araethura.datapipeline.models.ReportTaskRunnerHeartbeatInput](client, awsData, ServiceType, ServiceAndPrefix, "ReportTaskRunnerHeartbeat", POST, "/", input)
  override def getPipelineDefinition(input: org.lyranthe.araethura.datapipeline.models.GetPipelineDefinitionInput): F[org.lyranthe.araethura.datapipeline.models.GetPipelineDefinitionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.GetPipelineDefinitionOutput, org.lyranthe.araethura.datapipeline.models.GetPipelineDefinitionInput](client, awsData, ServiceType, ServiceAndPrefix, "GetPipelineDefinition", POST, "/", input)
  override def reportTaskProgress(input: org.lyranthe.araethura.datapipeline.models.ReportTaskProgressInput): F[org.lyranthe.araethura.datapipeline.models.ReportTaskProgressOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.ReportTaskProgressOutput, org.lyranthe.araethura.datapipeline.models.ReportTaskProgressInput](client, awsData, ServiceType, ServiceAndPrefix, "ReportTaskProgress", POST, "/", input)
  override def validatePipelineDefinition(input: org.lyranthe.araethura.datapipeline.models.ValidatePipelineDefinitionInput): F[org.lyranthe.araethura.datapipeline.models.ValidatePipelineDefinitionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.ValidatePipelineDefinitionOutput, org.lyranthe.araethura.datapipeline.models.ValidatePipelineDefinitionInput](client, awsData, ServiceType, ServiceAndPrefix, "ValidatePipelineDefinition", POST, "/", input)
  override def deletePipeline(input: org.lyranthe.araethura.datapipeline.models.DeletePipelineInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.DeletePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "DeletePipeline", POST, "/", input)
  override def pollForTask(input: org.lyranthe.araethura.datapipeline.models.PollForTaskInput): F[org.lyranthe.araethura.datapipeline.models.PollForTaskOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.PollForTaskOutput, org.lyranthe.araethura.datapipeline.models.PollForTaskInput](client, awsData, ServiceType, ServiceAndPrefix, "PollForTask", POST, "/", input)
  override def activatePipeline(input: org.lyranthe.araethura.datapipeline.models.ActivatePipelineInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.ActivatePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "ActivatePipeline", POST, "/", input)
  override def setStatus(input: org.lyranthe.araethura.datapipeline.models.SetStatusInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.SetStatusInput](client, awsData, ServiceType, ServiceAndPrefix, "SetStatus", POST, "/", input)
  override def setTaskStatus(input: org.lyranthe.araethura.datapipeline.models.SetTaskStatusInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.SetTaskStatusInput](client, awsData, ServiceType, ServiceAndPrefix, "SetTaskStatus", POST, "/", input)
  override def describeObjects(input: org.lyranthe.araethura.datapipeline.models.DescribeObjectsInput): F[org.lyranthe.araethura.datapipeline.models.DescribeObjectsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.DescribeObjectsOutput, org.lyranthe.araethura.datapipeline.models.DescribeObjectsInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeObjects", POST, "/", input)
  override def removeTags(input: org.lyranthe.araethura.datapipeline.models.RemoveTagsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.RemoveTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTags", POST, "/", input)
  override def addTags(input: org.lyranthe.araethura.datapipeline.models.AddTagsInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.datapipeline.models.AddTagsInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTags", POST, "/", input)
  override def describePipelines(input: org.lyranthe.araethura.datapipeline.models.DescribePipelinesInput): F[org.lyranthe.araethura.datapipeline.models.DescribePipelinesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.DescribePipelinesOutput, org.lyranthe.araethura.datapipeline.models.DescribePipelinesInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribePipelines", POST, "/", input)
  override def listPipelines(input: org.lyranthe.araethura.datapipeline.models.ListPipelinesInput): F[org.lyranthe.araethura.datapipeline.models.ListPipelinesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.ListPipelinesOutput, org.lyranthe.araethura.datapipeline.models.ListPipelinesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListPipelines", POST, "/", input)
  override def createPipeline(input: org.lyranthe.araethura.datapipeline.models.CreatePipelineInput): F[org.lyranthe.araethura.datapipeline.models.CreatePipelineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.datapipeline.models.CreatePipelineOutput, org.lyranthe.araethura.datapipeline.models.CreatePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "CreatePipeline", POST, "/", input)
}