package org.lyranthe.araethura.directory.models
final case class DirectoryLimitExceededException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class SchemaExtensionInfo(endDateTime: scala.Option[java.time.Instant] = scala.None, schemaExtensionStatusReason: scala.Option[java.lang.String] = scala.None, startDateTime: scala.Option[java.time.Instant] = scala.None, schemaExtensionStatus: scala.Option[java.lang.String] = scala.None, description: scala.Option[java.lang.String] = scala.None, schemaExtensionId: scala.Option[java.lang.String] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
case object RegisterEventTopicResult
final case class DescribeDirectoriesResult(directoryDescriptions: scala.Option[scala.List[org.lyranthe.araethura.directory.models.DirectoryDescription]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class CreateSnapshotResult(snapshotId: scala.Option[java.lang.String] = scala.None)
case object RemoveIpRoutesResult
final case class CreateTrustRequest(trustDirection: java.lang.String, remoteDomainName: java.lang.String, trustPassword: java.lang.String, directoryId: java.lang.String, trustType: scala.Option[java.lang.String] = scala.None, conditionalForwarderIpAddrs: scala.Option[scala.List[java.lang.String]] = scala.None)
final case class DescribeConditionalForwardersRequest(directoryId: java.lang.String, remoteDomainNames: scala.Option[scala.List[java.lang.String]] = scala.None)
final case class EnableRadiusRequest(directoryId: java.lang.String, radiusSettings: org.lyranthe.araethura.directory.models.RadiusSettings)
final case class CreateDirectoryRequest(name: java.lang.String, password: java.lang.String, size: java.lang.String, shortName: scala.Option[java.lang.String] = scala.None, description: scala.Option[java.lang.String] = scala.None, vpcSettings: scala.Option[org.lyranthe.araethura.directory.models.DirectoryVpcSettings] = scala.None)
final case class ClientException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class CreateAliasRequest(directoryId: java.lang.String, alias: java.lang.String)
case object AddIpRoutesResult
final case class StartSchemaExtensionRequest(directoryId: java.lang.String, createSnapshotBeforeSchemaExtension: scala.Boolean, ldifContent: java.lang.String, description: java.lang.String)
final case class EventTopic(createdDateTime: scala.Option[java.time.Instant] = scala.None, topicArn: scala.Option[java.lang.String] = scala.None, topicName: scala.Option[java.lang.String] = scala.None, status: scala.Option[java.lang.String] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
final case class RegisterEventTopicRequest(directoryId: java.lang.String, topicName: java.lang.String)
case object EnableSsoResult
final case class AuthenticationFailedException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
case object DeregisterEventTopicResult
final case class InvalidNextTokenException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class DescribeDomainControllersRequest(directoryId: java.lang.String, domainControllerIds: scala.Option[scala.List[java.lang.String]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
final case class DescribeConditionalForwardersResult(conditionalForwarders: scala.Option[scala.List[org.lyranthe.araethura.directory.models.ConditionalForwarder]] = scala.None)
final case class DescribeTrustsResult(trusts: scala.Option[scala.List[org.lyranthe.araethura.directory.models.Trust]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class ConditionalForwarder(remoteDomainName: scala.Option[java.lang.String] = scala.None, dnsIpAddrs: scala.Option[scala.List[java.lang.String]] = scala.None, replicationScope: scala.Option[java.lang.String] = scala.None)
case object UpdateRadiusResult
final case class UnsupportedOperationException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class ConnectDirectoryResult(directoryId: scala.Option[java.lang.String] = scala.None)
case object CancelSchemaExtensionResult
final case class DeleteDirectoryResult(directoryId: scala.Option[java.lang.String] = scala.None)
final case class CreateConditionalForwarderRequest(directoryId: java.lang.String, remoteDomainName: java.lang.String, dnsIpAddrs: scala.List[java.lang.String])
final case class DeleteTrustRequest(trustId: java.lang.String, deleteAssociatedConditionalForwarder: scala.Option[scala.Boolean] = scala.None)
final case class DirectoryLimits(cloudOnlyDirectoriesLimit: scala.Option[scala.Int] = scala.None, cloudOnlyMicrosoftADCurrentCount: scala.Option[scala.Int] = scala.None, connectedDirectoriesCurrentCount: scala.Option[scala.Int] = scala.None, cloudOnlyDirectoriesCurrentCount: scala.Option[scala.Int] = scala.None, cloudOnlyMicrosoftADLimit: scala.Option[scala.Int] = scala.None, connectedDirectoriesLimit: scala.Option[scala.Int] = scala.None, cloudOnlyDirectoriesLimitReached: scala.Option[scala.Boolean] = scala.None, cloudOnlyMicrosoftADLimitReached: scala.Option[scala.Boolean] = scala.None, connectedDirectoriesLimitReached: scala.Option[scala.Boolean] = scala.None)
final case class DeleteSnapshotResult(snapshotId: scala.Option[java.lang.String] = scala.None)
final case class DescribeDomainControllersResult(domainControllers: scala.Option[scala.List[org.lyranthe.araethura.directory.models.DomainController]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class DisableRadiusRequest(directoryId: java.lang.String)
final case class Attribute(name: scala.Option[java.lang.String] = scala.None, value: scala.Option[java.lang.String] = scala.None)
final case class InsufficientPermissionsException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class RadiusSettings(authenticationProtocol: scala.Option[java.lang.String] = scala.None, useSameUsername: scala.Option[scala.Boolean] = scala.None, radiusTimeout: scala.Option[scala.Int] = scala.None, displayLabel: scala.Option[java.lang.String] = scala.None, sharedSecret: scala.Option[java.lang.String] = scala.None, radiusServers: scala.Option[scala.List[java.lang.String]] = scala.None, radiusPort: scala.Option[scala.Int] = scala.None, radiusRetries: scala.Option[scala.Int] = scala.None)
final case class SnapshotLimitExceededException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class DomainController(vpcId: scala.Option[java.lang.String] = scala.None, launchTime: scala.Option[java.time.Instant] = scala.None, statusLastUpdatedDateTime: scala.Option[java.time.Instant] = scala.None, subnetId: scala.Option[java.lang.String] = scala.None, domainControllerId: scala.Option[java.lang.String] = scala.None, availabilityZone: scala.Option[java.lang.String] = scala.None, status: scala.Option[java.lang.String] = scala.None, dnsIpAddr: scala.Option[java.lang.String] = scala.None, statusReason: scala.Option[java.lang.String] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
final case class CreateComputerRequest(password: java.lang.String, computerName: java.lang.String, directoryId: java.lang.String, computerAttributes: scala.Option[scala.List[org.lyranthe.araethura.directory.models.Attribute]] = scala.None, organizationalUnitDistinguishedName: scala.Option[java.lang.String] = scala.None)
final case class CreateTrustResult(trustId: scala.Option[java.lang.String] = scala.None)
final case class DomainControllerLimitExceededException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
case object UpdateConditionalForwarderResult
final case class DirectoryVpcSettingsDescription(vpcId: scala.Option[java.lang.String] = scala.None, subnetIds: scala.Option[scala.List[java.lang.String]] = scala.None, securityGroupId: scala.Option[java.lang.String] = scala.None, availabilityZones: scala.Option[scala.List[java.lang.String]] = scala.None)
final case class VerifyTrustRequest(trustId: java.lang.String)
final case class DeleteTrustResult(trustId: scala.Option[java.lang.String] = scala.None)
case object AddTagsToResourceResult
final case class DescribeEventTopicsResult(eventTopics: scala.Option[scala.List[org.lyranthe.araethura.directory.models.EventTopic]] = scala.None)
case object RemoveTagsFromResourceResult
final case class DescribeDirectoriesRequest(directoryIds: scala.Option[scala.List[java.lang.String]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
case object DisableSsoResult
final case class RemoveIpRoutesRequest(directoryId: java.lang.String, cidrIps: scala.List[java.lang.String])
final case class GetSnapshotLimitsRequest(directoryId: java.lang.String)
final case class DescribeSnapshotsResult(snapshots: scala.Option[scala.List[org.lyranthe.araethura.directory.models.Snapshot]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class GetSnapshotLimitsResult(snapshotLimits: scala.Option[org.lyranthe.araethura.directory.models.SnapshotLimits] = scala.None)
final case class DeleteSnapshotRequest(snapshotId: java.lang.String)
final case class CreateAliasResult(directoryId: scala.Option[java.lang.String] = scala.None, alias: scala.Option[java.lang.String] = scala.None)
final case class Snapshot(snapshotId: scala.Option[java.lang.String] = scala.None, status: scala.Option[java.lang.String] = scala.None, `type`: scala.Option[java.lang.String] = scala.None, name: scala.Option[java.lang.String] = scala.None, startTime: scala.Option[java.time.Instant] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
final case class AddTagsToResourceRequest(resourceId: java.lang.String, tags: scala.List[org.lyranthe.araethura.directory.models.Tag])
final case class GetDirectoryLimitsResult(directoryLimits: scala.Option[org.lyranthe.araethura.directory.models.DirectoryLimits] = scala.None)
final case class EntityDoesNotExistException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class ListIpRoutesRequest(directoryId: java.lang.String, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
final case class ListSchemaExtensionsResult(schemaExtensionsInfo: scala.Option[scala.List[org.lyranthe.araethura.directory.models.SchemaExtensionInfo]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class CreateDirectoryResult(directoryId: scala.Option[java.lang.String] = scala.None)
case object GetDirectoryLimitsRequest
final case class EntityAlreadyExistsException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class ListSchemaExtensionsRequest(directoryId: java.lang.String, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
final case class CreateSnapshotRequest(directoryId: java.lang.String, name: scala.Option[java.lang.String] = scala.None)
final case class ConnectDirectoryRequest(name: java.lang.String, password: java.lang.String, size: java.lang.String, connectSettings: org.lyranthe.araethura.directory.models.DirectoryConnectSettings, shortName: scala.Option[java.lang.String] = scala.None, description: scala.Option[java.lang.String] = scala.None)
final case class DeleteConditionalForwarderRequest(directoryId: java.lang.String, remoteDomainName: java.lang.String)
final case class Trust(trustDirection: scala.Option[java.lang.String] = scala.None, createdDateTime: scala.Option[java.time.Instant] = scala.None, trustStateReason: scala.Option[java.lang.String] = scala.None, remoteDomainName: scala.Option[java.lang.String] = scala.None, lastUpdatedDateTime: scala.Option[java.time.Instant] = scala.None, trustId: scala.Option[java.lang.String] = scala.None, trustState: scala.Option[java.lang.String] = scala.None, stateLastUpdatedDateTime: scala.Option[java.time.Instant] = scala.None, trustType: scala.Option[java.lang.String] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
final case class CreateMicrosoftADRequest(name: java.lang.String, password: java.lang.String, vpcSettings: org.lyranthe.araethura.directory.models.DirectoryVpcSettings, shortName: scala.Option[java.lang.String] = scala.None, description: scala.Option[java.lang.String] = scala.None)
final case class DescribeSnapshotsRequest(directoryId: scala.Option[java.lang.String] = scala.None, snapshotIds: scala.Option[scala.List[java.lang.String]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
final case class VerifyTrustResult(trustId: scala.Option[java.lang.String] = scala.None)
case object CreateConditionalForwarderResult
final case class SnapshotLimits(manualSnapshotsLimit: scala.Option[scala.Int] = scala.None, manualSnapshotsCurrentCount: scala.Option[scala.Int] = scala.None, manualSnapshotsLimitReached: scala.Option[scala.Boolean] = scala.None)
case object DisableRadiusResult
final case class CreateComputerResult(computer: scala.Option[org.lyranthe.araethura.directory.models.Computer] = scala.None)
final case class ListTagsForResourceRequest(resourceId: java.lang.String, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
final case class DescribeTrustsRequest(directoryId: scala.Option[java.lang.String] = scala.None, trustIds: scala.Option[scala.List[java.lang.String]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None, limit: scala.Option[scala.Int] = scala.None)
final case class DescribeEventTopicsRequest(directoryId: scala.Option[java.lang.String] = scala.None, topicNames: scala.Option[scala.List[java.lang.String]] = scala.None)
case object DeleteConditionalForwarderResult
final case class DirectoryConnectSettings(vpcId: java.lang.String, subnetIds: scala.List[java.lang.String], customerDnsIps: scala.List[java.lang.String], customerUserName: java.lang.String)
final case class UpdateNumberOfDomainControllersRequest(directoryId: java.lang.String, desiredNumber: scala.Int)
final case class DirectoryConnectSettingsDescription(vpcId: scala.Option[java.lang.String] = scala.None, subnetIds: scala.Option[scala.List[java.lang.String]] = scala.None, customerUserName: scala.Option[java.lang.String] = scala.None, connectIps: scala.Option[scala.List[java.lang.String]] = scala.None, securityGroupId: scala.Option[java.lang.String] = scala.None, availabilityZones: scala.Option[scala.List[java.lang.String]] = scala.None)
final case class ListTagsForResourceResult(tags: scala.Option[scala.List[org.lyranthe.araethura.directory.models.Tag]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class DirectoryUnavailableException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
case object UpdateNumberOfDomainControllersResult
final case class DeregisterEventTopicRequest(directoryId: java.lang.String, topicName: java.lang.String)
case object RestoreFromSnapshotResult
final case class Computer(computerId: scala.Option[java.lang.String] = scala.None, computerName: scala.Option[java.lang.String] = scala.None, computerAttributes: scala.Option[scala.List[org.lyranthe.araethura.directory.models.Attribute]] = scala.None)
final case class DirectoryDescription(alias: scala.Option[java.lang.String] = scala.None, stageReason: scala.Option[java.lang.String] = scala.None, name: scala.Option[java.lang.String] = scala.None, ssoEnabled: scala.Option[scala.Boolean] = scala.None, launchTime: scala.Option[java.time.Instant] = scala.None, stageLastUpdatedDateTime: scala.Option[java.time.Instant] = scala.None, radiusSettings: scala.Option[org.lyranthe.araethura.directory.models.RadiusSettings] = scala.None, stage: scala.Option[java.lang.String] = scala.None, vpcSettings: scala.Option[org.lyranthe.araethura.directory.models.DirectoryVpcSettingsDescription] = scala.None, radiusStatus: scala.Option[java.lang.String] = scala.None, `type`: scala.Option[java.lang.String] = scala.None, size: scala.Option[java.lang.String] = scala.None, connectSettings: scala.Option[org.lyranthe.araethura.directory.models.DirectoryConnectSettingsDescription] = scala.None, shortName: scala.Option[java.lang.String] = scala.None, description: scala.Option[java.lang.String] = scala.None, desiredNumberOfDomainControllers: scala.Option[scala.Int] = scala.None, dnsIpAddrs: scala.Option[scala.List[java.lang.String]] = scala.None, accessUrl: scala.Option[java.lang.String] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
final case class ServiceException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class UpdateConditionalForwarderRequest(directoryId: java.lang.String, remoteDomainName: java.lang.String, dnsIpAddrs: scala.List[java.lang.String])
final case class DirectoryVpcSettings(vpcId: java.lang.String, subnetIds: scala.List[java.lang.String])
final case class UpdateRadiusRequest(directoryId: java.lang.String, radiusSettings: org.lyranthe.araethura.directory.models.RadiusSettings)
final case class ListIpRoutesResult(ipRoutesInfo: scala.Option[scala.List[org.lyranthe.araethura.directory.models.IpRouteInfo]] = scala.None, nextToken: scala.Option[java.lang.String] = scala.None)
final case class AddIpRoutesRequest(directoryId: java.lang.String, ipRoutes: scala.List[org.lyranthe.araethura.directory.models.IpRoute], updateSecurityGroupForDirectoryControllers: scala.Option[scala.Boolean] = scala.None)
final case class CreateMicrosoftADResult(directoryId: scala.Option[java.lang.String] = scala.None)
final case class IpRouteInfo(ipRouteStatusMsg: scala.Option[java.lang.String] = scala.None, addedDateTime: scala.Option[java.time.Instant] = scala.None, description: scala.Option[java.lang.String] = scala.None, ipRouteStatusReason: scala.Option[java.lang.String] = scala.None, cidrIp: scala.Option[java.lang.String] = scala.None, directoryId: scala.Option[java.lang.String] = scala.None)
final case class StartSchemaExtensionResult(schemaExtensionId: scala.Option[java.lang.String] = scala.None)
final case class TagLimitExceededException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class IpRoute(cidrIp: scala.Option[java.lang.String] = scala.None, description: scala.Option[java.lang.String] = scala.None)
final case class Tag(key: java.lang.String, value: java.lang.String)
final case class CancelSchemaExtensionRequest(directoryId: java.lang.String, schemaExtensionId: java.lang.String)
final case class DisableSsoRequest(directoryId: java.lang.String, userName: scala.Option[java.lang.String] = scala.None, password: scala.Option[java.lang.String] = scala.None)
final case class IpRouteLimitExceededException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
final case class RestoreFromSnapshotRequest(snapshotId: java.lang.String)
final case class DeleteDirectoryRequest(directoryId: java.lang.String)
final case class InvalidParameterException(message: scala.Option[java.lang.String] = scala.None, requestId: scala.Option[java.lang.String] = scala.None)
case object EnableRadiusResult
final case class EnableSsoRequest(directoryId: java.lang.String, userName: scala.Option[java.lang.String] = scala.None, password: scala.Option[java.lang.String] = scala.None)
final case class RemoveTagsFromResourceRequest(resourceId: java.lang.String, tagKeys: scala.List[java.lang.String])