package avias.directory
trait Amazondirectory[F[_]] {
  def connectDirectory(input: avias.directory.models.ConnectDirectoryRequest): F[avias.directory.models.ConnectDirectoryResult]
  def removeIpRoutes(input: avias.directory.models.RemoveIpRoutesRequest): F[scala.Unit]
  def deregisterEventTopic(input: avias.directory.models.DeregisterEventTopicRequest): F[scala.Unit]
  def createAlias(input: avias.directory.models.CreateAliasRequest): F[avias.directory.models.CreateAliasResult]
  def restoreFromSnapshot(input: avias.directory.models.RestoreFromSnapshotRequest): F[scala.Unit]
  def disableSso(input: avias.directory.models.DisableSsoRequest): F[scala.Unit]
  def createTrust(input: avias.directory.models.CreateTrustRequest): F[avias.directory.models.CreateTrustResult]
  def disableRadius(input: avias.directory.models.DisableRadiusRequest): F[scala.Unit]
  def updateConditionalForwarder(input: avias.directory.models.UpdateConditionalForwarderRequest): F[scala.Unit]
  def deleteDirectory(input: avias.directory.models.DeleteDirectoryRequest): F[avias.directory.models.DeleteDirectoryResult]
  def describeTrusts(input: avias.directory.models.DescribeTrustsRequest): F[avias.directory.models.DescribeTrustsResult]
  def cancelSchemaExtension(input: avias.directory.models.CancelSchemaExtensionRequest): F[scala.Unit]
  def listIpRoutes(input: avias.directory.models.ListIpRoutesRequest): F[avias.directory.models.ListIpRoutesResult]
  def getSnapshotLimits(input: avias.directory.models.GetSnapshotLimitsRequest): F[avias.directory.models.GetSnapshotLimitsResult]
  def createDirectory(input: avias.directory.models.CreateDirectoryRequest): F[avias.directory.models.CreateDirectoryResult]
  def describeEventTopics(input: avias.directory.models.DescribeEventTopicsRequest): F[avias.directory.models.DescribeEventTopicsResult]
  def describeSnapshots(input: avias.directory.models.DescribeSnapshotsRequest): F[avias.directory.models.DescribeSnapshotsResult]
  def deleteSnapshot(input: avias.directory.models.DeleteSnapshotRequest): F[avias.directory.models.DeleteSnapshotResult]
  def enableSso(input: avias.directory.models.EnableSsoRequest): F[scala.Unit]
  def createConditionalForwarder(input: avias.directory.models.CreateConditionalForwarderRequest): F[scala.Unit]
  def addTagsToResource(input: avias.directory.models.AddTagsToResourceRequest): F[scala.Unit]
  def getDirectoryLimits: F[avias.directory.models.GetDirectoryLimitsResult]
  def listTagsForResource(input: avias.directory.models.ListTagsForResourceRequest): F[avias.directory.models.ListTagsForResourceResult]
  def describeDirectories(input: avias.directory.models.DescribeDirectoriesRequest): F[avias.directory.models.DescribeDirectoriesResult]
  def removeTagsFromResource(input: avias.directory.models.RemoveTagsFromResourceRequest): F[scala.Unit]
  def createComputer(input: avias.directory.models.CreateComputerRequest): F[avias.directory.models.CreateComputerResult]
  def registerEventTopic(input: avias.directory.models.RegisterEventTopicRequest): F[scala.Unit]
  def deleteTrust(input: avias.directory.models.DeleteTrustRequest): F[avias.directory.models.DeleteTrustResult]
  def createMicrosoftAD(input: avias.directory.models.CreateMicrosoftADRequest): F[avias.directory.models.CreateMicrosoftADResult]
  def verifyTrust(input: avias.directory.models.VerifyTrustRequest): F[avias.directory.models.VerifyTrustResult]
  def deleteConditionalForwarder(input: avias.directory.models.DeleteConditionalForwarderRequest): F[scala.Unit]
  def startSchemaExtension(input: avias.directory.models.StartSchemaExtensionRequest): F[avias.directory.models.StartSchemaExtensionResult]
  def createSnapshot(input: avias.directory.models.CreateSnapshotRequest): F[avias.directory.models.CreateSnapshotResult]
  def describeConditionalForwarders(input: avias.directory.models.DescribeConditionalForwardersRequest): F[avias.directory.models.DescribeConditionalForwardersResult]
  def describeDomainControllers(input: avias.directory.models.DescribeDomainControllersRequest): F[avias.directory.models.DescribeDomainControllersResult]
  def listSchemaExtensions(input: avias.directory.models.ListSchemaExtensionsRequest): F[avias.directory.models.ListSchemaExtensionsResult]
  def updateRadius(input: avias.directory.models.UpdateRadiusRequest): F[scala.Unit]
  def enableRadius(input: avias.directory.models.EnableRadiusRequest): F[scala.Unit]
  def updateNumberOfDomainControllers(input: avias.directory.models.UpdateNumberOfDomainControllersRequest): F[scala.Unit]
  def addIpRoutes(input: avias.directory.models.AddIpRoutesRequest): F[scala.Unit]
}