package org.lyranthe.araethura.appstream.models
import org.lyranthe.araethura.appstream.models
final case class ImageBuilderStateChangeReason(code: scala.Option[java.lang.String] = None, message: scala.Option[java.lang.String] = None)
final case class DisassociateFleetRequest(fleetName: java.lang.String, stackName: java.lang.String)
final case class DirectoryConfig(directoryName: java.lang.String, organizationalUnitDistinguishedNames: scala.Option[scala.List[java.lang.String]] = None, serviceAccountCredentials: scala.Option[models.ServiceAccountCredentials] = None, createdTime: scala.Option[java.time.Instant] = None)
final case class ListAssociatedFleetsRequest(stackName: java.lang.String, nextToken: scala.Option[java.lang.String] = None)
final case class ResourceInUseException(message: scala.Option[java.lang.String] = None)
final case class ConcurrentModificationException(message: scala.Option[java.lang.String] = None)
case object StopFleetResult
final case class DescribeSessionsRequest(stackName: java.lang.String, fleetName: java.lang.String, nextToken: scala.Option[java.lang.String] = None, userId: scala.Option[java.lang.String] = None, limit: scala.Option[scala.Int] = None, authenticationType: scala.Option[java.lang.String] = None)
final case class DeleteFleetRequest(name: java.lang.String)
final case class StorageConnector(connectorType: java.lang.String, resourceIdentifier: scala.Option[java.lang.String] = None)
final case class DomainJoinInfo(directoryName: scala.Option[java.lang.String] = None, organizationalUnitDistinguishedName: scala.Option[java.lang.String] = None)
final case class Image(name: java.lang.String, platform: scala.Option[java.lang.String] = None, createdTime: scala.Option[java.time.Instant] = None, publicBaseImageReleasedDate: scala.Option[java.time.Instant] = None, arn: scala.Option[java.lang.String] = None, baseImageArn: scala.Option[java.lang.String] = None, displayName: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None, state: scala.Option[java.lang.String] = None, applications: scala.Option[scala.List[models.Application]] = None, visibility: scala.Option[java.lang.String] = None, imageBuilderSupported: scala.Option[scala.Boolean] = None, stateChangeReason: scala.Option[models.ImageStateChangeReason] = None)
final case class StopFleetRequest(name: java.lang.String)
final case class DescribeImagesResult(images: scala.Option[scala.List[models.Image]] = None)
final case class UpdateDirectoryConfigResult(directoryConfig: scala.Option[models.DirectoryConfig] = None)
final case class DescribeStacksRequest(names: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class CreateStreamingURLRequest(stackName: java.lang.String, fleetName: java.lang.String, userId: java.lang.String, applicationId: scala.Option[java.lang.String] = None, sessionContext: scala.Option[java.lang.String] = None, validity: scala.Option[scala.Long] = None)
final case class ListAssociatedStacksResult(names: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DeleteImageRequest(name: java.lang.String)
final case class CreateDirectoryConfigRequest(directoryName: java.lang.String, organizationalUnitDistinguishedNames: scala.List[java.lang.String], serviceAccountCredentials: models.ServiceAccountCredentials)
final case class StartImageBuilderRequest(name: java.lang.String)
final case class LimitExceededException(message: scala.Option[java.lang.String] = None)
final case class UpdateStackResult(stack: scala.Option[models.Stack] = None)
case object DeleteFleetResult
final case class ListAssociatedStacksRequest(fleetName: java.lang.String, nextToken: scala.Option[java.lang.String] = None)
final case class CreateImageBuilderResult(imageBuilder: scala.Option[models.ImageBuilder] = None)
final case class FleetError(errorCode: scala.Option[java.lang.String] = None, errorMessage: scala.Option[java.lang.String] = None)
final case class CreateStackResult(stack: scala.Option[models.Stack] = None)
final case class CreateStreamingURLResult(streamingURL: scala.Option[java.lang.String] = None, expires: scala.Option[java.time.Instant] = None)
final case class ComputeCapacity(desiredInstances: scala.Int)
final case class InvalidRoleException(message: scala.Option[java.lang.String] = None)
final case class DeleteImageBuilderResult(imageBuilder: scala.Option[models.ImageBuilder] = None)
final case class ImageBuilder(name: java.lang.String, stateChangeReason: scala.Option[models.ImageBuilderStateChangeReason] = None, platform: scala.Option[java.lang.String] = None, createdTime: scala.Option[java.time.Instant] = None, domainJoinInfo: scala.Option[models.DomainJoinInfo] = None, arn: scala.Option[java.lang.String] = None, imageArn: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None, displayName: scala.Option[java.lang.String] = None, instanceType: scala.Option[java.lang.String] = None, imageBuilderErrors: scala.Option[scala.List[models.ResourceError]] = None, state: scala.Option[java.lang.String] = None, enableDefaultInternetAccess: scala.Option[scala.Boolean] = None, vpcConfig: scala.Option[models.VpcConfig] = None)
final case class DeleteDirectoryConfigRequest(directoryName: java.lang.String)
final case class CreateImageBuilderRequest(imageName: java.lang.String, instanceType: java.lang.String, name: java.lang.String, displayName: scala.Option[java.lang.String] = None, domainJoinInfo: scala.Option[models.DomainJoinInfo] = None, enableDefaultInternetAccess: scala.Option[scala.Boolean] = None, vpcConfig: scala.Option[models.VpcConfig] = None, description: scala.Option[java.lang.String] = None)
final case class UpdateFleetRequest(name: java.lang.String, displayName: scala.Option[java.lang.String] = None, domainJoinInfo: scala.Option[models.DomainJoinInfo] = None, imageName: scala.Option[java.lang.String] = None, instanceType: scala.Option[java.lang.String] = None, computeCapacity: scala.Option[models.ComputeCapacity] = None, enableDefaultInternetAccess: scala.Option[scala.Boolean] = None, attributesToDelete: scala.Option[scala.List[java.lang.String]] = None, maxUserDurationInSeconds: scala.Option[scala.Int] = None, disconnectTimeoutInSeconds: scala.Option[scala.Int] = None, deleteVpcConfig: scala.Option[scala.Boolean] = None, vpcConfig: scala.Option[models.VpcConfig] = None, description: scala.Option[java.lang.String] = None)
final case class ExpireSessionRequest(sessionId: java.lang.String)
final case class CreateImageBuilderStreamingURLResult(streamingURL: scala.Option[java.lang.String] = None, expires: scala.Option[java.time.Instant] = None)
final case class ComputeCapacityStatus(desired: scala.Int, running: scala.Option[scala.Int] = None, inUse: scala.Option[scala.Int] = None, available: scala.Option[scala.Int] = None)
final case class ResourceAlreadyExistsException(message: scala.Option[java.lang.String] = None)
final case class DeleteImageBuilderRequest(name: java.lang.String)
final case class ResourceNotAvailableException(message: scala.Option[java.lang.String] = None)
final case class InvalidParameterCombinationException(message: scala.Option[java.lang.String] = None)
final case class Session(id: java.lang.String, stackName: java.lang.String, fleetName: java.lang.String, userId: java.lang.String, state: java.lang.String, authenticationType: scala.Option[java.lang.String] = None)
case object ExpireSessionResult
final case class DescribeSessionsResult(sessions: scala.Option[scala.List[models.Session]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class ResourceNotFoundException(message: scala.Option[java.lang.String] = None)
final case class AssociateFleetRequest(fleetName: java.lang.String, stackName: java.lang.String)
final case class CreateStackRequest(name: java.lang.String, description: scala.Option[java.lang.String] = None, displayName: scala.Option[java.lang.String] = None, storageConnectors: scala.Option[scala.List[models.StorageConnector]] = None)
final case class ServiceAccountCredentials(accountName: java.lang.String, accountPassword: java.lang.String)
case object StartFleetResult
final case class CreateDirectoryConfigResult(directoryConfig: scala.Option[models.DirectoryConfig] = None)
final case class Fleet(arn: java.lang.String, name: java.lang.String, imageName: java.lang.String, instanceType: java.lang.String, computeCapacityStatus: models.ComputeCapacityStatus, state: java.lang.String, createdTime: scala.Option[java.time.Instant] = None, fleetErrors: scala.Option[scala.List[models.FleetError]] = None, domainJoinInfo: scala.Option[models.DomainJoinInfo] = None, displayName: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None, fleetType: scala.Option[java.lang.String] = None, enableDefaultInternetAccess: scala.Option[scala.Boolean] = None, maxUserDurationInSeconds: scala.Option[scala.Int] = None, disconnectTimeoutInSeconds: scala.Option[scala.Int] = None, vpcConfig: scala.Option[models.VpcConfig] = None)
case object DisassociateFleetResult
final case class OperationNotPermittedException(message: scala.Option[java.lang.String] = None)
final case class IncompatibleImageException(message: scala.Option[java.lang.String] = None)
final case class Stack(name: java.lang.String, createdTime: scala.Option[java.time.Instant] = None, storageConnectors: scala.Option[scala.List[models.StorageConnector]] = None, arn: scala.Option[java.lang.String] = None, description: scala.Option[java.lang.String] = None, displayName: scala.Option[java.lang.String] = None, stackErrors: scala.Option[scala.List[models.StackError]] = None)
final case class UpdateDirectoryConfigRequest(directoryName: java.lang.String, organizationalUnitDistinguishedNames: scala.Option[scala.List[java.lang.String]] = None, serviceAccountCredentials: scala.Option[models.ServiceAccountCredentials] = None)
final case class DescribeImagesRequest(names: scala.Option[scala.List[java.lang.String]] = None)
final case class Application(name: scala.Option[java.lang.String] = None, displayName: scala.Option[java.lang.String] = None, iconURL: scala.Option[java.lang.String] = None, launchParameters: scala.Option[java.lang.String] = None, launchPath: scala.Option[java.lang.String] = None, enabled: scala.Option[scala.Boolean] = None, metadata: scala.Option[scala.collection.immutable.Map[java.lang.String, java.lang.String]] = None)
final case class DescribeImageBuildersResult(imageBuilders: scala.Option[scala.List[models.ImageBuilder]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class StopImageBuilderRequest(name: java.lang.String)
final case class UpdateStackRequest(name: java.lang.String, displayName: scala.Option[java.lang.String] = None, storageConnectors: scala.Option[scala.List[models.StorageConnector]] = None, deleteStorageConnectors: scala.Option[scala.Boolean] = None, description: scala.Option[java.lang.String] = None)
final case class UpdateFleetResult(fleet: scala.Option[models.Fleet] = None)
final case class CreateFleetResult(fleet: scala.Option[models.Fleet] = None)
final case class StopImageBuilderResult(imageBuilder: scala.Option[models.ImageBuilder] = None)
final case class CreateImageBuilderStreamingURLRequest(name: java.lang.String, validity: scala.Option[scala.Long] = None)
final case class ResourceError(errorCode: scala.Option[java.lang.String] = None, errorMessage: scala.Option[java.lang.String] = None, errorTimestamp: scala.Option[java.time.Instant] = None)
final case class ImageStateChangeReason(code: scala.Option[java.lang.String] = None, message: scala.Option[java.lang.String] = None)
final case class DescribeImageBuildersRequest(names: scala.Option[scala.List[java.lang.String]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DeleteImageResult(image: scala.Option[models.Image] = None)
case object AssociateFleetResult
final case class VpcConfig(subnetIds: scala.Option[scala.List[java.lang.String]] = None, securityGroupIds: scala.Option[scala.List[java.lang.String]] = None)
final case class CreateFleetRequest(imageName: java.lang.String, instanceType: java.lang.String, computeCapacity: models.ComputeCapacity, name: java.lang.String, displayName: scala.Option[java.lang.String] = None, domainJoinInfo: scala.Option[models.DomainJoinInfo] = None, fleetType: scala.Option[java.lang.String] = None, enableDefaultInternetAccess: scala.Option[scala.Boolean] = None, maxUserDurationInSeconds: scala.Option[scala.Int] = None, disconnectTimeoutInSeconds: scala.Option[scala.Int] = None, vpcConfig: scala.Option[models.VpcConfig] = None, description: scala.Option[java.lang.String] = None)
final case class DescribeDirectoryConfigsRequest(directoryNames: scala.Option[scala.List[java.lang.String]] = None, maxResults: scala.Option[scala.Int] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DescribeStacksResult(stacks: scala.Option[scala.List[models.Stack]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class DescribeFleetsResult(fleets: scala.Option[scala.List[models.Fleet]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class StartImageBuilderResult(imageBuilder: scala.Option[models.ImageBuilder] = None)
final case class DeleteStackRequest(name: java.lang.String)
final case class DescribeFleetsRequest(names: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class ListAssociatedFleetsResult(names: scala.Option[scala.List[java.lang.String]] = None, nextToken: scala.Option[java.lang.String] = None)
final case class StackError(errorCode: scala.Option[java.lang.String] = None, errorMessage: scala.Option[java.lang.String] = None)
final case class DescribeDirectoryConfigsResult(directoryConfigs: scala.Option[scala.List[models.DirectoryConfig]] = None, nextToken: scala.Option[java.lang.String] = None)
case object DeleteStackResult
case object DeleteDirectoryConfigResult
final case class StartFleetRequest(name: java.lang.String)