package org.lyranthe.araethura.appstream
trait Amazonappstream[F[_]] {
  def createStreamingURL(input: org.lyranthe.araethura.appstream.models.CreateStreamingURLRequest): F[org.lyranthe.araethura.appstream.models.CreateStreamingURLResult]
  def describeSessions(input: org.lyranthe.araethura.appstream.models.DescribeSessionsRequest): F[org.lyranthe.araethura.appstream.models.DescribeSessionsResult]
  def describeStacks(input: org.lyranthe.araethura.appstream.models.DescribeStacksRequest): F[org.lyranthe.araethura.appstream.models.DescribeStacksResult]
  def associateFleet(input: org.lyranthe.araethura.appstream.models.AssociateFleetRequest): F[scala.Unit]
  def deleteStack(input: org.lyranthe.araethura.appstream.models.DeleteStackRequest): F[scala.Unit]
  def disassociateFleet(input: org.lyranthe.araethura.appstream.models.DisassociateFleetRequest): F[scala.Unit]
  def stopImageBuilder(input: org.lyranthe.araethura.appstream.models.StopImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.StopImageBuilderResult]
  def describeImages(input: org.lyranthe.araethura.appstream.models.DescribeImagesRequest): F[org.lyranthe.araethura.appstream.models.DescribeImagesResult]
  def describeDirectoryConfigs(input: org.lyranthe.araethura.appstream.models.DescribeDirectoryConfigsRequest): F[org.lyranthe.araethura.appstream.models.DescribeDirectoryConfigsResult]
  def updateStack(input: org.lyranthe.araethura.appstream.models.UpdateStackRequest): F[org.lyranthe.araethura.appstream.models.UpdateStackResult]
  def listAssociatedFleets(input: org.lyranthe.araethura.appstream.models.ListAssociatedFleetsRequest): F[org.lyranthe.araethura.appstream.models.ListAssociatedFleetsResult]
  def updateDirectoryConfig(input: org.lyranthe.araethura.appstream.models.UpdateDirectoryConfigRequest): F[org.lyranthe.araethura.appstream.models.UpdateDirectoryConfigResult]
  def createStack(input: org.lyranthe.araethura.appstream.models.CreateStackRequest): F[org.lyranthe.araethura.appstream.models.CreateStackResult]
  def listAssociatedStacks(input: org.lyranthe.araethura.appstream.models.ListAssociatedStacksRequest): F[org.lyranthe.araethura.appstream.models.ListAssociatedStacksResult]
  def deleteImage(input: org.lyranthe.araethura.appstream.models.DeleteImageRequest): F[org.lyranthe.araethura.appstream.models.DeleteImageResult]
  def updateFleet(input: org.lyranthe.araethura.appstream.models.UpdateFleetRequest): F[org.lyranthe.araethura.appstream.models.UpdateFleetResult]
  def createDirectoryConfig(input: org.lyranthe.araethura.appstream.models.CreateDirectoryConfigRequest): F[org.lyranthe.araethura.appstream.models.CreateDirectoryConfigResult]
  def deleteImageBuilder(input: org.lyranthe.araethura.appstream.models.DeleteImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.DeleteImageBuilderResult]
  def deleteFleet(input: org.lyranthe.araethura.appstream.models.DeleteFleetRequest): F[scala.Unit]
  def describeImageBuilders(input: org.lyranthe.araethura.appstream.models.DescribeImageBuildersRequest): F[org.lyranthe.araethura.appstream.models.DescribeImageBuildersResult]
  def createFleet(input: org.lyranthe.araethura.appstream.models.CreateFleetRequest): F[org.lyranthe.araethura.appstream.models.CreateFleetResult]
  def createImageBuilder(input: org.lyranthe.araethura.appstream.models.CreateImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.CreateImageBuilderResult]
  def startFleet(input: org.lyranthe.araethura.appstream.models.StartFleetRequest): F[scala.Unit]
  def deleteDirectoryConfig(input: org.lyranthe.araethura.appstream.models.DeleteDirectoryConfigRequest): F[scala.Unit]
  def expireSession(input: org.lyranthe.araethura.appstream.models.ExpireSessionRequest): F[scala.Unit]
  def describeFleets(input: org.lyranthe.araethura.appstream.models.DescribeFleetsRequest): F[org.lyranthe.araethura.appstream.models.DescribeFleetsResult]
  def createImageBuilderStreamingURL(input: org.lyranthe.araethura.appstream.models.CreateImageBuilderStreamingURLRequest): F[org.lyranthe.araethura.appstream.models.CreateImageBuilderStreamingURLResult]
  def stopFleet(input: org.lyranthe.araethura.appstream.models.StopFleetRequest): F[scala.Unit]
  def startImageBuilder(input: org.lyranthe.araethura.appstream.models.StartImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.StartImageBuilderResult]
}