package avias.appstream
trait Amazonappstream[F[_]] {
  def createStreamingURL(input: avias.appstream.models.CreateStreamingURLRequest): F[avias.appstream.models.CreateStreamingURLResult]
  def describeSessions(input: avias.appstream.models.DescribeSessionsRequest): F[avias.appstream.models.DescribeSessionsResult]
  def describeStacks(input: avias.appstream.models.DescribeStacksRequest): F[avias.appstream.models.DescribeStacksResult]
  def associateFleet(input: avias.appstream.models.AssociateFleetRequest): F[scala.Unit]
  def deleteStack(input: avias.appstream.models.DeleteStackRequest): F[scala.Unit]
  def disassociateFleet(input: avias.appstream.models.DisassociateFleetRequest): F[scala.Unit]
  def stopImageBuilder(input: avias.appstream.models.StopImageBuilderRequest): F[avias.appstream.models.StopImageBuilderResult]
  def describeImages(input: avias.appstream.models.DescribeImagesRequest): F[avias.appstream.models.DescribeImagesResult]
  def describeDirectoryConfigs(input: avias.appstream.models.DescribeDirectoryConfigsRequest): F[avias.appstream.models.DescribeDirectoryConfigsResult]
  def updateStack(input: avias.appstream.models.UpdateStackRequest): F[avias.appstream.models.UpdateStackResult]
  def listAssociatedFleets(input: avias.appstream.models.ListAssociatedFleetsRequest): F[avias.appstream.models.ListAssociatedFleetsResult]
  def updateDirectoryConfig(input: avias.appstream.models.UpdateDirectoryConfigRequest): F[avias.appstream.models.UpdateDirectoryConfigResult]
  def createStack(input: avias.appstream.models.CreateStackRequest): F[avias.appstream.models.CreateStackResult]
  def listAssociatedStacks(input: avias.appstream.models.ListAssociatedStacksRequest): F[avias.appstream.models.ListAssociatedStacksResult]
  def deleteImage(input: avias.appstream.models.DeleteImageRequest): F[avias.appstream.models.DeleteImageResult]
  def updateFleet(input: avias.appstream.models.UpdateFleetRequest): F[avias.appstream.models.UpdateFleetResult]
  def createDirectoryConfig(input: avias.appstream.models.CreateDirectoryConfigRequest): F[avias.appstream.models.CreateDirectoryConfigResult]
  def deleteImageBuilder(input: avias.appstream.models.DeleteImageBuilderRequest): F[avias.appstream.models.DeleteImageBuilderResult]
  def deleteFleet(input: avias.appstream.models.DeleteFleetRequest): F[scala.Unit]
  def describeImageBuilders(input: avias.appstream.models.DescribeImageBuildersRequest): F[avias.appstream.models.DescribeImageBuildersResult]
  def createFleet(input: avias.appstream.models.CreateFleetRequest): F[avias.appstream.models.CreateFleetResult]
  def createImageBuilder(input: avias.appstream.models.CreateImageBuilderRequest): F[avias.appstream.models.CreateImageBuilderResult]
  def startFleet(input: avias.appstream.models.StartFleetRequest): F[scala.Unit]
  def deleteDirectoryConfig(input: avias.appstream.models.DeleteDirectoryConfigRequest): F[scala.Unit]
  def expireSession(input: avias.appstream.models.ExpireSessionRequest): F[scala.Unit]
  def describeFleets(input: avias.appstream.models.DescribeFleetsRequest): F[avias.appstream.models.DescribeFleetsResult]
  def createImageBuilderStreamingURL(input: avias.appstream.models.CreateImageBuilderStreamingURLRequest): F[avias.appstream.models.CreateImageBuilderStreamingURLResult]
  def stopFleet(input: avias.appstream.models.StopFleetRequest): F[scala.Unit]
  def startImageBuilder(input: avias.appstream.models.StartImageBuilderRequest): F[avias.appstream.models.StartImageBuilderResult]
}