package org.lyranthe.araethura.cloudhsm.http4s
import org.http4s.Method._
import org.lyranthe.araethura.cloudhsm.circe._
import org.lyranthe.araethura.cloudhsm.models
class AmazoncloudhsmClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.cloudhsm.Amazoncloudhsm[F] {
  private[this] final val ServiceType: String = "cloudhsm"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CloudHsmFrontendService")
  override def deleteLunaClient(input: models.DeleteLunaClientRequest): F[models.DeleteLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteLunaClientResponse, models.DeleteLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteLunaClient", POST, "/", input)
  override def describeHapg(input: models.DescribeHapgRequest): F[models.DescribeHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeHapgResponse, models.DescribeHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeHapg", POST, "/", input)
  override def describeLunaClient(input: models.DescribeLunaClientRequest): F[models.DescribeLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeLunaClientResponse, models.DescribeLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeLunaClient", POST, "/", input)
  override def modifyLunaClient(input: models.ModifyLunaClientRequest): F[models.ModifyLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ModifyLunaClientResponse, models.ModifyLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyLunaClient", POST, "/", input)
  override def createHapg(input: models.CreateHapgRequest): F[models.CreateHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateHapgResponse, models.CreateHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateHapg", POST, "/", input)
  override def addTagsToResource(input: models.AddTagsToResourceRequest): F[models.AddTagsToResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.AddTagsToResourceResponse, models.AddTagsToResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddTagsToResource", POST, "/", input)
  override def listHapgs(input: models.ListHapgsRequest): F[models.ListHapgsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListHapgsResponse, models.ListHapgsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListHapgs", POST, "/", input)
  override def listLunaClients(input: models.ListLunaClientsRequest): F[models.ListLunaClientsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListLunaClientsResponse, models.ListLunaClientsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListLunaClients", POST, "/", input)
  override def deleteHapg(input: models.DeleteHapgRequest): F[models.DeleteHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteHapgResponse, models.DeleteHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteHapg", POST, "/", input)
  override def getConfig(input: models.GetConfigRequest): F[models.GetConfigResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetConfigResponse, models.GetConfigRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetConfig", POST, "/", input)
  override def listTagsForResource(input: models.ListTagsForResourceRequest): F[models.ListTagsForResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTagsForResourceResponse, models.ListTagsForResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForResource", POST, "/", input)
  override def listAvailableZones: F[models.ListAvailableZonesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListAvailableZonesResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "ListAvailableZones", POST, "/", ())
  override def modifyHapg(input: models.ModifyHapgRequest): F[models.ModifyHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ModifyHapgResponse, models.ModifyHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyHapg", POST, "/", input)
  override def removeTagsFromResource(input: models.RemoveTagsFromResourceRequest): F[models.RemoveTagsFromResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RemoveTagsFromResourceResponse, models.RemoveTagsFromResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTagsFromResource", POST, "/", input)
  override def listHsms(input: models.ListHsmsRequest): F[models.ListHsmsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListHsmsResponse, models.ListHsmsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListHsms", POST, "/", input)
  override def deleteHsm(input: models.DeleteHsmRequest): F[models.DeleteHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteHsmResponse, models.DeleteHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteHsm", POST, "/", input)
  override def createHsm(input: models.CreateHsmRequest): F[models.CreateHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateHsmResponse, models.CreateHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateHsm", POST, "/", input)
  override def createLunaClient(input: models.CreateLunaClientRequest): F[models.CreateLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateLunaClientResponse, models.CreateLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateLunaClient", POST, "/", input)
  override def describeHsm(input: models.DescribeHsmRequest): F[models.DescribeHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeHsmResponse, models.DescribeHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeHsm", POST, "/", input)
  override def modifyHsm(input: models.ModifyHsmRequest): F[models.ModifyHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ModifyHsmResponse, models.ModifyHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyHsm", POST, "/", input)
}