package org.lyranthe.araethura.cloudhsm.http4s
import org.http4s.Method._
import org.lyranthe.araethura.cloudhsm.circe._
import org.lyranthe.araethura.cloudhsm.models
class AmazoncloudhsmClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.cloudhsm.Amazoncloudhsm[F] {
  private[this] final val ServiceType: String = "cloudhsm"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CloudHsmFrontendService")
  override def deleteLunaClient(input: org.lyranthe.araethura.cloudhsm.models.DeleteLunaClientRequest): F[org.lyranthe.araethura.cloudhsm.models.DeleteLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.DeleteLunaClientResponse, org.lyranthe.araethura.cloudhsm.models.DeleteLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteLunaClient", POST, "/", input)
  override def describeHapg(input: org.lyranthe.araethura.cloudhsm.models.DescribeHapgRequest): F[org.lyranthe.araethura.cloudhsm.models.DescribeHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.DescribeHapgResponse, org.lyranthe.araethura.cloudhsm.models.DescribeHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeHapg", POST, "/", input)
  override def describeLunaClient(input: org.lyranthe.araethura.cloudhsm.models.DescribeLunaClientRequest): F[org.lyranthe.araethura.cloudhsm.models.DescribeLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.DescribeLunaClientResponse, org.lyranthe.araethura.cloudhsm.models.DescribeLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeLunaClient", POST, "/", input)
  override def modifyLunaClient(input: org.lyranthe.araethura.cloudhsm.models.ModifyLunaClientRequest): F[org.lyranthe.araethura.cloudhsm.models.ModifyLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ModifyLunaClientResponse, org.lyranthe.araethura.cloudhsm.models.ModifyLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyLunaClient", POST, "/", input)
  override def createHapg(input: org.lyranthe.araethura.cloudhsm.models.CreateHapgRequest): F[org.lyranthe.araethura.cloudhsm.models.CreateHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.CreateHapgResponse, org.lyranthe.araethura.cloudhsm.models.CreateHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateHapg", POST, "/", input)
  override def addTagsToResource(input: org.lyranthe.araethura.cloudhsm.models.AddTagsToResourceRequest): F[org.lyranthe.araethura.cloudhsm.models.AddTagsToResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.AddTagsToResourceResponse, org.lyranthe.araethura.cloudhsm.models.AddTagsToResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddTagsToResource", POST, "/", input)
  override def listHapgs(input: org.lyranthe.araethura.cloudhsm.models.ListHapgsRequest): F[org.lyranthe.araethura.cloudhsm.models.ListHapgsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ListHapgsResponse, org.lyranthe.araethura.cloudhsm.models.ListHapgsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListHapgs", POST, "/", input)
  override def listLunaClients(input: org.lyranthe.araethura.cloudhsm.models.ListLunaClientsRequest): F[org.lyranthe.araethura.cloudhsm.models.ListLunaClientsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ListLunaClientsResponse, org.lyranthe.araethura.cloudhsm.models.ListLunaClientsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListLunaClients", POST, "/", input)
  override def deleteHapg(input: org.lyranthe.araethura.cloudhsm.models.DeleteHapgRequest): F[org.lyranthe.araethura.cloudhsm.models.DeleteHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.DeleteHapgResponse, org.lyranthe.araethura.cloudhsm.models.DeleteHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteHapg", POST, "/", input)
  override def getConfig(input: org.lyranthe.araethura.cloudhsm.models.GetConfigRequest): F[org.lyranthe.araethura.cloudhsm.models.GetConfigResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.GetConfigResponse, org.lyranthe.araethura.cloudhsm.models.GetConfigRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetConfig", POST, "/", input)
  override def listTagsForResource(input: org.lyranthe.araethura.cloudhsm.models.ListTagsForResourceRequest): F[org.lyranthe.araethura.cloudhsm.models.ListTagsForResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ListTagsForResourceResponse, org.lyranthe.araethura.cloudhsm.models.ListTagsForResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForResource", POST, "/", input)
  override def listAvailableZones: F[org.lyranthe.araethura.cloudhsm.models.ListAvailableZonesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ListAvailableZonesResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "ListAvailableZones", POST, "/", ())
  override def modifyHapg(input: org.lyranthe.araethura.cloudhsm.models.ModifyHapgRequest): F[org.lyranthe.araethura.cloudhsm.models.ModifyHapgResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ModifyHapgResponse, org.lyranthe.araethura.cloudhsm.models.ModifyHapgRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyHapg", POST, "/", input)
  override def removeTagsFromResource(input: org.lyranthe.araethura.cloudhsm.models.RemoveTagsFromResourceRequest): F[org.lyranthe.araethura.cloudhsm.models.RemoveTagsFromResourceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.RemoveTagsFromResourceResponse, org.lyranthe.araethura.cloudhsm.models.RemoveTagsFromResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTagsFromResource", POST, "/", input)
  override def listHsms(input: org.lyranthe.araethura.cloudhsm.models.ListHsmsRequest): F[org.lyranthe.araethura.cloudhsm.models.ListHsmsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ListHsmsResponse, org.lyranthe.araethura.cloudhsm.models.ListHsmsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListHsms", POST, "/", input)
  override def deleteHsm(input: org.lyranthe.araethura.cloudhsm.models.DeleteHsmRequest): F[org.lyranthe.araethura.cloudhsm.models.DeleteHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.DeleteHsmResponse, org.lyranthe.araethura.cloudhsm.models.DeleteHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteHsm", POST, "/", input)
  override def createHsm(input: org.lyranthe.araethura.cloudhsm.models.CreateHsmRequest): F[org.lyranthe.araethura.cloudhsm.models.CreateHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.CreateHsmResponse, org.lyranthe.araethura.cloudhsm.models.CreateHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateHsm", POST, "/", input)
  override def createLunaClient(input: org.lyranthe.araethura.cloudhsm.models.CreateLunaClientRequest): F[org.lyranthe.araethura.cloudhsm.models.CreateLunaClientResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.CreateLunaClientResponse, org.lyranthe.araethura.cloudhsm.models.CreateLunaClientRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateLunaClient", POST, "/", input)
  override def describeHsm(input: org.lyranthe.araethura.cloudhsm.models.DescribeHsmRequest): F[org.lyranthe.araethura.cloudhsm.models.DescribeHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.DescribeHsmResponse, org.lyranthe.araethura.cloudhsm.models.DescribeHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeHsm", POST, "/", input)
  override def modifyHsm(input: org.lyranthe.araethura.cloudhsm.models.ModifyHsmRequest): F[org.lyranthe.araethura.cloudhsm.models.ModifyHsmResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cloudhsm.models.ModifyHsmResponse, org.lyranthe.araethura.cloudhsm.models.ModifyHsmRequest](client, awsData, ServiceType, ServiceAndPrefix, "ModifyHsm", POST, "/", input)
}