package org.lyranthe.araethura.cognitoidentity.http4s
import org.http4s.Method._
import org.lyranthe.araethura.cognitoidentity.circe._
import org.lyranthe.araethura.cognitoidentity.models
class AmazoncognitoidentityClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.cognitoidentity.Amazoncognitoidentity[F] {
  private[this] final val ServiceType: String = "cognito-identity"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSCognitoIdentityService")
  override def updateIdentityPool(input: models.IdentityPool): F[models.IdentityPool] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.IdentityPool, models.IdentityPool](client, awsData, ServiceType, ServiceAndPrefix, "UpdateIdentityPool", POST, "/", input)
  override def deleteIdentities(input: models.DeleteIdentitiesInput): F[models.DeleteIdentitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteIdentitiesResponse, models.DeleteIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteIdentities", POST, "/", input)
  override def getId(input: models.GetIdInput): F[models.GetIdResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetIdResponse, models.GetIdInput](client, awsData, ServiceType, ServiceAndPrefix, "GetId", POST, "/", input)
  override def getIdentityPoolRoles(input: models.GetIdentityPoolRolesInput): F[models.GetIdentityPoolRolesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetIdentityPoolRolesResponse, models.GetIdentityPoolRolesInput](client, awsData, ServiceType, ServiceAndPrefix, "GetIdentityPoolRoles", POST, "/", input)
  override def unlinkDeveloperIdentity(input: models.UnlinkDeveloperIdentityInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.UnlinkDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "UnlinkDeveloperIdentity", POST, "/", input)
  override def unlinkIdentity(input: models.UnlinkIdentityInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.UnlinkIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "UnlinkIdentity", POST, "/", input)
  override def getOpenIdTokenForDeveloperIdentity(input: models.GetOpenIdTokenForDeveloperIdentityInput): F[models.GetOpenIdTokenForDeveloperIdentityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetOpenIdTokenForDeveloperIdentityResponse, models.GetOpenIdTokenForDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "GetOpenIdTokenForDeveloperIdentity", POST, "/", input)
  override def listIdentities(input: models.ListIdentitiesInput): F[models.ListIdentitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListIdentitiesResponse, models.ListIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListIdentities", POST, "/", input)
  override def createIdentityPool(input: models.CreateIdentityPoolInput): F[models.IdentityPool] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.IdentityPool, models.CreateIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateIdentityPool", POST, "/", input)
  override def setIdentityPoolRoles(input: models.SetIdentityPoolRolesInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.SetIdentityPoolRolesInput](client, awsData, ServiceType, ServiceAndPrefix, "SetIdentityPoolRoles", POST, "/", input)
  override def lookupDeveloperIdentity(input: models.LookupDeveloperIdentityInput): F[models.LookupDeveloperIdentityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.LookupDeveloperIdentityResponse, models.LookupDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "LookupDeveloperIdentity", POST, "/", input)
  override def mergeDeveloperIdentities(input: models.MergeDeveloperIdentitiesInput): F[models.MergeDeveloperIdentitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.MergeDeveloperIdentitiesResponse, models.MergeDeveloperIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "MergeDeveloperIdentities", POST, "/", input)
  override def describeIdentity(input: models.DescribeIdentityInput): F[models.IdentityDescription] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.IdentityDescription, models.DescribeIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeIdentity", POST, "/", input)
  override def describeIdentityPool(input: models.DescribeIdentityPoolInput): F[models.IdentityPool] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.IdentityPool, models.DescribeIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeIdentityPool", POST, "/", input)
  override def getCredentialsForIdentity(input: models.GetCredentialsForIdentityInput): F[models.GetCredentialsForIdentityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetCredentialsForIdentityResponse, models.GetCredentialsForIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "GetCredentialsForIdentity", POST, "/", input)
  override def listIdentityPools(input: models.ListIdentityPoolsInput): F[models.ListIdentityPoolsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListIdentityPoolsResponse, models.ListIdentityPoolsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListIdentityPools", POST, "/", input)
  override def getOpenIdToken(input: models.GetOpenIdTokenInput): F[models.GetOpenIdTokenResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetOpenIdTokenResponse, models.GetOpenIdTokenInput](client, awsData, ServiceType, ServiceAndPrefix, "GetOpenIdToken", POST, "/", input)
  override def deleteIdentityPool(input: models.DeleteIdentityPoolInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.DeleteIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteIdentityPool", POST, "/", input)
}