package org.lyranthe.araethura.cognitoidentity.http4s
import org.http4s.Method._
import org.lyranthe.araethura.cognitoidentity.circe._
import org.lyranthe.araethura.cognitoidentity.models
class AmazoncognitoidentityClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.cognitoidentity.Amazoncognitoidentity[F] {
  private[this] final val ServiceType: String = "cognito-identity"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSCognitoIdentityService")
  override def updateIdentityPool(input: org.lyranthe.araethura.cognitoidentity.models.IdentityPool): F[org.lyranthe.araethura.cognitoidentity.models.IdentityPool] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.IdentityPool, org.lyranthe.araethura.cognitoidentity.models.IdentityPool](client, awsData, ServiceType, ServiceAndPrefix, "UpdateIdentityPool", POST, "/", input)
  override def deleteIdentities(input: org.lyranthe.araethura.cognitoidentity.models.DeleteIdentitiesInput): F[org.lyranthe.araethura.cognitoidentity.models.DeleteIdentitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.DeleteIdentitiesResponse, org.lyranthe.araethura.cognitoidentity.models.DeleteIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteIdentities", POST, "/", input)
  override def getId(input: org.lyranthe.araethura.cognitoidentity.models.GetIdInput): F[org.lyranthe.araethura.cognitoidentity.models.GetIdResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.GetIdResponse, org.lyranthe.araethura.cognitoidentity.models.GetIdInput](client, awsData, ServiceType, ServiceAndPrefix, "GetId", POST, "/", input)
  override def getIdentityPoolRoles(input: org.lyranthe.araethura.cognitoidentity.models.GetIdentityPoolRolesInput): F[org.lyranthe.araethura.cognitoidentity.models.GetIdentityPoolRolesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.GetIdentityPoolRolesResponse, org.lyranthe.araethura.cognitoidentity.models.GetIdentityPoolRolesInput](client, awsData, ServiceType, ServiceAndPrefix, "GetIdentityPoolRoles", POST, "/", input)
  override def unlinkDeveloperIdentity(input: org.lyranthe.araethura.cognitoidentity.models.UnlinkDeveloperIdentityInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.cognitoidentity.models.UnlinkDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "UnlinkDeveloperIdentity", POST, "/", input)
  override def unlinkIdentity(input: org.lyranthe.araethura.cognitoidentity.models.UnlinkIdentityInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.cognitoidentity.models.UnlinkIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "UnlinkIdentity", POST, "/", input)
  override def getOpenIdTokenForDeveloperIdentity(input: org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityInput): F[org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityResponse, org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "GetOpenIdTokenForDeveloperIdentity", POST, "/", input)
  override def listIdentities(input: org.lyranthe.araethura.cognitoidentity.models.ListIdentitiesInput): F[org.lyranthe.araethura.cognitoidentity.models.ListIdentitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.ListIdentitiesResponse, org.lyranthe.araethura.cognitoidentity.models.ListIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListIdentities", POST, "/", input)
  override def createIdentityPool(input: org.lyranthe.araethura.cognitoidentity.models.CreateIdentityPoolInput): F[org.lyranthe.araethura.cognitoidentity.models.IdentityPool] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.IdentityPool, org.lyranthe.araethura.cognitoidentity.models.CreateIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateIdentityPool", POST, "/", input)
  override def setIdentityPoolRoles(input: org.lyranthe.araethura.cognitoidentity.models.SetIdentityPoolRolesInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.cognitoidentity.models.SetIdentityPoolRolesInput](client, awsData, ServiceType, ServiceAndPrefix, "SetIdentityPoolRoles", POST, "/", input)
  override def lookupDeveloperIdentity(input: org.lyranthe.araethura.cognitoidentity.models.LookupDeveloperIdentityInput): F[org.lyranthe.araethura.cognitoidentity.models.LookupDeveloperIdentityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.LookupDeveloperIdentityResponse, org.lyranthe.araethura.cognitoidentity.models.LookupDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "LookupDeveloperIdentity", POST, "/", input)
  override def mergeDeveloperIdentities(input: org.lyranthe.araethura.cognitoidentity.models.MergeDeveloperIdentitiesInput): F[org.lyranthe.araethura.cognitoidentity.models.MergeDeveloperIdentitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.MergeDeveloperIdentitiesResponse, org.lyranthe.araethura.cognitoidentity.models.MergeDeveloperIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "MergeDeveloperIdentities", POST, "/", input)
  override def describeIdentity(input: org.lyranthe.araethura.cognitoidentity.models.DescribeIdentityInput): F[org.lyranthe.araethura.cognitoidentity.models.IdentityDescription] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.IdentityDescription, org.lyranthe.araethura.cognitoidentity.models.DescribeIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeIdentity", POST, "/", input)
  override def describeIdentityPool(input: org.lyranthe.araethura.cognitoidentity.models.DescribeIdentityPoolInput): F[org.lyranthe.araethura.cognitoidentity.models.IdentityPool] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.IdentityPool, org.lyranthe.araethura.cognitoidentity.models.DescribeIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeIdentityPool", POST, "/", input)
  override def getCredentialsForIdentity(input: org.lyranthe.araethura.cognitoidentity.models.GetCredentialsForIdentityInput): F[org.lyranthe.araethura.cognitoidentity.models.GetCredentialsForIdentityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.GetCredentialsForIdentityResponse, org.lyranthe.araethura.cognitoidentity.models.GetCredentialsForIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "GetCredentialsForIdentity", POST, "/", input)
  override def listIdentityPools(input: org.lyranthe.araethura.cognitoidentity.models.ListIdentityPoolsInput): F[org.lyranthe.araethura.cognitoidentity.models.ListIdentityPoolsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.ListIdentityPoolsResponse, org.lyranthe.araethura.cognitoidentity.models.ListIdentityPoolsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListIdentityPools", POST, "/", input)
  override def getOpenIdToken(input: org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenInput): F[org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenResponse, org.lyranthe.araethura.cognitoidentity.models.GetOpenIdTokenInput](client, awsData, ServiceType, ServiceAndPrefix, "GetOpenIdToken", POST, "/", input)
  override def deleteIdentityPool(input: org.lyranthe.araethura.cognitoidentity.models.DeleteIdentityPoolInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.cognitoidentity.models.DeleteIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteIdentityPool", POST, "/", input)
}