package org.lyranthe.araethura.inspector
trait Amazoninspector[F[_]] {
  def createAssessmentTemplate(input: org.lyranthe.araethura.inspector.models.CreateAssessmentTemplateRequest): F[org.lyranthe.araethura.inspector.models.CreateAssessmentTemplateResponse]
  def removeAttributesFromFindings(input: org.lyranthe.araethura.inspector.models.RemoveAttributesFromFindingsRequest): F[org.lyranthe.araethura.inspector.models.RemoveAttributesFromFindingsResponse]
  def listEventSubscriptions(input: org.lyranthe.araethura.inspector.models.ListEventSubscriptionsRequest): F[org.lyranthe.araethura.inspector.models.ListEventSubscriptionsResponse]
  def setTagsForResource(input: org.lyranthe.araethura.inspector.models.SetTagsForResourceRequest): F[scala.Unit]
  def listFindings(input: org.lyranthe.araethura.inspector.models.ListFindingsRequest): F[org.lyranthe.araethura.inspector.models.ListFindingsResponse]
  def listTagsForResource(input: org.lyranthe.araethura.inspector.models.ListTagsForResourceRequest): F[org.lyranthe.araethura.inspector.models.ListTagsForResourceResponse]
  def unsubscribeFromEvent(input: org.lyranthe.araethura.inspector.models.UnsubscribeFromEventRequest): F[scala.Unit]
  def describeRulesPackages(input: org.lyranthe.araethura.inspector.models.DescribeRulesPackagesRequest): F[org.lyranthe.araethura.inspector.models.DescribeRulesPackagesResponse]
  def addAttributesToFindings(input: org.lyranthe.araethura.inspector.models.AddAttributesToFindingsRequest): F[org.lyranthe.araethura.inspector.models.AddAttributesToFindingsResponse]
  def updateAssessmentTarget(input: org.lyranthe.araethura.inspector.models.UpdateAssessmentTargetRequest): F[scala.Unit]
  def listRulesPackages(input: org.lyranthe.araethura.inspector.models.ListRulesPackagesRequest): F[org.lyranthe.araethura.inspector.models.ListRulesPackagesResponse]
  def describeAssessmentTemplates(input: org.lyranthe.araethura.inspector.models.DescribeAssessmentTemplatesRequest): F[org.lyranthe.araethura.inspector.models.DescribeAssessmentTemplatesResponse]
  def listAssessmentRuns(input: org.lyranthe.araethura.inspector.models.ListAssessmentRunsRequest): F[org.lyranthe.araethura.inspector.models.ListAssessmentRunsResponse]
  def describeFindings(input: org.lyranthe.araethura.inspector.models.DescribeFindingsRequest): F[org.lyranthe.araethura.inspector.models.DescribeFindingsResponse]
  def listAssessmentTargets(input: org.lyranthe.araethura.inspector.models.ListAssessmentTargetsRequest): F[org.lyranthe.araethura.inspector.models.ListAssessmentTargetsResponse]
  def describeResourceGroups(input: org.lyranthe.araethura.inspector.models.DescribeResourceGroupsRequest): F[org.lyranthe.araethura.inspector.models.DescribeResourceGroupsResponse]
  def getTelemetryMetadata(input: org.lyranthe.araethura.inspector.models.GetTelemetryMetadataRequest): F[org.lyranthe.araethura.inspector.models.GetTelemetryMetadataResponse]
  def deleteAssessmentTarget(input: org.lyranthe.araethura.inspector.models.DeleteAssessmentTargetRequest): F[scala.Unit]
  def describeAssessmentRuns(input: org.lyranthe.araethura.inspector.models.DescribeAssessmentRunsRequest): F[org.lyranthe.araethura.inspector.models.DescribeAssessmentRunsResponse]
  def previewAgents(input: org.lyranthe.araethura.inspector.models.PreviewAgentsRequest): F[org.lyranthe.araethura.inspector.models.PreviewAgentsResponse]
  def registerCrossAccountAccessRole(input: org.lyranthe.araethura.inspector.models.RegisterCrossAccountAccessRoleRequest): F[scala.Unit]
  def describeAssessmentTargets(input: org.lyranthe.araethura.inspector.models.DescribeAssessmentTargetsRequest): F[org.lyranthe.araethura.inspector.models.DescribeAssessmentTargetsResponse]
  def deleteAssessmentRun(input: org.lyranthe.araethura.inspector.models.DeleteAssessmentRunRequest): F[scala.Unit]
  def listAssessmentRunAgents(input: org.lyranthe.araethura.inspector.models.ListAssessmentRunAgentsRequest): F[org.lyranthe.araethura.inspector.models.ListAssessmentRunAgentsResponse]
  def getAssessmentReport(input: org.lyranthe.araethura.inspector.models.GetAssessmentReportRequest): F[org.lyranthe.araethura.inspector.models.GetAssessmentReportResponse]
  def describeCrossAccountAccessRole: F[org.lyranthe.araethura.inspector.models.DescribeCrossAccountAccessRoleResponse]
  def startAssessmentRun(input: org.lyranthe.araethura.inspector.models.StartAssessmentRunRequest): F[org.lyranthe.araethura.inspector.models.StartAssessmentRunResponse]
  def deleteAssessmentTemplate(input: org.lyranthe.araethura.inspector.models.DeleteAssessmentTemplateRequest): F[scala.Unit]
  def createResourceGroup(input: org.lyranthe.araethura.inspector.models.CreateResourceGroupRequest): F[org.lyranthe.araethura.inspector.models.CreateResourceGroupResponse]
  def subscribeToEvent(input: org.lyranthe.araethura.inspector.models.SubscribeToEventRequest): F[scala.Unit]
  def createAssessmentTarget(input: org.lyranthe.araethura.inspector.models.CreateAssessmentTargetRequest): F[org.lyranthe.araethura.inspector.models.CreateAssessmentTargetResponse]
  def stopAssessmentRun(input: org.lyranthe.araethura.inspector.models.StopAssessmentRunRequest): F[scala.Unit]
  def listAssessmentTemplates(input: org.lyranthe.araethura.inspector.models.ListAssessmentTemplatesRequest): F[org.lyranthe.araethura.inspector.models.ListAssessmentTemplatesResponse]
}