package org.lyranthe.araethura.datapipeline.models
import org.lyranthe.araethura.datapipeline.models
final case class PutPipelineDefinitionOutput(errored: scala.Boolean, validationErrors: scala.Option[scala.List[models.ValidationError]] = None, validationWarnings: scala.Option[scala.List[models.ValidationWarning]] = None)
final case class QueryObjectsOutput(ids: scala.Option[scala.List[java.lang.String]] = None, marker: scala.Option[java.lang.String] = None, hasMoreResults: scala.Option[scala.Boolean] = None)
final case class DescribePipelinesInput(pipelineIds: scala.List[java.lang.String])
final case class ReportTaskRunnerHeartbeatOutput(terminate: scala.Boolean)
final case class Field(key: java.lang.String, refValue: scala.Option[java.lang.String] = None, stringValue: scala.Option[java.lang.String] = None)
final case class ValidatePipelineDefinitionInput(pipelineId: java.lang.String, pipelineObjects: scala.List[models.PipelineObject], parameterObjects: scala.Option[scala.List[models.ParameterObject]] = None, parameterValues: scala.Option[scala.List[models.ParameterValue]] = None)
final case class CreatePipelineInput(name: java.lang.String, uniqueId: java.lang.String, description: scala.Option[java.lang.String] = None, tags: scala.Option[scala.List[models.Tag]] = None)
final case class Operator(`type`: scala.Option[java.lang.String] = None, values: scala.Option[scala.List[java.lang.String]] = None)
final case class PipelineNotFoundException(message: scala.Option[java.lang.String] = None)
final case class Query(selectors: scala.Option[scala.List[models.Selector]] = None)
final case class GetPipelineDefinitionInput(pipelineId: java.lang.String, version: scala.Option[java.lang.String] = None)
final case class DescribePipelinesOutput(pipelineDescriptionList: scala.List[models.PipelineDescription])
final case class PutPipelineDefinitionInput(pipelineId: java.lang.String, pipelineObjects: scala.List[models.PipelineObject], parameterObjects: scala.Option[scala.List[models.ParameterObject]] = None, parameterValues: scala.Option[scala.List[models.ParameterValue]] = None)
final case class ValidationError(id: scala.Option[java.lang.String] = None, errors: scala.Option[scala.List[java.lang.String]] = None)
final case class SetTaskStatusInput(taskId: java.lang.String, taskStatus: java.lang.String, errorId: scala.Option[java.lang.String] = None, errorStackTrace: scala.Option[java.lang.String] = None, errorMessage: scala.Option[java.lang.String] = None)
final case class PipelineDescription(pipelineId: java.lang.String, name: java.lang.String, fields: scala.List[models.Field], description: scala.Option[java.lang.String] = None, tags: scala.Option[scala.List[models.Tag]] = None)
final case class ListPipelinesOutput(pipelineIdList: scala.List[models.PipelineIdName], marker: scala.Option[java.lang.String] = None, hasMoreResults: scala.Option[scala.Boolean] = None)
final case class CreatePipelineOutput(pipelineId: java.lang.String)
case object SetTaskStatusOutput
final case class DescribeObjectsInput(pipelineId: java.lang.String, objectIds: scala.List[java.lang.String], evaluateExpressions: scala.Option[scala.Boolean] = None, marker: scala.Option[java.lang.String] = None)
final case class ValidatePipelineDefinitionOutput(errored: scala.Boolean, validationErrors: scala.Option[scala.List[models.ValidationError]] = None, validationWarnings: scala.Option[scala.List[models.ValidationWarning]] = None)
final case class PipelineDeletedException(message: scala.Option[java.lang.String] = None)
final case class GetPipelineDefinitionOutput(pipelineObjects: scala.Option[scala.List[models.PipelineObject]] = None, parameterObjects: scala.Option[scala.List[models.ParameterObject]] = None, parameterValues: scala.Option[scala.List[models.ParameterValue]] = None)
final case class InternalServiceError(message: scala.Option[java.lang.String] = None)
final case class Selector(fieldName: scala.Option[java.lang.String] = None, operator: scala.Option[models.Operator] = None)
final case class TaskObject(taskId: scala.Option[java.lang.String] = None, pipelineId: scala.Option[java.lang.String] = None, attemptId: scala.Option[java.lang.String] = None, objects: scala.Option[scala.collection.immutable.Map[java.lang.String, models.PipelineObject]] = None)
final case class InstanceIdentity(document: scala.Option[java.lang.String] = None, signature: scala.Option[java.lang.String] = None)
final case class SetStatusInput(pipelineId: java.lang.String, objectIds: scala.List[java.lang.String], status: java.lang.String)
final case class DeactivatePipelineInput(pipelineId: java.lang.String, cancelActive: scala.Option[scala.Boolean] = None)
case object DeactivatePipelineOutput
final case class ParameterObject(id: java.lang.String, attributes: scala.List[models.ParameterAttribute])
final case class ReportTaskRunnerHeartbeatInput(taskrunnerId: java.lang.String, hostname: scala.Option[java.lang.String] = None, workerGroup: scala.Option[java.lang.String] = None)
final case class ParameterAttribute(key: java.lang.String, stringValue: java.lang.String)
final case class InvalidRequestException(message: scala.Option[java.lang.String] = None)
final case class AddTagsInput(pipelineId: java.lang.String, tags: scala.List[models.Tag])
case object RemoveTagsOutput
final case class PollForTaskOutput(taskObject: scala.Option[models.TaskObject] = None)
final case class PipelineObject(id: java.lang.String, name: java.lang.String, fields: scala.List[models.Field])
case object ActivatePipelineOutput
final case class PollForTaskInput(workerGroup: java.lang.String, hostname: scala.Option[java.lang.String] = None, instanceIdentity: scala.Option[models.InstanceIdentity] = None)
final case class ValidationWarning(id: scala.Option[java.lang.String] = None, warnings: scala.Option[scala.List[java.lang.String]] = None)
final case class QueryObjectsInput(pipelineId: java.lang.String, sphere: java.lang.String, marker: scala.Option[java.lang.String] = None, query: scala.Option[models.Query] = None, limit: scala.Option[scala.Int] = None)
final case class ParameterValue(id: java.lang.String, stringValue: java.lang.String)
final case class PipelineIdName(id: scala.Option[java.lang.String] = None, name: scala.Option[java.lang.String] = None)
final case class ReportTaskProgressOutput(canceled: scala.Boolean)
case object AddTagsOutput
final case class RemoveTagsInput(pipelineId: java.lang.String, tagKeys: scala.List[java.lang.String])
final case class Tag(key: java.lang.String, value: java.lang.String)
final case class DeletePipelineInput(pipelineId: java.lang.String)
final case class EvaluateExpressionInput(pipelineId: java.lang.String, objectId: java.lang.String, expression: java.lang.String)
final case class TaskNotFoundException(message: scala.Option[java.lang.String] = None)
final case class ActivatePipelineInput(pipelineId: java.lang.String, parameterValues: scala.Option[scala.List[models.ParameterValue]] = None, startTimestamp: scala.Option[java.time.Instant] = None)
final case class DescribeObjectsOutput(pipelineObjects: scala.List[models.PipelineObject], marker: scala.Option[java.lang.String] = None, hasMoreResults: scala.Option[scala.Boolean] = None)
final case class ListPipelinesInput(marker: scala.Option[java.lang.String] = None)
final case class ReportTaskProgressInput(taskId: java.lang.String, fields: scala.Option[scala.List[models.Field]] = None)
final case class EvaluateExpressionOutput(evaluatedExpression: java.lang.String)