package org.lyranthe.araethura.datapipeline
trait Amazondatapipeline[F[_]] {
  def deactivatePipeline(input: org.lyranthe.araethura.datapipeline.models.DeactivatePipelineInput): F[scala.Unit]
  def queryObjects(input: org.lyranthe.araethura.datapipeline.models.QueryObjectsInput): F[org.lyranthe.araethura.datapipeline.models.QueryObjectsOutput]
  def putPipelineDefinition(input: org.lyranthe.araethura.datapipeline.models.PutPipelineDefinitionInput): F[org.lyranthe.araethura.datapipeline.models.PutPipelineDefinitionOutput]
  def evaluateExpression(input: org.lyranthe.araethura.datapipeline.models.EvaluateExpressionInput): F[org.lyranthe.araethura.datapipeline.models.EvaluateExpressionOutput]
  def reportTaskRunnerHeartbeat(input: org.lyranthe.araethura.datapipeline.models.ReportTaskRunnerHeartbeatInput): F[org.lyranthe.araethura.datapipeline.models.ReportTaskRunnerHeartbeatOutput]
  def getPipelineDefinition(input: org.lyranthe.araethura.datapipeline.models.GetPipelineDefinitionInput): F[org.lyranthe.araethura.datapipeline.models.GetPipelineDefinitionOutput]
  def reportTaskProgress(input: org.lyranthe.araethura.datapipeline.models.ReportTaskProgressInput): F[org.lyranthe.araethura.datapipeline.models.ReportTaskProgressOutput]
  def validatePipelineDefinition(input: org.lyranthe.araethura.datapipeline.models.ValidatePipelineDefinitionInput): F[org.lyranthe.araethura.datapipeline.models.ValidatePipelineDefinitionOutput]
  def deletePipeline(input: org.lyranthe.araethura.datapipeline.models.DeletePipelineInput): F[scala.Unit]
  def pollForTask(input: org.lyranthe.araethura.datapipeline.models.PollForTaskInput): F[org.lyranthe.araethura.datapipeline.models.PollForTaskOutput]
  def activatePipeline(input: org.lyranthe.araethura.datapipeline.models.ActivatePipelineInput): F[scala.Unit]
  def setStatus(input: org.lyranthe.araethura.datapipeline.models.SetStatusInput): F[scala.Unit]
  def setTaskStatus(input: org.lyranthe.araethura.datapipeline.models.SetTaskStatusInput): F[scala.Unit]
  def describeObjects(input: org.lyranthe.araethura.datapipeline.models.DescribeObjectsInput): F[org.lyranthe.araethura.datapipeline.models.DescribeObjectsOutput]
  def removeTags(input: org.lyranthe.araethura.datapipeline.models.RemoveTagsInput): F[scala.Unit]
  def addTags(input: org.lyranthe.araethura.datapipeline.models.AddTagsInput): F[scala.Unit]
  def describePipelines(input: org.lyranthe.araethura.datapipeline.models.DescribePipelinesInput): F[org.lyranthe.araethura.datapipeline.models.DescribePipelinesOutput]
  def listPipelines(input: org.lyranthe.araethura.datapipeline.models.ListPipelinesInput): F[org.lyranthe.araethura.datapipeline.models.ListPipelinesOutput]
  def createPipeline(input: org.lyranthe.araethura.datapipeline.models.CreatePipelineInput): F[org.lyranthe.araethura.datapipeline.models.CreatePipelineOutput]
}