package org.lyranthe.araethura.events.http4s
import org.http4s.Method._
import org.lyranthe.araethura.events.circe._
import org.lyranthe.araethura.events.models
class AmazoneventsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.events.Amazonevents[F] {
  private[this] final val ServiceType: String = "events"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSEvents")
  override def putEvents(input: org.lyranthe.araethura.events.models.PutEventsRequest): F[org.lyranthe.araethura.events.models.PutEventsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.PutEventsResponse, org.lyranthe.araethura.events.models.PutEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutEvents", POST, "/", input)
  override def removePermission(input: org.lyranthe.araethura.events.models.RemovePermissionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.events.models.RemovePermissionRequest](client, awsData, ServiceType, ServiceAndPrefix, "RemovePermission", POST, "/", input)
  override def describeEventBus: F[org.lyranthe.araethura.events.models.DescribeEventBusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.DescribeEventBusResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEventBus", POST, "/", ())
  override def describeRule(input: org.lyranthe.araethura.events.models.DescribeRuleRequest): F[org.lyranthe.araethura.events.models.DescribeRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.DescribeRuleResponse, org.lyranthe.araethura.events.models.DescribeRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeRule", POST, "/", input)
  override def disableRule(input: org.lyranthe.araethura.events.models.DisableRuleRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.events.models.DisableRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisableRule", POST, "/", input)
  override def testEventPattern(input: org.lyranthe.araethura.events.models.TestEventPatternRequest): F[org.lyranthe.araethura.events.models.TestEventPatternResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.TestEventPatternResponse, org.lyranthe.araethura.events.models.TestEventPatternRequest](client, awsData, ServiceType, ServiceAndPrefix, "TestEventPattern", POST, "/", input)
  override def enableRule(input: org.lyranthe.araethura.events.models.EnableRuleRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.events.models.EnableRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "EnableRule", POST, "/", input)
  override def listTargetsByRule(input: org.lyranthe.araethura.events.models.ListTargetsByRuleRequest): F[org.lyranthe.araethura.events.models.ListTargetsByRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.ListTargetsByRuleResponse, org.lyranthe.araethura.events.models.ListTargetsByRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTargetsByRule", POST, "/", input)
  override def deleteRule(input: org.lyranthe.araethura.events.models.DeleteRuleRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.events.models.DeleteRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteRule", POST, "/", input)
  override def removeTargets(input: org.lyranthe.araethura.events.models.RemoveTargetsRequest): F[org.lyranthe.araethura.events.models.RemoveTargetsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.RemoveTargetsResponse, org.lyranthe.araethura.events.models.RemoveTargetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTargets", POST, "/", input)
  override def putRule(input: org.lyranthe.araethura.events.models.PutRuleRequest): F[org.lyranthe.araethura.events.models.PutRuleResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.PutRuleResponse, org.lyranthe.araethura.events.models.PutRuleRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutRule", POST, "/", input)
  override def putPermission(input: org.lyranthe.araethura.events.models.PutPermissionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.events.models.PutPermissionRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutPermission", POST, "/", input)
  override def listRuleNamesByTarget(input: org.lyranthe.araethura.events.models.ListRuleNamesByTargetRequest): F[org.lyranthe.araethura.events.models.ListRuleNamesByTargetResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.ListRuleNamesByTargetResponse, org.lyranthe.araethura.events.models.ListRuleNamesByTargetRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListRuleNamesByTarget", POST, "/", input)
  override def putTargets(input: org.lyranthe.araethura.events.models.PutTargetsRequest): F[org.lyranthe.araethura.events.models.PutTargetsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.PutTargetsResponse, org.lyranthe.araethura.events.models.PutTargetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutTargets", POST, "/", input)
  override def listRules(input: org.lyranthe.araethura.events.models.ListRulesRequest): F[org.lyranthe.araethura.events.models.ListRulesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.events.models.ListRulesResponse, org.lyranthe.araethura.events.models.ListRulesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListRules", POST, "/", input)
}