package org.lyranthe.araethura.route53domains.http4s
import org.http4s.Method._
import org.lyranthe.araethura.route53domains.circe._
import org.lyranthe.araethura.route53domains.models
class Amazonroute53domainsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.route53domains.Amazonroute53domains[F] {
  private[this] final val ServiceType: String = "route53domains"
  private[this] final val ServiceAndPrefix: Option[String] = Some("Route53Domains_v20140515")
  override def updateDomainContact(input: org.lyranthe.araethura.route53domains.models.UpdateDomainContactRequest): F[org.lyranthe.araethura.route53domains.models.UpdateDomainContactResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.UpdateDomainContactResponse, org.lyranthe.araethura.route53domains.models.UpdateDomainContactRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDomainContact", POST, "/", input)
  override def updateTagsForDomain(input: org.lyranthe.araethura.route53domains.models.UpdateTagsForDomainRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.route53domains.models.UpdateTagsForDomainRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateTagsForDomain", POST, "/", input)
  override def listOperations(input: org.lyranthe.araethura.route53domains.models.ListOperationsRequest): F[org.lyranthe.araethura.route53domains.models.ListOperationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.ListOperationsResponse, org.lyranthe.araethura.route53domains.models.ListOperationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListOperations", POST, "/", input)
  override def disableDomainTransferLock(input: org.lyranthe.araethura.route53domains.models.DisableDomainTransferLockRequest): F[org.lyranthe.araethura.route53domains.models.DisableDomainTransferLockResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.DisableDomainTransferLockResponse, org.lyranthe.araethura.route53domains.models.DisableDomainTransferLockRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisableDomainTransferLock", POST, "/", input)
  override def updateDomainContactPrivacy(input: org.lyranthe.araethura.route53domains.models.UpdateDomainContactPrivacyRequest): F[org.lyranthe.araethura.route53domains.models.UpdateDomainContactPrivacyResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.UpdateDomainContactPrivacyResponse, org.lyranthe.araethura.route53domains.models.UpdateDomainContactPrivacyRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDomainContactPrivacy", POST, "/", input)
  override def transferDomain(input: org.lyranthe.araethura.route53domains.models.TransferDomainRequest): F[org.lyranthe.araethura.route53domains.models.TransferDomainResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.TransferDomainResponse, org.lyranthe.araethura.route53domains.models.TransferDomainRequest](client, awsData, ServiceType, ServiceAndPrefix, "TransferDomain", POST, "/", input)
  override def getDomainDetail(input: org.lyranthe.araethura.route53domains.models.GetDomainDetailRequest): F[org.lyranthe.araethura.route53domains.models.GetDomainDetailResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.GetDomainDetailResponse, org.lyranthe.araethura.route53domains.models.GetDomainDetailRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetDomainDetail", POST, "/", input)
  override def retrieveDomainAuthCode(input: org.lyranthe.araethura.route53domains.models.RetrieveDomainAuthCodeRequest): F[org.lyranthe.araethura.route53domains.models.RetrieveDomainAuthCodeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.RetrieveDomainAuthCodeResponse, org.lyranthe.araethura.route53domains.models.RetrieveDomainAuthCodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "RetrieveDomainAuthCode", POST, "/", input)
  override def listTagsForDomain(input: org.lyranthe.araethura.route53domains.models.ListTagsForDomainRequest): F[org.lyranthe.araethura.route53domains.models.ListTagsForDomainResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.ListTagsForDomainResponse, org.lyranthe.araethura.route53domains.models.ListTagsForDomainRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForDomain", POST, "/", input)
  override def resendContactReachabilityEmail(input: org.lyranthe.araethura.route53domains.models.ResendContactReachabilityEmailRequest): F[org.lyranthe.araethura.route53domains.models.ResendContactReachabilityEmailResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.ResendContactReachabilityEmailResponse, org.lyranthe.araethura.route53domains.models.ResendContactReachabilityEmailRequest](client, awsData, ServiceType, ServiceAndPrefix, "ResendContactReachabilityEmail", POST, "/", input)
  override def checkDomainAvailability(input: org.lyranthe.araethura.route53domains.models.CheckDomainAvailabilityRequest): F[org.lyranthe.araethura.route53domains.models.CheckDomainAvailabilityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.CheckDomainAvailabilityResponse, org.lyranthe.araethura.route53domains.models.CheckDomainAvailabilityRequest](client, awsData, ServiceType, ServiceAndPrefix, "CheckDomainAvailability", POST, "/", input)
  override def getDomainSuggestions(input: org.lyranthe.araethura.route53domains.models.GetDomainSuggestionsRequest): F[org.lyranthe.araethura.route53domains.models.GetDomainSuggestionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.GetDomainSuggestionsResponse, org.lyranthe.araethura.route53domains.models.GetDomainSuggestionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetDomainSuggestions", POST, "/", input)
  override def getOperationDetail(input: org.lyranthe.araethura.route53domains.models.GetOperationDetailRequest): F[org.lyranthe.araethura.route53domains.models.GetOperationDetailResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.GetOperationDetailResponse, org.lyranthe.araethura.route53domains.models.GetOperationDetailRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetOperationDetail", POST, "/", input)
  override def viewBilling(input: org.lyranthe.araethura.route53domains.models.ViewBillingRequest): F[org.lyranthe.araethura.route53domains.models.ViewBillingResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.ViewBillingResponse, org.lyranthe.araethura.route53domains.models.ViewBillingRequest](client, awsData, ServiceType, ServiceAndPrefix, "ViewBilling", POST, "/", input)
  override def renewDomain(input: org.lyranthe.araethura.route53domains.models.RenewDomainRequest): F[org.lyranthe.araethura.route53domains.models.RenewDomainResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.RenewDomainResponse, org.lyranthe.araethura.route53domains.models.RenewDomainRequest](client, awsData, ServiceType, ServiceAndPrefix, "RenewDomain", POST, "/", input)
  override def checkDomainTransferability(input: org.lyranthe.araethura.route53domains.models.CheckDomainTransferabilityRequest): F[org.lyranthe.araethura.route53domains.models.CheckDomainTransferabilityResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.CheckDomainTransferabilityResponse, org.lyranthe.araethura.route53domains.models.CheckDomainTransferabilityRequest](client, awsData, ServiceType, ServiceAndPrefix, "CheckDomainTransferability", POST, "/", input)
  override def deleteTagsForDomain(input: org.lyranthe.araethura.route53domains.models.DeleteTagsForDomainRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.route53domains.models.DeleteTagsForDomainRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteTagsForDomain", POST, "/", input)
  override def disableDomainAutoRenew(input: org.lyranthe.araethura.route53domains.models.DisableDomainAutoRenewRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.route53domains.models.DisableDomainAutoRenewRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisableDomainAutoRenew", POST, "/", input)
  override def enableDomainAutoRenew(input: org.lyranthe.araethura.route53domains.models.EnableDomainAutoRenewRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.route53domains.models.EnableDomainAutoRenewRequest](client, awsData, ServiceType, ServiceAndPrefix, "EnableDomainAutoRenew", POST, "/", input)
  override def registerDomain(input: org.lyranthe.araethura.route53domains.models.RegisterDomainRequest): F[org.lyranthe.araethura.route53domains.models.RegisterDomainResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.RegisterDomainResponse, org.lyranthe.araethura.route53domains.models.RegisterDomainRequest](client, awsData, ServiceType, ServiceAndPrefix, "RegisterDomain", POST, "/", input)
  override def enableDomainTransferLock(input: org.lyranthe.araethura.route53domains.models.EnableDomainTransferLockRequest): F[org.lyranthe.araethura.route53domains.models.EnableDomainTransferLockResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.EnableDomainTransferLockResponse, org.lyranthe.araethura.route53domains.models.EnableDomainTransferLockRequest](client, awsData, ServiceType, ServiceAndPrefix, "EnableDomainTransferLock", POST, "/", input)
  override def getContactReachabilityStatus(input: org.lyranthe.araethura.route53domains.models.GetContactReachabilityStatusRequest): F[org.lyranthe.araethura.route53domains.models.GetContactReachabilityStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.GetContactReachabilityStatusResponse, org.lyranthe.araethura.route53domains.models.GetContactReachabilityStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetContactReachabilityStatus", POST, "/", input)
  override def listDomains(input: org.lyranthe.araethura.route53domains.models.ListDomainsRequest): F[org.lyranthe.araethura.route53domains.models.ListDomainsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.ListDomainsResponse, org.lyranthe.araethura.route53domains.models.ListDomainsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListDomains", POST, "/", input)
  override def updateDomainNameservers(input: org.lyranthe.araethura.route53domains.models.UpdateDomainNameserversRequest): F[org.lyranthe.araethura.route53domains.models.UpdateDomainNameserversResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.route53domains.models.UpdateDomainNameserversResponse, org.lyranthe.araethura.route53domains.models.UpdateDomainNameserversRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDomainNameservers", POST, "/", input)
}