package avias.dax.http4s
import org.http4s.Method._
import avias.dax.circe._
import avias.dax.models
class AmazondaxClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.dax.Amazondax[F] {
  private[this] final val ServiceType: String = "dax"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AmazonDAXV3")
  override def describeClusters(input: avias.dax.models.DescribeClustersRequest): F[avias.dax.models.DescribeClustersResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DescribeClustersResponse, avias.dax.models.DescribeClustersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeClusters", POST, "/", input)
  override def describeEvents(input: avias.dax.models.DescribeEventsRequest): F[avias.dax.models.DescribeEventsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DescribeEventsResponse, avias.dax.models.DescribeEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEvents", POST, "/", input)
  override def rebootNode(input: avias.dax.models.RebootNodeRequest): F[avias.dax.models.RebootNodeResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.RebootNodeResponse, avias.dax.models.RebootNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "RebootNode", POST, "/", input)
  override def tagResource(input: avias.dax.models.TagResourceRequest): F[avias.dax.models.TagResourceResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.TagResourceResponse, avias.dax.models.TagResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "TagResource", POST, "/", input)
  override def createSubnetGroup(input: avias.dax.models.CreateSubnetGroupRequest): F[avias.dax.models.CreateSubnetGroupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.CreateSubnetGroupResponse, avias.dax.models.CreateSubnetGroupRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateSubnetGroup", POST, "/", input)
  override def describeParameterGroups(input: avias.dax.models.DescribeParameterGroupsRequest): F[avias.dax.models.DescribeParameterGroupsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DescribeParameterGroupsResponse, avias.dax.models.DescribeParameterGroupsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeParameterGroups", POST, "/", input)
  override def untagResource(input: avias.dax.models.UntagResourceRequest): F[avias.dax.models.UntagResourceResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.UntagResourceResponse, avias.dax.models.UntagResourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "UntagResource", POST, "/", input)
  override def deleteCluster(input: avias.dax.models.DeleteClusterRequest): F[avias.dax.models.DeleteClusterResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DeleteClusterResponse, avias.dax.models.DeleteClusterRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteCluster", POST, "/", input)
  override def deleteParameterGroup(input: avias.dax.models.DeleteParameterGroupRequest): F[avias.dax.models.DeleteParameterGroupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DeleteParameterGroupResponse, avias.dax.models.DeleteParameterGroupRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteParameterGroup", POST, "/", input)
  override def increaseReplicationFactor(input: avias.dax.models.IncreaseReplicationFactorRequest): F[avias.dax.models.IncreaseReplicationFactorResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.IncreaseReplicationFactorResponse, avias.dax.models.IncreaseReplicationFactorRequest](client, awsData, ServiceType, ServiceAndPrefix, "IncreaseReplicationFactor", POST, "/", input)
  override def updateCluster(input: avias.dax.models.UpdateClusterRequest): F[avias.dax.models.UpdateClusterResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.UpdateClusterResponse, avias.dax.models.UpdateClusterRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateCluster", POST, "/", input)
  override def listTags(input: avias.dax.models.ListTagsRequest): F[avias.dax.models.ListTagsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.ListTagsResponse, avias.dax.models.ListTagsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTags", POST, "/", input)
  override def describeParameters(input: avias.dax.models.DescribeParametersRequest): F[avias.dax.models.DescribeParametersResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DescribeParametersResponse, avias.dax.models.DescribeParametersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeParameters", POST, "/", input)
  override def deleteSubnetGroup(input: avias.dax.models.DeleteSubnetGroupRequest): F[avias.dax.models.DeleteSubnetGroupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DeleteSubnetGroupResponse, avias.dax.models.DeleteSubnetGroupRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteSubnetGroup", POST, "/", input)
  override def describeSubnetGroups(input: avias.dax.models.DescribeSubnetGroupsRequest): F[avias.dax.models.DescribeSubnetGroupsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DescribeSubnetGroupsResponse, avias.dax.models.DescribeSubnetGroupsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSubnetGroups", POST, "/", input)
  override def updateParameterGroup(input: avias.dax.models.UpdateParameterGroupRequest): F[avias.dax.models.UpdateParameterGroupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.UpdateParameterGroupResponse, avias.dax.models.UpdateParameterGroupRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateParameterGroup", POST, "/", input)
  override def describeDefaultParameters(input: avias.dax.models.DescribeDefaultParametersRequest): F[avias.dax.models.DescribeDefaultParametersResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DescribeDefaultParametersResponse, avias.dax.models.DescribeDefaultParametersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDefaultParameters", POST, "/", input)
  override def createParameterGroup(input: avias.dax.models.CreateParameterGroupRequest): F[avias.dax.models.CreateParameterGroupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.CreateParameterGroupResponse, avias.dax.models.CreateParameterGroupRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateParameterGroup", POST, "/", input)
  override def createCluster(input: avias.dax.models.CreateClusterRequest): F[avias.dax.models.CreateClusterResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.CreateClusterResponse, avias.dax.models.CreateClusterRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateCluster", POST, "/", input)
  override def decreaseReplicationFactor(input: avias.dax.models.DecreaseReplicationFactorRequest): F[avias.dax.models.DecreaseReplicationFactorResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.DecreaseReplicationFactorResponse, avias.dax.models.DecreaseReplicationFactorRequest](client, awsData, ServiceType, ServiceAndPrefix, "DecreaseReplicationFactor", POST, "/", input)
  override def updateSubnetGroup(input: avias.dax.models.UpdateSubnetGroupRequest): F[avias.dax.models.UpdateSubnetGroupResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.dax.models.UpdateSubnetGroupResponse, avias.dax.models.UpdateSubnetGroupRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateSubnetGroup", POST, "/", input)
}