package org.lyranthe.araethura.opsworkscm.http4s
import org.http4s.Method._
import org.lyranthe.araethura.opsworkscm.circe._
import org.lyranthe.araethura.opsworkscm.models
class AmazonopsworkscmClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.opsworkscm.Amazonopsworkscm[F] {
  private[this] final val ServiceType: String = "opsworks-cm"
  private[this] final val ServiceAndPrefix: Option[String] = Some("OpsWorksCM_V2016_11_01")
  override def describeAccountAttributes: F[org.lyranthe.araethura.opsworkscm.models.DescribeAccountAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.DescribeAccountAttributesResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAccountAttributes", POST, "/", ())
  override def updateServer(input: org.lyranthe.araethura.opsworkscm.models.UpdateServerRequest): F[org.lyranthe.araethura.opsworkscm.models.UpdateServerResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.UpdateServerResponse, org.lyranthe.araethura.opsworkscm.models.UpdateServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateServer", POST, "/", input)
  override def startMaintenance(input: org.lyranthe.araethura.opsworkscm.models.StartMaintenanceRequest): F[org.lyranthe.araethura.opsworkscm.models.StartMaintenanceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.StartMaintenanceResponse, org.lyranthe.araethura.opsworkscm.models.StartMaintenanceRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartMaintenance", POST, "/", input)
  override def updateServerEngineAttributes(input: org.lyranthe.araethura.opsworkscm.models.UpdateServerEngineAttributesRequest): F[org.lyranthe.araethura.opsworkscm.models.UpdateServerEngineAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.UpdateServerEngineAttributesResponse, org.lyranthe.araethura.opsworkscm.models.UpdateServerEngineAttributesRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateServerEngineAttributes", POST, "/", input)
  override def createServer(input: org.lyranthe.araethura.opsworkscm.models.CreateServerRequest): F[org.lyranthe.araethura.opsworkscm.models.CreateServerResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.CreateServerResponse, org.lyranthe.araethura.opsworkscm.models.CreateServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateServer", POST, "/", input)
  override def describeServers(input: org.lyranthe.araethura.opsworkscm.models.DescribeServersRequest): F[org.lyranthe.araethura.opsworkscm.models.DescribeServersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.DescribeServersResponse, org.lyranthe.araethura.opsworkscm.models.DescribeServersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeServers", POST, "/", input)
  override def describeNodeAssociationStatus(input: org.lyranthe.araethura.opsworkscm.models.DescribeNodeAssociationStatusRequest): F[org.lyranthe.araethura.opsworkscm.models.DescribeNodeAssociationStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.DescribeNodeAssociationStatusResponse, org.lyranthe.araethura.opsworkscm.models.DescribeNodeAssociationStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeNodeAssociationStatus", POST, "/", input)
  override def describeBackups(input: org.lyranthe.araethura.opsworkscm.models.DescribeBackupsRequest): F[org.lyranthe.araethura.opsworkscm.models.DescribeBackupsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.DescribeBackupsResponse, org.lyranthe.araethura.opsworkscm.models.DescribeBackupsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBackups", POST, "/", input)
  override def describeEvents(input: org.lyranthe.araethura.opsworkscm.models.DescribeEventsRequest): F[org.lyranthe.araethura.opsworkscm.models.DescribeEventsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.DescribeEventsResponse, org.lyranthe.araethura.opsworkscm.models.DescribeEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEvents", POST, "/", input)
  override def createBackup(input: org.lyranthe.araethura.opsworkscm.models.CreateBackupRequest): F[org.lyranthe.araethura.opsworkscm.models.CreateBackupResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.CreateBackupResponse, org.lyranthe.araethura.opsworkscm.models.CreateBackupRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateBackup", POST, "/", input)
  override def deleteServer(input: org.lyranthe.araethura.opsworkscm.models.DeleteServerRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.opsworkscm.models.DeleteServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteServer", POST, "/", input)
  override def deleteBackup(input: org.lyranthe.araethura.opsworkscm.models.DeleteBackupRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.opsworkscm.models.DeleteBackupRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteBackup", POST, "/", input)
  override def associateNode(input: org.lyranthe.araethura.opsworkscm.models.AssociateNodeRequest): F[org.lyranthe.araethura.opsworkscm.models.AssociateNodeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.AssociateNodeResponse, org.lyranthe.araethura.opsworkscm.models.AssociateNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateNode", POST, "/", input)
  override def disassociateNode(input: org.lyranthe.araethura.opsworkscm.models.DisassociateNodeRequest): F[org.lyranthe.araethura.opsworkscm.models.DisassociateNodeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.opsworkscm.models.DisassociateNodeResponse, org.lyranthe.araethura.opsworkscm.models.DisassociateNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateNode", POST, "/", input)
  override def restoreServer(input: org.lyranthe.araethura.opsworkscm.models.RestoreServerRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.opsworkscm.models.RestoreServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "RestoreServer", POST, "/", input)
}