package org.lyranthe.araethura.opsworkscm.http4s
import org.http4s.Method._
import org.lyranthe.araethura.opsworkscm.circe._
import org.lyranthe.araethura.opsworkscm.models
class AmazonopsworkscmClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.opsworkscm.Amazonopsworkscm[F] {
  private[this] final val ServiceType: String = "opsworks-cm"
  private[this] final val ServiceAndPrefix: Option[String] = Some("OpsWorksCM_V2016_11_01")
  override def describeAccountAttributes: F[models.DescribeAccountAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeAccountAttributesResponse, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAccountAttributes", POST, "/", ())
  override def updateServer(input: models.UpdateServerRequest): F[models.UpdateServerResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateServerResponse, models.UpdateServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateServer", POST, "/", input)
  override def startMaintenance(input: models.StartMaintenanceRequest): F[models.StartMaintenanceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StartMaintenanceResponse, models.StartMaintenanceRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartMaintenance", POST, "/", input)
  override def updateServerEngineAttributes(input: models.UpdateServerEngineAttributesRequest): F[models.UpdateServerEngineAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateServerEngineAttributesResponse, models.UpdateServerEngineAttributesRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateServerEngineAttributes", POST, "/", input)
  override def createServer(input: models.CreateServerRequest): F[models.CreateServerResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateServerResponse, models.CreateServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateServer", POST, "/", input)
  override def describeServers(input: models.DescribeServersRequest): F[models.DescribeServersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeServersResponse, models.DescribeServersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeServers", POST, "/", input)
  override def describeNodeAssociationStatus(input: models.DescribeNodeAssociationStatusRequest): F[models.DescribeNodeAssociationStatusResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeNodeAssociationStatusResponse, models.DescribeNodeAssociationStatusRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeNodeAssociationStatus", POST, "/", input)
  override def describeBackups(input: models.DescribeBackupsRequest): F[models.DescribeBackupsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeBackupsResponse, models.DescribeBackupsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeBackups", POST, "/", input)
  override def describeEvents(input: models.DescribeEventsRequest): F[models.DescribeEventsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeEventsResponse, models.DescribeEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEvents", POST, "/", input)
  override def createBackup(input: models.CreateBackupRequest): F[models.CreateBackupResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateBackupResponse, models.CreateBackupRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateBackup", POST, "/", input)
  override def deleteServer(input: models.DeleteServerRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteServer", POST, "/", input)
  override def deleteBackup(input: models.DeleteBackupRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteBackupRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteBackup", POST, "/", input)
  override def associateNode(input: models.AssociateNodeRequest): F[models.AssociateNodeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.AssociateNodeResponse, models.AssociateNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateNode", POST, "/", input)
  override def disassociateNode(input: models.DisassociateNodeRequest): F[models.DisassociateNodeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DisassociateNodeResponse, models.DisassociateNodeRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateNode", POST, "/", input)
  override def restoreServer(input: models.RestoreServerRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.RestoreServerRequest](client, awsData, ServiceType, ServiceAndPrefix, "RestoreServer", POST, "/", input)
}