package org.lyranthe.araethura.kinesisanalytics.http4s
import org.http4s.Method._
import org.lyranthe.araethura.kinesisanalytics.circe._
import org.lyranthe.araethura.kinesisanalytics.models
class AmazonkinesisanalyticsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.kinesisanalytics.Amazonkinesisanalytics[F] {
  private[this] final val ServiceType: String = "kinesisanalytics"
  private[this] final val ServiceAndPrefix: Option[String] = Some("KinesisAnalytics_20150814")
  override def createApplication(input: models.CreateApplicationRequest): F[models.CreateApplicationResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateApplicationResponse, models.CreateApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateApplication", POST, "/", input)
  override def deleteApplicationInputProcessingConfiguration(input: models.DeleteApplicationInputProcessingConfigurationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteApplicationInputProcessingConfigurationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplicationInputProcessingConfiguration", POST, "/", input)
  override def deleteApplicationOutput(input: models.DeleteApplicationOutputRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteApplicationOutputRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplicationOutput", POST, "/", input)
  override def deleteApplicationReferenceDataSource(input: models.DeleteApplicationReferenceDataSourceRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteApplicationReferenceDataSourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplicationReferenceDataSource", POST, "/", input)
  override def listApplications(input: models.ListApplicationsRequest): F[models.ListApplicationsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListApplicationsResponse, models.ListApplicationsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListApplications", POST, "/", input)
  override def deleteApplication(input: models.DeleteApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplication", POST, "/", input)
  override def stopApplication(input: models.StopApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.StopApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopApplication", POST, "/", input)
  override def addApplicationOutput(input: models.AddApplicationOutputRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddApplicationOutputRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddApplicationOutput", POST, "/", input)
  override def addApplicationReferenceDataSource(input: models.AddApplicationReferenceDataSourceRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddApplicationReferenceDataSourceRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddApplicationReferenceDataSource", POST, "/", input)
  override def updateApplication(input: models.UpdateApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.UpdateApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateApplication", POST, "/", input)
  override def describeApplication(input: models.DescribeApplicationRequest): F[models.DescribeApplicationResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeApplicationResponse, models.DescribeApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeApplication", POST, "/", input)
  override def addApplicationInputProcessingConfiguration(input: models.AddApplicationInputProcessingConfigurationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddApplicationInputProcessingConfigurationRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddApplicationInputProcessingConfiguration", POST, "/", input)
  override def deleteApplicationCloudWatchLoggingOption(input: models.DeleteApplicationCloudWatchLoggingOptionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.DeleteApplicationCloudWatchLoggingOptionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteApplicationCloudWatchLoggingOption", POST, "/", input)
  override def startApplication(input: models.StartApplicationRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.StartApplicationRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartApplication", POST, "/", input)
  override def discoverInputSchema(input: models.DiscoverInputSchemaRequest): F[models.DiscoverInputSchemaResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DiscoverInputSchemaResponse, models.DiscoverInputSchemaRequest](client, awsData, ServiceType, ServiceAndPrefix, "DiscoverInputSchema", POST, "/", input)
  override def addApplicationInput(input: models.AddApplicationInputRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddApplicationInputRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddApplicationInput", POST, "/", input)
  override def addApplicationCloudWatchLoggingOption(input: models.AddApplicationCloudWatchLoggingOptionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, models.AddApplicationCloudWatchLoggingOptionRequest](client, awsData, ServiceType, ServiceAndPrefix, "AddApplicationCloudWatchLoggingOption", POST, "/", input)
}