package avias.dms
trait Amazondms[F[_]] {
  def describeTableStatistics(input: avias.dms.models.DescribeTableStatisticsMessage): F[avias.dms.models.DescribeTableStatisticsResponse]
  def modifyEventSubscription(input: avias.dms.models.ModifyEventSubscriptionMessage): F[avias.dms.models.ModifyEventSubscriptionResponse]
  def describeReplicationInstances(input: avias.dms.models.DescribeReplicationInstancesMessage): F[avias.dms.models.DescribeReplicationInstancesResponse]
  def describeCertificates(input: avias.dms.models.DescribeCertificatesMessage): F[avias.dms.models.DescribeCertificatesResponse]
  def deleteCertificate(input: avias.dms.models.DeleteCertificateMessage): F[avias.dms.models.DeleteCertificateResponse]
  def stopReplicationTask(input: avias.dms.models.StopReplicationTaskMessage): F[avias.dms.models.StopReplicationTaskResponse]
  def describeEndpointTypes(input: avias.dms.models.DescribeEndpointTypesMessage): F[avias.dms.models.DescribeEndpointTypesResponse]
  def startReplicationTaskAssessment(input: avias.dms.models.StartReplicationTaskAssessmentMessage): F[avias.dms.models.StartReplicationTaskAssessmentResponse]
  def modifyReplicationTask(input: avias.dms.models.ModifyReplicationTaskMessage): F[avias.dms.models.ModifyReplicationTaskResponse]
  def deleteReplicationTask(input: avias.dms.models.DeleteReplicationTaskMessage): F[avias.dms.models.DeleteReplicationTaskResponse]
  def startReplicationTask(input: avias.dms.models.StartReplicationTaskMessage): F[avias.dms.models.StartReplicationTaskResponse]
  def createReplicationInstance(input: avias.dms.models.CreateReplicationInstanceMessage): F[avias.dms.models.CreateReplicationInstanceResponse]
  def describeEventCategories(input: avias.dms.models.DescribeEventCategoriesMessage): F[avias.dms.models.DescribeEventCategoriesResponse]
  def deleteEventSubscription(input: avias.dms.models.DeleteEventSubscriptionMessage): F[avias.dms.models.DeleteEventSubscriptionResponse]
  def testConnection(input: avias.dms.models.TestConnectionMessage): F[avias.dms.models.TestConnectionResponse]
  def describeConnections(input: avias.dms.models.DescribeConnectionsMessage): F[avias.dms.models.DescribeConnectionsResponse]
  def listTagsForResource(input: avias.dms.models.ListTagsForResourceMessage): F[avias.dms.models.ListTagsForResourceResponse]
  def createEventSubscription(input: avias.dms.models.CreateEventSubscriptionMessage): F[avias.dms.models.CreateEventSubscriptionResponse]
  def describeOrderableReplicationInstances(input: avias.dms.models.DescribeOrderableReplicationInstancesMessage): F[avias.dms.models.DescribeOrderableReplicationInstancesResponse]
  def describeReplicationTasks(input: avias.dms.models.DescribeReplicationTasksMessage): F[avias.dms.models.DescribeReplicationTasksResponse]
  def modifyReplicationSubnetGroup(input: avias.dms.models.ModifyReplicationSubnetGroupMessage): F[avias.dms.models.ModifyReplicationSubnetGroupResponse]
  def describeReplicationTaskAssessmentResults(input: avias.dms.models.DescribeReplicationTaskAssessmentResultsMessage): F[avias.dms.models.DescribeReplicationTaskAssessmentResultsResponse]
  def describeReplicationSubnetGroups(input: avias.dms.models.DescribeReplicationSubnetGroupsMessage): F[avias.dms.models.DescribeReplicationSubnetGroupsResponse]
  def deleteReplicationInstance(input: avias.dms.models.DeleteReplicationInstanceMessage): F[avias.dms.models.DeleteReplicationInstanceResponse]
  def createReplicationSubnetGroup(input: avias.dms.models.CreateReplicationSubnetGroupMessage): F[avias.dms.models.CreateReplicationSubnetGroupResponse]
  def createReplicationTask(input: avias.dms.models.CreateReplicationTaskMessage): F[avias.dms.models.CreateReplicationTaskResponse]
  def addTagsToResource(input: avias.dms.models.AddTagsToResourceMessage): F[scala.Unit]
  def describeEndpoints(input: avias.dms.models.DescribeEndpointsMessage): F[avias.dms.models.DescribeEndpointsResponse]
  def removeTagsFromResource(input: avias.dms.models.RemoveTagsFromResourceMessage): F[scala.Unit]
  def importCertificate(input: avias.dms.models.ImportCertificateMessage): F[avias.dms.models.ImportCertificateResponse]
  def modifyEndpoint(input: avias.dms.models.ModifyEndpointMessage): F[avias.dms.models.ModifyEndpointResponse]
  def describeEventSubscriptions(input: avias.dms.models.DescribeEventSubscriptionsMessage): F[avias.dms.models.DescribeEventSubscriptionsResponse]
  def deleteReplicationSubnetGroup(input: avias.dms.models.DeleteReplicationSubnetGroupMessage): F[scala.Unit]
  def describeEvents(input: avias.dms.models.DescribeEventsMessage): F[avias.dms.models.DescribeEventsResponse]
  def describeRefreshSchemasStatus(input: avias.dms.models.DescribeRefreshSchemasStatusMessage): F[avias.dms.models.DescribeRefreshSchemasStatusResponse]
  def describeAccountAttributes: F[avias.dms.models.DescribeAccountAttributesResponse]
  def refreshSchemas(input: avias.dms.models.RefreshSchemasMessage): F[avias.dms.models.RefreshSchemasResponse]
  def reloadTables(input: avias.dms.models.ReloadTablesMessage): F[avias.dms.models.ReloadTablesResponse]
  def deleteEndpoint(input: avias.dms.models.DeleteEndpointMessage): F[avias.dms.models.DeleteEndpointResponse]
  def createEndpoint(input: avias.dms.models.CreateEndpointMessage): F[avias.dms.models.CreateEndpointResponse]
  def modifyReplicationInstance(input: avias.dms.models.ModifyReplicationInstanceMessage): F[avias.dms.models.ModifyReplicationInstanceResponse]
  def describeSchemas(input: avias.dms.models.DescribeSchemasMessage): F[avias.dms.models.DescribeSchemasResponse]
}