package org.lyranthe.araethura.rekognition.http4s
import org.http4s.Method._
import org.lyranthe.araethura.rekognition.circe._
import org.lyranthe.araethura.rekognition.models
class AmazonrekognitionClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.rekognition.Amazonrekognition[F] {
  private[this] final val ServiceType: String = "rekognition"
  private[this] final val ServiceAndPrefix: Option[String] = Some("RekognitionService")
  override def detectFaces(input: models.DetectFacesRequest): F[models.DetectFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DetectFacesResponse, models.DetectFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DetectFaces", POST, "/", input)
  override def indexFaces(input: models.IndexFacesRequest): F[models.IndexFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.IndexFacesResponse, models.IndexFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "IndexFaces", POST, "/", input)
  override def searchFaces(input: models.SearchFacesRequest): F[models.SearchFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.SearchFacesResponse, models.SearchFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "SearchFaces", POST, "/", input)
  override def recognizeCelebrities(input: models.RecognizeCelebritiesRequest): F[models.RecognizeCelebritiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RecognizeCelebritiesResponse, models.RecognizeCelebritiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RecognizeCelebrities", POST, "/", input)
  override def detectLabels(input: models.DetectLabelsRequest): F[models.DetectLabelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DetectLabelsResponse, models.DetectLabelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DetectLabels", POST, "/", input)
  override def deleteFaces(input: models.DeleteFacesRequest): F[models.DeleteFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteFacesResponse, models.DeleteFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteFaces", POST, "/", input)
  override def deleteCollection(input: models.DeleteCollectionRequest): F[models.DeleteCollectionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteCollectionResponse, models.DeleteCollectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteCollection", POST, "/", input)
  override def listCollections(input: models.ListCollectionsRequest): F[models.ListCollectionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListCollectionsResponse, models.ListCollectionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListCollections", POST, "/", input)
  override def getCelebrityInfo(input: models.GetCelebrityInfoRequest): F[models.GetCelebrityInfoResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetCelebrityInfoResponse, models.GetCelebrityInfoRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetCelebrityInfo", POST, "/", input)
  override def detectModerationLabels(input: models.DetectModerationLabelsRequest): F[models.DetectModerationLabelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DetectModerationLabelsResponse, models.DetectModerationLabelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DetectModerationLabels", POST, "/", input)
  override def compareFaces(input: models.CompareFacesRequest): F[models.CompareFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CompareFacesResponse, models.CompareFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "CompareFaces", POST, "/", input)
  override def listFaces(input: models.ListFacesRequest): F[models.ListFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListFacesResponse, models.ListFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListFaces", POST, "/", input)
  override def searchFacesByImage(input: models.SearchFacesByImageRequest): F[models.SearchFacesByImageResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.SearchFacesByImageResponse, models.SearchFacesByImageRequest](client, awsData, ServiceType, ServiceAndPrefix, "SearchFacesByImage", POST, "/", input)
  override def createCollection(input: models.CreateCollectionRequest): F[models.CreateCollectionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateCollectionResponse, models.CreateCollectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateCollection", POST, "/", input)
}