package org.lyranthe.araethura.rekognition.http4s
import org.http4s.Method._
import org.lyranthe.araethura.rekognition.circe._
import org.lyranthe.araethura.rekognition.models
class AmazonrekognitionClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.rekognition.Amazonrekognition[F] {
  private[this] final val ServiceType: String = "rekognition"
  private[this] final val ServiceAndPrefix: Option[String] = Some("RekognitionService")
  override def detectFaces(input: org.lyranthe.araethura.rekognition.models.DetectFacesRequest): F[org.lyranthe.araethura.rekognition.models.DetectFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.DetectFacesResponse, org.lyranthe.araethura.rekognition.models.DetectFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DetectFaces", POST, "/", input)
  override def indexFaces(input: org.lyranthe.araethura.rekognition.models.IndexFacesRequest): F[org.lyranthe.araethura.rekognition.models.IndexFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.IndexFacesResponse, org.lyranthe.araethura.rekognition.models.IndexFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "IndexFaces", POST, "/", input)
  override def searchFaces(input: org.lyranthe.araethura.rekognition.models.SearchFacesRequest): F[org.lyranthe.araethura.rekognition.models.SearchFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.SearchFacesResponse, org.lyranthe.araethura.rekognition.models.SearchFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "SearchFaces", POST, "/", input)
  override def recognizeCelebrities(input: org.lyranthe.araethura.rekognition.models.RecognizeCelebritiesRequest): F[org.lyranthe.araethura.rekognition.models.RecognizeCelebritiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.RecognizeCelebritiesResponse, org.lyranthe.araethura.rekognition.models.RecognizeCelebritiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "RecognizeCelebrities", POST, "/", input)
  override def detectLabels(input: org.lyranthe.araethura.rekognition.models.DetectLabelsRequest): F[org.lyranthe.araethura.rekognition.models.DetectLabelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.DetectLabelsResponse, org.lyranthe.araethura.rekognition.models.DetectLabelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DetectLabels", POST, "/", input)
  override def deleteFaces(input: org.lyranthe.araethura.rekognition.models.DeleteFacesRequest): F[org.lyranthe.araethura.rekognition.models.DeleteFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.DeleteFacesResponse, org.lyranthe.araethura.rekognition.models.DeleteFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteFaces", POST, "/", input)
  override def deleteCollection(input: org.lyranthe.araethura.rekognition.models.DeleteCollectionRequest): F[org.lyranthe.araethura.rekognition.models.DeleteCollectionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.DeleteCollectionResponse, org.lyranthe.araethura.rekognition.models.DeleteCollectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteCollection", POST, "/", input)
  override def listCollections(input: org.lyranthe.araethura.rekognition.models.ListCollectionsRequest): F[org.lyranthe.araethura.rekognition.models.ListCollectionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.ListCollectionsResponse, org.lyranthe.araethura.rekognition.models.ListCollectionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListCollections", POST, "/", input)
  override def getCelebrityInfo(input: org.lyranthe.araethura.rekognition.models.GetCelebrityInfoRequest): F[org.lyranthe.araethura.rekognition.models.GetCelebrityInfoResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.GetCelebrityInfoResponse, org.lyranthe.araethura.rekognition.models.GetCelebrityInfoRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetCelebrityInfo", POST, "/", input)
  override def detectModerationLabels(input: org.lyranthe.araethura.rekognition.models.DetectModerationLabelsRequest): F[org.lyranthe.araethura.rekognition.models.DetectModerationLabelsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.DetectModerationLabelsResponse, org.lyranthe.araethura.rekognition.models.DetectModerationLabelsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DetectModerationLabels", POST, "/", input)
  override def compareFaces(input: org.lyranthe.araethura.rekognition.models.CompareFacesRequest): F[org.lyranthe.araethura.rekognition.models.CompareFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.CompareFacesResponse, org.lyranthe.araethura.rekognition.models.CompareFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "CompareFaces", POST, "/", input)
  override def listFaces(input: org.lyranthe.araethura.rekognition.models.ListFacesRequest): F[org.lyranthe.araethura.rekognition.models.ListFacesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.ListFacesResponse, org.lyranthe.araethura.rekognition.models.ListFacesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListFaces", POST, "/", input)
  override def searchFacesByImage(input: org.lyranthe.araethura.rekognition.models.SearchFacesByImageRequest): F[org.lyranthe.araethura.rekognition.models.SearchFacesByImageResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.SearchFacesByImageResponse, org.lyranthe.araethura.rekognition.models.SearchFacesByImageRequest](client, awsData, ServiceType, ServiceAndPrefix, "SearchFacesByImage", POST, "/", input)
  override def createCollection(input: org.lyranthe.araethura.rekognition.models.CreateCollectionRequest): F[org.lyranthe.araethura.rekognition.models.CreateCollectionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.rekognition.models.CreateCollectionResponse, org.lyranthe.araethura.rekognition.models.CreateCollectionRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateCollection", POST, "/", input)
}