package org.lyranthe.araethura.health.http4s
import org.http4s.Method._
import org.lyranthe.araethura.health.circe._
import org.lyranthe.araethura.health.models
class AmazonhealthClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.health.Amazonhealth[F] {
  private[this] final val ServiceType: String = "health"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSHealth_20160804")
  override def describeEventDetails(input: org.lyranthe.araethura.health.models.DescribeEventDetailsRequest): F[org.lyranthe.araethura.health.models.DescribeEventDetailsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.health.models.DescribeEventDetailsResponse, org.lyranthe.araethura.health.models.DescribeEventDetailsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEventDetails", POST, "/", input)
  override def describeEntityAggregates(input: org.lyranthe.araethura.health.models.DescribeEntityAggregatesRequest): F[org.lyranthe.araethura.health.models.DescribeEntityAggregatesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.health.models.DescribeEntityAggregatesResponse, org.lyranthe.araethura.health.models.DescribeEntityAggregatesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEntityAggregates", POST, "/", input)
  override def describeEventAggregates(input: org.lyranthe.araethura.health.models.DescribeEventAggregatesRequest): F[org.lyranthe.araethura.health.models.DescribeEventAggregatesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.health.models.DescribeEventAggregatesResponse, org.lyranthe.araethura.health.models.DescribeEventAggregatesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEventAggregates", POST, "/", input)
  override def describeAffectedEntities(input: org.lyranthe.araethura.health.models.DescribeAffectedEntitiesRequest): F[org.lyranthe.araethura.health.models.DescribeAffectedEntitiesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.health.models.DescribeAffectedEntitiesResponse, org.lyranthe.araethura.health.models.DescribeAffectedEntitiesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeAffectedEntities", POST, "/", input)
  override def describeEventTypes(input: org.lyranthe.araethura.health.models.DescribeEventTypesRequest): F[org.lyranthe.araethura.health.models.DescribeEventTypesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.health.models.DescribeEventTypesResponse, org.lyranthe.araethura.health.models.DescribeEventTypesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEventTypes", POST, "/", input)
  override def describeEvents(input: org.lyranthe.araethura.health.models.DescribeEventsRequest): F[org.lyranthe.araethura.health.models.DescribeEventsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.health.models.DescribeEventsResponse, org.lyranthe.araethura.health.models.DescribeEventsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeEvents", POST, "/", input)
}