package avias.simpleworkflow.http4s
import org.http4s.Method._
import avias.simpleworkflow.circe._
import avias.simpleworkflow.models
import avias.common.http4s.ClientUtils._
class AmazonsimpleworkflowClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.simpleworkflow.Amazonsimpleworkflow[F] {
  private[this] final val ServiceType: String = "swf"
  private[this] final val ServiceAndPrefix: Option[String] = Some("SimpleWorkflowService")
  override def countClosedWorkflowExecutions(input: avias.simpleworkflow.models.CountClosedWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionCount] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowExecutionCount, avias.simpleworkflow.models.CountClosedWorkflowExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "CountClosedWorkflowExecutions", POST, "/", input)
  override def listClosedWorkflowExecutions(input: avias.simpleworkflow.models.ListClosedWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionInfos] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowExecutionInfos, avias.simpleworkflow.models.ListClosedWorkflowExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListClosedWorkflowExecutions", POST, "/", input)
  override def deprecateActivityType(input: avias.simpleworkflow.models.DeprecateActivityTypeInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.DeprecateActivityTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "DeprecateActivityType", POST, "/", input)
  override def registerWorkflowType(input: avias.simpleworkflow.models.RegisterWorkflowTypeInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RegisterWorkflowTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "RegisterWorkflowType", POST, "/", input)
  override def listDomains(input: avias.simpleworkflow.models.ListDomainsInput): F[avias.simpleworkflow.models.DomainInfos] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.DomainInfos, avias.simpleworkflow.models.ListDomainsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListDomains", POST, "/", input)
  override def respondActivityTaskFailed(input: avias.simpleworkflow.models.RespondActivityTaskFailedInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RespondActivityTaskFailedInput](client, awsData, ServiceType, ServiceAndPrefix, "RespondActivityTaskFailed", POST, "/", input)
  override def listWorkflowTypes(input: avias.simpleworkflow.models.ListWorkflowTypesInput): F[avias.simpleworkflow.models.WorkflowTypeInfos] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowTypeInfos, avias.simpleworkflow.models.ListWorkflowTypesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListWorkflowTypes", POST, "/", input)
  override def describeWorkflowType(input: avias.simpleworkflow.models.DescribeWorkflowTypeInput): F[avias.simpleworkflow.models.WorkflowTypeDetail] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowTypeDetail, avias.simpleworkflow.models.DescribeWorkflowTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkflowType", POST, "/", input)
  override def listActivityTypes(input: avias.simpleworkflow.models.ListActivityTypesInput): F[avias.simpleworkflow.models.ActivityTypeInfos] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.ActivityTypeInfos, avias.simpleworkflow.models.ListActivityTypesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListActivityTypes", POST, "/", input)
  override def countPendingActivityTasks(input: avias.simpleworkflow.models.CountPendingActivityTasksInput): F[avias.simpleworkflow.models.PendingTaskCount] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.PendingTaskCount, avias.simpleworkflow.models.CountPendingActivityTasksInput](client, awsData, ServiceType, ServiceAndPrefix, "CountPendingActivityTasks", POST, "/", input)
  override def startWorkflowExecution(input: avias.simpleworkflow.models.StartWorkflowExecutionInput): F[avias.simpleworkflow.models.Run] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.Run, avias.simpleworkflow.models.StartWorkflowExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartWorkflowExecution", POST, "/", input)
  override def registerDomain(input: avias.simpleworkflow.models.RegisterDomainInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RegisterDomainInput](client, awsData, ServiceType, ServiceAndPrefix, "RegisterDomain", POST, "/", input)
  override def recordActivityTaskHeartbeat(input: avias.simpleworkflow.models.RecordActivityTaskHeartbeatInput): F[avias.simpleworkflow.models.ActivityTaskStatus] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.ActivityTaskStatus, avias.simpleworkflow.models.RecordActivityTaskHeartbeatInput](client, awsData, ServiceType, ServiceAndPrefix, "RecordActivityTaskHeartbeat", POST, "/", input)
  override def describeActivityType(input: avias.simpleworkflow.models.DescribeActivityTypeInput): F[avias.simpleworkflow.models.ActivityTypeDetail] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.ActivityTypeDetail, avias.simpleworkflow.models.DescribeActivityTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeActivityType", POST, "/", input)
  override def getWorkflowExecutionHistory(input: avias.simpleworkflow.models.GetWorkflowExecutionHistoryInput): F[avias.simpleworkflow.models.History] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.History, avias.simpleworkflow.models.GetWorkflowExecutionHistoryInput](client, awsData, ServiceType, ServiceAndPrefix, "GetWorkflowExecutionHistory", POST, "/", input)
  override def pollForDecisionTask(input: avias.simpleworkflow.models.PollForDecisionTaskInput): F[avias.simpleworkflow.models.DecisionTask] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.DecisionTask, avias.simpleworkflow.models.PollForDecisionTaskInput](client, awsData, ServiceType, ServiceAndPrefix, "PollForDecisionTask", POST, "/", input)
  override def countOpenWorkflowExecutions(input: avias.simpleworkflow.models.CountOpenWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionCount] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowExecutionCount, avias.simpleworkflow.models.CountOpenWorkflowExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "CountOpenWorkflowExecutions", POST, "/", input)
  override def listOpenWorkflowExecutions(input: avias.simpleworkflow.models.ListOpenWorkflowExecutionsInput): F[avias.simpleworkflow.models.WorkflowExecutionInfos] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowExecutionInfos, avias.simpleworkflow.models.ListOpenWorkflowExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListOpenWorkflowExecutions", POST, "/", input)
  override def pollForActivityTask(input: avias.simpleworkflow.models.PollForActivityTaskInput): F[avias.simpleworkflow.models.ActivityTask] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.ActivityTask, avias.simpleworkflow.models.PollForActivityTaskInput](client, awsData, ServiceType, ServiceAndPrefix, "PollForActivityTask", POST, "/", input)
  override def terminateWorkflowExecution(input: avias.simpleworkflow.models.TerminateWorkflowExecutionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.TerminateWorkflowExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "TerminateWorkflowExecution", POST, "/", input)
  override def describeDomain(input: avias.simpleworkflow.models.DescribeDomainInput): F[avias.simpleworkflow.models.DomainDetail] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.DomainDetail, avias.simpleworkflow.models.DescribeDomainInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDomain", POST, "/", input)
  override def respondDecisionTaskCompleted(input: avias.simpleworkflow.models.RespondDecisionTaskCompletedInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RespondDecisionTaskCompletedInput](client, awsData, ServiceType, ServiceAndPrefix, "RespondDecisionTaskCompleted", POST, "/", input)
  override def deprecateWorkflowType(input: avias.simpleworkflow.models.DeprecateWorkflowTypeInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.DeprecateWorkflowTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "DeprecateWorkflowType", POST, "/", input)
  override def signalWorkflowExecution(input: avias.simpleworkflow.models.SignalWorkflowExecutionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.SignalWorkflowExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "SignalWorkflowExecution", POST, "/", input)
  override def describeWorkflowExecution(input: avias.simpleworkflow.models.DescribeWorkflowExecutionInput): F[avias.simpleworkflow.models.WorkflowExecutionDetail] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.WorkflowExecutionDetail, avias.simpleworkflow.models.DescribeWorkflowExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeWorkflowExecution", POST, "/", input)
  override def respondActivityTaskCompleted(input: avias.simpleworkflow.models.RespondActivityTaskCompletedInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RespondActivityTaskCompletedInput](client, awsData, ServiceType, ServiceAndPrefix, "RespondActivityTaskCompleted", POST, "/", input)
  override def countPendingDecisionTasks(input: avias.simpleworkflow.models.CountPendingDecisionTasksInput): F[avias.simpleworkflow.models.PendingTaskCount] = avias.common.http4s.ClientUtils.doRequest[F, avias.simpleworkflow.models.PendingTaskCount, avias.simpleworkflow.models.CountPendingDecisionTasksInput](client, awsData, ServiceType, ServiceAndPrefix, "CountPendingDecisionTasks", POST, "/", input)
  override def registerActivityType(input: avias.simpleworkflow.models.RegisterActivityTypeInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RegisterActivityTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "RegisterActivityType", POST, "/", input)
  override def respondActivityTaskCanceled(input: avias.simpleworkflow.models.RespondActivityTaskCanceledInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RespondActivityTaskCanceledInput](client, awsData, ServiceType, ServiceAndPrefix, "RespondActivityTaskCanceled", POST, "/", input)
  override def deprecateDomain(input: avias.simpleworkflow.models.DeprecateDomainInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.DeprecateDomainInput](client, awsData, ServiceType, ServiceAndPrefix, "DeprecateDomain", POST, "/", input)
  override def requestCancelWorkflowExecution(input: avias.simpleworkflow.models.RequestCancelWorkflowExecutionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.simpleworkflow.models.RequestCancelWorkflowExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "RequestCancelWorkflowExecution", POST, "/", input)
}