package org.lyranthe.araethura.servermigration.http4s
import org.http4s.Method._
import org.lyranthe.araethura.servermigration.circe._
import org.lyranthe.araethura.servermigration.models
class AmazonservermigrationClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.servermigration.Amazonservermigration[F] {
  private[this] final val ServiceType: String = "sms"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSServerMigrationService_V2016_10_24")
  override def getReplicationRuns(input: org.lyranthe.araethura.servermigration.models.GetReplicationRunsRequest): F[org.lyranthe.araethura.servermigration.models.GetReplicationRunsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.servermigration.models.GetReplicationRunsResponse, org.lyranthe.araethura.servermigration.models.GetReplicationRunsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetReplicationRuns", POST, "/", input)
  override def updateReplicationJob(input: org.lyranthe.araethura.servermigration.models.UpdateReplicationJobRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.servermigration.models.UpdateReplicationJobRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateReplicationJob", POST, "/", input)
  override def getServers(input: org.lyranthe.araethura.servermigration.models.GetServersRequest): F[org.lyranthe.araethura.servermigration.models.GetServersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.servermigration.models.GetServersResponse, org.lyranthe.araethura.servermigration.models.GetServersRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetServers", POST, "/", input)
  override def getConnectors(input: org.lyranthe.araethura.servermigration.models.GetConnectorsRequest): F[org.lyranthe.araethura.servermigration.models.GetConnectorsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.servermigration.models.GetConnectorsResponse, org.lyranthe.araethura.servermigration.models.GetConnectorsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetConnectors", POST, "/", input)
  override def startOnDemandReplicationRun(input: org.lyranthe.araethura.servermigration.models.StartOnDemandReplicationRunRequest): F[org.lyranthe.araethura.servermigration.models.StartOnDemandReplicationRunResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.servermigration.models.StartOnDemandReplicationRunResponse, org.lyranthe.araethura.servermigration.models.StartOnDemandReplicationRunRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartOnDemandReplicationRun", POST, "/", input)
  override def deleteReplicationJob(input: org.lyranthe.araethura.servermigration.models.DeleteReplicationJobRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.servermigration.models.DeleteReplicationJobRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteReplicationJob", POST, "/", input)
  override def disassociateConnector(input: org.lyranthe.araethura.servermigration.models.DisassociateConnectorRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.servermigration.models.DisassociateConnectorRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateConnector", POST, "/", input)
  override def getReplicationJobs(input: org.lyranthe.araethura.servermigration.models.GetReplicationJobsRequest): F[org.lyranthe.araethura.servermigration.models.GetReplicationJobsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.servermigration.models.GetReplicationJobsResponse, org.lyranthe.araethura.servermigration.models.GetReplicationJobsRequest](client, awsData, ServiceType, ServiceAndPrefix, "GetReplicationJobs", POST, "/", input)
  override def deleteServerCatalog: F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DeleteServerCatalog", POST, "/", ())
  override def importServerCatalog: F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "ImportServerCatalog", POST, "/", ())
  override def createReplicationJob(input: org.lyranthe.araethura.servermigration.models.CreateReplicationJobRequest): F[org.lyranthe.araethura.servermigration.models.CreateReplicationJobResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.servermigration.models.CreateReplicationJobResponse, org.lyranthe.araethura.servermigration.models.CreateReplicationJobRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateReplicationJob", POST, "/", input)
}