package avias.stepfunctions.http4s
import org.http4s.Method._
import avias.stepfunctions.circe._
import avias.stepfunctions.models
import avias.common.http4s.ClientUtils._
class AmazonstepfunctionsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.stepfunctions.Amazonstepfunctions[F] {
  private[this] final val ServiceType: String = "states"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSStepFunctions")
  override def listStateMachines(input: avias.stepfunctions.models.ListStateMachinesInput): F[avias.stepfunctions.models.ListStateMachinesOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.ListStateMachinesOutput, avias.stepfunctions.models.ListStateMachinesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListStateMachines", POST, "/", input)
  override def createActivity(input: avias.stepfunctions.models.CreateActivityInput): F[avias.stepfunctions.models.CreateActivityOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.CreateActivityOutput, avias.stepfunctions.models.CreateActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateActivity", POST, "/", input)
  override def startExecution(input: avias.stepfunctions.models.StartExecutionInput): F[avias.stepfunctions.models.StartExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.StartExecutionOutput, avias.stepfunctions.models.StartExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartExecution", POST, "/", input)
  override def sendTaskFailure(input: avias.stepfunctions.models.SendTaskFailureInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.stepfunctions.models.SendTaskFailureInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskFailure", POST, "/", input)
  override def describeActivity(input: avias.stepfunctions.models.DescribeActivityInput): F[avias.stepfunctions.models.DescribeActivityOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.DescribeActivityOutput, avias.stepfunctions.models.DescribeActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeActivity", POST, "/", input)
  override def stopExecution(input: avias.stepfunctions.models.StopExecutionInput): F[avias.stepfunctions.models.StopExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.StopExecutionOutput, avias.stepfunctions.models.StopExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopExecution", POST, "/", input)
  override def deleteActivity(input: avias.stepfunctions.models.DeleteActivityInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.stepfunctions.models.DeleteActivityInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteActivity", POST, "/", input)
  override def describeStateMachineForExecution(input: avias.stepfunctions.models.DescribeStateMachineForExecutionInput): F[avias.stepfunctions.models.DescribeStateMachineForExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.DescribeStateMachineForExecutionOutput, avias.stepfunctions.models.DescribeStateMachineForExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStateMachineForExecution", POST, "/", input)
  override def getExecutionHistory(input: avias.stepfunctions.models.GetExecutionHistoryInput): F[avias.stepfunctions.models.GetExecutionHistoryOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.GetExecutionHistoryOutput, avias.stepfunctions.models.GetExecutionHistoryInput](client, awsData, ServiceType, ServiceAndPrefix, "GetExecutionHistory", POST, "/", input)
  override def listActivities(input: avias.stepfunctions.models.ListActivitiesInput): F[avias.stepfunctions.models.ListActivitiesOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.ListActivitiesOutput, avias.stepfunctions.models.ListActivitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListActivities", POST, "/", input)
  override def deleteStateMachine(input: avias.stepfunctions.models.DeleteStateMachineInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.stepfunctions.models.DeleteStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteStateMachine", POST, "/", input)
  override def updateStateMachine(input: avias.stepfunctions.models.UpdateStateMachineInput): F[avias.stepfunctions.models.UpdateStateMachineOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.UpdateStateMachineOutput, avias.stepfunctions.models.UpdateStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateStateMachine", POST, "/", input)
  override def createStateMachine(input: avias.stepfunctions.models.CreateStateMachineInput): F[avias.stepfunctions.models.CreateStateMachineOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.CreateStateMachineOutput, avias.stepfunctions.models.CreateStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateStateMachine", POST, "/", input)
  override def getActivityTask(input: avias.stepfunctions.models.GetActivityTaskInput): F[avias.stepfunctions.models.GetActivityTaskOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.GetActivityTaskOutput, avias.stepfunctions.models.GetActivityTaskInput](client, awsData, ServiceType, ServiceAndPrefix, "GetActivityTask", POST, "/", input)
  override def sendTaskHeartbeat(input: avias.stepfunctions.models.SendTaskHeartbeatInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.stepfunctions.models.SendTaskHeartbeatInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskHeartbeat", POST, "/", input)
  override def listExecutions(input: avias.stepfunctions.models.ListExecutionsInput): F[avias.stepfunctions.models.ListExecutionsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.ListExecutionsOutput, avias.stepfunctions.models.ListExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListExecutions", POST, "/", input)
  override def sendTaskSuccess(input: avias.stepfunctions.models.SendTaskSuccessInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.stepfunctions.models.SendTaskSuccessInput](client, awsData, ServiceType, ServiceAndPrefix, "SendTaskSuccess", POST, "/", input)
  override def describeStateMachine(input: avias.stepfunctions.models.DescribeStateMachineInput): F[avias.stepfunctions.models.DescribeStateMachineOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.DescribeStateMachineOutput, avias.stepfunctions.models.DescribeStateMachineInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStateMachine", POST, "/", input)
  override def describeExecution(input: avias.stepfunctions.models.DescribeExecutionInput): F[avias.stepfunctions.models.DescribeExecutionOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.stepfunctions.models.DescribeExecutionOutput, avias.stepfunctions.models.DescribeExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeExecution", POST, "/", input)
}