package avias.kinesisfirehose.http4s
import org.http4s.Method._
import avias.kinesisfirehose.circe._
import avias.kinesisfirehose.models
class AmazonkinesisfirehoseClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.kinesisfirehose.Amazonkinesisfirehose[F] {
  private[this] final val ServiceType: String = "firehose"
  private[this] final val ServiceAndPrefix: Option[String] = Some("Firehose_20150804")
  override def updateDestination(input: avias.kinesisfirehose.models.UpdateDestinationInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesisfirehose.models.UpdateDestinationInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDestination", POST, "/", input)
  override def describeDeliveryStream(input: avias.kinesisfirehose.models.DescribeDeliveryStreamInput): F[avias.kinesisfirehose.models.DescribeDeliveryStreamOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesisfirehose.models.DescribeDeliveryStreamOutput, avias.kinesisfirehose.models.DescribeDeliveryStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDeliveryStream", POST, "/", input)
  override def putRecord(input: avias.kinesisfirehose.models.PutRecordInput): F[avias.kinesisfirehose.models.PutRecordOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesisfirehose.models.PutRecordOutput, avias.kinesisfirehose.models.PutRecordInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecord", POST, "/", input)
  override def listDeliveryStreams(input: avias.kinesisfirehose.models.ListDeliveryStreamsInput): F[avias.kinesisfirehose.models.ListDeliveryStreamsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesisfirehose.models.ListDeliveryStreamsOutput, avias.kinesisfirehose.models.ListDeliveryStreamsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListDeliveryStreams", POST, "/", input)
  override def createDeliveryStream(input: avias.kinesisfirehose.models.CreateDeliveryStreamInput): F[avias.kinesisfirehose.models.CreateDeliveryStreamOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesisfirehose.models.CreateDeliveryStreamOutput, avias.kinesisfirehose.models.CreateDeliveryStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateDeliveryStream", POST, "/", input)
  override def deleteDeliveryStream(input: avias.kinesisfirehose.models.DeleteDeliveryStreamInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesisfirehose.models.DeleteDeliveryStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDeliveryStream", POST, "/", input)
  override def putRecordBatch(input: avias.kinesisfirehose.models.PutRecordBatchInput): F[avias.kinesisfirehose.models.PutRecordBatchOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesisfirehose.models.PutRecordBatchOutput, avias.kinesisfirehose.models.PutRecordBatchInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecordBatch", POST, "/", input)
}