package avias.stepfunctions
trait Amazonstepfunctions[F[_]] {
  def listStateMachines(input: avias.stepfunctions.models.ListStateMachinesInput): F[avias.stepfunctions.models.ListStateMachinesOutput]
  def createActivity(input: avias.stepfunctions.models.CreateActivityInput): F[avias.stepfunctions.models.CreateActivityOutput]
  def startExecution(input: avias.stepfunctions.models.StartExecutionInput): F[avias.stepfunctions.models.StartExecutionOutput]
  def sendTaskFailure(input: avias.stepfunctions.models.SendTaskFailureInput): F[scala.Unit]
  def describeActivity(input: avias.stepfunctions.models.DescribeActivityInput): F[avias.stepfunctions.models.DescribeActivityOutput]
  def stopExecution(input: avias.stepfunctions.models.StopExecutionInput): F[avias.stepfunctions.models.StopExecutionOutput]
  def deleteActivity(input: avias.stepfunctions.models.DeleteActivityInput): F[scala.Unit]
  def describeStateMachineForExecution(input: avias.stepfunctions.models.DescribeStateMachineForExecutionInput): F[avias.stepfunctions.models.DescribeStateMachineForExecutionOutput]
  def getExecutionHistory(input: avias.stepfunctions.models.GetExecutionHistoryInput): F[avias.stepfunctions.models.GetExecutionHistoryOutput]
  def listActivities(input: avias.stepfunctions.models.ListActivitiesInput): F[avias.stepfunctions.models.ListActivitiesOutput]
  def deleteStateMachine(input: avias.stepfunctions.models.DeleteStateMachineInput): F[scala.Unit]
  def updateStateMachine(input: avias.stepfunctions.models.UpdateStateMachineInput): F[avias.stepfunctions.models.UpdateStateMachineOutput]
  def createStateMachine(input: avias.stepfunctions.models.CreateStateMachineInput): F[avias.stepfunctions.models.CreateStateMachineOutput]
  def getActivityTask(input: avias.stepfunctions.models.GetActivityTaskInput): F[avias.stepfunctions.models.GetActivityTaskOutput]
  def sendTaskHeartbeat(input: avias.stepfunctions.models.SendTaskHeartbeatInput): F[scala.Unit]
  def listExecutions(input: avias.stepfunctions.models.ListExecutionsInput): F[avias.stepfunctions.models.ListExecutionsOutput]
  def sendTaskSuccess(input: avias.stepfunctions.models.SendTaskSuccessInput): F[scala.Unit]
  def describeStateMachine(input: avias.stepfunctions.models.DescribeStateMachineInput): F[avias.stepfunctions.models.DescribeStateMachineOutput]
  def describeExecution(input: avias.stepfunctions.models.DescribeExecutionInput): F[avias.stepfunctions.models.DescribeExecutionOutput]
}