package org.lyranthe.araethura.route53domains.models
import org.lyranthe.araethura.route53domains.models
final case class BillingRecord(billDate: scala.Option[java.time.Instant] = None, price: scala.Option[scala.Double] = None, operation: scala.Option[java.lang.String] = None, domainName: scala.Option[java.lang.String] = None, invoiceId: scala.Option[java.lang.String] = None)
final case class ExtraParam(name: java.lang.String, value: java.lang.String)
final case class ViewBillingResponse(nextPageMarker: scala.Option[java.lang.String] = None, billingRecords: scala.Option[scala.List[models.BillingRecord]] = None)
final case class RenewDomainRequest(domainName: java.lang.String, currentExpiryYear: scala.Int, durationInYears: scala.Option[scala.Int] = None)
final case class UnsupportedTLD(message: scala.Option[java.lang.String] = None)
final case class TransferDomainResponse(operationId: java.lang.String)
final case class GetContactReachabilityStatusRequest(domainName: scala.Option[java.lang.String] = None)
final case class Nameserver(name: java.lang.String, glueIps: scala.Option[scala.List[java.lang.String]] = None)
final case class ListDomainsRequest(marker: scala.Option[java.lang.String] = None, maxItems: scala.Option[scala.Int] = None)
final case class DeleteTagsForDomainRequest(domainName: java.lang.String, tagsToDelete: scala.List[java.lang.String])
final case class DomainSuggestion(domainName: scala.Option[java.lang.String] = None, availability: scala.Option[java.lang.String] = None)
final case class ListOperationsRequest(marker: scala.Option[java.lang.String] = None, maxItems: scala.Option[scala.Int] = None)
final case class ResendContactReachabilityEmailRequest(domainName: scala.Option[java.lang.String] = None)
final case class CheckDomainAvailabilityRequest(domainName: java.lang.String, idnLangCode: scala.Option[java.lang.String] = None)
final case class DuplicateRequest(message: scala.Option[java.lang.String] = None)
final case class GetOperationDetailRequest(operationId: java.lang.String)
final case class GetDomainSuggestionsRequest(domainName: java.lang.String, suggestionCount: scala.Int, onlyAvailable: scala.Boolean)
final case class OperationLimitExceeded(message: scala.Option[java.lang.String] = None)
final case class RegisterDomainResponse(operationId: java.lang.String)
final case class UpdateDomainContactPrivacyResponse(operationId: java.lang.String)
final case class EnableDomainTransferLockRequest(domainName: java.lang.String)
final case class DisableDomainTransferLockRequest(domainName: java.lang.String)
final case class UpdateDomainNameserversRequest(domainName: java.lang.String, nameservers: scala.List[models.Nameserver], fiauthKey: scala.Option[java.lang.String] = None)
final case class CheckDomainTransferabilityRequest(domainName: java.lang.String, authCode: scala.Option[java.lang.String] = None)
final case class OperationSummary(operationId: java.lang.String, status: java.lang.String, `type`: java.lang.String, submittedDate: java.time.Instant)
final case class RegisterDomainRequest(durationInYears: scala.Int, domainName: java.lang.String, adminContact: models.ContactDetail, registrantContact: models.ContactDetail, techContact: models.ContactDetail, idnLangCode: scala.Option[java.lang.String] = None, autoRenew: scala.Option[scala.Boolean] = None, privacyProtectAdminContact: scala.Option[scala.Boolean] = None, privacyProtectRegistrantContact: scala.Option[scala.Boolean] = None, privacyProtectTechContact: scala.Option[scala.Boolean] = None)
final case class DomainSummary(domainName: java.lang.String, autoRenew: scala.Option[scala.Boolean] = None, transferLock: scala.Option[scala.Boolean] = None, expiry: scala.Option[java.time.Instant] = None)
case object DeleteTagsForDomainResponse
final case class GetContactReachabilityStatusResponse(domainName: scala.Option[java.lang.String] = None, status: scala.Option[java.lang.String] = None)
final case class RenewDomainResponse(operationId: java.lang.String)
final case class GetDomainDetailResponse(domainName: java.lang.String, nameservers: scala.List[models.Nameserver], adminContact: models.ContactDetail, registrantContact: models.ContactDetail, techContact: models.ContactDetail, registrarName: scala.Option[java.lang.String] = None, creationDate: scala.Option[java.time.Instant] = None, updatedDate: scala.Option[java.time.Instant] = None, expirationDate: scala.Option[java.time.Instant] = None, abuseContactEmail: scala.Option[java.lang.String] = None, statusList: scala.Option[scala.List[java.lang.String]] = None, whoIsServer: scala.Option[java.lang.String] = None, abuseContactPhone: scala.Option[java.lang.String] = None, dnsSec: scala.Option[java.lang.String] = None, registrarUrl: scala.Option[java.lang.String] = None, reseller: scala.Option[java.lang.String] = None, autoRenew: scala.Option[scala.Boolean] = None, adminPrivacy: scala.Option[scala.Boolean] = None, registrantPrivacy: scala.Option[scala.Boolean] = None, techPrivacy: scala.Option[scala.Boolean] = None, registryDomainId: scala.Option[java.lang.String] = None)
final case class ViewBillingRequest(start: scala.Option[java.time.Instant] = None, end: scala.Option[java.time.Instant] = None, marker: scala.Option[java.lang.String] = None, maxItems: scala.Option[scala.Int] = None)
final case class CheckDomainTransferabilityResponse(transferability: models.DomainTransferability)
final case class UpdateDomainNameserversResponse(operationId: java.lang.String)
final case class RetrieveDomainAuthCodeRequest(domainName: java.lang.String)
final case class GetDomainSuggestionsResponse(suggestionsList: scala.Option[scala.List[models.DomainSuggestion]] = None)
final case class TransferDomainRequest(durationInYears: scala.Int, domainName: java.lang.String, adminContact: models.ContactDetail, registrantContact: models.ContactDetail, techContact: models.ContactDetail, nameservers: scala.Option[scala.List[models.Nameserver]] = None, idnLangCode: scala.Option[java.lang.String] = None, authCode: scala.Option[java.lang.String] = None, autoRenew: scala.Option[scala.Boolean] = None, privacyProtectAdminContact: scala.Option[scala.Boolean] = None, privacyProtectRegistrantContact: scala.Option[scala.Boolean] = None, privacyProtectTechContact: scala.Option[scala.Boolean] = None)
case object UpdateTagsForDomainResponse
final case class GetDomainDetailRequest(domainName: java.lang.String)
final case class ResendContactReachabilityEmailResponse(domainName: scala.Option[java.lang.String] = None, emailAddress: scala.Option[java.lang.String] = None, isAlreadyVerified: scala.Option[scala.Boolean] = None)
final case class ListOperationsResponse(operations: scala.List[models.OperationSummary], nextPageMarker: scala.Option[java.lang.String] = None)
final case class Tag(key: scala.Option[java.lang.String] = None, value: scala.Option[java.lang.String] = None)
final case class ListTagsForDomainResponse(tagList: scala.List[models.Tag])
final case class ListDomainsResponse(domains: scala.List[models.DomainSummary], nextPageMarker: scala.Option[java.lang.String] = None)
final case class DisableDomainTransferLockResponse(operationId: java.lang.String)
final case class ContactDetail(contactType: scala.Option[java.lang.String] = None, email: scala.Option[java.lang.String] = None, phoneNumber: scala.Option[java.lang.String] = None, fax: scala.Option[java.lang.String] = None, firstName: scala.Option[java.lang.String] = None, lastName: scala.Option[java.lang.String] = None, organizationName: scala.Option[java.lang.String] = None, extraParams: scala.Option[scala.List[models.ExtraParam]] = None, state: scala.Option[java.lang.String] = None, zipCode: scala.Option[java.lang.String] = None, countryCode: scala.Option[java.lang.String] = None, city: scala.Option[java.lang.String] = None, addressLine1: scala.Option[java.lang.String] = None, addressLine2: scala.Option[java.lang.String] = None)
final case class InvalidInput(message: scala.Option[java.lang.String] = None)
final case class DomainTransferability(transferable: scala.Option[java.lang.String] = None)
final case class DisableDomainAutoRenewRequest(domainName: java.lang.String)
final case class DomainLimitExceeded(message: scala.Option[java.lang.String] = None)
final case class UpdateDomainContactResponse(operationId: java.lang.String)
final case class TLDRulesViolation(message: scala.Option[java.lang.String] = None)
final case class UpdateDomainContactRequest(domainName: java.lang.String, adminContact: scala.Option[models.ContactDetail] = None, registrantContact: scala.Option[models.ContactDetail] = None, techContact: scala.Option[models.ContactDetail] = None)
final case class EnableDomainTransferLockResponse(operationId: java.lang.String)
final case class UpdateTagsForDomainRequest(domainName: java.lang.String, tagsToUpdate: scala.Option[scala.List[models.Tag]] = None)
final case class CheckDomainAvailabilityResponse(availability: java.lang.String)
final case class ListTagsForDomainRequest(domainName: java.lang.String)
case object EnableDomainAutoRenewResponse
final case class EnableDomainAutoRenewRequest(domainName: java.lang.String)
final case class GetOperationDetailResponse(submittedDate: scala.Option[java.time.Instant] = None, operationId: scala.Option[java.lang.String] = None, `type`: scala.Option[java.lang.String] = None, status: scala.Option[java.lang.String] = None, domainName: scala.Option[java.lang.String] = None, message: scala.Option[java.lang.String] = None)
final case class UpdateDomainContactPrivacyRequest(domainName: java.lang.String, adminPrivacy: scala.Option[scala.Boolean] = None, registrantPrivacy: scala.Option[scala.Boolean] = None, techPrivacy: scala.Option[scala.Boolean] = None)
case object DisableDomainAutoRenewResponse
final case class RetrieveDomainAuthCodeResponse(authCode: java.lang.String)