package org.lyranthe.araethura.route53domains
trait Amazonroute53domains[F[_]] {
  def updateDomainContact(input: models.UpdateDomainContactRequest): F[models.UpdateDomainContactResponse]
  def updateTagsForDomain(input: models.UpdateTagsForDomainRequest): F[scala.Unit]
  def listOperations(input: models.ListOperationsRequest): F[models.ListOperationsResponse]
  def disableDomainTransferLock(input: models.DisableDomainTransferLockRequest): F[models.DisableDomainTransferLockResponse]
  def updateDomainContactPrivacy(input: models.UpdateDomainContactPrivacyRequest): F[models.UpdateDomainContactPrivacyResponse]
  def transferDomain(input: models.TransferDomainRequest): F[models.TransferDomainResponse]
  def getDomainDetail(input: models.GetDomainDetailRequest): F[models.GetDomainDetailResponse]
  def retrieveDomainAuthCode(input: models.RetrieveDomainAuthCodeRequest): F[models.RetrieveDomainAuthCodeResponse]
  def listTagsForDomain(input: models.ListTagsForDomainRequest): F[models.ListTagsForDomainResponse]
  def resendContactReachabilityEmail(input: models.ResendContactReachabilityEmailRequest): F[models.ResendContactReachabilityEmailResponse]
  def checkDomainAvailability(input: models.CheckDomainAvailabilityRequest): F[models.CheckDomainAvailabilityResponse]
  def getDomainSuggestions(input: models.GetDomainSuggestionsRequest): F[models.GetDomainSuggestionsResponse]
  def getOperationDetail(input: models.GetOperationDetailRequest): F[models.GetOperationDetailResponse]
  def viewBilling(input: models.ViewBillingRequest): F[models.ViewBillingResponse]
  def renewDomain(input: models.RenewDomainRequest): F[models.RenewDomainResponse]
  def checkDomainTransferability(input: models.CheckDomainTransferabilityRequest): F[models.CheckDomainTransferabilityResponse]
  def deleteTagsForDomain(input: models.DeleteTagsForDomainRequest): F[scala.Unit]
  def disableDomainAutoRenew(input: models.DisableDomainAutoRenewRequest): F[scala.Unit]
  def enableDomainAutoRenew(input: models.EnableDomainAutoRenewRequest): F[scala.Unit]
  def registerDomain(input: models.RegisterDomainRequest): F[models.RegisterDomainResponse]
  def enableDomainTransferLock(input: models.EnableDomainTransferLockRequest): F[models.EnableDomainTransferLockResponse]
  def getContactReachabilityStatus(input: models.GetContactReachabilityStatusRequest): F[models.GetContactReachabilityStatusResponse]
  def listDomains(input: models.ListDomainsRequest): F[models.ListDomainsResponse]
  def updateDomainNameservers(input: models.UpdateDomainNameserversRequest): F[models.UpdateDomainNameserversResponse]
}