package org.lyranthe.araethura.route53domains
trait Amazonroute53domains[F[_]] {
  def updateDomainContact(input: org.lyranthe.araethura.route53domains.models.UpdateDomainContactRequest): F[org.lyranthe.araethura.route53domains.models.UpdateDomainContactResponse]
  def updateTagsForDomain(input: org.lyranthe.araethura.route53domains.models.UpdateTagsForDomainRequest): F[scala.Unit]
  def listOperations(input: org.lyranthe.araethura.route53domains.models.ListOperationsRequest): F[org.lyranthe.araethura.route53domains.models.ListOperationsResponse]
  def disableDomainTransferLock(input: org.lyranthe.araethura.route53domains.models.DisableDomainTransferLockRequest): F[org.lyranthe.araethura.route53domains.models.DisableDomainTransferLockResponse]
  def updateDomainContactPrivacy(input: org.lyranthe.araethura.route53domains.models.UpdateDomainContactPrivacyRequest): F[org.lyranthe.araethura.route53domains.models.UpdateDomainContactPrivacyResponse]
  def transferDomain(input: org.lyranthe.araethura.route53domains.models.TransferDomainRequest): F[org.lyranthe.araethura.route53domains.models.TransferDomainResponse]
  def getDomainDetail(input: org.lyranthe.araethura.route53domains.models.GetDomainDetailRequest): F[org.lyranthe.araethura.route53domains.models.GetDomainDetailResponse]
  def retrieveDomainAuthCode(input: org.lyranthe.araethura.route53domains.models.RetrieveDomainAuthCodeRequest): F[org.lyranthe.araethura.route53domains.models.RetrieveDomainAuthCodeResponse]
  def listTagsForDomain(input: org.lyranthe.araethura.route53domains.models.ListTagsForDomainRequest): F[org.lyranthe.araethura.route53domains.models.ListTagsForDomainResponse]
  def resendContactReachabilityEmail(input: org.lyranthe.araethura.route53domains.models.ResendContactReachabilityEmailRequest): F[org.lyranthe.araethura.route53domains.models.ResendContactReachabilityEmailResponse]
  def checkDomainAvailability(input: org.lyranthe.araethura.route53domains.models.CheckDomainAvailabilityRequest): F[org.lyranthe.araethura.route53domains.models.CheckDomainAvailabilityResponse]
  def getDomainSuggestions(input: org.lyranthe.araethura.route53domains.models.GetDomainSuggestionsRequest): F[org.lyranthe.araethura.route53domains.models.GetDomainSuggestionsResponse]
  def getOperationDetail(input: org.lyranthe.araethura.route53domains.models.GetOperationDetailRequest): F[org.lyranthe.araethura.route53domains.models.GetOperationDetailResponse]
  def viewBilling(input: org.lyranthe.araethura.route53domains.models.ViewBillingRequest): F[org.lyranthe.araethura.route53domains.models.ViewBillingResponse]
  def renewDomain(input: org.lyranthe.araethura.route53domains.models.RenewDomainRequest): F[org.lyranthe.araethura.route53domains.models.RenewDomainResponse]
  def checkDomainTransferability(input: org.lyranthe.araethura.route53domains.models.CheckDomainTransferabilityRequest): F[org.lyranthe.araethura.route53domains.models.CheckDomainTransferabilityResponse]
  def deleteTagsForDomain(input: org.lyranthe.araethura.route53domains.models.DeleteTagsForDomainRequest): F[scala.Unit]
  def disableDomainAutoRenew(input: org.lyranthe.araethura.route53domains.models.DisableDomainAutoRenewRequest): F[scala.Unit]
  def enableDomainAutoRenew(input: org.lyranthe.araethura.route53domains.models.EnableDomainAutoRenewRequest): F[scala.Unit]
  def registerDomain(input: org.lyranthe.araethura.route53domains.models.RegisterDomainRequest): F[org.lyranthe.araethura.route53domains.models.RegisterDomainResponse]
  def enableDomainTransferLock(input: org.lyranthe.araethura.route53domains.models.EnableDomainTransferLockRequest): F[org.lyranthe.araethura.route53domains.models.EnableDomainTransferLockResponse]
  def getContactReachabilityStatus(input: org.lyranthe.araethura.route53domains.models.GetContactReachabilityStatusRequest): F[org.lyranthe.araethura.route53domains.models.GetContactReachabilityStatusResponse]
  def listDomains(input: org.lyranthe.araethura.route53domains.models.ListDomainsRequest): F[org.lyranthe.araethura.route53domains.models.ListDomainsResponse]
  def updateDomainNameservers(input: org.lyranthe.araethura.route53domains.models.UpdateDomainNameserversRequest): F[org.lyranthe.araethura.route53domains.models.UpdateDomainNameserversResponse]
}