package org.lyranthe.araethura.ecs.http4s
import org.http4s.Method._
import org.lyranthe.araethura.ecs.circe._
import org.lyranthe.araethura.ecs.models
class AmazonecsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.ecs.Amazonecs[F] {
  private[this] final val ServiceType: String = "ecs"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AmazonEC2ContainerServiceV20141113")
  override def submitContainerStateChange(input: models.SubmitContainerStateChangeRequest): F[models.SubmitContainerStateChangeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.SubmitContainerStateChangeResponse, models.SubmitContainerStateChangeRequest](client, awsData, ServiceType, ServiceAndPrefix, "SubmitContainerStateChange", POST, "/", input)
  override def describeTaskDefinition(input: models.DescribeTaskDefinitionRequest): F[models.DescribeTaskDefinitionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeTaskDefinitionResponse, models.DescribeTaskDefinitionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTaskDefinition", POST, "/", input)
  override def listAttributes(input: models.ListAttributesRequest): F[models.ListAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListAttributesResponse, models.ListAttributesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListAttributes", POST, "/", input)
  override def listContainerInstances(input: models.ListContainerInstancesRequest): F[models.ListContainerInstancesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListContainerInstancesResponse, models.ListContainerInstancesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListContainerInstances", POST, "/", input)
  override def deregisterContainerInstance(input: models.DeregisterContainerInstanceRequest): F[models.DeregisterContainerInstanceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeregisterContainerInstanceResponse, models.DeregisterContainerInstanceRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeregisterContainerInstance", POST, "/", input)
  override def deleteService(input: models.DeleteServiceRequest): F[models.DeleteServiceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteServiceResponse, models.DeleteServiceRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteService", POST, "/", input)
  override def runTask(input: models.RunTaskRequest): F[models.RunTaskResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RunTaskResponse, models.RunTaskRequest](client, awsData, ServiceType, ServiceAndPrefix, "RunTask", POST, "/", input)
  override def describeClusters(input: models.DescribeClustersRequest): F[models.DescribeClustersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeClustersResponse, models.DescribeClustersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeClusters", POST, "/", input)
  override def putAttributes(input: models.PutAttributesRequest): F[models.PutAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutAttributesResponse, models.PutAttributesRequest](client, awsData, ServiceType, ServiceAndPrefix, "PutAttributes", POST, "/", input)
  override def describeServices(input: models.DescribeServicesRequest): F[models.DescribeServicesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeServicesResponse, models.DescribeServicesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeServices", POST, "/", input)
  override def createService(input: models.CreateServiceRequest): F[models.CreateServiceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateServiceResponse, models.CreateServiceRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateService", POST, "/", input)
  override def listTasks(input: models.ListTasksRequest): F[models.ListTasksResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTasksResponse, models.ListTasksRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTasks", POST, "/", input)
  override def listTaskDefinitions(input: models.ListTaskDefinitionsRequest): F[models.ListTaskDefinitionsResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTaskDefinitionsResponse, models.ListTaskDefinitionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTaskDefinitions", POST, "/", input)
  override def describeContainerInstances(input: models.DescribeContainerInstancesRequest): F[models.DescribeContainerInstancesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeContainerInstancesResponse, models.DescribeContainerInstancesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeContainerInstances", POST, "/", input)
  override def listClusters(input: models.ListClustersRequest): F[models.ListClustersResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListClustersResponse, models.ListClustersRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListClusters", POST, "/", input)
  override def deleteCluster(input: models.DeleteClusterRequest): F[models.DeleteClusterResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteClusterResponse, models.DeleteClusterRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteCluster", POST, "/", input)
  override def updateContainerInstancesState(input: models.UpdateContainerInstancesStateRequest): F[models.UpdateContainerInstancesStateResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateContainerInstancesStateResponse, models.UpdateContainerInstancesStateRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateContainerInstancesState", POST, "/", input)
  override def deregisterTaskDefinition(input: models.DeregisterTaskDefinitionRequest): F[models.DeregisterTaskDefinitionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeregisterTaskDefinitionResponse, models.DeregisterTaskDefinitionRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeregisterTaskDefinition", POST, "/", input)
  override def stopTask(input: models.StopTaskRequest): F[models.StopTaskResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StopTaskResponse, models.StopTaskRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopTask", POST, "/", input)
  override def updateService(input: models.UpdateServiceRequest): F[models.UpdateServiceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateServiceResponse, models.UpdateServiceRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateService", POST, "/", input)
  override def startTask(input: models.StartTaskRequest): F[models.StartTaskResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.StartTaskResponse, models.StartTaskRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartTask", POST, "/", input)
  override def registerContainerInstance(input: models.RegisterContainerInstanceRequest): F[models.RegisterContainerInstanceResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RegisterContainerInstanceResponse, models.RegisterContainerInstanceRequest](client, awsData, ServiceType, ServiceAndPrefix, "RegisterContainerInstance", POST, "/", input)
  override def registerTaskDefinition(input: models.RegisterTaskDefinitionRequest): F[models.RegisterTaskDefinitionResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.RegisterTaskDefinitionResponse, models.RegisterTaskDefinitionRequest](client, awsData, ServiceType, ServiceAndPrefix, "RegisterTaskDefinition", POST, "/", input)
  override def deleteAttributes(input: models.DeleteAttributesRequest): F[models.DeleteAttributesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DeleteAttributesResponse, models.DeleteAttributesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteAttributes", POST, "/", input)
  override def submitTaskStateChange(input: models.SubmitTaskStateChangeRequest): F[models.SubmitTaskStateChangeResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.SubmitTaskStateChangeResponse, models.SubmitTaskStateChangeRequest](client, awsData, ServiceType, ServiceAndPrefix, "SubmitTaskStateChange", POST, "/", input)
  override def discoverPollEndpoint(input: models.DiscoverPollEndpointRequest): F[models.DiscoverPollEndpointResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DiscoverPollEndpointResponse, models.DiscoverPollEndpointRequest](client, awsData, ServiceType, ServiceAndPrefix, "DiscoverPollEndpoint", POST, "/", input)
  override def createCluster(input: models.CreateClusterRequest): F[models.CreateClusterResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.CreateClusterResponse, models.CreateClusterRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateCluster", POST, "/", input)
  override def updateContainerAgent(input: models.UpdateContainerAgentRequest): F[models.UpdateContainerAgentResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateContainerAgentResponse, models.UpdateContainerAgentRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateContainerAgent", POST, "/", input)
  override def describeTasks(input: models.DescribeTasksRequest): F[models.DescribeTasksResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeTasksResponse, models.DescribeTasksRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeTasks", POST, "/", input)
  override def listTaskDefinitionFamilies(input: models.ListTaskDefinitionFamiliesRequest): F[models.ListTaskDefinitionFamiliesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTaskDefinitionFamiliesResponse, models.ListTaskDefinitionFamiliesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListTaskDefinitionFamilies", POST, "/", input)
  override def listServices(input: models.ListServicesRequest): F[models.ListServicesResponse] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListServicesResponse, models.ListServicesRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListServices", POST, "/", input)
}