package org.lyranthe.araethura.codepipeline.http4s
import org.http4s.Method._
import org.lyranthe.araethura.codepipeline.circe._
import org.lyranthe.araethura.codepipeline.models
class AmazoncodepipelineClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.codepipeline.Amazoncodepipeline[F] {
  private[this] final val ServiceType: String = "codepipeline"
  private[this] final val ServiceAndPrefix: Option[String] = Some("CodePipeline_20150709")
  override def listPipelineExecutions(input: org.lyranthe.araethura.codepipeline.models.ListPipelineExecutionsInput): F[org.lyranthe.araethura.codepipeline.models.ListPipelineExecutionsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.ListPipelineExecutionsOutput, org.lyranthe.araethura.codepipeline.models.ListPipelineExecutionsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListPipelineExecutions", POST, "/", input)
  override def createCustomActionType(input: org.lyranthe.araethura.codepipeline.models.CreateCustomActionTypeInput): F[org.lyranthe.araethura.codepipeline.models.CreateCustomActionTypeOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.CreateCustomActionTypeOutput, org.lyranthe.araethura.codepipeline.models.CreateCustomActionTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateCustomActionType", POST, "/", input)
  override def putActionRevision(input: org.lyranthe.araethura.codepipeline.models.PutActionRevisionInput): F[org.lyranthe.araethura.codepipeline.models.PutActionRevisionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.PutActionRevisionOutput, org.lyranthe.araethura.codepipeline.models.PutActionRevisionInput](client, awsData, ServiceType, ServiceAndPrefix, "PutActionRevision", POST, "/", input)
  override def acknowledgeJob(input: org.lyranthe.araethura.codepipeline.models.AcknowledgeJobInput): F[org.lyranthe.araethura.codepipeline.models.AcknowledgeJobOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.AcknowledgeJobOutput, org.lyranthe.araethura.codepipeline.models.AcknowledgeJobInput](client, awsData, ServiceType, ServiceAndPrefix, "AcknowledgeJob", POST, "/", input)
  override def putApprovalResult(input: org.lyranthe.araethura.codepipeline.models.PutApprovalResultInput): F[org.lyranthe.araethura.codepipeline.models.PutApprovalResultOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.PutApprovalResultOutput, org.lyranthe.araethura.codepipeline.models.PutApprovalResultInput](client, awsData, ServiceType, ServiceAndPrefix, "PutApprovalResult", POST, "/", input)
  override def putJobFailureResult(input: org.lyranthe.araethura.codepipeline.models.PutJobFailureResultInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.PutJobFailureResultInput](client, awsData, ServiceType, ServiceAndPrefix, "PutJobFailureResult", POST, "/", input)
  override def listActionTypes(input: org.lyranthe.araethura.codepipeline.models.ListActionTypesInput): F[org.lyranthe.araethura.codepipeline.models.ListActionTypesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.ListActionTypesOutput, org.lyranthe.araethura.codepipeline.models.ListActionTypesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListActionTypes", POST, "/", input)
  override def putThirdPartyJobSuccessResult(input: org.lyranthe.araethura.codepipeline.models.PutThirdPartyJobSuccessResultInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.PutThirdPartyJobSuccessResultInput](client, awsData, ServiceType, ServiceAndPrefix, "PutThirdPartyJobSuccessResult", POST, "/", input)
  override def pollForJobs(input: org.lyranthe.araethura.codepipeline.models.PollForJobsInput): F[org.lyranthe.araethura.codepipeline.models.PollForJobsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.PollForJobsOutput, org.lyranthe.araethura.codepipeline.models.PollForJobsInput](client, awsData, ServiceType, ServiceAndPrefix, "PollForJobs", POST, "/", input)
  override def acknowledgeThirdPartyJob(input: org.lyranthe.araethura.codepipeline.models.AcknowledgeThirdPartyJobInput): F[org.lyranthe.araethura.codepipeline.models.AcknowledgeThirdPartyJobOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.AcknowledgeThirdPartyJobOutput, org.lyranthe.araethura.codepipeline.models.AcknowledgeThirdPartyJobInput](client, awsData, ServiceType, ServiceAndPrefix, "AcknowledgeThirdPartyJob", POST, "/", input)
  override def deleteCustomActionType(input: org.lyranthe.araethura.codepipeline.models.DeleteCustomActionTypeInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.DeleteCustomActionTypeInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteCustomActionType", POST, "/", input)
  override def putThirdPartyJobFailureResult(input: org.lyranthe.araethura.codepipeline.models.PutThirdPartyJobFailureResultInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.PutThirdPartyJobFailureResultInput](client, awsData, ServiceType, ServiceAndPrefix, "PutThirdPartyJobFailureResult", POST, "/", input)
  override def listPipelines(input: org.lyranthe.araethura.codepipeline.models.ListPipelinesInput): F[org.lyranthe.araethura.codepipeline.models.ListPipelinesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.ListPipelinesOutput, org.lyranthe.araethura.codepipeline.models.ListPipelinesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListPipelines", POST, "/", input)
  override def startPipelineExecution(input: org.lyranthe.araethura.codepipeline.models.StartPipelineExecutionInput): F[org.lyranthe.araethura.codepipeline.models.StartPipelineExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.StartPipelineExecutionOutput, org.lyranthe.araethura.codepipeline.models.StartPipelineExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartPipelineExecution", POST, "/", input)
  override def getThirdPartyJobDetails(input: org.lyranthe.araethura.codepipeline.models.GetThirdPartyJobDetailsInput): F[org.lyranthe.araethura.codepipeline.models.GetThirdPartyJobDetailsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.GetThirdPartyJobDetailsOutput, org.lyranthe.araethura.codepipeline.models.GetThirdPartyJobDetailsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetThirdPartyJobDetails", POST, "/", input)
  override def deletePipeline(input: org.lyranthe.araethura.codepipeline.models.DeletePipelineInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.DeletePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "DeletePipeline", POST, "/", input)
  override def enableStageTransition(input: org.lyranthe.araethura.codepipeline.models.EnableStageTransitionInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.EnableStageTransitionInput](client, awsData, ServiceType, ServiceAndPrefix, "EnableStageTransition", POST, "/", input)
  override def createPipeline(input: org.lyranthe.araethura.codepipeline.models.CreatePipelineInput): F[org.lyranthe.araethura.codepipeline.models.CreatePipelineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.CreatePipelineOutput, org.lyranthe.araethura.codepipeline.models.CreatePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "CreatePipeline", POST, "/", input)
  override def getPipeline(input: org.lyranthe.araethura.codepipeline.models.GetPipelineInput): F[org.lyranthe.araethura.codepipeline.models.GetPipelineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.GetPipelineOutput, org.lyranthe.araethura.codepipeline.models.GetPipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "GetPipeline", POST, "/", input)
  override def pollForThirdPartyJobs(input: org.lyranthe.araethura.codepipeline.models.PollForThirdPartyJobsInput): F[org.lyranthe.araethura.codepipeline.models.PollForThirdPartyJobsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.PollForThirdPartyJobsOutput, org.lyranthe.araethura.codepipeline.models.PollForThirdPartyJobsInput](client, awsData, ServiceType, ServiceAndPrefix, "PollForThirdPartyJobs", POST, "/", input)
  override def getPipelineExecution(input: org.lyranthe.araethura.codepipeline.models.GetPipelineExecutionInput): F[org.lyranthe.araethura.codepipeline.models.GetPipelineExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.GetPipelineExecutionOutput, org.lyranthe.araethura.codepipeline.models.GetPipelineExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "GetPipelineExecution", POST, "/", input)
  override def updatePipeline(input: org.lyranthe.araethura.codepipeline.models.UpdatePipelineInput): F[org.lyranthe.araethura.codepipeline.models.UpdatePipelineOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.UpdatePipelineOutput, org.lyranthe.araethura.codepipeline.models.UpdatePipelineInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdatePipeline", POST, "/", input)
  override def retryStageExecution(input: org.lyranthe.araethura.codepipeline.models.RetryStageExecutionInput): F[org.lyranthe.araethura.codepipeline.models.RetryStageExecutionOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.RetryStageExecutionOutput, org.lyranthe.araethura.codepipeline.models.RetryStageExecutionInput](client, awsData, ServiceType, ServiceAndPrefix, "RetryStageExecution", POST, "/", input)
  override def getJobDetails(input: org.lyranthe.araethura.codepipeline.models.GetJobDetailsInput): F[org.lyranthe.araethura.codepipeline.models.GetJobDetailsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.GetJobDetailsOutput, org.lyranthe.araethura.codepipeline.models.GetJobDetailsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetJobDetails", POST, "/", input)
  override def disableStageTransition(input: org.lyranthe.araethura.codepipeline.models.DisableStageTransitionInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.DisableStageTransitionInput](client, awsData, ServiceType, ServiceAndPrefix, "DisableStageTransition", POST, "/", input)
  override def getPipelineState(input: org.lyranthe.araethura.codepipeline.models.GetPipelineStateInput): F[org.lyranthe.araethura.codepipeline.models.GetPipelineStateOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.codepipeline.models.GetPipelineStateOutput, org.lyranthe.araethura.codepipeline.models.GetPipelineStateInput](client, awsData, ServiceType, ServiceAndPrefix, "GetPipelineState", POST, "/", input)
  override def putJobSuccessResult(input: org.lyranthe.araethura.codepipeline.models.PutJobSuccessResultInput): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.codepipeline.models.PutJobSuccessResultInput](client, awsData, ServiceType, ServiceAndPrefix, "PutJobSuccessResult", POST, "/", input)
}