package org.lyranthe.araethura.resourcegroupstaggingapi.http4s
import org.http4s.Method._
import org.lyranthe.araethura.resourcegroupstaggingapi.circe._
import org.lyranthe.araethura.resourcegroupstaggingapi.models
class AmazonresourcegroupstaggingapiClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.resourcegroupstaggingapi.Amazonresourcegroupstaggingapi[F] {
  private[this] final val ServiceType: String = "tagging"
  private[this] final val ServiceAndPrefix: Option[String] = Some("ResourceGroupsTaggingAPI_20170126")
  override def getResources(input: org.lyranthe.araethura.resourcegroupstaggingapi.models.GetResourcesInput): F[org.lyranthe.araethura.resourcegroupstaggingapi.models.GetResourcesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.resourcegroupstaggingapi.models.GetResourcesOutput, org.lyranthe.araethura.resourcegroupstaggingapi.models.GetResourcesInput](client, awsData, ServiceType, ServiceAndPrefix, "GetResources", POST, "/", input)
  override def tagResources(input: org.lyranthe.araethura.resourcegroupstaggingapi.models.TagResourcesInput): F[org.lyranthe.araethura.resourcegroupstaggingapi.models.TagResourcesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.resourcegroupstaggingapi.models.TagResourcesOutput, org.lyranthe.araethura.resourcegroupstaggingapi.models.TagResourcesInput](client, awsData, ServiceType, ServiceAndPrefix, "TagResources", POST, "/", input)
  override def getTagValues(input: org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagValuesInput): F[org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagValuesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagValuesOutput, org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagValuesInput](client, awsData, ServiceType, ServiceAndPrefix, "GetTagValues", POST, "/", input)
  override def getTagKeys(input: org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagKeysInput): F[org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagKeysOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagKeysOutput, org.lyranthe.araethura.resourcegroupstaggingapi.models.GetTagKeysInput](client, awsData, ServiceType, ServiceAndPrefix, "GetTagKeys", POST, "/", input)
  override def untagResources(input: org.lyranthe.araethura.resourcegroupstaggingapi.models.UntagResourcesInput): F[org.lyranthe.araethura.resourcegroupstaggingapi.models.UntagResourcesOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.resourcegroupstaggingapi.models.UntagResourcesOutput, org.lyranthe.araethura.resourcegroupstaggingapi.models.UntagResourcesInput](client, awsData, ServiceType, ServiceAndPrefix, "UntagResources", POST, "/", input)
}