package org.lyranthe.araethura.emr
trait Amazonemr[F[_]] {
  def modifyInstanceFleet(input: models.ModifyInstanceFleetInput): F[Unit]
  def deleteSecurityConfiguration(input: models.DeleteSecurityConfigurationInput): F[scala.Unit]
  def listSecurityConfigurations(input: models.ListSecurityConfigurationsInput): F[models.ListSecurityConfigurationsOutput]
  def modifyInstanceGroups(input: models.ModifyInstanceGroupsInput): F[Unit]
  def describeSecurityConfiguration(input: models.DescribeSecurityConfigurationInput): F[models.DescribeSecurityConfigurationOutput]
  def putAutoScalingPolicy(input: models.PutAutoScalingPolicyInput): F[models.PutAutoScalingPolicyOutput]
  def listSteps(input: models.ListStepsInput): F[models.ListStepsOutput]
  def addJobFlowSteps(input: models.AddJobFlowStepsInput): F[models.AddJobFlowStepsOutput]
  def cancelSteps(input: models.CancelStepsInput): F[models.CancelStepsOutput]
  def listInstanceFleets(input: models.ListInstanceFleetsInput): F[models.ListInstanceFleetsOutput]
  def addInstanceFleet(input: models.AddInstanceFleetInput): F[models.AddInstanceFleetOutput]
  def listClusters(input: models.ListClustersInput): F[models.ListClustersOutput]
  def runJobFlow(input: models.RunJobFlowInput): F[models.RunJobFlowOutput]
  def listInstances(input: models.ListInstancesInput): F[models.ListInstancesOutput]
  def describeStep(input: models.DescribeStepInput): F[models.DescribeStepOutput]
  def setVisibleToAllUsers(input: models.SetVisibleToAllUsersInput): F[Unit]
  def describeCluster(input: models.DescribeClusterInput): F[models.DescribeClusterOutput]
  def terminateJobFlows(input: models.TerminateJobFlowsInput): F[Unit]
  def removeAutoScalingPolicy(input: models.RemoveAutoScalingPolicyInput): F[scala.Unit]
  def addInstanceGroups(input: models.AddInstanceGroupsInput): F[models.AddInstanceGroupsOutput]
  def listInstanceGroups(input: models.ListInstanceGroupsInput): F[models.ListInstanceGroupsOutput]
  def addTags(input: models.AddTagsInput): F[scala.Unit]
  def createSecurityConfiguration(input: models.CreateSecurityConfigurationInput): F[models.CreateSecurityConfigurationOutput]
  def removeTags(input: models.RemoveTagsInput): F[scala.Unit]
  def listBootstrapActions(input: models.ListBootstrapActionsInput): F[models.ListBootstrapActionsOutput]
  def setTerminationProtection(input: models.SetTerminationProtectionInput): F[Unit]
  def describeJobFlows(input: models.DescribeJobFlowsInput): F[models.DescribeJobFlowsOutput]
}