package avias.emr
trait Amazonemr[F[_]] {
  def modifyInstanceFleet(input: avias.emr.models.ModifyInstanceFleetInput): F[scala.Unit]
  def deleteSecurityConfiguration(input: avias.emr.models.DeleteSecurityConfigurationInput): F[scala.Unit]
  def listSecurityConfigurations(input: avias.emr.models.ListSecurityConfigurationsInput): F[avias.emr.models.ListSecurityConfigurationsOutput]
  def modifyInstanceGroups(input: avias.emr.models.ModifyInstanceGroupsInput): F[scala.Unit]
  def describeSecurityConfiguration(input: avias.emr.models.DescribeSecurityConfigurationInput): F[avias.emr.models.DescribeSecurityConfigurationOutput]
  def putAutoScalingPolicy(input: avias.emr.models.PutAutoScalingPolicyInput): F[avias.emr.models.PutAutoScalingPolicyOutput]
  def listSteps(input: avias.emr.models.ListStepsInput): F[avias.emr.models.ListStepsOutput]
  def addJobFlowSteps(input: avias.emr.models.AddJobFlowStepsInput): F[avias.emr.models.AddJobFlowStepsOutput]
  def cancelSteps(input: avias.emr.models.CancelStepsInput): F[avias.emr.models.CancelStepsOutput]
  def listInstanceFleets(input: avias.emr.models.ListInstanceFleetsInput): F[avias.emr.models.ListInstanceFleetsOutput]
  def addInstanceFleet(input: avias.emr.models.AddInstanceFleetInput): F[avias.emr.models.AddInstanceFleetOutput]
  def listClusters(input: avias.emr.models.ListClustersInput): F[avias.emr.models.ListClustersOutput]
  def runJobFlow(input: avias.emr.models.RunJobFlowInput): F[avias.emr.models.RunJobFlowOutput]
  def listInstances(input: avias.emr.models.ListInstancesInput): F[avias.emr.models.ListInstancesOutput]
  def describeStep(input: avias.emr.models.DescribeStepInput): F[avias.emr.models.DescribeStepOutput]
  def setVisibleToAllUsers(input: avias.emr.models.SetVisibleToAllUsersInput): F[scala.Unit]
  def describeCluster(input: avias.emr.models.DescribeClusterInput): F[avias.emr.models.DescribeClusterOutput]
  def terminateJobFlows(input: avias.emr.models.TerminateJobFlowsInput): F[scala.Unit]
  def removeAutoScalingPolicy(input: avias.emr.models.RemoveAutoScalingPolicyInput): F[scala.Unit]
  def addInstanceGroups(input: avias.emr.models.AddInstanceGroupsInput): F[avias.emr.models.AddInstanceGroupsOutput]
  def listInstanceGroups(input: avias.emr.models.ListInstanceGroupsInput): F[avias.emr.models.ListInstanceGroupsOutput]
  def addTags(input: avias.emr.models.AddTagsInput): F[scala.Unit]
  def createSecurityConfiguration(input: avias.emr.models.CreateSecurityConfigurationInput): F[avias.emr.models.CreateSecurityConfigurationOutput]
  def removeTags(input: avias.emr.models.RemoveTagsInput): F[scala.Unit]
  def listBootstrapActions(input: avias.emr.models.ListBootstrapActionsInput): F[avias.emr.models.ListBootstrapActionsOutput]
  def setTerminationProtection(input: avias.emr.models.SetTerminationProtectionInput): F[scala.Unit]
  def describeJobFlows(input: avias.emr.models.DescribeJobFlowsInput): F[avias.emr.models.DescribeJobFlowsOutput]
}