package org.lyranthe.araethura.emr
trait Amazonemr[F[_]] {
  def modifyInstanceFleet(input: org.lyranthe.araethura.emr.models.ModifyInstanceFleetInput): F[scala.Unit]
  def deleteSecurityConfiguration(input: org.lyranthe.araethura.emr.models.DeleteSecurityConfigurationInput): F[scala.Unit]
  def listSecurityConfigurations(input: org.lyranthe.araethura.emr.models.ListSecurityConfigurationsInput): F[org.lyranthe.araethura.emr.models.ListSecurityConfigurationsOutput]
  def modifyInstanceGroups(input: org.lyranthe.araethura.emr.models.ModifyInstanceGroupsInput): F[scala.Unit]
  def describeSecurityConfiguration(input: org.lyranthe.araethura.emr.models.DescribeSecurityConfigurationInput): F[org.lyranthe.araethura.emr.models.DescribeSecurityConfigurationOutput]
  def putAutoScalingPolicy(input: org.lyranthe.araethura.emr.models.PutAutoScalingPolicyInput): F[org.lyranthe.araethura.emr.models.PutAutoScalingPolicyOutput]
  def listSteps(input: org.lyranthe.araethura.emr.models.ListStepsInput): F[org.lyranthe.araethura.emr.models.ListStepsOutput]
  def addJobFlowSteps(input: org.lyranthe.araethura.emr.models.AddJobFlowStepsInput): F[org.lyranthe.araethura.emr.models.AddJobFlowStepsOutput]
  def cancelSteps(input: org.lyranthe.araethura.emr.models.CancelStepsInput): F[org.lyranthe.araethura.emr.models.CancelStepsOutput]
  def listInstanceFleets(input: org.lyranthe.araethura.emr.models.ListInstanceFleetsInput): F[org.lyranthe.araethura.emr.models.ListInstanceFleetsOutput]
  def addInstanceFleet(input: org.lyranthe.araethura.emr.models.AddInstanceFleetInput): F[org.lyranthe.araethura.emr.models.AddInstanceFleetOutput]
  def listClusters(input: org.lyranthe.araethura.emr.models.ListClustersInput): F[org.lyranthe.araethura.emr.models.ListClustersOutput]
  def runJobFlow(input: org.lyranthe.araethura.emr.models.RunJobFlowInput): F[org.lyranthe.araethura.emr.models.RunJobFlowOutput]
  def listInstances(input: org.lyranthe.araethura.emr.models.ListInstancesInput): F[org.lyranthe.araethura.emr.models.ListInstancesOutput]
  def describeStep(input: org.lyranthe.araethura.emr.models.DescribeStepInput): F[org.lyranthe.araethura.emr.models.DescribeStepOutput]
  def setVisibleToAllUsers(input: org.lyranthe.araethura.emr.models.SetVisibleToAllUsersInput): F[scala.Unit]
  def describeCluster(input: org.lyranthe.araethura.emr.models.DescribeClusterInput): F[org.lyranthe.araethura.emr.models.DescribeClusterOutput]
  def terminateJobFlows(input: org.lyranthe.araethura.emr.models.TerminateJobFlowsInput): F[scala.Unit]
  def removeAutoScalingPolicy(input: org.lyranthe.araethura.emr.models.RemoveAutoScalingPolicyInput): F[scala.Unit]
  def addInstanceGroups(input: org.lyranthe.araethura.emr.models.AddInstanceGroupsInput): F[org.lyranthe.araethura.emr.models.AddInstanceGroupsOutput]
  def listInstanceGroups(input: org.lyranthe.araethura.emr.models.ListInstanceGroupsInput): F[org.lyranthe.araethura.emr.models.ListInstanceGroupsOutput]
  def addTags(input: org.lyranthe.araethura.emr.models.AddTagsInput): F[scala.Unit]
  def createSecurityConfiguration(input: org.lyranthe.araethura.emr.models.CreateSecurityConfigurationInput): F[org.lyranthe.araethura.emr.models.CreateSecurityConfigurationOutput]
  def removeTags(input: org.lyranthe.araethura.emr.models.RemoveTagsInput): F[scala.Unit]
  def listBootstrapActions(input: org.lyranthe.araethura.emr.models.ListBootstrapActionsInput): F[org.lyranthe.araethura.emr.models.ListBootstrapActionsOutput]
  def setTerminationProtection(input: org.lyranthe.araethura.emr.models.SetTerminationProtectionInput): F[scala.Unit]
  def describeJobFlows(input: org.lyranthe.araethura.emr.models.DescribeJobFlowsInput): F[org.lyranthe.araethura.emr.models.DescribeJobFlowsOutput]
}