package avias.cognitoidentity.http4s
import org.http4s.Method._
import avias.cognitoidentity.circe._
import avias.cognitoidentity.models
import avias.common.http4s.ClientUtils._
class AmazoncognitoidentityClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.cognitoidentity.Amazoncognitoidentity[F] {
  private[this] final val ServiceType: String = "cognito-identity"
  private[this] final val ServiceAndPrefix: Option[String] = Some("AWSCognitoIdentityService")
  override def updateIdentityPool(input: avias.cognitoidentity.models.IdentityPool): F[avias.cognitoidentity.models.IdentityPool] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.IdentityPool, avias.cognitoidentity.models.IdentityPool](client, awsData, ServiceType, ServiceAndPrefix, "UpdateIdentityPool", POST, "/", input)
  override def deleteIdentities(input: avias.cognitoidentity.models.DeleteIdentitiesInput): F[avias.cognitoidentity.models.DeleteIdentitiesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.DeleteIdentitiesResponse, avias.cognitoidentity.models.DeleteIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteIdentities", POST, "/", input)
  override def getId(input: avias.cognitoidentity.models.GetIdInput): F[avias.cognitoidentity.models.GetIdResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.GetIdResponse, avias.cognitoidentity.models.GetIdInput](client, awsData, ServiceType, ServiceAndPrefix, "GetId", POST, "/", input)
  override def getIdentityPoolRoles(input: avias.cognitoidentity.models.GetIdentityPoolRolesInput): F[avias.cognitoidentity.models.GetIdentityPoolRolesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.GetIdentityPoolRolesResponse, avias.cognitoidentity.models.GetIdentityPoolRolesInput](client, awsData, ServiceType, ServiceAndPrefix, "GetIdentityPoolRoles", POST, "/", input)
  override def unlinkDeveloperIdentity(input: avias.cognitoidentity.models.UnlinkDeveloperIdentityInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.cognitoidentity.models.UnlinkDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "UnlinkDeveloperIdentity", POST, "/", input)
  override def unlinkIdentity(input: avias.cognitoidentity.models.UnlinkIdentityInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.cognitoidentity.models.UnlinkIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "UnlinkIdentity", POST, "/", input)
  override def getOpenIdTokenForDeveloperIdentity(input: avias.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityInput): F[avias.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityResponse, avias.cognitoidentity.models.GetOpenIdTokenForDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "GetOpenIdTokenForDeveloperIdentity", POST, "/", input)
  override def listIdentities(input: avias.cognitoidentity.models.ListIdentitiesInput): F[avias.cognitoidentity.models.ListIdentitiesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.ListIdentitiesResponse, avias.cognitoidentity.models.ListIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "ListIdentities", POST, "/", input)
  override def createIdentityPool(input: avias.cognitoidentity.models.CreateIdentityPoolInput): F[avias.cognitoidentity.models.IdentityPool] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.IdentityPool, avias.cognitoidentity.models.CreateIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateIdentityPool", POST, "/", input)
  override def setIdentityPoolRoles(input: avias.cognitoidentity.models.SetIdentityPoolRolesInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.cognitoidentity.models.SetIdentityPoolRolesInput](client, awsData, ServiceType, ServiceAndPrefix, "SetIdentityPoolRoles", POST, "/", input)
  override def lookupDeveloperIdentity(input: avias.cognitoidentity.models.LookupDeveloperIdentityInput): F[avias.cognitoidentity.models.LookupDeveloperIdentityResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.LookupDeveloperIdentityResponse, avias.cognitoidentity.models.LookupDeveloperIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "LookupDeveloperIdentity", POST, "/", input)
  override def mergeDeveloperIdentities(input: avias.cognitoidentity.models.MergeDeveloperIdentitiesInput): F[avias.cognitoidentity.models.MergeDeveloperIdentitiesResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.MergeDeveloperIdentitiesResponse, avias.cognitoidentity.models.MergeDeveloperIdentitiesInput](client, awsData, ServiceType, ServiceAndPrefix, "MergeDeveloperIdentities", POST, "/", input)
  override def describeIdentity(input: avias.cognitoidentity.models.DescribeIdentityInput): F[avias.cognitoidentity.models.IdentityDescription] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.IdentityDescription, avias.cognitoidentity.models.DescribeIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeIdentity", POST, "/", input)
  override def describeIdentityPool(input: avias.cognitoidentity.models.DescribeIdentityPoolInput): F[avias.cognitoidentity.models.IdentityPool] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.IdentityPool, avias.cognitoidentity.models.DescribeIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeIdentityPool", POST, "/", input)
  override def getCredentialsForIdentity(input: avias.cognitoidentity.models.GetCredentialsForIdentityInput): F[avias.cognitoidentity.models.GetCredentialsForIdentityResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.GetCredentialsForIdentityResponse, avias.cognitoidentity.models.GetCredentialsForIdentityInput](client, awsData, ServiceType, ServiceAndPrefix, "GetCredentialsForIdentity", POST, "/", input)
  override def listIdentityPools(input: avias.cognitoidentity.models.ListIdentityPoolsInput): F[avias.cognitoidentity.models.ListIdentityPoolsResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.ListIdentityPoolsResponse, avias.cognitoidentity.models.ListIdentityPoolsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListIdentityPools", POST, "/", input)
  override def getOpenIdToken(input: avias.cognitoidentity.models.GetOpenIdTokenInput): F[avias.cognitoidentity.models.GetOpenIdTokenResponse] = avias.common.http4s.ClientUtils.doRequest[F, avias.cognitoidentity.models.GetOpenIdTokenResponse, avias.cognitoidentity.models.GetOpenIdTokenInput](client, awsData, ServiceType, ServiceAndPrefix, "GetOpenIdToken", POST, "/", input)
  override def deleteIdentityPool(input: avias.cognitoidentity.models.DeleteIdentityPoolInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.cognitoidentity.models.DeleteIdentityPoolInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteIdentityPool", POST, "/", input)
}