package org.lyranthe.araethura.appstream.http4s
import org.http4s.Method._
import org.lyranthe.araethura.appstream.circe._
import org.lyranthe.araethura.appstream.models
class AmazonappstreamClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.appstream.Amazonappstream[F] {
  private[this] final val ServiceType: String = "appstream2"
  private[this] final val ServiceAndPrefix: Option[String] = Some("PhotonAdminProxyService")
  override def createStreamingURL(input: org.lyranthe.araethura.appstream.models.CreateStreamingURLRequest): F[org.lyranthe.araethura.appstream.models.CreateStreamingURLResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.CreateStreamingURLResult, org.lyranthe.araethura.appstream.models.CreateStreamingURLRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateStreamingURL", POST, "/", input)
  override def describeSessions(input: org.lyranthe.araethura.appstream.models.DescribeSessionsRequest): F[org.lyranthe.araethura.appstream.models.DescribeSessionsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DescribeSessionsResult, org.lyranthe.araethura.appstream.models.DescribeSessionsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeSessions", POST, "/", input)
  override def describeStacks(input: org.lyranthe.araethura.appstream.models.DescribeStacksRequest): F[org.lyranthe.araethura.appstream.models.DescribeStacksResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DescribeStacksResult, org.lyranthe.araethura.appstream.models.DescribeStacksRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStacks", POST, "/", input)
  override def associateFleet(input: org.lyranthe.araethura.appstream.models.AssociateFleetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.AssociateFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "AssociateFleet", POST, "/", input)
  override def deleteStack(input: org.lyranthe.araethura.appstream.models.DeleteStackRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.DeleteStackRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteStack", POST, "/", input)
  override def disassociateFleet(input: org.lyranthe.araethura.appstream.models.DisassociateFleetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.DisassociateFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DisassociateFleet", POST, "/", input)
  override def stopImageBuilder(input: org.lyranthe.araethura.appstream.models.StopImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.StopImageBuilderResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.StopImageBuilderResult, org.lyranthe.araethura.appstream.models.StopImageBuilderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopImageBuilder", POST, "/", input)
  override def describeImages(input: org.lyranthe.araethura.appstream.models.DescribeImagesRequest): F[org.lyranthe.araethura.appstream.models.DescribeImagesResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DescribeImagesResult, org.lyranthe.araethura.appstream.models.DescribeImagesRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeImages", POST, "/", input)
  override def describeDirectoryConfigs(input: org.lyranthe.araethura.appstream.models.DescribeDirectoryConfigsRequest): F[org.lyranthe.araethura.appstream.models.DescribeDirectoryConfigsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DescribeDirectoryConfigsResult, org.lyranthe.araethura.appstream.models.DescribeDirectoryConfigsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeDirectoryConfigs", POST, "/", input)
  override def updateStack(input: org.lyranthe.araethura.appstream.models.UpdateStackRequest): F[org.lyranthe.araethura.appstream.models.UpdateStackResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.UpdateStackResult, org.lyranthe.araethura.appstream.models.UpdateStackRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateStack", POST, "/", input)
  override def listAssociatedFleets(input: org.lyranthe.araethura.appstream.models.ListAssociatedFleetsRequest): F[org.lyranthe.araethura.appstream.models.ListAssociatedFleetsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.ListAssociatedFleetsResult, org.lyranthe.araethura.appstream.models.ListAssociatedFleetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListAssociatedFleets", POST, "/", input)
  override def updateDirectoryConfig(input: org.lyranthe.araethura.appstream.models.UpdateDirectoryConfigRequest): F[org.lyranthe.araethura.appstream.models.UpdateDirectoryConfigResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.UpdateDirectoryConfigResult, org.lyranthe.araethura.appstream.models.UpdateDirectoryConfigRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateDirectoryConfig", POST, "/", input)
  override def createStack(input: org.lyranthe.araethura.appstream.models.CreateStackRequest): F[org.lyranthe.araethura.appstream.models.CreateStackResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.CreateStackResult, org.lyranthe.araethura.appstream.models.CreateStackRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateStack", POST, "/", input)
  override def listAssociatedStacks(input: org.lyranthe.araethura.appstream.models.ListAssociatedStacksRequest): F[org.lyranthe.araethura.appstream.models.ListAssociatedStacksResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.ListAssociatedStacksResult, org.lyranthe.araethura.appstream.models.ListAssociatedStacksRequest](client, awsData, ServiceType, ServiceAndPrefix, "ListAssociatedStacks", POST, "/", input)
  override def deleteImage(input: org.lyranthe.araethura.appstream.models.DeleteImageRequest): F[org.lyranthe.araethura.appstream.models.DeleteImageResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DeleteImageResult, org.lyranthe.araethura.appstream.models.DeleteImageRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteImage", POST, "/", input)
  override def updateFleet(input: org.lyranthe.araethura.appstream.models.UpdateFleetRequest): F[org.lyranthe.araethura.appstream.models.UpdateFleetResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.UpdateFleetResult, org.lyranthe.araethura.appstream.models.UpdateFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "UpdateFleet", POST, "/", input)
  override def createDirectoryConfig(input: org.lyranthe.araethura.appstream.models.CreateDirectoryConfigRequest): F[org.lyranthe.araethura.appstream.models.CreateDirectoryConfigResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.CreateDirectoryConfigResult, org.lyranthe.araethura.appstream.models.CreateDirectoryConfigRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateDirectoryConfig", POST, "/", input)
  override def deleteImageBuilder(input: org.lyranthe.araethura.appstream.models.DeleteImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.DeleteImageBuilderResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DeleteImageBuilderResult, org.lyranthe.araethura.appstream.models.DeleteImageBuilderRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteImageBuilder", POST, "/", input)
  override def deleteFleet(input: org.lyranthe.araethura.appstream.models.DeleteFleetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.DeleteFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteFleet", POST, "/", input)
  override def describeImageBuilders(input: org.lyranthe.araethura.appstream.models.DescribeImageBuildersRequest): F[org.lyranthe.araethura.appstream.models.DescribeImageBuildersResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DescribeImageBuildersResult, org.lyranthe.araethura.appstream.models.DescribeImageBuildersRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeImageBuilders", POST, "/", input)
  override def createFleet(input: org.lyranthe.araethura.appstream.models.CreateFleetRequest): F[org.lyranthe.araethura.appstream.models.CreateFleetResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.CreateFleetResult, org.lyranthe.araethura.appstream.models.CreateFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateFleet", POST, "/", input)
  override def createImageBuilder(input: org.lyranthe.araethura.appstream.models.CreateImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.CreateImageBuilderResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.CreateImageBuilderResult, org.lyranthe.araethura.appstream.models.CreateImageBuilderRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateImageBuilder", POST, "/", input)
  override def startFleet(input: org.lyranthe.araethura.appstream.models.StartFleetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.StartFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartFleet", POST, "/", input)
  override def deleteDirectoryConfig(input: org.lyranthe.araethura.appstream.models.DeleteDirectoryConfigRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.DeleteDirectoryConfigRequest](client, awsData, ServiceType, ServiceAndPrefix, "DeleteDirectoryConfig", POST, "/", input)
  override def expireSession(input: org.lyranthe.araethura.appstream.models.ExpireSessionRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.ExpireSessionRequest](client, awsData, ServiceType, ServiceAndPrefix, "ExpireSession", POST, "/", input)
  override def describeFleets(input: org.lyranthe.araethura.appstream.models.DescribeFleetsRequest): F[org.lyranthe.araethura.appstream.models.DescribeFleetsResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.DescribeFleetsResult, org.lyranthe.araethura.appstream.models.DescribeFleetsRequest](client, awsData, ServiceType, ServiceAndPrefix, "DescribeFleets", POST, "/", input)
  override def createImageBuilderStreamingURL(input: org.lyranthe.araethura.appstream.models.CreateImageBuilderStreamingURLRequest): F[org.lyranthe.araethura.appstream.models.CreateImageBuilderStreamingURLResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.CreateImageBuilderStreamingURLResult, org.lyranthe.araethura.appstream.models.CreateImageBuilderStreamingURLRequest](client, awsData, ServiceType, ServiceAndPrefix, "CreateImageBuilderStreamingURL", POST, "/", input)
  override def stopFleet(input: org.lyranthe.araethura.appstream.models.StopFleetRequest): F[scala.Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, scala.Unit, org.lyranthe.araethura.appstream.models.StopFleetRequest](client, awsData, ServiceType, ServiceAndPrefix, "StopFleet", POST, "/", input)
  override def startImageBuilder(input: org.lyranthe.araethura.appstream.models.StartImageBuilderRequest): F[org.lyranthe.araethura.appstream.models.StartImageBuilderResult] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.appstream.models.StartImageBuilderResult, org.lyranthe.araethura.appstream.models.StartImageBuilderRequest](client, awsData, ServiceType, ServiceAndPrefix, "StartImageBuilder", POST, "/", input)
}