package org.lyranthe.araethura.directconnect
trait Amazondirectconnect[F[_]] {
  def describeVirtualGateways: F[org.lyranthe.araethura.directconnect.models.VirtualGateways]
  def deleteBGPPeer(input: org.lyranthe.araethura.directconnect.models.DeleteBGPPeerRequest): F[org.lyranthe.araethura.directconnect.models.DeleteBGPPeerResponse]
  def describeDirectConnectGateways(input: org.lyranthe.araethura.directconnect.models.DescribeDirectConnectGatewaysRequest): F[org.lyranthe.araethura.directconnect.models.DescribeDirectConnectGatewaysResult]
  def allocatePrivateVirtualInterface(input: org.lyranthe.araethura.directconnect.models.AllocatePrivateVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.VirtualInterface]
  def deleteConnection(input: org.lyranthe.araethura.directconnect.models.DeleteConnectionRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
  def deleteDirectConnectGateway(input: org.lyranthe.araethura.directconnect.models.DeleteDirectConnectGatewayRequest): F[org.lyranthe.araethura.directconnect.models.DeleteDirectConnectGatewayResult]
  def confirmConnection(input: org.lyranthe.araethura.directconnect.models.ConfirmConnectionRequest): F[org.lyranthe.araethura.directconnect.models.ConfirmConnectionResponse]
  def describeDirectConnectGatewayAssociations(input: org.lyranthe.araethura.directconnect.models.DescribeDirectConnectGatewayAssociationsRequest): F[org.lyranthe.araethura.directconnect.models.DescribeDirectConnectGatewayAssociationsResult]
  def associateVirtualInterface(input: org.lyranthe.araethura.directconnect.models.AssociateVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.VirtualInterface]
  def disassociateConnectionFromLag(input: org.lyranthe.araethura.directconnect.models.DisassociateConnectionFromLagRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
  def confirmPublicVirtualInterface(input: org.lyranthe.araethura.directconnect.models.ConfirmPublicVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.ConfirmPublicVirtualInterfaceResponse]
  def createDirectConnectGateway(input: org.lyranthe.araethura.directconnect.models.CreateDirectConnectGatewayRequest): F[org.lyranthe.araethura.directconnect.models.CreateDirectConnectGatewayResult]
  def untagResource(input: org.lyranthe.araethura.directconnect.models.UntagResourceRequest): F[scala.Unit]
  def createInterconnect(input: org.lyranthe.araethura.directconnect.models.CreateInterconnectRequest): F[org.lyranthe.araethura.directconnect.models.Interconnect]
  def createPrivateVirtualInterface(input: org.lyranthe.araethura.directconnect.models.CreatePrivateVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.VirtualInterface]
  def describeConnections(input: org.lyranthe.araethura.directconnect.models.DescribeConnectionsRequest): F[org.lyranthe.araethura.directconnect.models.Connections]
  def describeLags(input: org.lyranthe.araethura.directconnect.models.DescribeLagsRequest): F[org.lyranthe.araethura.directconnect.models.Lags]
  def describeConnectionsOnInterconnect(input: org.lyranthe.araethura.directconnect.models.DescribeConnectionsOnInterconnectRequest): F[org.lyranthe.araethura.directconnect.models.Connections]
  def describeInterconnects(input: org.lyranthe.araethura.directconnect.models.DescribeInterconnectsRequest): F[org.lyranthe.araethura.directconnect.models.Interconnects]
  def describeLocations: F[org.lyranthe.araethura.directconnect.models.Locations]
  def describeConnectionLoa(input: org.lyranthe.araethura.directconnect.models.DescribeConnectionLoaRequest): F[org.lyranthe.araethura.directconnect.models.DescribeConnectionLoaResponse]
  def deleteVirtualInterface(input: org.lyranthe.araethura.directconnect.models.DeleteVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.DeleteVirtualInterfaceResponse]
  def allocatePublicVirtualInterface(input: org.lyranthe.araethura.directconnect.models.AllocatePublicVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.VirtualInterface]
  def confirmPrivateVirtualInterface(input: org.lyranthe.araethura.directconnect.models.ConfirmPrivateVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.ConfirmPrivateVirtualInterfaceResponse]
  def deleteDirectConnectGatewayAssociation(input: org.lyranthe.araethura.directconnect.models.DeleteDirectConnectGatewayAssociationRequest): F[org.lyranthe.araethura.directconnect.models.DeleteDirectConnectGatewayAssociationResult]
  def describeDirectConnectGatewayAttachments(input: org.lyranthe.araethura.directconnect.models.DescribeDirectConnectGatewayAttachmentsRequest): F[org.lyranthe.araethura.directconnect.models.DescribeDirectConnectGatewayAttachmentsResult]
  def createConnection(input: org.lyranthe.araethura.directconnect.models.CreateConnectionRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
  def describeHostedConnections(input: org.lyranthe.araethura.directconnect.models.DescribeHostedConnectionsRequest): F[org.lyranthe.araethura.directconnect.models.Connections]
  def allocateHostedConnection(input: org.lyranthe.araethura.directconnect.models.AllocateHostedConnectionRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
  def createPublicVirtualInterface(input: org.lyranthe.araethura.directconnect.models.CreatePublicVirtualInterfaceRequest): F[org.lyranthe.araethura.directconnect.models.VirtualInterface]
  def deleteInterconnect(input: org.lyranthe.araethura.directconnect.models.DeleteInterconnectRequest): F[org.lyranthe.araethura.directconnect.models.DeleteInterconnectResponse]
  def createBGPPeer(input: org.lyranthe.araethura.directconnect.models.CreateBGPPeerRequest): F[org.lyranthe.araethura.directconnect.models.CreateBGPPeerResponse]
  def describeVirtualInterfaces(input: org.lyranthe.araethura.directconnect.models.DescribeVirtualInterfacesRequest): F[org.lyranthe.araethura.directconnect.models.VirtualInterfaces]
  def createDirectConnectGatewayAssociation(input: org.lyranthe.araethura.directconnect.models.CreateDirectConnectGatewayAssociationRequest): F[org.lyranthe.araethura.directconnect.models.CreateDirectConnectGatewayAssociationResult]
  def deleteLag(input: org.lyranthe.araethura.directconnect.models.DeleteLagRequest): F[org.lyranthe.araethura.directconnect.models.Lag]
  def describeInterconnectLoa(input: org.lyranthe.araethura.directconnect.models.DescribeInterconnectLoaRequest): F[org.lyranthe.araethura.directconnect.models.DescribeInterconnectLoaResponse]
  def associateHostedConnection(input: org.lyranthe.araethura.directconnect.models.AssociateHostedConnectionRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
  def createLag(input: org.lyranthe.araethura.directconnect.models.CreateLagRequest): F[org.lyranthe.araethura.directconnect.models.Lag]
  def allocateConnectionOnInterconnect(input: org.lyranthe.araethura.directconnect.models.AllocateConnectionOnInterconnectRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
  def describeTags(input: org.lyranthe.araethura.directconnect.models.DescribeTagsRequest): F[org.lyranthe.araethura.directconnect.models.DescribeTagsResponse]
  def updateLag(input: org.lyranthe.araethura.directconnect.models.UpdateLagRequest): F[org.lyranthe.araethura.directconnect.models.Lag]
  def tagResource(input: org.lyranthe.araethura.directconnect.models.TagResourceRequest): F[scala.Unit]
  def describeLoa(input: org.lyranthe.araethura.directconnect.models.DescribeLoaRequest): F[org.lyranthe.araethura.directconnect.models.Loa]
  def associateConnectionWithLag(input: org.lyranthe.araethura.directconnect.models.AssociateConnectionWithLagRequest): F[org.lyranthe.araethura.directconnect.models.Connection]
}