package org.lyranthe.araethura.dynamodbstreams.http4s
import org.http4s.Method._
import org.lyranthe.araethura.dynamodbstreams.circe._
import org.lyranthe.araethura.dynamodbstreams.models
class AmazondynamodbstreamsClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.dynamodbstreams.Amazondynamodbstreams[F] {
  private[this] final val ServiceType: String = "streams.dynamodb"
  private[this] final val ServiceAndPrefix: Option[String] = Some("DynamoDBStreams_20120810")
  override def getShardIterator(input: org.lyranthe.araethura.dynamodbstreams.models.GetShardIteratorInput): F[org.lyranthe.araethura.dynamodbstreams.models.GetShardIteratorOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodbstreams.models.GetShardIteratorOutput, org.lyranthe.araethura.dynamodbstreams.models.GetShardIteratorInput](client, awsData, ServiceType, ServiceAndPrefix, "GetShardIterator", POST, "/", input)
  override def listStreams(input: org.lyranthe.araethura.dynamodbstreams.models.ListStreamsInput): F[org.lyranthe.araethura.dynamodbstreams.models.ListStreamsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodbstreams.models.ListStreamsOutput, org.lyranthe.araethura.dynamodbstreams.models.ListStreamsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListStreams", POST, "/", input)
  override def describeStream(input: org.lyranthe.araethura.dynamodbstreams.models.DescribeStreamInput): F[org.lyranthe.araethura.dynamodbstreams.models.DescribeStreamOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodbstreams.models.DescribeStreamOutput, org.lyranthe.araethura.dynamodbstreams.models.DescribeStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStream", POST, "/", input)
  override def getRecords(input: org.lyranthe.araethura.dynamodbstreams.models.GetRecordsInput): F[org.lyranthe.araethura.dynamodbstreams.models.GetRecordsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, org.lyranthe.araethura.dynamodbstreams.models.GetRecordsOutput, org.lyranthe.araethura.dynamodbstreams.models.GetRecordsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetRecords", POST, "/", input)
}