package org.lyranthe.araethura.kinesis.http4s
import org.http4s.Method._
import org.lyranthe.araethura.kinesis.circe._
import org.lyranthe.araethura.kinesis.models
class AmazonkinesisClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: org.lyranthe.araethura.common.AwsData[F]) extends org.lyranthe.araethura.kinesis.Amazonkinesis[F] {
  private[this] final val ServiceType: String = "kinesis"
  private[this] final val ServiceAndPrefix: Option[String] = Some("Kinesis_20131202")
  override def putRecord(input: models.PutRecordInput): F[models.PutRecordOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutRecordOutput, models.PutRecordInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecord", POST, "/", input)
  override def describeStream(input: models.DescribeStreamInput): F[models.DescribeStreamOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeStreamOutput, models.DescribeStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStream", POST, "/", input)
  override def addTagsToStream(input: models.AddTagsToStreamInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.AddTagsToStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTagsToStream", POST, "/", input)
  override def getShardIterator(input: models.GetShardIteratorInput): F[models.GetShardIteratorOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetShardIteratorOutput, models.GetShardIteratorInput](client, awsData, ServiceType, ServiceAndPrefix, "GetShardIterator", POST, "/", input)
  override def listTagsForStream(input: models.ListTagsForStreamInput): F[models.ListTagsForStreamOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListTagsForStreamOutput, models.ListTagsForStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForStream", POST, "/", input)
  override def startStreamEncryption(input: models.StartStreamEncryptionInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.StartStreamEncryptionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartStreamEncryption", POST, "/", input)
  override def putRecords(input: models.PutRecordsInput): F[models.PutRecordsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.PutRecordsOutput, models.PutRecordsInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecords", POST, "/", input)
  override def enableEnhancedMonitoring(input: models.EnableEnhancedMonitoringInput): F[models.EnhancedMonitoringOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.EnhancedMonitoringOutput, models.EnableEnhancedMonitoringInput](client, awsData, ServiceType, ServiceAndPrefix, "EnableEnhancedMonitoring", POST, "/", input)
  override def stopStreamEncryption(input: models.StopStreamEncryptionInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.StopStreamEncryptionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopStreamEncryption", POST, "/", input)
  override def describeLimits: F[models.DescribeLimitsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeLimitsOutput, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeLimits", POST, "/", ())
  override def getRecords(input: models.GetRecordsInput): F[models.GetRecordsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.GetRecordsOutput, models.GetRecordsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetRecords", POST, "/", input)
  override def mergeShards(input: models.MergeShardsInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.MergeShardsInput](client, awsData, ServiceType, ServiceAndPrefix, "MergeShards", POST, "/", input)
  override def createStream(input: models.CreateStreamInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.CreateStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateStream", POST, "/", input)
  override def listStreams(input: models.ListStreamsInput): F[models.ListStreamsOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.ListStreamsOutput, models.ListStreamsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListStreams", POST, "/", input)
  override def increaseStreamRetentionPeriod(input: models.IncreaseStreamRetentionPeriodInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.IncreaseStreamRetentionPeriodInput](client, awsData, ServiceType, ServiceAndPrefix, "IncreaseStreamRetentionPeriod", POST, "/", input)
  override def describeStreamSummary(input: models.DescribeStreamSummaryInput): F[models.DescribeStreamSummaryOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.DescribeStreamSummaryOutput, models.DescribeStreamSummaryInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStreamSummary", POST, "/", input)
  override def disableEnhancedMonitoring(input: models.DisableEnhancedMonitoringInput): F[models.EnhancedMonitoringOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.EnhancedMonitoringOutput, models.DisableEnhancedMonitoringInput](client, awsData, ServiceType, ServiceAndPrefix, "DisableEnhancedMonitoring", POST, "/", input)
  override def deleteStream(input: models.DeleteStreamInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.DeleteStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteStream", POST, "/", input)
  override def removeTagsFromStream(input: models.RemoveTagsFromStreamInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.RemoveTagsFromStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTagsFromStream", POST, "/", input)
  override def splitShard(input: models.SplitShardInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.SplitShardInput](client, awsData, ServiceType, ServiceAndPrefix, "SplitShard", POST, "/", input)
  override def decreaseStreamRetentionPeriod(input: models.DecreaseStreamRetentionPeriodInput): F[Unit] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, Unit, models.DecreaseStreamRetentionPeriodInput](client, awsData, ServiceType, ServiceAndPrefix, "DecreaseStreamRetentionPeriod", POST, "/", input)
  override def updateShardCount(input: models.UpdateShardCountInput): F[models.UpdateShardCountOutput] = org.lyranthe.araethura.common.http4s.ClientUtils.doRequest[F, models.UpdateShardCountOutput, models.UpdateShardCountInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateShardCount", POST, "/", input)
}