package avias.kinesis.http4s
import org.http4s.Method._
import avias.kinesis.circe._
import avias.kinesis.models
class AmazonkinesisClient[F[_]: cats.effect.Sync](client: org.http4s.client.Client[F], awsData: avias.common.AwsData[F]) extends avias.kinesis.Amazonkinesis[F] {
  private[this] final val ServiceType: String = "kinesis"
  private[this] final val ServiceAndPrefix: Option[String] = Some("Kinesis_20131202")
  override def putRecord(input: avias.kinesis.models.PutRecordInput): F[avias.kinesis.models.PutRecordOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.PutRecordOutput, avias.kinesis.models.PutRecordInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecord", POST, "/", input)
  override def describeStream(input: avias.kinesis.models.DescribeStreamInput): F[avias.kinesis.models.DescribeStreamOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.DescribeStreamOutput, avias.kinesis.models.DescribeStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStream", POST, "/", input)
  override def addTagsToStream(input: avias.kinesis.models.AddTagsToStreamInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.AddTagsToStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "AddTagsToStream", POST, "/", input)
  override def getShardIterator(input: avias.kinesis.models.GetShardIteratorInput): F[avias.kinesis.models.GetShardIteratorOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.GetShardIteratorOutput, avias.kinesis.models.GetShardIteratorInput](client, awsData, ServiceType, ServiceAndPrefix, "GetShardIterator", POST, "/", input)
  override def listTagsForStream(input: avias.kinesis.models.ListTagsForStreamInput): F[avias.kinesis.models.ListTagsForStreamOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.ListTagsForStreamOutput, avias.kinesis.models.ListTagsForStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "ListTagsForStream", POST, "/", input)
  override def startStreamEncryption(input: avias.kinesis.models.StartStreamEncryptionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.StartStreamEncryptionInput](client, awsData, ServiceType, ServiceAndPrefix, "StartStreamEncryption", POST, "/", input)
  override def putRecords(input: avias.kinesis.models.PutRecordsInput): F[avias.kinesis.models.PutRecordsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.PutRecordsOutput, avias.kinesis.models.PutRecordsInput](client, awsData, ServiceType, ServiceAndPrefix, "PutRecords", POST, "/", input)
  override def enableEnhancedMonitoring(input: avias.kinesis.models.EnableEnhancedMonitoringInput): F[avias.kinesis.models.EnhancedMonitoringOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.EnhancedMonitoringOutput, avias.kinesis.models.EnableEnhancedMonitoringInput](client, awsData, ServiceType, ServiceAndPrefix, "EnableEnhancedMonitoring", POST, "/", input)
  override def stopStreamEncryption(input: avias.kinesis.models.StopStreamEncryptionInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.StopStreamEncryptionInput](client, awsData, ServiceType, ServiceAndPrefix, "StopStreamEncryption", POST, "/", input)
  override def describeLimits: F[avias.kinesis.models.DescribeLimitsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.DescribeLimitsOutput, scala.Unit](client, awsData, ServiceType, ServiceAndPrefix, "DescribeLimits", POST, "/", ())
  override def getRecords(input: avias.kinesis.models.GetRecordsInput): F[avias.kinesis.models.GetRecordsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.GetRecordsOutput, avias.kinesis.models.GetRecordsInput](client, awsData, ServiceType, ServiceAndPrefix, "GetRecords", POST, "/", input)
  override def mergeShards(input: avias.kinesis.models.MergeShardsInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.MergeShardsInput](client, awsData, ServiceType, ServiceAndPrefix, "MergeShards", POST, "/", input)
  override def createStream(input: avias.kinesis.models.CreateStreamInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.CreateStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "CreateStream", POST, "/", input)
  override def listStreams(input: avias.kinesis.models.ListStreamsInput): F[avias.kinesis.models.ListStreamsOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.ListStreamsOutput, avias.kinesis.models.ListStreamsInput](client, awsData, ServiceType, ServiceAndPrefix, "ListStreams", POST, "/", input)
  override def increaseStreamRetentionPeriod(input: avias.kinesis.models.IncreaseStreamRetentionPeriodInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.IncreaseStreamRetentionPeriodInput](client, awsData, ServiceType, ServiceAndPrefix, "IncreaseStreamRetentionPeriod", POST, "/", input)
  override def describeStreamSummary(input: avias.kinesis.models.DescribeStreamSummaryInput): F[avias.kinesis.models.DescribeStreamSummaryOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.DescribeStreamSummaryOutput, avias.kinesis.models.DescribeStreamSummaryInput](client, awsData, ServiceType, ServiceAndPrefix, "DescribeStreamSummary", POST, "/", input)
  override def disableEnhancedMonitoring(input: avias.kinesis.models.DisableEnhancedMonitoringInput): F[avias.kinesis.models.EnhancedMonitoringOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.EnhancedMonitoringOutput, avias.kinesis.models.DisableEnhancedMonitoringInput](client, awsData, ServiceType, ServiceAndPrefix, "DisableEnhancedMonitoring", POST, "/", input)
  override def deleteStream(input: avias.kinesis.models.DeleteStreamInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.DeleteStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "DeleteStream", POST, "/", input)
  override def removeTagsFromStream(input: avias.kinesis.models.RemoveTagsFromStreamInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.RemoveTagsFromStreamInput](client, awsData, ServiceType, ServiceAndPrefix, "RemoveTagsFromStream", POST, "/", input)
  override def splitShard(input: avias.kinesis.models.SplitShardInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.SplitShardInput](client, awsData, ServiceType, ServiceAndPrefix, "SplitShard", POST, "/", input)
  override def decreaseStreamRetentionPeriod(input: avias.kinesis.models.DecreaseStreamRetentionPeriodInput): F[scala.Unit] = avias.common.http4s.ClientUtils.doRequest[F, scala.Unit, avias.kinesis.models.DecreaseStreamRetentionPeriodInput](client, awsData, ServiceType, ServiceAndPrefix, "DecreaseStreamRetentionPeriod", POST, "/", input)
  override def updateShardCount(input: avias.kinesis.models.UpdateShardCountInput): F[avias.kinesis.models.UpdateShardCountOutput] = avias.common.http4s.ClientUtils.doRequest[F, avias.kinesis.models.UpdateShardCountOutput, avias.kinesis.models.UpdateShardCountInput](client, awsData, ServiceType, ServiceAndPrefix, "UpdateShardCount", POST, "/", input)
}