package org.lyranthe.araethura.ecs
trait Amazonecs[F[_]] {
  def submitContainerStateChange(input: org.lyranthe.araethura.ecs.models.SubmitContainerStateChangeRequest): F[org.lyranthe.araethura.ecs.models.SubmitContainerStateChangeResponse]
  def describeTaskDefinition(input: org.lyranthe.araethura.ecs.models.DescribeTaskDefinitionRequest): F[org.lyranthe.araethura.ecs.models.DescribeTaskDefinitionResponse]
  def listAttributes(input: org.lyranthe.araethura.ecs.models.ListAttributesRequest): F[org.lyranthe.araethura.ecs.models.ListAttributesResponse]
  def listContainerInstances(input: org.lyranthe.araethura.ecs.models.ListContainerInstancesRequest): F[org.lyranthe.araethura.ecs.models.ListContainerInstancesResponse]
  def deregisterContainerInstance(input: org.lyranthe.araethura.ecs.models.DeregisterContainerInstanceRequest): F[org.lyranthe.araethura.ecs.models.DeregisterContainerInstanceResponse]
  def deleteService(input: org.lyranthe.araethura.ecs.models.DeleteServiceRequest): F[org.lyranthe.araethura.ecs.models.DeleteServiceResponse]
  def runTask(input: org.lyranthe.araethura.ecs.models.RunTaskRequest): F[org.lyranthe.araethura.ecs.models.RunTaskResponse]
  def describeClusters(input: org.lyranthe.araethura.ecs.models.DescribeClustersRequest): F[org.lyranthe.araethura.ecs.models.DescribeClustersResponse]
  def putAttributes(input: org.lyranthe.araethura.ecs.models.PutAttributesRequest): F[org.lyranthe.araethura.ecs.models.PutAttributesResponse]
  def describeServices(input: org.lyranthe.araethura.ecs.models.DescribeServicesRequest): F[org.lyranthe.araethura.ecs.models.DescribeServicesResponse]
  def createService(input: org.lyranthe.araethura.ecs.models.CreateServiceRequest): F[org.lyranthe.araethura.ecs.models.CreateServiceResponse]
  def listTasks(input: org.lyranthe.araethura.ecs.models.ListTasksRequest): F[org.lyranthe.araethura.ecs.models.ListTasksResponse]
  def listTaskDefinitions(input: org.lyranthe.araethura.ecs.models.ListTaskDefinitionsRequest): F[org.lyranthe.araethura.ecs.models.ListTaskDefinitionsResponse]
  def describeContainerInstances(input: org.lyranthe.araethura.ecs.models.DescribeContainerInstancesRequest): F[org.lyranthe.araethura.ecs.models.DescribeContainerInstancesResponse]
  def listClusters(input: org.lyranthe.araethura.ecs.models.ListClustersRequest): F[org.lyranthe.araethura.ecs.models.ListClustersResponse]
  def deleteCluster(input: org.lyranthe.araethura.ecs.models.DeleteClusterRequest): F[org.lyranthe.araethura.ecs.models.DeleteClusterResponse]
  def updateContainerInstancesState(input: org.lyranthe.araethura.ecs.models.UpdateContainerInstancesStateRequest): F[org.lyranthe.araethura.ecs.models.UpdateContainerInstancesStateResponse]
  def deregisterTaskDefinition(input: org.lyranthe.araethura.ecs.models.DeregisterTaskDefinitionRequest): F[org.lyranthe.araethura.ecs.models.DeregisterTaskDefinitionResponse]
  def stopTask(input: org.lyranthe.araethura.ecs.models.StopTaskRequest): F[org.lyranthe.araethura.ecs.models.StopTaskResponse]
  def updateService(input: org.lyranthe.araethura.ecs.models.UpdateServiceRequest): F[org.lyranthe.araethura.ecs.models.UpdateServiceResponse]
  def startTask(input: org.lyranthe.araethura.ecs.models.StartTaskRequest): F[org.lyranthe.araethura.ecs.models.StartTaskResponse]
  def registerContainerInstance(input: org.lyranthe.araethura.ecs.models.RegisterContainerInstanceRequest): F[org.lyranthe.araethura.ecs.models.RegisterContainerInstanceResponse]
  def registerTaskDefinition(input: org.lyranthe.araethura.ecs.models.RegisterTaskDefinitionRequest): F[org.lyranthe.araethura.ecs.models.RegisterTaskDefinitionResponse]
  def deleteAttributes(input: org.lyranthe.araethura.ecs.models.DeleteAttributesRequest): F[org.lyranthe.araethura.ecs.models.DeleteAttributesResponse]
  def submitTaskStateChange(input: org.lyranthe.araethura.ecs.models.SubmitTaskStateChangeRequest): F[org.lyranthe.araethura.ecs.models.SubmitTaskStateChangeResponse]
  def discoverPollEndpoint(input: org.lyranthe.araethura.ecs.models.DiscoverPollEndpointRequest): F[org.lyranthe.araethura.ecs.models.DiscoverPollEndpointResponse]
  def createCluster(input: org.lyranthe.araethura.ecs.models.CreateClusterRequest): F[org.lyranthe.araethura.ecs.models.CreateClusterResponse]
  def updateContainerAgent(input: org.lyranthe.araethura.ecs.models.UpdateContainerAgentRequest): F[org.lyranthe.araethura.ecs.models.UpdateContainerAgentResponse]
  def describeTasks(input: org.lyranthe.araethura.ecs.models.DescribeTasksRequest): F[org.lyranthe.araethura.ecs.models.DescribeTasksResponse]
  def listTaskDefinitionFamilies(input: org.lyranthe.araethura.ecs.models.ListTaskDefinitionFamiliesRequest): F[org.lyranthe.araethura.ecs.models.ListTaskDefinitionFamiliesResponse]
  def listServices(input: org.lyranthe.araethura.ecs.models.ListServicesRequest): F[org.lyranthe.araethura.ecs.models.ListServicesResponse]
}