package avias.ecs
trait Amazonecs[F[_]] {
  def submitContainerStateChange(input: avias.ecs.models.SubmitContainerStateChangeRequest): F[avias.ecs.models.SubmitContainerStateChangeResponse]
  def describeTaskDefinition(input: avias.ecs.models.DescribeTaskDefinitionRequest): F[avias.ecs.models.DescribeTaskDefinitionResponse]
  def listAttributes(input: avias.ecs.models.ListAttributesRequest): F[avias.ecs.models.ListAttributesResponse]
  def listContainerInstances(input: avias.ecs.models.ListContainerInstancesRequest): F[avias.ecs.models.ListContainerInstancesResponse]
  def deregisterContainerInstance(input: avias.ecs.models.DeregisterContainerInstanceRequest): F[avias.ecs.models.DeregisterContainerInstanceResponse]
  def deleteService(input: avias.ecs.models.DeleteServiceRequest): F[avias.ecs.models.DeleteServiceResponse]
  def runTask(input: avias.ecs.models.RunTaskRequest): F[avias.ecs.models.RunTaskResponse]
  def describeClusters(input: avias.ecs.models.DescribeClustersRequest): F[avias.ecs.models.DescribeClustersResponse]
  def putAttributes(input: avias.ecs.models.PutAttributesRequest): F[avias.ecs.models.PutAttributesResponse]
  def describeServices(input: avias.ecs.models.DescribeServicesRequest): F[avias.ecs.models.DescribeServicesResponse]
  def createService(input: avias.ecs.models.CreateServiceRequest): F[avias.ecs.models.CreateServiceResponse]
  def listTasks(input: avias.ecs.models.ListTasksRequest): F[avias.ecs.models.ListTasksResponse]
  def listTaskDefinitions(input: avias.ecs.models.ListTaskDefinitionsRequest): F[avias.ecs.models.ListTaskDefinitionsResponse]
  def describeContainerInstances(input: avias.ecs.models.DescribeContainerInstancesRequest): F[avias.ecs.models.DescribeContainerInstancesResponse]
  def listClusters(input: avias.ecs.models.ListClustersRequest): F[avias.ecs.models.ListClustersResponse]
  def deleteCluster(input: avias.ecs.models.DeleteClusterRequest): F[avias.ecs.models.DeleteClusterResponse]
  def updateContainerInstancesState(input: avias.ecs.models.UpdateContainerInstancesStateRequest): F[avias.ecs.models.UpdateContainerInstancesStateResponse]
  def deregisterTaskDefinition(input: avias.ecs.models.DeregisterTaskDefinitionRequest): F[avias.ecs.models.DeregisterTaskDefinitionResponse]
  def stopTask(input: avias.ecs.models.StopTaskRequest): F[avias.ecs.models.StopTaskResponse]
  def updateService(input: avias.ecs.models.UpdateServiceRequest): F[avias.ecs.models.UpdateServiceResponse]
  def startTask(input: avias.ecs.models.StartTaskRequest): F[avias.ecs.models.StartTaskResponse]
  def registerContainerInstance(input: avias.ecs.models.RegisterContainerInstanceRequest): F[avias.ecs.models.RegisterContainerInstanceResponse]
  def registerTaskDefinition(input: avias.ecs.models.RegisterTaskDefinitionRequest): F[avias.ecs.models.RegisterTaskDefinitionResponse]
  def deleteAttributes(input: avias.ecs.models.DeleteAttributesRequest): F[avias.ecs.models.DeleteAttributesResponse]
  def submitTaskStateChange(input: avias.ecs.models.SubmitTaskStateChangeRequest): F[avias.ecs.models.SubmitTaskStateChangeResponse]
  def discoverPollEndpoint(input: avias.ecs.models.DiscoverPollEndpointRequest): F[avias.ecs.models.DiscoverPollEndpointResponse]
  def createCluster(input: avias.ecs.models.CreateClusterRequest): F[avias.ecs.models.CreateClusterResponse]
  def updateContainerAgent(input: avias.ecs.models.UpdateContainerAgentRequest): F[avias.ecs.models.UpdateContainerAgentResponse]
  def describeTasks(input: avias.ecs.models.DescribeTasksRequest): F[avias.ecs.models.DescribeTasksResponse]
  def listTaskDefinitionFamilies(input: avias.ecs.models.ListTaskDefinitionFamiliesRequest): F[avias.ecs.models.ListTaskDefinitionFamiliesResponse]
  def listServices(input: avias.ecs.models.ListServicesRequest): F[avias.ecs.models.ListServicesResponse]
}